// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
    struct Scalars {
        uint256 x;
        uint256 y;
        address addr;
    }

    struct Packed {
        uint256 val;
        bool    flag;
        uint8   tag;
    }

    struct WithFixedArr {
        uint256    x;
        uint256[3] arr;
        uint256    y;
    }

    struct Inner {
        uint256 v;
        bool    active;
    }

    struct WithNested {
        uint256 a;
        Inner   inner;
        uint256 b;
    }

    Scalars[]      scalarsArr;
    Packed[]       packedArr;
    WithFixedArr[] fixedArrArr;
    WithNested[]   nestedArr;

    function popScalars()   public { scalarsArr.pop(); }
    function popPacked()    public { packedArr.pop(); }
    function popFixedArr()  public { fixedArrArr.pop(); }
    function popNested()    public { nestedArr.pop(); }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @C_89 {
// CHECK-NEXT:     sol.state_var @scalarsArr_40 slot 0 offset 0 : !sol.array<? x !sol.struct<(ui256, ui256, !sol.address), Storage>, Storage> loc(#loc2)
// CHECK-NEXT:     sol.state_var @packedArr_44 slot 1 offset 0 : !sol.array<? x !sol.struct<(ui256, i1, ui8), Storage>, Storage> loc(#loc3)
// CHECK-NEXT:     sol.state_var @fixedArrArr_48 slot 2 offset 0 : !sol.array<? x !sol.struct<(ui256, !sol.array<3 x ui256, Storage>, ui256), Storage>, Storage> loc(#loc4)
// CHECK-NEXT:     sol.state_var @nestedArr_52 slot 3 offset 0 : !sol.array<? x !sol.struct<(ui256, !sol.struct<(ui256, i1), Storage>, ui256), Storage>, Storage> loc(#loc5)
// CHECK-NEXT:     sol.func @C_89() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @popScalars_61() attributes {id = 61 : i64, orig_fn_type = () -> (), selector = -1741011576 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @scalarsArr_40 : !sol.array<? x !sol.struct<(ui256, ui256, !sol.address), Storage>, Storage> loc(#loc2)
// CHECK-NEXT:       sol.pop %0 : !sol.array<? x !sol.struct<(ui256, ui256, !sol.address), Storage>, Storage> loc(#loc7)
// CHECK-NEXT:       sol.return loc(#loc6)
// CHECK-NEXT:     } loc(#loc6)
// CHECK-NEXT:     sol.func @popPacked_70() attributes {id = 70 : i64, orig_fn_type = () -> (), selector = -1709012456 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @packedArr_44 : !sol.array<? x !sol.struct<(ui256, i1, ui8), Storage>, Storage> loc(#loc3)
// CHECK-NEXT:       sol.pop %0 : !sol.array<? x !sol.struct<(ui256, i1, ui8), Storage>, Storage> loc(#loc9)
// CHECK-NEXT:       sol.return loc(#loc8)
// CHECK-NEXT:     } loc(#loc8)
// CHECK-NEXT:     sol.func @popFixedArr_79() attributes {id = 79 : i64, orig_fn_type = () -> (), selector = 560108862 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @fixedArrArr_48 : !sol.array<? x !sol.struct<(ui256, !sol.array<3 x ui256, Storage>, ui256), Storage>, Storage> loc(#loc4)
// CHECK-NEXT:       sol.pop %0 : !sol.array<? x !sol.struct<(ui256, !sol.array<3 x ui256, Storage>, ui256), Storage>, Storage> loc(#loc11)
// CHECK-NEXT:       sol.return loc(#loc10)
// CHECK-NEXT:     } loc(#loc10)
// CHECK-NEXT:     sol.func @popNested_88() attributes {id = 88 : i64, orig_fn_type = () -> (), selector = -124270945 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @nestedArr_52 : !sol.array<? x !sol.struct<(ui256, !sol.struct<(ui256, i1), Storage>, ui256), Storage>, Storage> loc(#loc5)
// CHECK-NEXT:       sol.pop %0 : !sol.array<? x !sol.struct<(ui256, !sol.struct<(ui256, i1), Storage>, ui256), Storage>, Storage> loc(#loc13)
// CHECK-NEXT:       sol.return loc(#loc12)
// CHECK-NEXT:     } loc(#loc12)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:32:4)
// CHECK-NEXT: #loc3 = loc({{.*}}:33:4)
// CHECK-NEXT: #loc4 = loc({{.*}}:34:4)
// CHECK-NEXT: #loc5 = loc({{.*}}:35:4)
// CHECK-NEXT: #loc6 = loc({{.*}}:37:4)
// CHECK-NEXT: #loc7 = loc({{.*}}:37:37)
// CHECK-NEXT: #loc8 = loc({{.*}}:38:4)
// CHECK-NEXT: #loc9 = loc({{.*}}:38:37)
// CHECK-NEXT: #loc10 = loc({{.*}}:39:4)
// CHECK-NEXT: #loc11 = loc({{.*}}:39:37)
// CHECK-NEXT: #loc12 = loc({{.*}}:40:4)
// CHECK-NEXT: #loc13 = loc({{.*}}:40:37)
// CHECK-EMPTY:
