// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
    uint[(2**256)-1] s;
    function getS(uint256 i) public view returns (uint) {
        return s[i];
    }
}

contract D {
    uint256[2**100] a;
    uint256[2**100] b;

    struct S {
        uint256 x;
        uint256[2**70] inner;
    }
    S s;

    function setElt(uint256 i, uint256 v) public {
        a[i] = v;
    }

    function delElt(uint256 i) public {
        delete a[i];
    }

    function delArr() public {
        delete a;
    }

    function copyArr() public {
        a = b;
    }

    function getLen() public view returns (uint256) {
        return a.length;
    }

    function viaRef(uint256 i, uint256 v) public {
        uint256[2**100] storage r = a;
        r[i] = v;
    }

    function delStruct() public {
        delete s;
    }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #View = #sol<StateMutability View>
// CHECK-NEXT: #loc4 = loc({{.*}}:4:18)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @C_22 {
// CHECK-NEXT:     sol.state_var @s_9 slot 0 offset 0 : !sol.array<115792089237316195423570985008687907853269984665640564039457584007913129639935 x ui256, Storage> loc(#loc2)
// CHECK-NEXT:     sol.func @C_22() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @getS_21(%arg0: ui256 loc({{.*}}:4:18)) -> ui256 attributes {id = 21 : i64, orig_fn_type = (ui256) -> ui256, selector = -737313952 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc4)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc4)
// CHECK-NEXT:       %1 = sol.addr_of @s_9 : !sol.array<115792089237316195423570985008687907853269984665640564039457584007913129639935 x ui256, Storage> loc(#loc2)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc5)
// CHECK-NEXT:       %3 = sol.gep %1, %2 : !sol.array<115792089237316195423570985008687907853269984665640564039457584007913129639935 x ui256, Storage>, ui256, !sol.ptr<ui256, Storage> loc(#loc6)
// CHECK-NEXT:       %4 = sol.load %3 : !sol.ptr<ui256, Storage>, ui256 loc(#loc6)
// CHECK-NEXT:       sol.return %4 : ui256 loc(#loc7)
// CHECK-NEXT:     } loc(#loc3)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:3:4)
// CHECK-NEXT: #loc3 = loc({{.*}}:4:4)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:17)
// CHECK-NEXT: #loc6 = loc({{.*}}:5:15)
// CHECK-NEXT: #loc7 = loc({{.*}}:5:8)
// CHECK-NEXT: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #View = #sol<StateMutability View>
// CHECK-NEXT: #loc6 = loc({{.*}}:19:20)
// CHECK-NEXT: #loc7 = loc({{.*}}:19:31)
// CHECK-NEXT: #loc12 = loc({{.*}}:23:20)
// CHECK-NEXT: #loc24 = loc({{.*}}:39:20)
// CHECK-NEXT: #loc25 = loc({{.*}}:39:31)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @D_127 {
// CHECK-NEXT:     sol.state_var @a_28 slot 0 offset 0 : !sol.array<1267650600228229401496703205376 x ui256, Storage> loc(#loc2)
// CHECK-NEXT:     sol.state_var @b_34 slot 1267650600228229401496703205376 offset 0 : !sol.array<1267650600228229401496703205376 x ui256, Storage> loc(#loc3)
// CHECK-NEXT:     sol.state_var @s_46 slot 2535301200456458802993406410752 offset 0 : !sol.struct<(ui256, !sol.array<1180591620717411303424 x ui256, Storage>), Storage> loc(#loc4)
// CHECK-NEXT:     sol.func @D_127() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @setElt_60(%arg0: ui256 loc({{.*}}:19:20), %arg1: ui256 loc({{.*}}:19:31)) attributes {id = 60 : i64, orig_fn_type = (ui256, ui256) -> (), selector = 1996358004 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc6)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc6)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc7)
// CHECK-NEXT:       sol.store %arg1, %1 : ui256, !sol.ptr<ui256, Stack> loc(#loc7)
// CHECK-NEXT:       %2 = sol.addr_of @a_28 : !sol.array<1267650600228229401496703205376 x ui256, Storage> loc(#loc2)
// CHECK-NEXT:       %3 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc8)
// CHECK-NEXT:       %4 = sol.gep %2, %3 : !sol.array<1267650600228229401496703205376 x ui256, Storage>, ui256, !sol.ptr<ui256, Storage> loc(#loc9)
// CHECK-NEXT:       %5 = sol.load %1 : !sol.ptr<ui256, Stack>, ui256 loc(#loc10)
// CHECK-NEXT:       sol.store %5, %4 : ui256, !sol.ptr<ui256, Storage> loc(#loc9)
// CHECK-NEXT:       sol.return loc(#loc5)
// CHECK-NEXT:     } loc(#loc5)
// CHECK-NEXT:     sol.func @delElt_71(%arg0: ui256 loc({{.*}}:23:20)) attributes {id = 71 : i64, orig_fn_type = (ui256) -> (), selector = -1581371784 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc12)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc12)
// CHECK-NEXT:       %1 = sol.addr_of @a_28 : !sol.array<1267650600228229401496703205376 x ui256, Storage> loc(#loc2)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc13)
// CHECK-NEXT:       %3 = sol.gep %1, %2 : !sol.array<1267650600228229401496703205376 x ui256, Storage>, ui256, !sol.ptr<ui256, Storage> loc(#loc14)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc15)
// CHECK-NEXT:       sol.store %c0_ui256, %3 : ui256, !sol.ptr<ui256, Storage> loc(#loc15)
// CHECK-NEXT:       sol.return loc(#loc11)
// CHECK-NEXT:     } loc(#loc11)
// CHECK-NEXT:     sol.func @delArr_78() attributes {id = 78 : i64, orig_fn_type = () -> (), selector = -203604435 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @a_28 : !sol.array<1267650600228229401496703205376 x ui256, Storage> loc(#loc2)
// CHECK-NEXT:       sol.delete %0 : !sol.array<1267650600228229401496703205376 x ui256, Storage> loc(#loc17)
// CHECK-NEXT:       sol.return loc(#loc16)
// CHECK-NEXT:     } loc(#loc16)
// CHECK-NEXT:     sol.func @copyArr_86() attributes {id = 86 : i64, orig_fn_type = () -> (), selector = 1616550925 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @a_28 : !sol.array<1267650600228229401496703205376 x ui256, Storage> loc(#loc2)
// CHECK-NEXT:       %1 = sol.addr_of @b_34 : !sol.array<1267650600228229401496703205376 x ui256, Storage> loc(#loc3)
// CHECK-NEXT:       sol.copy %1, %0 : !sol.array<1267650600228229401496703205376 x ui256, Storage>, !sol.array<1267650600228229401496703205376 x ui256, Storage> loc(#loc19)
// CHECK-NEXT:       sol.return loc(#loc18)
// CHECK-NEXT:     } loc(#loc18)
// CHECK-NEXT:     sol.func @getLen_95() -> ui256 attributes {id = 95 : i64, orig_fn_type = () -> ui256, selector = 1250999895 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.addr_of @a_28 : !sol.array<1267650600228229401496703205376 x ui256, Storage> loc(#loc2)
// CHECK-NEXT:       %1 = sol.length %0 : !sol.array<1267650600228229401496703205376 x ui256, Storage> loc(#loc21)
// CHECK-NEXT:       sol.return %1 : ui256 loc(#loc22)
// CHECK-NEXT:     } loc(#loc20)
// CHECK-NEXT:     sol.func @viaRef_119(%arg0: ui256 loc({{.*}}:39:20), %arg1: ui256 loc({{.*}}:39:31)) attributes {id = 119 : i64, orig_fn_type = (ui256, ui256) -> (), selector = 114796897 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc24)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc24)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc25)
// CHECK-NEXT:       sol.store %arg1, %1 : ui256, !sol.ptr<ui256, Stack> loc(#loc25)
// CHECK-NEXT:       %2 = sol.addr_of @a_28 : !sol.array<1267650600228229401496703205376 x ui256, Storage> loc(#loc2)
// CHECK-NEXT:       %3 = sol.alloca : !sol.ptr<!sol.array<1267650600228229401496703205376 x ui256, Storage>, Stack> loc(#loc26)
// CHECK-NEXT:       sol.store %2, %3 : !sol.array<1267650600228229401496703205376 x ui256, Storage>, !sol.ptr<!sol.array<1267650600228229401496703205376 x ui256, Storage>, Stack> loc(#loc26)
// CHECK-NEXT:       %4 = sol.load %3 : !sol.ptr<!sol.array<1267650600228229401496703205376 x ui256, Storage>, Stack>, !sol.array<1267650600228229401496703205376 x ui256, Storage> loc(#loc27)
// CHECK-NEXT:       %5 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc28)
// CHECK-NEXT:       %6 = sol.gep %4, %5 : !sol.array<1267650600228229401496703205376 x ui256, Storage>, ui256, !sol.ptr<ui256, Storage> loc(#loc27)
// CHECK-NEXT:       %7 = sol.load %1 : !sol.ptr<ui256, Stack>, ui256 loc(#loc29)
// CHECK-NEXT:       sol.store %7, %6 : ui256, !sol.ptr<ui256, Storage> loc(#loc27)
// CHECK-NEXT:       sol.return loc(#loc23)
// CHECK-NEXT:     } loc(#loc23)
// CHECK-NEXT:     sol.func @delStruct_126() attributes {id = 126 : i64, orig_fn_type = () -> (), selector = -776086975 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @s_46 : !sol.struct<(ui256, !sol.array<1180591620717411303424 x ui256, Storage>), Storage> loc(#loc4)
// CHECK-NEXT:       sol.delete %0 : !sol.struct<(ui256, !sol.array<1180591620717411303424 x ui256, Storage>), Storage> loc(#loc31)
// CHECK-NEXT:       sol.return loc(#loc30)
// CHECK-NEXT:     } loc(#loc30)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:9:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:10:4)
// CHECK-NEXT: #loc3 = loc({{.*}}:11:4)
// CHECK-NEXT: #loc4 = loc({{.*}}:17:4)
// CHECK-NEXT: #loc5 = loc({{.*}}:19:4)
// CHECK-NEXT: #loc8 = loc({{.*}}:20:10)
// CHECK-NEXT: #loc9 = loc({{.*}}:20:8)
// CHECK-NEXT: #loc10 = loc({{.*}}:20:15)
// CHECK-NEXT: #loc11 = loc({{.*}}:23:4)
// CHECK-NEXT: #loc13 = loc({{.*}}:24:17)
// CHECK-NEXT: #loc14 = loc({{.*}}:24:15)
// CHECK-NEXT: #loc15 = loc({{.*}}:24:8)
// CHECK-NEXT: #loc16 = loc({{.*}}:27:4)
// CHECK-NEXT: #loc17 = loc({{.*}}:28:8)
// CHECK-NEXT: #loc18 = loc({{.*}}:31:4)
// CHECK-NEXT: #loc19 = loc({{.*}}:32:8)
// CHECK-NEXT: #loc20 = loc({{.*}}:35:4)
// CHECK-NEXT: #loc21 = loc({{.*}}:36:15)
// CHECK-NEXT: #loc22 = loc({{.*}}:36:8)
// CHECK-NEXT: #loc23 = loc({{.*}}:39:4)
// CHECK-NEXT: #loc26 = loc({{.*}}:40:8)
// CHECK-NEXT: #loc27 = loc({{.*}}:41:8)
// CHECK-NEXT: #loc28 = loc({{.*}}:41:10)
// CHECK-NEXT: #loc29 = loc({{.*}}:41:15)
// CHECK-NEXT: #loc30 = loc({{.*}}:44:4)
// CHECK-NEXT: #loc31 = loc({{.*}}:45:8)
// CHECK-EMPTY:
