// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
  function f(uint256 x) public pure returns (uint256 r) {
    assembly {
      switch x
      case 1 {
        r := 1
      }
      case 100000000000000000000 {
        r := 20
      }
      case 1000000000000000000000000000000 {
        r := 30
      }
      default {
        r := 0
      }
    }
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #Pure = #sol<StateMutability Pure>
// CHECK-NEXT: #loc3 = loc({{.*}}:3:13)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @C_10 {
// CHECK-NEXT:     sol.func @C_10() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @f_9(%arg0: ui256 loc({{.*}}:3:13)) -> ui256 attributes {id = 9 : i64, orig_fn_type = (ui256) -> ui256, selector = -1277270901 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc4)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc4)
// CHECK-NEXT:       sol.store %c0_ui256, %1 : ui256, !sol.ptr<ui256, Stack> loc(#loc4)
// CHECK-NEXT:       sol.inline_asm {
// CHECK-NEXT:         %3 = sol.yul_ptr_cast %0 : !sol.ptr<ui256, Stack> -> !yul.ptr loc(#loc5)
// CHECK-NEXT:         %4 = yul.load %3 : !yul.ptr -> i256 loc(#loc6)
// CHECK-NEXT:         yul.switch %4 : i256
// CHECK-NEXT:         case 1 {
// CHECK-NEXT:           %c1_i256 = yul.constant 1 loc(#loc8)
// CHECK-NEXT:           %5 = sol.yul_ptr_cast %1 : !sol.ptr<ui256, Stack> -> !yul.ptr loc(#loc5)
// CHECK-NEXT:           yul.store %c1_i256, %5 : i256, !yul.ptr loc(#loc9)
// CHECK-NEXT:           yul.yield loc(#loc7)
// CHECK-NEXT:         }
// CHECK-NEXT:         case 100000000000000000000 {
// CHECK-NEXT:           %c20_i256 = yul.constant 20 loc(#loc10)
// CHECK-NEXT:           %5 = sol.yul_ptr_cast %1 : !sol.ptr<ui256, Stack> -> !yul.ptr loc(#loc5)
// CHECK-NEXT:           yul.store %c20_i256, %5 : i256, !yul.ptr loc(#loc11)
// CHECK-NEXT:           yul.yield loc(#loc7)
// CHECK-NEXT:         }
// CHECK-NEXT:         case 1000000000000000000000000000000 {
// CHECK-NEXT:           %c30_i256 = yul.constant 30 loc(#loc12)
// CHECK-NEXT:           %5 = sol.yul_ptr_cast %1 : !sol.ptr<ui256, Stack> -> !yul.ptr loc(#loc5)
// CHECK-NEXT:           yul.store %c30_i256, %5 : i256, !yul.ptr loc(#loc13)
// CHECK-NEXT:           yul.yield loc(#loc7)
// CHECK-NEXT:         }
// CHECK-NEXT:         default {
// CHECK-NEXT:           %c0_i256 = yul.constant 0 loc(#loc14)
// CHECK-NEXT:           %5 = sol.yul_ptr_cast %1 : !sol.ptr<ui256, Stack> -> !yul.ptr loc(#loc5)
// CHECK-NEXT:           yul.store %c0_i256, %5 : i256, !yul.ptr loc(#loc15)
// CHECK-NEXT:           yul.yield loc(#loc7)
// CHECK-NEXT:         } loc(#loc7)
// CHECK-NEXT:       } loc(#loc5)
// CHECK-NEXT:       %2 = sol.load %1 : !sol.ptr<ui256, Stack>, ui256 loc(#loc2)
// CHECK-NEXT:       sol.return %2 : ui256 loc(#loc2)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:3:2)
// CHECK-NEXT: #loc4 = loc({{.*}}:3:45)
// CHECK-NEXT: #loc5 = loc({{.*}}:4:4)
// CHECK-NEXT: #loc6 = loc({{.*}}:5:13)
// CHECK-NEXT: #loc7 = loc({{.*}}:5:6)
// CHECK-NEXT: #loc8 = loc({{.*}}:7:13)
// CHECK-NEXT: #loc9 = loc({{.*}}:7:8)
// CHECK-NEXT: #loc10 = loc({{.*}}:10:13)
// CHECK-NEXT: #loc11 = loc({{.*}}:10:8)
// CHECK-NEXT: #loc12 = loc({{.*}}:13:13)
// CHECK-NEXT: #loc13 = loc({{.*}}:13:8)
// CHECK-NEXT: #loc14 = loc({{.*}}:16:13)
// CHECK-NEXT: #loc15 = loc({{.*}}:16:8)
// CHECK-EMPTY:
