// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

// Tests three cleanup scenarios when copying bytes to storage:
//
// 1. new_after_event: sol.malloc for new bytes(N) must carry zero_init so that
//    stale data written by event ABI encoding (which reuses the same scratch
//    region without advancing the free pointer) cannot leak into storage.
//
// 2. dirty_past_end: a byte written at offset (length) inside the last
//    32-byte word via inline assembly must not appear in storage; the partial
//    last slot must be masked before the store.
//
// 3. calldata_to_storage: calldata bytes whose final ABI word carries dirty
//    high bits beyond the declared length must be masked before storing;
//    s.push() must extend cleanly.

contract C {
    event Ev(uint[], uint);
    bytes public s;

    function new_after_event() external returns (bytes memory) {
        uint[] memory x = new uint[](2);
        emit Ev(x, 0x21);
        bytes memory m = new bytes(63);
        s = m;
        s.push();
        return s;
    }

    function dirty_past_end() external returns (bytes memory) {
        bytes memory m = new bytes(63);
        assembly {
            mstore8(add(m, add(32, 63)), 0x42)
        }
        s = m;
        s.push();
        return s;
    }

    function calldata_to_storage(bytes calldata c) external returns (bytes memory) {
        s = c;
        s.push();
        return s;
    }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #loc36 = loc({{.*}}:39:33)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @C_94 {
// CHECK-NEXT:     sol.state_var @s_9 slot 0 offset 0 : !sol.string<Storage> loc(#loc2)
// CHECK-NEXT:     sol.func @get_s_9() -> !sol.string<Memory> attributes {orig_fn_type = () -> !sol.string<Memory>, selector = -2034821918 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @s_9 : !sol.string<Storage> loc(#loc2)
// CHECK-NEXT:       %1 = sol.data_loc_cast %0 : !sol.string<Storage>, !sol.string<Memory> loc(#loc2)
// CHECK-NEXT:       sol.return %1 : !sol.string<Memory> loc(#loc2)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     sol.func @C_94() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @new_after_event_49() -> !sol.string<Memory> attributes {id = 49 : i64, orig_fn_type = () -> !sol.string<Memory>, selector = 256580655 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc4)
// CHECK-NEXT:       %1 = sol.malloc :  !sol.string<Memory> loc(#loc4)
// CHECK-NEXT:       sol.store %1, %0 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc4)
// CHECK-NEXT:       %c2_ui8 = sol.constant 2 : ui8 loc(#loc5)
// CHECK-NEXT:       %2 = sol.malloc %c2_ui8 zero_init : ui8 !sol.array<? x ui256, Memory> loc(#loc6)
// CHECK-NEXT:       %3 = sol.alloca : !sol.ptr<!sol.array<? x ui256, Memory>, Stack> loc(#loc7)
// CHECK-NEXT:       sol.store %2, %3 : !sol.array<? x ui256, Memory>, !sol.ptr<!sol.array<? x ui256, Memory>, Stack> loc(#loc7)
// CHECK-NEXT:       %4 = sol.load %3 : !sol.ptr<!sol.array<? x ui256, Memory>, Stack>, !sol.array<? x ui256, Memory> loc(#loc8)
// CHECK-NEXT:       %c33_ui8 = sol.constant 33 : ui8 loc(#loc9)
// CHECK-NEXT:       %5 = sol.cast %c33_ui8 : ui8 to ui256 loc(#loc9)
// CHECK-NEXT:       sol.emit "Ev(uint256[],uint256)" non_indexed = [%4, %5] : !sol.array<? x ui256, Memory>, ui256 loc(#loc10)
// CHECK-NEXT:       %c63_ui8 = sol.constant 63 : ui8 loc(#loc11)
// CHECK-NEXT:       %6 = sol.malloc %c63_ui8 zero_init : ui8 !sol.string<Memory> loc(#loc12)
// CHECK-NEXT:       %7 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc13)
// CHECK-NEXT:       sol.store %6, %7 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc13)
// CHECK-NEXT:       %8 = sol.load %7 : !sol.ptr<!sol.string<Memory>, Stack>, !sol.string<Memory> loc(#loc14)
// CHECK-NEXT:       %9 = sol.addr_of @s_9 : !sol.string<Storage> loc(#loc2)
// CHECK-NEXT:       sol.copy %8, %9 : !sol.string<Memory>, !sol.string<Storage> loc(#loc15)
// CHECK-NEXT:       %10 = sol.addr_of @s_9 : !sol.string<Storage> loc(#loc2)
// CHECK-NEXT:       %11 = sol.push %10 : !sol.string<Storage> -> !sol.ptr<!sol.byte, Storage> loc(#loc16)
// CHECK-NEXT:       %12 = sol.addr_of @s_9 : !sol.string<Storage> loc(#loc2)
// CHECK-NEXT:       %13 = sol.data_loc_cast %12 : !sol.string<Storage>, !sol.string<Memory> loc(#loc2)
// CHECK-NEXT:       sol.return %13 : !sol.string<Memory> loc(#loc17)
// CHECK-NEXT:     } loc(#loc3)
// CHECK-NEXT:     sol.func @dirty_past_end_74() -> !sol.string<Memory> attributes {id = 74 : i64, orig_fn_type = () -> !sol.string<Memory>, selector = -1831565415 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc19)
// CHECK-NEXT:       %1 = sol.malloc :  !sol.string<Memory> loc(#loc19)
// CHECK-NEXT:       sol.store %1, %0 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc19)
// CHECK-NEXT:       %c63_ui8 = sol.constant 63 : ui8 loc(#loc20)
// CHECK-NEXT:       %2 = sol.malloc %c63_ui8 zero_init : ui8 !sol.string<Memory> loc(#loc21)
// CHECK-NEXT:       %3 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc22)
// CHECK-NEXT:       sol.store %2, %3 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc22)
// CHECK-NEXT:       sol.inline_asm {
// CHECK-NEXT:         %10 = sol.yul_ptr_cast %3 : !sol.ptr<!sol.string<Memory>, Stack> -> !yul.ptr loc(#loc23)
// CHECK-NEXT:         %11 = yul.load %10 : !yul.ptr -> i256 loc(#loc24)
// CHECK-NEXT:         %c32_i256 = yul.constant 32 loc(#loc25)
// CHECK-NEXT:         %c63_i256 = yul.constant 63 loc(#loc26)
// CHECK-NEXT:         %12 = yul.add %c32_i256, %c63_i256 loc(#loc27)
// CHECK-NEXT:         %13 = yul.add %11, %12 loc(#loc28)
// CHECK-NEXT:         %c66_i256 = yul.constant 66 loc(#loc29)
// CHECK-NEXT:         yul.mstore8 %13, %c66_i256 loc(#loc30)
// CHECK-NEXT:       } loc(#loc23)
// CHECK-NEXT:       %4 = sol.load %3 : !sol.ptr<!sol.string<Memory>, Stack>, !sol.string<Memory> loc(#loc31)
// CHECK-NEXT:       %5 = sol.addr_of @s_9 : !sol.string<Storage> loc(#loc2)
// CHECK-NEXT:       sol.copy %4, %5 : !sol.string<Memory>, !sol.string<Storage> loc(#loc32)
// CHECK-NEXT:       %6 = sol.addr_of @s_9 : !sol.string<Storage> loc(#loc2)
// CHECK-NEXT:       %7 = sol.push %6 : !sol.string<Storage> -> !sol.ptr<!sol.byte, Storage> loc(#loc33)
// CHECK-NEXT:       %8 = sol.addr_of @s_9 : !sol.string<Storage> loc(#loc2)
// CHECK-NEXT:       %9 = sol.data_loc_cast %8 : !sol.string<Storage>, !sol.string<Memory> loc(#loc2)
// CHECK-NEXT:       sol.return %9 : !sol.string<Memory> loc(#loc34)
// CHECK-NEXT:     } loc(#loc18)
// CHECK-NEXT:     sol.func @calldata_to_storage_93(%arg0: !sol.string<CallData> loc({{.*}}:39:33)) -> !sol.string<Memory> attributes {id = 93 : i64, orig_fn_type = (!sol.string<CallData>) -> !sol.string<Memory>, selector = 1725830022 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<CallData>, Stack> loc(#loc36)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.string<CallData>, !sol.ptr<!sol.string<CallData>, Stack> loc(#loc36)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc37)
// CHECK-NEXT:       %2 = sol.malloc :  !sol.string<Memory> loc(#loc37)
// CHECK-NEXT:       sol.store %2, %1 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc37)
// CHECK-NEXT:       %3 = sol.load %0 : !sol.ptr<!sol.string<CallData>, Stack>, !sol.string<CallData> loc(#loc38)
// CHECK-NEXT:       %4 = sol.addr_of @s_9 : !sol.string<Storage> loc(#loc2)
// CHECK-NEXT:       sol.copy %3, %4 : !sol.string<CallData>, !sol.string<Storage> loc(#loc39)
// CHECK-NEXT:       %5 = sol.addr_of @s_9 : !sol.string<Storage> loc(#loc2)
// CHECK-NEXT:       %6 = sol.push %5 : !sol.string<Storage> -> !sol.ptr<!sol.byte, Storage> loc(#loc40)
// CHECK-NEXT:       %7 = sol.addr_of @s_9 : !sol.string<Storage> loc(#loc2)
// CHECK-NEXT:       %8 = sol.data_loc_cast %7 : !sol.string<Storage>, !sol.string<Memory> loc(#loc2)
// CHECK-NEXT:       sol.return %8 : !sol.string<Memory> loc(#loc41)
// CHECK-NEXT:     } loc(#loc35)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:16:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:18:4)
// CHECK-NEXT: #loc3 = loc({{.*}}:20:4)
// CHECK-NEXT: #loc4 = loc({{.*}}:20:49)
// CHECK-NEXT: #loc5 = loc({{.*}}:21:37)
// CHECK-NEXT: #loc6 = loc({{.*}}:21:26)
// CHECK-NEXT: #loc7 = loc({{.*}}:21:8)
// CHECK-NEXT: #loc8 = loc({{.*}}:22:16)
// CHECK-NEXT: #loc9 = loc({{.*}}:22:19)
// CHECK-NEXT: #loc10 = loc({{.*}}:22:13)
// CHECK-NEXT: #loc11 = loc({{.*}}:23:35)
// CHECK-NEXT: #loc12 = loc({{.*}}:23:25)
// CHECK-NEXT: #loc13 = loc({{.*}}:23:8)
// CHECK-NEXT: #loc14 = loc({{.*}}:24:12)
// CHECK-NEXT: #loc15 = loc({{.*}}:24:8)
// CHECK-NEXT: #loc16 = loc({{.*}}:25:8)
// CHECK-NEXT: #loc17 = loc({{.*}}:26:8)
// CHECK-NEXT: #loc18 = loc({{.*}}:29:4)
// CHECK-NEXT: #loc19 = loc({{.*}}:29:48)
// CHECK-NEXT: #loc20 = loc({{.*}}:30:35)
// CHECK-NEXT: #loc21 = loc({{.*}}:30:25)
// CHECK-NEXT: #loc22 = loc({{.*}}:30:8)
// CHECK-NEXT: #loc23 = loc({{.*}}:31:8)
// CHECK-NEXT: #loc24 = loc({{.*}}:32:24)
// CHECK-NEXT: #loc25 = loc({{.*}}:32:31)
// CHECK-NEXT: #loc26 = loc({{.*}}:32:35)
// CHECK-NEXT: #loc27 = loc({{.*}}:32:27)
// CHECK-NEXT: #loc28 = loc({{.*}}:32:20)
// CHECK-NEXT: #loc29 = loc({{.*}}:32:41)
// CHECK-NEXT: #loc30 = loc({{.*}}:32:12)
// CHECK-NEXT: #loc31 = loc({{.*}}:34:12)
// CHECK-NEXT: #loc32 = loc({{.*}}:34:8)
// CHECK-NEXT: #loc33 = loc({{.*}}:35:8)
// CHECK-NEXT: #loc34 = loc({{.*}}:36:8)
// CHECK-NEXT: #loc35 = loc({{.*}}:39:4)
// CHECK-NEXT: #loc37 = loc({{.*}}:39:69)
// CHECK-NEXT: #loc38 = loc({{.*}}:40:12)
// CHECK-NEXT: #loc39 = loc({{.*}}:40:8)
// CHECK-NEXT: #loc40 = loc({{.*}}:41:8)
// CHECK-NEXT: #loc41 = loc({{.*}}:42:8)
// CHECK-EMPTY:
