// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
  bytes data;

  function readBytes1(bytes memory a) public returns (bytes1) {
    return a[1];
  }

  function readBytes2(bytes memory a) public returns (bytes2) {
    return bytes2(a[1]);
  }

  function storeBytesMemory(bytes memory a, bytes1 x) public returns (bytes1) {
    a[4] = x;
    return a[4];
  }

  function readStorage() public returns (bytes1) {
    return data[1];
  }

  function writeStorage(bytes1 x) public returns (bytes1) {
    data[4] = x;
    return data[4];
  }

  function storeLiteral(bytes memory a) public returns (bytes1) {
    a[0] = "X";
    return a[0];
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #loc4 = loc({{.*}}:5:22)
// CHECK-NEXT: #loc9 = loc({{.*}}:9:22)
// CHECK-NEXT: #loc14 = loc({{.*}}:13:28)
// CHECK-NEXT: #loc15 = loc({{.*}}:13:44)
// CHECK-NEXT: #loc27 = loc({{.*}}:22:24)
// CHECK-NEXT: #loc35 = loc({{.*}}:27:24)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @C_96 {
// CHECK-NEXT:     sol.state_var @data_2 slot 0 offset 0 : !sol.string<Storage> loc(#loc2)
// CHECK-NEXT:     sol.func @C_96() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @readBytes1_14(%arg0: !sol.string<Memory> loc({{.*}}:5:22)) -> !sol.fixedbytes<1> attributes {id = 14 : i64, orig_fn_type = (!sol.string<Memory>) -> !sol.fixedbytes<1>, selector = 1724325524 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc4)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc4)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<!sol.string<Memory>, Stack>, !sol.string<Memory> loc(#loc5)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc6)
// CHECK-NEXT:       %2 = sol.gep %1, %c1_ui8 : !sol.string<Memory>, ui8, !sol.ptr<!sol.byte, Memory> loc(#loc5)
// CHECK-NEXT:       %3 = sol.load %2 : !sol.ptr<!sol.byte, Memory>, !sol.byte loc(#loc5)
// CHECK-NEXT:       %4 = sol.bytes_cast %3 : !sol.byte to !sol.fixedbytes<1> loc(#loc5)
// CHECK-NEXT:       sol.return %4 : !sol.fixedbytes<1> loc(#loc7)
// CHECK-NEXT:     } loc(#loc3)
// CHECK-NEXT:     sol.func @readBytes2_29(%arg0: !sol.string<Memory> loc({{.*}}:9:22)) -> !sol.fixedbytes<2> attributes {id = 29 : i64, orig_fn_type = (!sol.string<Memory>) -> !sol.fixedbytes<2>, selector = 311712088 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc9)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc9)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<!sol.string<Memory>, Stack>, !sol.string<Memory> loc(#loc10)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc11)
// CHECK-NEXT:       %2 = sol.gep %1, %c1_ui8 : !sol.string<Memory>, ui8, !sol.ptr<!sol.byte, Memory> loc(#loc10)
// CHECK-NEXT:       %3 = sol.load %2 : !sol.ptr<!sol.byte, Memory>, !sol.byte loc(#loc10)
// CHECK-NEXT:       %4 = sol.bytes_cast %3 : !sol.byte to !sol.fixedbytes<2> loc(#loc10)
// CHECK-NEXT:       sol.return %4 : !sol.fixedbytes<2> loc(#loc12)
// CHECK-NEXT:     } loc(#loc8)
// CHECK-NEXT:     sol.func @storeBytesMemory_49(%arg0: !sol.string<Memory> loc({{.*}}:13:28), %arg1: !sol.fixedbytes<1> loc({{.*}}:13:44)) -> !sol.fixedbytes<1> attributes {id = 49 : i64, orig_fn_type = (!sol.string<Memory>, !sol.fixedbytes<1>) -> !sol.fixedbytes<1>, selector = 709329944 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc14)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc14)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.fixedbytes<1>, Stack> loc(#loc15)
// CHECK-NEXT:       sol.store %arg1, %1 : !sol.fixedbytes<1>, !sol.ptr<!sol.fixedbytes<1>, Stack> loc(#loc15)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.string<Memory>, Stack>, !sol.string<Memory> loc(#loc16)
// CHECK-NEXT:       %c4_ui8 = sol.constant 4 : ui8 loc(#loc17)
// CHECK-NEXT:       %3 = sol.gep %2, %c4_ui8 : !sol.string<Memory>, ui8, !sol.ptr<!sol.byte, Memory> loc(#loc16)
// CHECK-NEXT:       %4 = sol.load %1 : !sol.ptr<!sol.fixedbytes<1>, Stack>, !sol.fixedbytes<1> loc(#loc18)
// CHECK-NEXT:       %5 = sol.bytes_cast %4 : !sol.fixedbytes<1> to !sol.byte loc(#loc18)
// CHECK-NEXT:       sol.store %5, %3 : !sol.byte, !sol.ptr<!sol.byte, Memory> loc(#loc16)
// CHECK-NEXT:       %6 = sol.load %0 : !sol.ptr<!sol.string<Memory>, Stack>, !sol.string<Memory> loc(#loc19)
// CHECK-NEXT:       %c4_ui8_0 = sol.constant 4 : ui8 loc(#loc20)
// CHECK-NEXT:       %7 = sol.gep %6, %c4_ui8_0 : !sol.string<Memory>, ui8, !sol.ptr<!sol.byte, Memory> loc(#loc19)
// CHECK-NEXT:       %8 = sol.load %7 : !sol.ptr<!sol.byte, Memory>, !sol.byte loc(#loc19)
// CHECK-NEXT:       %9 = sol.bytes_cast %8 : !sol.byte to !sol.fixedbytes<1> loc(#loc19)
// CHECK-NEXT:       sol.return %9 : !sol.fixedbytes<1> loc(#loc21)
// CHECK-NEXT:     } loc(#loc13)
// CHECK-NEXT:     sol.func @readStorage_59() -> !sol.fixedbytes<1> attributes {id = 59 : i64, orig_fn_type = () -> !sol.fixedbytes<1>, selector = 838524383 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @data_2 : !sol.string<Storage> loc(#loc2)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc23)
// CHECK-NEXT:       %1 = sol.gep %0, %c1_ui8 : !sol.string<Storage>, ui8, !sol.ptr<!sol.byte, Storage> loc(#loc24)
// CHECK-NEXT:       %2 = sol.load %1 : !sol.ptr<!sol.byte, Storage>, !sol.byte loc(#loc24)
// CHECK-NEXT:       %3 = sol.bytes_cast %2 : !sol.byte to !sol.fixedbytes<1> loc(#loc24)
// CHECK-NEXT:       sol.return %3 : !sol.fixedbytes<1> loc(#loc25)
// CHECK-NEXT:     } loc(#loc22)
// CHECK-NEXT:     sol.func @writeStorage_77(%arg0: !sol.fixedbytes<1> loc({{.*}}:22:24)) -> !sol.fixedbytes<1> attributes {id = 77 : i64, orig_fn_type = (!sol.fixedbytes<1>) -> !sol.fixedbytes<1>, selector = 1404230888 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.fixedbytes<1>, Stack> loc(#loc27)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.fixedbytes<1>, !sol.ptr<!sol.fixedbytes<1>, Stack> loc(#loc27)
// CHECK-NEXT:       %1 = sol.addr_of @data_2 : !sol.string<Storage> loc(#loc2)
// CHECK-NEXT:       %c4_ui8 = sol.constant 4 : ui8 loc(#loc28)
// CHECK-NEXT:       %2 = sol.gep %1, %c4_ui8 : !sol.string<Storage>, ui8, !sol.ptr<!sol.byte, Storage> loc(#loc29)
// CHECK-NEXT:       %3 = sol.load %0 : !sol.ptr<!sol.fixedbytes<1>, Stack>, !sol.fixedbytes<1> loc(#loc30)
// CHECK-NEXT:       %4 = sol.bytes_cast %3 : !sol.fixedbytes<1> to !sol.byte loc(#loc30)
// CHECK-NEXT:       sol.store %4, %2 : !sol.byte, !sol.ptr<!sol.byte, Storage> loc(#loc29)
// CHECK-NEXT:       %5 = sol.addr_of @data_2 : !sol.string<Storage> loc(#loc2)
// CHECK-NEXT:       %c4_ui8_0 = sol.constant 4 : ui8 loc(#loc31)
// CHECK-NEXT:       %6 = sol.gep %5, %c4_ui8_0 : !sol.string<Storage>, ui8, !sol.ptr<!sol.byte, Storage> loc(#loc32)
// CHECK-NEXT:       %7 = sol.load %6 : !sol.ptr<!sol.byte, Storage>, !sol.byte loc(#loc32)
// CHECK-NEXT:       %8 = sol.bytes_cast %7 : !sol.byte to !sol.fixedbytes<1> loc(#loc32)
// CHECK-NEXT:       sol.return %8 : !sol.fixedbytes<1> loc(#loc33)
// CHECK-NEXT:     } loc(#loc26)
// CHECK-NEXT:     sol.func @storeLiteral_95(%arg0: !sol.string<Memory> loc({{.*}}:27:24)) -> !sol.fixedbytes<1> attributes {id = 95 : i64, orig_fn_type = (!sol.string<Memory>) -> !sol.fixedbytes<1>, selector = 1806029979 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc35)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc35)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<!sol.string<Memory>, Stack>, !sol.string<Memory> loc(#loc36)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc37)
// CHECK-NEXT:       %2 = sol.gep %1, %c0_ui8 : !sol.string<Memory>, ui8, !sol.ptr<!sol.byte, Memory> loc(#loc36)
// CHECK-NEXT:       %3 = sol.string_lit "X" -> !sol.string<Memory> loc(#loc38)
// CHECK-NEXT:       %c88_ui8 = sol.constant 88 : ui8 loc(#loc38)
// CHECK-NEXT:       %4 = sol.bytes_cast %c88_ui8 : ui8 to !sol.byte loc(#loc38)
// CHECK-NEXT:       sol.store %4, %2 : !sol.byte, !sol.ptr<!sol.byte, Memory> loc(#loc36)
// CHECK-NEXT:       %5 = sol.load %0 : !sol.ptr<!sol.string<Memory>, Stack>, !sol.string<Memory> loc(#loc39)
// CHECK-NEXT:       %c0_ui8_0 = sol.constant 0 : ui8 loc(#loc40)
// CHECK-NEXT:       %6 = sol.gep %5, %c0_ui8_0 : !sol.string<Memory>, ui8, !sol.ptr<!sol.byte, Memory> loc(#loc39)
// CHECK-NEXT:       %7 = sol.load %6 : !sol.ptr<!sol.byte, Memory>, !sol.byte loc(#loc39)
// CHECK-NEXT:       %8 = sol.bytes_cast %7 : !sol.byte to !sol.fixedbytes<1> loc(#loc39)
// CHECK-NEXT:       sol.return %8 : !sol.fixedbytes<1> loc(#loc41)
// CHECK-NEXT:     } loc(#loc34)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:3:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:5:2)
// CHECK-NEXT: #loc5 = loc({{.*}}:6:11)
// CHECK-NEXT: #loc6 = loc({{.*}}:6:13)
// CHECK-NEXT: #loc7 = loc({{.*}}:6:4)
// CHECK-NEXT: #loc8 = loc({{.*}}:9:2)
// CHECK-NEXT: #loc10 = loc({{.*}}:10:18)
// CHECK-NEXT: #loc11 = loc({{.*}}:10:20)
// CHECK-NEXT: #loc12 = loc({{.*}}:10:4)
// CHECK-NEXT: #loc13 = loc({{.*}}:13:2)
// CHECK-NEXT: #loc16 = loc({{.*}}:14:4)
// CHECK-NEXT: #loc17 = loc({{.*}}:14:6)
// CHECK-NEXT: #loc18 = loc({{.*}}:14:11)
// CHECK-NEXT: #loc19 = loc({{.*}}:15:11)
// CHECK-NEXT: #loc20 = loc({{.*}}:15:13)
// CHECK-NEXT: #loc21 = loc({{.*}}:15:4)
// CHECK-NEXT: #loc22 = loc({{.*}}:18:2)
// CHECK-NEXT: #loc23 = loc({{.*}}:19:16)
// CHECK-NEXT: #loc24 = loc({{.*}}:19:11)
// CHECK-NEXT: #loc25 = loc({{.*}}:19:4)
// CHECK-NEXT: #loc26 = loc({{.*}}:22:2)
// CHECK-NEXT: #loc28 = loc({{.*}}:23:9)
// CHECK-NEXT: #loc29 = loc({{.*}}:23:4)
// CHECK-NEXT: #loc30 = loc({{.*}}:23:14)
// CHECK-NEXT: #loc31 = loc({{.*}}:24:16)
// CHECK-NEXT: #loc32 = loc({{.*}}:24:11)
// CHECK-NEXT: #loc33 = loc({{.*}}:24:4)
// CHECK-NEXT: #loc34 = loc({{.*}}:27:2)
// CHECK-NEXT: #loc36 = loc({{.*}}:28:4)
// CHECK-NEXT: #loc37 = loc({{.*}}:28:6)
// CHECK-NEXT: #loc38 = loc({{.*}}:28:11)
// CHECK-NEXT: #loc39 = loc({{.*}}:29:11)
// CHECK-NEXT: #loc40 = loc({{.*}}:29:13)
// CHECK-NEXT: #loc41 = loc({{.*}}:29:4)
// CHECK-EMPTY:
