// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
  uint public value = 11;

  struct S {
    function() external view returns (uint) fn;
  }

  function g() public view returns (uint) {
    return 7;
  }

  function directGetter() public view returns (uint) {
    return this.value();
  }

  function getterPointer() public view returns (uint) {
    function() external view returns (uint) fp = this.value;
    return fp();
  }

  function getterStruct() public view returns (uint) {
    S memory s;
    s.fn = this.value;
    return s.fn();
  }

  function functionStruct() public view returns (uint) {
    S memory s;
    s.fn = this.g;
    return s.fn();
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #View = #sol<StateMutability View>
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @C_89 {
// CHECK-NEXT:     sol.state_var @value_3 slot 0 offset 0 : ui256 loc(#loc2)
// CHECK-NEXT:     sol.func @get_value_3() -> ui256 attributes {orig_fn_type = () -> ui256, selector = 1067774533 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @value_3 : !sol.ptr<ui256, Storage> loc(#loc2)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<ui256, Storage>, ui256 loc(#loc2)
// CHECK-NEXT:       sol.return %1 : ui256 loc(#loc2)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     sol.func @C_89() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @value_3 : !sol.ptr<ui256, Storage> loc(#loc2)
// CHECK-NEXT:       %c11_ui8 = sol.constant 11 : ui8 loc(#loc3)
// CHECK-NEXT:       %1 = sol.cast %c11_ui8 : ui8 to ui256 loc(#loc3)
// CHECK-NEXT:       sol.store %1, %0 : ui256, !sol.ptr<ui256, Storage> loc(#loc2)
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @g_18() -> ui256 attributes {id = 18 : i64, orig_fn_type = () -> ui256, selector = -501769330 : i32, state_mutability = #View} {
// CHECK-NEXT:       %c7_ui8 = sol.constant 7 : ui8 loc(#loc5)
// CHECK-NEXT:       %0 = sol.cast %c7_ui8 : ui8 to ui256 loc(#loc5)
// CHECK-NEXT:       sol.return %0 : ui256 loc(#loc6)
// CHECK-NEXT:     } loc(#loc4)
// CHECK-NEXT:     sol.func @directGetter_28() -> ui256 attributes {id = 28 : i64, orig_fn_type = () -> ui256, selector = 1643294894 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.this : !sol.contract<"C_89"> loc(#loc8)
// CHECK-NEXT:       %1 = sol.address_cast %0 : !sol.contract<"C_89"> to !sol.address loc(#loc8)
// CHECK-NEXT:       %c1067774533_ui256 = sol.constant 1067774533 : ui256 loc(#loc8)
// CHECK-NEXT:       %2 = sol.gasleft : ui256 loc(#loc8)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc8)
// CHECK-NEXT:       %status, %3 = sol.ext_call "get_value_3"() at %1 gas %2 value %c0_ui256 selector %c1067774533_ui256 {callee_type = () -> ui256, static_call} : !sol.address, () -> (i1, ui256) loc(#loc8)
// CHECK-NEXT:       sol.return %3 : ui256 loc(#loc9)
// CHECK-NEXT:     } loc(#loc7)
// CHECK-NEXT:     sol.func @getterPointer_46() -> ui256 attributes {id = 46 : i64, orig_fn_type = () -> ui256, selector = 669862793 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.this : !sol.contract<"C_89"> loc(#loc11)
// CHECK-NEXT:       %1 = sol.address_cast %0 : !sol.contract<"C_89"> to !sol.address loc(#loc11)
// CHECK-NEXT:       %2 = sol.ext_func_constant %1 {selector = 1067774533 : i32} : !sol.address -> !sol.ext_func_ref<() -> ui256> loc(#loc11)
// CHECK-NEXT:       %3 = sol.alloca : !sol.ptr<!sol.ext_func_ref<() -> ui256>, Stack> loc(#loc12)
// CHECK-NEXT:       sol.store %2, %3 : !sol.ext_func_ref<() -> ui256>, !sol.ptr<!sol.ext_func_ref<() -> ui256>, Stack> loc(#loc12)
// CHECK-NEXT:       %4 = sol.load %3 : !sol.ptr<!sol.ext_func_ref<() -> ui256>, Stack>, !sol.ext_func_ref<() -> ui256> loc(#loc13)
// CHECK-NEXT:       %5 = sol.gasleft : ui256 loc(#loc13)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc13)
// CHECK-NEXT:       %6:2 = sol.ext_icall %4() gas %5 value %c0_ui256 {static_call} : !sol.ext_func_ref<() -> ui256>, () -> (i1, ui256) loc(#loc13)
// CHECK-NEXT:       sol.return %6#1 : ui256 loc(#loc14)
// CHECK-NEXT:     } loc(#loc10)
// CHECK-NEXT:     sol.func @getterStruct_67() -> ui256 attributes {id = 67 : i64, orig_fn_type = () -> ui256, selector = 907433812 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory>, Stack> loc(#loc16)
// CHECK-NEXT:       %1 = sol.malloc zero_init :  !sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory> loc(#loc16)
// CHECK-NEXT:       sol.store %1, %0 : !sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory>, !sol.ptr<!sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory>, Stack> loc(#loc16)
// CHECK-NEXT:       %c0_ui64 = sol.constant 0 : ui64 loc(#loc17)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory>, Stack>, !sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory> loc(#loc17)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui64 : !sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory>, ui64, !sol.ptr<!sol.ext_func_ref<() -> ui256>, Memory> loc(#loc17)
// CHECK-NEXT:       %4 = sol.this : !sol.contract<"C_89"> loc(#loc18)
// CHECK-NEXT:       %5 = sol.address_cast %4 : !sol.contract<"C_89"> to !sol.address loc(#loc18)
// CHECK-NEXT:       %6 = sol.ext_func_constant %5 {selector = 1067774533 : i32} : !sol.address -> !sol.ext_func_ref<() -> ui256> loc(#loc18)
// CHECK-NEXT:       sol.store %6, %3 : !sol.ext_func_ref<() -> ui256>, !sol.ptr<!sol.ext_func_ref<() -> ui256>, Memory> loc(#loc17)
// CHECK-NEXT:       %c0_ui64_0 = sol.constant 0 : ui64 loc(#loc19)
// CHECK-NEXT:       %7 = sol.load %0 : !sol.ptr<!sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory>, Stack>, !sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory> loc(#loc19)
// CHECK-NEXT:       %8 = sol.gep %7, %c0_ui64_0 : !sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory>, ui64, !sol.ptr<!sol.ext_func_ref<() -> ui256>, Memory> loc(#loc19)
// CHECK-NEXT:       %9 = sol.load %8 : !sol.ptr<!sol.ext_func_ref<() -> ui256>, Memory>, !sol.ext_func_ref<() -> ui256> loc(#loc19)
// CHECK-NEXT:       %10 = sol.gasleft : ui256 loc(#loc19)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc19)
// CHECK-NEXT:       %11:2 = sol.ext_icall %9() gas %10 value %c0_ui256 {static_call} : !sol.ext_func_ref<() -> ui256>, () -> (i1, ui256) loc(#loc19)
// CHECK-NEXT:       sol.return %11#1 : ui256 loc(#loc20)
// CHECK-NEXT:     } loc(#loc15)
// CHECK-NEXT:     sol.func @functionStruct_88() -> ui256 attributes {id = 88 : i64, orig_fn_type = () -> ui256, selector = -131672527 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory>, Stack> loc(#loc22)
// CHECK-NEXT:       %1 = sol.malloc zero_init :  !sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory> loc(#loc22)
// CHECK-NEXT:       sol.store %1, %0 : !sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory>, !sol.ptr<!sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory>, Stack> loc(#loc22)
// CHECK-NEXT:       %c0_ui64 = sol.constant 0 : ui64 loc(#loc23)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory>, Stack>, !sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory> loc(#loc23)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui64 : !sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory>, ui64, !sol.ptr<!sol.ext_func_ref<() -> ui256>, Memory> loc(#loc23)
// CHECK-NEXT:       %4 = sol.this : !sol.contract<"C_89"> loc(#loc24)
// CHECK-NEXT:       %5 = sol.address_cast %4 : !sol.contract<"C_89"> to !sol.address loc(#loc24)
// CHECK-NEXT:       %6 = sol.ext_func_constant %5 {selector = -501769330 : i32} : !sol.address -> !sol.ext_func_ref<() -> ui256> loc(#loc24)
// CHECK-NEXT:       sol.store %6, %3 : !sol.ext_func_ref<() -> ui256>, !sol.ptr<!sol.ext_func_ref<() -> ui256>, Memory> loc(#loc23)
// CHECK-NEXT:       %c0_ui64_0 = sol.constant 0 : ui64 loc(#loc25)
// CHECK-NEXT:       %7 = sol.load %0 : !sol.ptr<!sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory>, Stack>, !sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory> loc(#loc25)
// CHECK-NEXT:       %8 = sol.gep %7, %c0_ui64_0 : !sol.struct<(!sol.ext_func_ref<() -> ui256>), Memory>, ui64, !sol.ptr<!sol.ext_func_ref<() -> ui256>, Memory> loc(#loc25)
// CHECK-NEXT:       %9 = sol.load %8 : !sol.ptr<!sol.ext_func_ref<() -> ui256>, Memory>, !sol.ext_func_ref<() -> ui256> loc(#loc25)
// CHECK-NEXT:       %10 = sol.gasleft : ui256 loc(#loc25)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc25)
// CHECK-NEXT:       %11:2 = sol.ext_icall %9() gas %10 value %c0_ui256 {static_call} : !sol.ext_func_ref<() -> ui256>, () -> (i1, ui256) loc(#loc25)
// CHECK-NEXT:       sol.return %11#1 : ui256 loc(#loc26)
// CHECK-NEXT:     } loc(#loc21)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:3:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:3:22)
// CHECK-NEXT: #loc4 = loc({{.*}}:9:2)
// CHECK-NEXT: #loc5 = loc({{.*}}:10:11)
// CHECK-NEXT: #loc6 = loc({{.*}}:10:4)
// CHECK-NEXT: #loc7 = loc({{.*}}:13:2)
// CHECK-NEXT: #loc8 = loc({{.*}}:14:11)
// CHECK-NEXT: #loc9 = loc({{.*}}:14:4)
// CHECK-NEXT: #loc10 = loc({{.*}}:17:2)
// CHECK-NEXT: #loc11 = loc({{.*}}:18:49)
// CHECK-NEXT: #loc12 = loc({{.*}}:18:4)
// CHECK-NEXT: #loc13 = loc({{.*}}:19:11)
// CHECK-NEXT: #loc14 = loc({{.*}}:19:4)
// CHECK-NEXT: #loc15 = loc({{.*}}:22:2)
// CHECK-NEXT: #loc16 = loc({{.*}}:23:4)
// CHECK-NEXT: #loc17 = loc({{.*}}:24:4)
// CHECK-NEXT: #loc18 = loc({{.*}}:24:11)
// CHECK-NEXT: #loc19 = loc({{.*}}:25:11)
// CHECK-NEXT: #loc20 = loc({{.*}}:25:4)
// CHECK-NEXT: #loc21 = loc({{.*}}:28:2)
// CHECK-NEXT: #loc22 = loc({{.*}}:29:4)
// CHECK-NEXT: #loc23 = loc({{.*}}:30:4)
// CHECK-NEXT: #loc24 = loc({{.*}}:30:11)
// CHECK-NEXT: #loc25 = loc({{.*}}:31:11)
// CHECK-NEXT: #loc26 = loc({{.*}}:31:4)
// CHECK-EMPTY:
