// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

function ret() returns (uint) { return 42; }
function no_ret(uint a) {}
function main() returns (uint) {
  no_ret(42);
  return ret();
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Prague = #sol<EvmVersion Prague>
// CHECK-NEXT: #loc5 = loc({{.*}}:3:16)
// CHECK-NEXT: module attributes {sol.evm_version = #Prague} {
// CHECK-NEXT:   sol.func @ret_8() -> ui256 attributes {state_mutability = #NonPayable} {
// CHECK-NEXT:     %c42_ui8 = sol.constant 42 : ui8 loc(#loc2)
// CHECK-NEXT:     %0 = sol.cast %c42_ui8 : ui8 to ui256 loc(#loc2)
// CHECK-NEXT:     sol.return %0 : ui256 loc(#loc3)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   sol.func @no_ret_14(%arg0: ui256 loc({{.*}}:3:16)) attributes {state_mutability = #NonPayable} {
// CHECK-NEXT:     %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc5)
// CHECK-NEXT:     sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc5)
// CHECK-NEXT:     sol.return loc(#loc4)
// CHECK-NEXT:   } loc(#loc4)
// CHECK-NEXT:   sol.func @main_27() -> ui256 attributes {state_mutability = #NonPayable} {
// CHECK-NEXT:     %c42_ui8 = sol.constant 42 : ui8 loc(#loc7)
// CHECK-NEXT:     %0 = sol.cast %c42_ui8 : ui8 to ui256 loc(#loc7)
// CHECK-NEXT:     sol.call @no_ret_14(%0) : (ui256) -> () loc(#loc8)
// CHECK-NEXT:     %1 = sol.call @ret_8() : () -> ui256 loc(#loc9)
// CHECK-NEXT:     sol.return %1 : ui256 loc(#loc10)
// CHECK-NEXT:   } loc(#loc6)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:2:39)
// CHECK-NEXT: #loc3 = loc({{.*}}:2:32)
// CHECK-NEXT: #loc4 = loc({{.*}}:3:0)
// CHECK-NEXT: #loc6 = loc({{.*}}:4:0)
// CHECK-NEXT: #loc7 = loc({{.*}}:5:9)
// CHECK-NEXT: #loc8 = loc({{.*}}:5:2)
// CHECK-NEXT: #loc9 = loc({{.*}}:6:9)
// CHECK-NEXT: #loc10 = loc({{.*}}:6:2)
// CHECK-EMPTY:
