// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract Delete {
    enum Status { Active, Inactive, Pending }

    struct Point { uint x; uint y; }
    struct WithMap { uint id; mapping(uint => uint) m; }
    struct Mixed {
        uint[3] fixedArr;
        uint[]  dynamicArr;
        mapping(uint => uint) m;
        address owner;
        bool    active;
    }

    uint    uintVar;
    bool    boolVar;
    address addrVar;
    bytes32 bytesVar;
    int16   intVar;
    Status  enumVar;

    uint[3] staticArr;
    uint[]  dynArr;

    Point[]   pointArr;
    Point[2]  pointFixed;
    WithMap[] withMapArr;
    mapping(uint => uint)[]   mapArr;
    mapping(uint => uint)[][] mapArr2D;
    Mixed   mixedS;
    WithMap withMapS;

    // delete on a uint state variable resets it to 0.
    function deleteUint() public {
        delete uintVar;
    }

    // delete on a bool resets it to false.
    function deleteBool() public {
        delete boolVar;
    }

    // delete on an address resets it to address(0).
    function deleteAddr() public {
        delete addrVar;
    }

    // delete on bytes32 resets it to 0.
    function deleteBytes() public {
        delete bytesVar;
    }

    // delete on a signed integer resets it to 0.
    function deleteInt() public {
        delete intVar;
    }

    // delete on an enum resets it to its first member (ordinal 0).
    function deleteEnum() public {
        delete enumVar;
    }

    // delete on a single element of a static array → sol.store of zero.
    function deleteStaticElem() public {
        staticArr[0] = 1; staticArr[1] = 2; staticArr[2] = 3;
        delete staticArr[1];
    }

    // delete on a whole static array → sol.delete clears all element slots.
    function deleteStaticArr() public {
        staticArr[0] = 1; staticArr[1] = 2; staticArr[2] = 3;
        delete staticArr;
    }

    // delete on a dynamic storage array → sol.delete clears length and data.
    function deleteDynArr() public {
        dynArr.push(10); dynArr.push(20);
        delete dynArr;
    }

    // delete on an element of a dynamic storage array → sol.store of zero.
    function deleteDynElem() public {
        dynArr.push(1); dynArr.push(2); dynArr.push(3);
        delete dynArr[1];
    }

    // delete on a local (stack) variable → sol.store of zero.
    function deleteLocal() public pure returns (uint) {
        uint v = 99;
        delete v;
        return v;
    }

    // delete on a dynamic array of value structs → clears each element's slots.
    function deletePointArr() public {
        delete pointArr;
    }

    // delete on a static array of value structs → clears all element slots.
    function deletePointFixed() public {
        delete pointFixed;
    }

    // delete on a dynamic array of structs containing a mapping → clears the
    // value members of each element; mapping members are skipped.
    function deleteWithMapArr() public {
        delete withMapArr;
    }

    // delete on a dynamic array of mappings → clears the length only; the
    // mapping element base-slots are never written.
    function deleteMapArr() public {
        delete mapArr;
    }

    // delete on a nested dynamic array of mappings → clears the outer length
    // and each inner array length; mapping base-slots are skipped.
    function deleteMapArr2D() public {
        delete mapArr2D;
    }

    // delete on a struct mixing static array, dynamic array, mapping and value
    // members → clears every value/array member; the mapping is skipped.
    function deleteMixedStruct() public {
        delete mixedS;
    }

    // delete on a struct with a value member and a mapping → clears the value
    // member; the mapping member is skipped.
    function deleteWithMapStruct() public {
        delete withMapS;
    }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #Pure = #sol<StateMutability Pure>
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @Delete_287 {
// CHECK-NEXT:     sol.state_var @uintVar_34 slot 0 offset 0 : ui256 loc(#loc2)
// CHECK-NEXT:     sol.state_var @boolVar_36 slot 1 offset 0 : i1 loc(#loc3)
// CHECK-NEXT:     sol.state_var @addrVar_38 slot 1 offset 1 : !sol.address loc(#loc4)
// CHECK-NEXT:     sol.state_var @bytesVar_40 slot 2 offset 0 : !sol.fixedbytes<32> loc(#loc5)
// CHECK-NEXT:     sol.state_var @intVar_42 slot 3 offset 0 : si16 loc(#loc6)
// CHECK-NEXT:     sol.state_var @enumVar_45 slot 3 offset 2 : !sol.enum<2> loc(#loc7)
// CHECK-NEXT:     sol.state_var @staticArr_49 slot 4 offset 0 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:     sol.state_var @dynArr_52 slot 7 offset 0 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:     sol.state_var @pointArr_56 slot 8 offset 0 : !sol.array<? x !sol.struct<(ui256, ui256), Storage>, Storage> loc(#loc10)
// CHECK-NEXT:     sol.state_var @pointFixed_61 slot 9 offset 0 : !sol.array<2 x !sol.struct<(ui256, ui256), Storage>, Storage> loc(#loc11)
// CHECK-NEXT:     sol.state_var @withMapArr_65 slot 13 offset 0 : !sol.array<? x !sol.struct<(ui256, !sol.mapping<ui256, ui256>), Storage>, Storage> loc(#loc12)
// CHECK-NEXT:     sol.state_var @mapArr_70 slot 14 offset 0 : !sol.array<? x !sol.mapping<ui256, ui256>, Storage> loc(#loc13)
// CHECK-NEXT:     sol.state_var @mapArr2D_76 slot 15 offset 0 : !sol.array<? x !sol.array<? x !sol.mapping<ui256, ui256>, Storage>, Storage> loc(#loc14)
// CHECK-NEXT:     sol.state_var @mixedS_79 slot 16 offset 0 : !sol.struct<(!sol.array<3 x ui256, Storage>, !sol.array<? x ui256, Storage>, !sol.mapping<ui256, ui256>, !sol.address, i1), Storage> loc(#loc15)
// CHECK-NEXT:     sol.state_var @withMapS_82 slot 22 offset 0 : !sol.struct<(ui256, !sol.mapping<ui256, ui256>), Storage> loc(#loc16)
// CHECK-NEXT:     sol.func @Delete_287() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @deleteUint_89() attributes {id = 89 : i64, orig_fn_type = () -> (), selector = -652922037 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @uintVar_34 : !sol.ptr<ui256, Storage> loc(#loc2)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc18)
// CHECK-NEXT:       sol.store %c0_ui256, %0 : ui256, !sol.ptr<ui256, Storage> loc(#loc18)
// CHECK-NEXT:       sol.return loc(#loc17)
// CHECK-NEXT:     } loc(#loc17)
// CHECK-NEXT:     sol.func @deleteBool_96() attributes {id = 96 : i64, orig_fn_type = () -> (), selector = 1278930689 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @boolVar_36 : !sol.ptr<i1, Storage> loc(#loc3)
// CHECK-NEXT:       %false = sol.constant false loc(#loc20)
// CHECK-NEXT:       sol.store %false, %0 : i1, !sol.ptr<i1, Storage> loc(#loc20)
// CHECK-NEXT:       sol.return loc(#loc19)
// CHECK-NEXT:     } loc(#loc19)
// CHECK-NEXT:     sol.func @deleteAddr_103() attributes {id = 103 : i64, orig_fn_type = () -> (), selector = 1553010268 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @addrVar_38 : !sol.ptr<!sol.address, Storage> loc(#loc4)
// CHECK-NEXT:       %c0_ui160 = sol.constant 0 : ui160 loc(#loc22)
// CHECK-NEXT:       %1 = sol.address_cast %c0_ui160 : ui160 to !sol.address loc(#loc22)
// CHECK-NEXT:       sol.store %1, %0 : !sol.address, !sol.ptr<!sol.address, Storage> loc(#loc22)
// CHECK-NEXT:       sol.return loc(#loc21)
// CHECK-NEXT:     } loc(#loc21)
// CHECK-NEXT:     sol.func @deleteBytes_110() attributes {id = 110 : i64, orig_fn_type = () -> (), selector = 87269612 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @bytesVar_40 : !sol.ptr<!sol.fixedbytes<32>, Storage> loc(#loc5)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc24)
// CHECK-NEXT:       %1 = sol.bytes_cast %c0_ui256 : ui256 to !sol.fixedbytes<32> loc(#loc24)
// CHECK-NEXT:       sol.store %1, %0 : !sol.fixedbytes<32>, !sol.ptr<!sol.fixedbytes<32>, Storage> loc(#loc24)
// CHECK-NEXT:       sol.return loc(#loc23)
// CHECK-NEXT:     } loc(#loc23)
// CHECK-NEXT:     sol.func @deleteInt_117() attributes {id = 117 : i64, orig_fn_type = () -> (), selector = -1429758948 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @intVar_42 : !sol.ptr<si16, Storage> loc(#loc6)
// CHECK-NEXT:       %c0_si16 = sol.constant 0 : si16 loc(#loc26)
// CHECK-NEXT:       sol.store %c0_si16, %0 : si16, !sol.ptr<si16, Storage> loc(#loc26)
// CHECK-NEXT:       sol.return loc(#loc25)
// CHECK-NEXT:     } loc(#loc25)
// CHECK-NEXT:     sol.func @deleteEnum_124() attributes {id = 124 : i64, orig_fn_type = () -> (), selector = 140565673 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @enumVar_45 : !sol.ptr<!sol.enum<2>, Storage> loc(#loc7)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc28)
// CHECK-NEXT:       %1 = sol.enum_cast %c0_ui256 : ui256 to !sol.enum<2> loc(#loc28)
// CHECK-NEXT:       sol.store %1, %0 : !sol.enum<2>, !sol.ptr<!sol.enum<2>, Storage> loc(#loc28)
// CHECK-NEXT:       sol.return loc(#loc27)
// CHECK-NEXT:     } loc(#loc27)
// CHECK-NEXT:     sol.func @deleteStaticElem_151() attributes {id = 151 : i64, orig_fn_type = () -> (), selector = -1872549905 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @staticArr_49 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc30)
// CHECK-NEXT:       %1 = sol.gep %0, %c0_ui8 : !sol.array<3 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc31)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc32)
// CHECK-NEXT:       %2 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc32)
// CHECK-NEXT:       sol.store %2, %1 : ui256, !sol.ptr<ui256, Storage> loc(#loc31)
// CHECK-NEXT:       %3 = sol.addr_of @staticArr_49 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       %c1_ui8_0 = sol.constant 1 : ui8 loc(#loc33)
// CHECK-NEXT:       %4 = sol.gep %3, %c1_ui8_0 : !sol.array<3 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc34)
// CHECK-NEXT:       %c2_ui8 = sol.constant 2 : ui8 loc(#loc35)
// CHECK-NEXT:       %5 = sol.cast %c2_ui8 : ui8 to ui256 loc(#loc35)
// CHECK-NEXT:       sol.store %5, %4 : ui256, !sol.ptr<ui256, Storage> loc(#loc34)
// CHECK-NEXT:       %6 = sol.addr_of @staticArr_49 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       %c2_ui8_1 = sol.constant 2 : ui8 loc(#loc36)
// CHECK-NEXT:       %7 = sol.gep %6, %c2_ui8_1 : !sol.array<3 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc37)
// CHECK-NEXT:       %c3_ui8 = sol.constant 3 : ui8 loc(#loc38)
// CHECK-NEXT:       %8 = sol.cast %c3_ui8 : ui8 to ui256 loc(#loc38)
// CHECK-NEXT:       sol.store %8, %7 : ui256, !sol.ptr<ui256, Storage> loc(#loc37)
// CHECK-NEXT:       %9 = sol.addr_of @staticArr_49 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       %c1_ui8_2 = sol.constant 1 : ui8 loc(#loc39)
// CHECK-NEXT:       %10 = sol.gep %9, %c1_ui8_2 : !sol.array<3 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc40)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc41)
// CHECK-NEXT:       sol.store %c0_ui256, %10 : ui256, !sol.ptr<ui256, Storage> loc(#loc41)
// CHECK-NEXT:       sol.return loc(#loc29)
// CHECK-NEXT:     } loc(#loc29)
// CHECK-NEXT:     sol.func @deleteStaticArr_176() attributes {id = 176 : i64, orig_fn_type = () -> (), selector = 1898683568 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @staticArr_49 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc43)
// CHECK-NEXT:       %1 = sol.gep %0, %c0_ui8 : !sol.array<3 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc44)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc45)
// CHECK-NEXT:       %2 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc45)
// CHECK-NEXT:       sol.store %2, %1 : ui256, !sol.ptr<ui256, Storage> loc(#loc44)
// CHECK-NEXT:       %3 = sol.addr_of @staticArr_49 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       %c1_ui8_0 = sol.constant 1 : ui8 loc(#loc46)
// CHECK-NEXT:       %4 = sol.gep %3, %c1_ui8_0 : !sol.array<3 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc47)
// CHECK-NEXT:       %c2_ui8 = sol.constant 2 : ui8 loc(#loc48)
// CHECK-NEXT:       %5 = sol.cast %c2_ui8 : ui8 to ui256 loc(#loc48)
// CHECK-NEXT:       sol.store %5, %4 : ui256, !sol.ptr<ui256, Storage> loc(#loc47)
// CHECK-NEXT:       %6 = sol.addr_of @staticArr_49 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       %c2_ui8_1 = sol.constant 2 : ui8 loc(#loc49)
// CHECK-NEXT:       %7 = sol.gep %6, %c2_ui8_1 : !sol.array<3 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc50)
// CHECK-NEXT:       %c3_ui8 = sol.constant 3 : ui8 loc(#loc51)
// CHECK-NEXT:       %8 = sol.cast %c3_ui8 : ui8 to ui256 loc(#loc51)
// CHECK-NEXT:       sol.store %8, %7 : ui256, !sol.ptr<ui256, Storage> loc(#loc50)
// CHECK-NEXT:       %9 = sol.addr_of @staticArr_49 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       sol.delete %9 : !sol.array<3 x ui256, Storage> loc(#loc52)
// CHECK-NEXT:       sol.return loc(#loc42)
// CHECK-NEXT:     } loc(#loc42)
// CHECK-NEXT:     sol.func @deleteDynArr_195() attributes {id = 195 : i64, orig_fn_type = () -> (), selector = -215073169 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @dynArr_52 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:       %1 = sol.push %0 : !sol.array<? x ui256, Storage> -> !sol.ptr<ui256, Storage> loc(#loc54)
// CHECK-NEXT:       %c10_ui8 = sol.constant 10 : ui8 loc(#loc55)
// CHECK-NEXT:       %2 = sol.cast %c10_ui8 : ui8 to ui256 loc(#loc55)
// CHECK-NEXT:       sol.store %2, %1 : ui256, !sol.ptr<ui256, Storage> loc(#loc54)
// CHECK-NEXT:       %3 = sol.addr_of @dynArr_52 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:       %4 = sol.push %3 : !sol.array<? x ui256, Storage> -> !sol.ptr<ui256, Storage> loc(#loc56)
// CHECK-NEXT:       %c20_ui8 = sol.constant 20 : ui8 loc(#loc57)
// CHECK-NEXT:       %5 = sol.cast %c20_ui8 : ui8 to ui256 loc(#loc57)
// CHECK-NEXT:       sol.store %5, %4 : ui256, !sol.ptr<ui256, Storage> loc(#loc56)
// CHECK-NEXT:       %6 = sol.addr_of @dynArr_52 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:       sol.delete %6 : !sol.array<? x ui256, Storage> loc(#loc58)
// CHECK-NEXT:       sol.return loc(#loc53)
// CHECK-NEXT:     } loc(#loc53)
// CHECK-NEXT:     sol.func @deleteDynElem_222() attributes {id = 222 : i64, orig_fn_type = () -> (), selector = -1665371042 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @dynArr_52 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:       %1 = sol.push %0 : !sol.array<? x ui256, Storage> -> !sol.ptr<ui256, Storage> loc(#loc60)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc61)
// CHECK-NEXT:       %2 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc61)
// CHECK-NEXT:       sol.store %2, %1 : ui256, !sol.ptr<ui256, Storage> loc(#loc60)
// CHECK-NEXT:       %3 = sol.addr_of @dynArr_52 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:       %4 = sol.push %3 : !sol.array<? x ui256, Storage> -> !sol.ptr<ui256, Storage> loc(#loc62)
// CHECK-NEXT:       %c2_ui8 = sol.constant 2 : ui8 loc(#loc63)
// CHECK-NEXT:       %5 = sol.cast %c2_ui8 : ui8 to ui256 loc(#loc63)
// CHECK-NEXT:       sol.store %5, %4 : ui256, !sol.ptr<ui256, Storage> loc(#loc62)
// CHECK-NEXT:       %6 = sol.addr_of @dynArr_52 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:       %7 = sol.push %6 : !sol.array<? x ui256, Storage> -> !sol.ptr<ui256, Storage> loc(#loc64)
// CHECK-NEXT:       %c3_ui8 = sol.constant 3 : ui8 loc(#loc65)
// CHECK-NEXT:       %8 = sol.cast %c3_ui8 : ui8 to ui256 loc(#loc65)
// CHECK-NEXT:       sol.store %8, %7 : ui256, !sol.ptr<ui256, Storage> loc(#loc64)
// CHECK-NEXT:       %9 = sol.addr_of @dynArr_52 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:       %c1_ui8_0 = sol.constant 1 : ui8 loc(#loc66)
// CHECK-NEXT:       %10 = sol.gep %9, %c1_ui8_0 : !sol.array<? x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc67)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc68)
// CHECK-NEXT:       sol.store %c0_ui256, %10 : ui256, !sol.ptr<ui256, Storage> loc(#loc68)
// CHECK-NEXT:       sol.return loc(#loc59)
// CHECK-NEXT:     } loc(#loc59)
// CHECK-NEXT:     sol.func @deleteLocal_237() -> ui256 attributes {id = 237 : i64, orig_fn_type = () -> ui256, selector = 1547838093 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %c99_ui8 = sol.constant 99 : ui8 loc(#loc70)
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc71)
// CHECK-NEXT:       %1 = sol.cast %c99_ui8 : ui8 to ui256 loc(#loc70)
// CHECK-NEXT:       sol.store %1, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc71)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc72)
// CHECK-NEXT:       sol.store %c0_ui256, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc72)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc73)
// CHECK-NEXT:       sol.return %2 : ui256 loc(#loc74)
// CHECK-NEXT:     } loc(#loc69)
// CHECK-NEXT:     sol.func @deletePointArr_244() attributes {id = 244 : i64, orig_fn_type = () -> (), selector = 1318596472 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @pointArr_56 : !sol.array<? x !sol.struct<(ui256, ui256), Storage>, Storage> loc(#loc10)
// CHECK-NEXT:       sol.delete %0 : !sol.array<? x !sol.struct<(ui256, ui256), Storage>, Storage> loc(#loc76)
// CHECK-NEXT:       sol.return loc(#loc75)
// CHECK-NEXT:     } loc(#loc75)
// CHECK-NEXT:     sol.func @deletePointFixed_251() attributes {id = 251 : i64, orig_fn_type = () -> (), selector = 1080472298 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @pointFixed_61 : !sol.array<2 x !sol.struct<(ui256, ui256), Storage>, Storage> loc(#loc11)
// CHECK-NEXT:       sol.delete %0 : !sol.array<2 x !sol.struct<(ui256, ui256), Storage>, Storage> loc(#loc78)
// CHECK-NEXT:       sol.return loc(#loc77)
// CHECK-NEXT:     } loc(#loc77)
// CHECK-NEXT:     sol.func @deleteWithMapArr_258() attributes {id = 258 : i64, orig_fn_type = () -> (), selector = -1181626706 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @withMapArr_65 : !sol.array<? x !sol.struct<(ui256, !sol.mapping<ui256, ui256>), Storage>, Storage> loc(#loc12)
// CHECK-NEXT:       sol.delete %0 : !sol.array<? x !sol.struct<(ui256, !sol.mapping<ui256, ui256>), Storage>, Storage> loc(#loc80)
// CHECK-NEXT:       sol.return loc(#loc79)
// CHECK-NEXT:     } loc(#loc79)
// CHECK-NEXT:     sol.func @deleteMapArr_265() attributes {id = 265 : i64, orig_fn_type = () -> (), selector = -1033855038 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @mapArr_70 : !sol.array<? x !sol.mapping<ui256, ui256>, Storage> loc(#loc13)
// CHECK-NEXT:       sol.delete %0 : !sol.array<? x !sol.mapping<ui256, ui256>, Storage> loc(#loc82)
// CHECK-NEXT:       sol.return loc(#loc81)
// CHECK-NEXT:     } loc(#loc81)
// CHECK-NEXT:     sol.func @deleteMapArr2D_272() attributes {id = 272 : i64, orig_fn_type = () -> (), selector = -423922142 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @mapArr2D_76 : !sol.array<? x !sol.array<? x !sol.mapping<ui256, ui256>, Storage>, Storage> loc(#loc14)
// CHECK-NEXT:       sol.delete %0 : !sol.array<? x !sol.array<? x !sol.mapping<ui256, ui256>, Storage>, Storage> loc(#loc84)
// CHECK-NEXT:       sol.return loc(#loc83)
// CHECK-NEXT:     } loc(#loc83)
// CHECK-NEXT:     sol.func @deleteMixedStruct_279() attributes {id = 279 : i64, orig_fn_type = () -> (), selector = 1662523059 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @mixedS_79 : !sol.struct<(!sol.array<3 x ui256, Storage>, !sol.array<? x ui256, Storage>, !sol.mapping<ui256, ui256>, !sol.address, i1), Storage> loc(#loc15)
// CHECK-NEXT:       sol.delete %0 : !sol.struct<(!sol.array<3 x ui256, Storage>, !sol.array<? x ui256, Storage>, !sol.mapping<ui256, ui256>, !sol.address, i1), Storage> loc(#loc86)
// CHECK-NEXT:       sol.return loc(#loc85)
// CHECK-NEXT:     } loc(#loc85)
// CHECK-NEXT:     sol.func @deleteWithMapStruct_286() attributes {id = 286 : i64, orig_fn_type = () -> (), selector = 122150337 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @withMapS_82 : !sol.struct<(ui256, !sol.mapping<ui256, ui256>), Storage> loc(#loc16)
// CHECK-NEXT:       sol.delete %0 : !sol.struct<(ui256, !sol.mapping<ui256, ui256>), Storage> loc(#loc88)
// CHECK-NEXT:       sol.return loc(#loc87)
// CHECK-NEXT:     } loc(#loc87)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:15:4)
// CHECK-NEXT: #loc3 = loc({{.*}}:16:4)
// CHECK-NEXT: #loc4 = loc({{.*}}:17:4)
// CHECK-NEXT: #loc5 = loc({{.*}}:18:4)
// CHECK-NEXT: #loc6 = loc({{.*}}:19:4)
// CHECK-NEXT: #loc7 = loc({{.*}}:20:4)
// CHECK-NEXT: #loc8 = loc({{.*}}:22:4)
// CHECK-NEXT: #loc9 = loc({{.*}}:23:4)
// CHECK-NEXT: #loc10 = loc({{.*}}:25:4)
// CHECK-NEXT: #loc11 = loc({{.*}}:26:4)
// CHECK-NEXT: #loc12 = loc({{.*}}:27:4)
// CHECK-NEXT: #loc13 = loc({{.*}}:28:4)
// CHECK-NEXT: #loc14 = loc({{.*}}:29:4)
// CHECK-NEXT: #loc15 = loc({{.*}}:30:4)
// CHECK-NEXT: #loc16 = loc({{.*}}:31:4)
// CHECK-NEXT: #loc17 = loc({{.*}}:34:4)
// CHECK-NEXT: #loc18 = loc({{.*}}:35:8)
// CHECK-NEXT: #loc19 = loc({{.*}}:39:4)
// CHECK-NEXT: #loc20 = loc({{.*}}:40:8)
// CHECK-NEXT: #loc21 = loc({{.*}}:44:4)
// CHECK-NEXT: #loc22 = loc({{.*}}:45:8)
// CHECK-NEXT: #loc23 = loc({{.*}}:49:4)
// CHECK-NEXT: #loc24 = loc({{.*}}:50:8)
// CHECK-NEXT: #loc25 = loc({{.*}}:54:4)
// CHECK-NEXT: #loc26 = loc({{.*}}:55:8)
// CHECK-NEXT: #loc27 = loc({{.*}}:59:4)
// CHECK-NEXT: #loc28 = loc({{.*}}:60:8)
// CHECK-NEXT: #loc29 = loc({{.*}}:64:4)
// CHECK-NEXT: #loc30 = loc({{.*}}:65:18)
// CHECK-NEXT: #loc31 = loc({{.*}}:65:8)
// CHECK-NEXT: #loc32 = loc({{.*}}:65:23)
// CHECK-NEXT: #loc33 = loc({{.*}}:65:36)
// CHECK-NEXT: #loc34 = loc({{.*}}:65:26)
// CHECK-NEXT: #loc35 = loc({{.*}}:65:41)
// CHECK-NEXT: #loc36 = loc({{.*}}:65:54)
// CHECK-NEXT: #loc37 = loc({{.*}}:65:44)
// CHECK-NEXT: #loc38 = loc({{.*}}:65:59)
// CHECK-NEXT: #loc39 = loc({{.*}}:66:25)
// CHECK-NEXT: #loc40 = loc({{.*}}:66:15)
// CHECK-NEXT: #loc41 = loc({{.*}}:66:8)
// CHECK-NEXT: #loc42 = loc({{.*}}:70:4)
// CHECK-NEXT: #loc43 = loc({{.*}}:71:18)
// CHECK-NEXT: #loc44 = loc({{.*}}:71:8)
// CHECK-NEXT: #loc45 = loc({{.*}}:71:23)
// CHECK-NEXT: #loc46 = loc({{.*}}:71:36)
// CHECK-NEXT: #loc47 = loc({{.*}}:71:26)
// CHECK-NEXT: #loc48 = loc({{.*}}:71:41)
// CHECK-NEXT: #loc49 = loc({{.*}}:71:54)
// CHECK-NEXT: #loc50 = loc({{.*}}:71:44)
// CHECK-NEXT: #loc51 = loc({{.*}}:71:59)
// CHECK-NEXT: #loc52 = loc({{.*}}:72:8)
// CHECK-NEXT: #loc53 = loc({{.*}}:76:4)
// CHECK-NEXT: #loc54 = loc({{.*}}:77:8)
// CHECK-NEXT: #loc55 = loc({{.*}}:77:20)
// CHECK-NEXT: #loc56 = loc({{.*}}:77:25)
// CHECK-NEXT: #loc57 = loc({{.*}}:77:37)
// CHECK-NEXT: #loc58 = loc({{.*}}:78:8)
// CHECK-NEXT: #loc59 = loc({{.*}}:82:4)
// CHECK-NEXT: #loc60 = loc({{.*}}:83:8)
// CHECK-NEXT: #loc61 = loc({{.*}}:83:20)
// CHECK-NEXT: #loc62 = loc({{.*}}:83:24)
// CHECK-NEXT: #loc63 = loc({{.*}}:83:36)
// CHECK-NEXT: #loc64 = loc({{.*}}:83:40)
// CHECK-NEXT: #loc65 = loc({{.*}}:83:52)
// CHECK-NEXT: #loc66 = loc({{.*}}:84:22)
// CHECK-NEXT: #loc67 = loc({{.*}}:84:15)
// CHECK-NEXT: #loc68 = loc({{.*}}:84:8)
// CHECK-NEXT: #loc69 = loc({{.*}}:88:4)
// CHECK-NEXT: #loc70 = loc({{.*}}:89:17)
// CHECK-NEXT: #loc71 = loc({{.*}}:89:8)
// CHECK-NEXT: #loc72 = loc({{.*}}:90:8)
// CHECK-NEXT: #loc73 = loc({{.*}}:91:15)
// CHECK-NEXT: #loc74 = loc({{.*}}:91:8)
// CHECK-NEXT: #loc75 = loc({{.*}}:95:4)
// CHECK-NEXT: #loc76 = loc({{.*}}:96:8)
// CHECK-NEXT: #loc77 = loc({{.*}}:100:4)
// CHECK-NEXT: #loc78 = loc({{.*}}:101:8)
// CHECK-NEXT: #loc79 = loc({{.*}}:106:4)
// CHECK-NEXT: #loc80 = loc({{.*}}:107:8)
// CHECK-NEXT: #loc81 = loc({{.*}}:112:4)
// CHECK-NEXT: #loc82 = loc({{.*}}:113:8)
// CHECK-NEXT: #loc83 = loc({{.*}}:118:4)
// CHECK-NEXT: #loc84 = loc({{.*}}:119:8)
// CHECK-NEXT: #loc85 = loc({{.*}}:124:4)
// CHECK-NEXT: #loc86 = loc({{.*}}:125:8)
// CHECK-NEXT: #loc87 = loc({{.*}}:130:4)
// CHECK-NEXT: #loc88 = loc({{.*}}:131:8)
// CHECK-EMPTY:
