// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract Delete {
    enum Status { Active, Inactive, Pending }

    uint    uintVar;
    bool    boolVar;
    address addrVar;
    bytes32 bytesVar;
    int16   intVar;
    Status  enumVar;

    uint[3] staticArr;
    uint[]  dynArr;

    // delete on a uint state variable resets it to 0.
    function deleteUint() public {
        delete uintVar;
    }

    // delete on a bool resets it to false.
    function deleteBool() public {
        delete boolVar;
    }

    // delete on an address resets it to address(0).
    function deleteAddr() public {
        delete addrVar;
    }

    // delete on bytes32 resets it to 0.
    function deleteBytes() public {
        delete bytesVar;
    }

    // delete on a signed integer resets it to 0.
    function deleteInt() public {
        delete intVar;
    }

    // delete on an enum resets it to its first member (ordinal 0).
    function deleteEnum() public {
        delete enumVar;
    }

    // delete on a single element of a static array → sol.store of zero.
    function deleteStaticElem() public {
        staticArr[0] = 1; staticArr[1] = 2; staticArr[2] = 3;
        delete staticArr[1];
    }

    // delete on a whole static array → sol.copy from zero-init Memory array.
    function deleteStaticArr() public {
        staticArr[0] = 1; staticArr[1] = 2; staticArr[2] = 3;
        delete staticArr;
    }

    // delete on a dynamic storage array → sol.copy from zero-init Memory array.
    function deleteDynArr() public {
        dynArr.push(10); dynArr.push(20);
        delete dynArr;
    }

    // delete on an element of a dynamic storage array → sol.store of zero.
    function deleteDynElem() public {
        dynArr.push(1); dynArr.push(2); dynArr.push(3);
        delete dynArr[1];
    }

    // delete on a local (stack) variable → sol.store of zero.
    function deleteLocal() public pure returns (uint) {
        uint v = 99;
        delete v;
        return v;
    }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #Pure = #sol<StateMutability Pure>
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @Delete_180 {
// CHECK-NEXT:     sol.state_var @uintVar_6 slot 0 offset 0 : ui256 loc(#loc2)
// CHECK-NEXT:     sol.state_var @boolVar_8 slot 1 offset 0 : i1 loc(#loc3)
// CHECK-NEXT:     sol.state_var @addrVar_10 slot 1 offset 1 : !sol.address loc(#loc4)
// CHECK-NEXT:     sol.state_var @bytesVar_12 slot 2 offset 0 : !sol.bytes<32> loc(#loc5)
// CHECK-NEXT:     sol.state_var @intVar_14 slot 3 offset 0 : si16 loc(#loc6)
// CHECK-NEXT:     sol.state_var @enumVar_17 slot 3 offset 2 : !sol.enum<2> loc(#loc7)
// CHECK-NEXT:     sol.state_var @staticArr_21 slot 4 offset 0 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:     sol.state_var @dynArr_24 slot 7 offset 0 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:     sol.func @Delete_180() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @deleteUint_31() attributes {id = 31 : i64, orig_fn_type = () -> (), selector = -652922037 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @uintVar_6 : !sol.ptr<ui256, Storage> loc(#loc2)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc11)
// CHECK-NEXT:       sol.store %c0_ui256, %0 : ui256, !sol.ptr<ui256, Storage> loc(#loc11)
// CHECK-NEXT:       sol.return loc(#loc10)
// CHECK-NEXT:     } loc(#loc10)
// CHECK-NEXT:     sol.func @deleteBool_38() attributes {id = 38 : i64, orig_fn_type = () -> (), selector = 1278930689 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @boolVar_8 : !sol.ptr<i1, Storage> loc(#loc3)
// CHECK-NEXT:       %false = sol.constant false loc(#loc13)
// CHECK-NEXT:       sol.store %false, %0 : i1, !sol.ptr<i1, Storage> loc(#loc13)
// CHECK-NEXT:       sol.return loc(#loc12)
// CHECK-NEXT:     } loc(#loc12)
// CHECK-NEXT:     sol.func @deleteAddr_45() attributes {id = 45 : i64, orig_fn_type = () -> (), selector = 1553010268 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @addrVar_10 : !sol.ptr<!sol.address, Storage> loc(#loc4)
// CHECK-NEXT:       %c0_ui160 = sol.constant 0 : ui160 loc(#loc15)
// CHECK-NEXT:       %1 = sol.address_cast %c0_ui160 : ui160 to !sol.address loc(#loc15)
// CHECK-NEXT:       sol.store %1, %0 : !sol.address, !sol.ptr<!sol.address, Storage> loc(#loc15)
// CHECK-NEXT:       sol.return loc(#loc14)
// CHECK-NEXT:     } loc(#loc14)
// CHECK-NEXT:     sol.func @deleteBytes_52() attributes {id = 52 : i64, orig_fn_type = () -> (), selector = 87269612 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @bytesVar_12 : !sol.ptr<!sol.bytes<32>, Storage> loc(#loc5)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc17)
// CHECK-NEXT:       %1 = sol.bytes_cast %c0_ui256 : ui256 to !sol.bytes<32> loc(#loc17)
// CHECK-NEXT:       sol.store %1, %0 : !sol.bytes<32>, !sol.ptr<!sol.bytes<32>, Storage> loc(#loc17)
// CHECK-NEXT:       sol.return loc(#loc16)
// CHECK-NEXT:     } loc(#loc16)
// CHECK-NEXT:     sol.func @deleteInt_59() attributes {id = 59 : i64, orig_fn_type = () -> (), selector = -1429758948 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @intVar_14 : !sol.ptr<si16, Storage> loc(#loc6)
// CHECK-NEXT:       %c0_si16 = sol.constant 0 : si16 loc(#loc19)
// CHECK-NEXT:       sol.store %c0_si16, %0 : si16, !sol.ptr<si16, Storage> loc(#loc19)
// CHECK-NEXT:       sol.return loc(#loc18)
// CHECK-NEXT:     } loc(#loc18)
// CHECK-NEXT:     sol.func @deleteEnum_66() attributes {id = 66 : i64, orig_fn_type = () -> (), selector = 140565673 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @enumVar_17 : !sol.ptr<!sol.enum<2>, Storage> loc(#loc7)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc21)
// CHECK-NEXT:       %1 = sol.enum_cast %c0_ui256 : ui256 to <2> loc(#loc21)
// CHECK-NEXT:       sol.store %1, %0 : !sol.enum<2>, !sol.ptr<!sol.enum<2>, Storage> loc(#loc21)
// CHECK-NEXT:       sol.return loc(#loc20)
// CHECK-NEXT:     } loc(#loc20)
// CHECK-NEXT:     sol.func @deleteStaticElem_93() attributes {id = 93 : i64, orig_fn_type = () -> (), selector = -1872549905 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @staticArr_21 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc23)
// CHECK-NEXT:       %1 = sol.gep %0, %c0_ui8 : !sol.array<3 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc24)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc25)
// CHECK-NEXT:       %2 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc25)
// CHECK-NEXT:       sol.store %2, %1 : ui256, !sol.ptr<ui256, Storage> loc(#loc24)
// CHECK-NEXT:       %3 = sol.addr_of @staticArr_21 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       %c1_ui8_0 = sol.constant 1 : ui8 loc(#loc26)
// CHECK-NEXT:       %4 = sol.gep %3, %c1_ui8_0 : !sol.array<3 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc27)
// CHECK-NEXT:       %c2_ui8 = sol.constant 2 : ui8 loc(#loc28)
// CHECK-NEXT:       %5 = sol.cast %c2_ui8 : ui8 to ui256 loc(#loc28)
// CHECK-NEXT:       sol.store %5, %4 : ui256, !sol.ptr<ui256, Storage> loc(#loc27)
// CHECK-NEXT:       %6 = sol.addr_of @staticArr_21 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       %c2_ui8_1 = sol.constant 2 : ui8 loc(#loc29)
// CHECK-NEXT:       %7 = sol.gep %6, %c2_ui8_1 : !sol.array<3 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc30)
// CHECK-NEXT:       %c3_ui8 = sol.constant 3 : ui8 loc(#loc31)
// CHECK-NEXT:       %8 = sol.cast %c3_ui8 : ui8 to ui256 loc(#loc31)
// CHECK-NEXT:       sol.store %8, %7 : ui256, !sol.ptr<ui256, Storage> loc(#loc30)
// CHECK-NEXT:       %9 = sol.addr_of @staticArr_21 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       %c1_ui8_2 = sol.constant 1 : ui8 loc(#loc32)
// CHECK-NEXT:       %10 = sol.gep %9, %c1_ui8_2 : !sol.array<3 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc33)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc34)
// CHECK-NEXT:       sol.store %c0_ui256, %10 : ui256, !sol.ptr<ui256, Storage> loc(#loc34)
// CHECK-NEXT:       sol.return loc(#loc22)
// CHECK-NEXT:     } loc(#loc22)
// CHECK-NEXT:     sol.func @deleteStaticArr_118() attributes {id = 118 : i64, orig_fn_type = () -> (), selector = 1898683568 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @staticArr_21 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc36)
// CHECK-NEXT:       %1 = sol.gep %0, %c0_ui8 : !sol.array<3 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc37)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc38)
// CHECK-NEXT:       %2 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc38)
// CHECK-NEXT:       sol.store %2, %1 : ui256, !sol.ptr<ui256, Storage> loc(#loc37)
// CHECK-NEXT:       %3 = sol.addr_of @staticArr_21 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       %c1_ui8_0 = sol.constant 1 : ui8 loc(#loc39)
// CHECK-NEXT:       %4 = sol.gep %3, %c1_ui8_0 : !sol.array<3 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc40)
// CHECK-NEXT:       %c2_ui8 = sol.constant 2 : ui8 loc(#loc41)
// CHECK-NEXT:       %5 = sol.cast %c2_ui8 : ui8 to ui256 loc(#loc41)
// CHECK-NEXT:       sol.store %5, %4 : ui256, !sol.ptr<ui256, Storage> loc(#loc40)
// CHECK-NEXT:       %6 = sol.addr_of @staticArr_21 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       %c2_ui8_1 = sol.constant 2 : ui8 loc(#loc42)
// CHECK-NEXT:       %7 = sol.gep %6, %c2_ui8_1 : !sol.array<3 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc43)
// CHECK-NEXT:       %c3_ui8 = sol.constant 3 : ui8 loc(#loc44)
// CHECK-NEXT:       %8 = sol.cast %c3_ui8 : ui8 to ui256 loc(#loc44)
// CHECK-NEXT:       sol.store %8, %7 : ui256, !sol.ptr<ui256, Storage> loc(#loc43)
// CHECK-NEXT:       %9 = sol.addr_of @staticArr_21 : !sol.array<3 x ui256, Storage> loc(#loc8)
// CHECK-NEXT:       %10 = sol.malloc zero_init :  !sol.array<3 x ui256, Memory> loc(#loc45)
// CHECK-NEXT:       sol.copy %10, %9 : !sol.array<3 x ui256, Memory>, !sol.array<3 x ui256, Storage> loc(#loc45)
// CHECK-NEXT:       sol.return loc(#loc35)
// CHECK-NEXT:     } loc(#loc35)
// CHECK-NEXT:     sol.func @deleteDynArr_137() attributes {id = 137 : i64, orig_fn_type = () -> (), selector = -215073169 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @dynArr_24 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:       %1 = sol.push %0 : !sol.array<? x ui256, Storage> -> !sol.ptr<ui256, Storage> loc(#loc47)
// CHECK-NEXT:       %c10_ui8 = sol.constant 10 : ui8 loc(#loc48)
// CHECK-NEXT:       %2 = sol.cast %c10_ui8 : ui8 to ui256 loc(#loc48)
// CHECK-NEXT:       sol.store %2, %1 : ui256, !sol.ptr<ui256, Storage> loc(#loc47)
// CHECK-NEXT:       %3 = sol.addr_of @dynArr_24 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:       %4 = sol.push %3 : !sol.array<? x ui256, Storage> -> !sol.ptr<ui256, Storage> loc(#loc49)
// CHECK-NEXT:       %c20_ui8 = sol.constant 20 : ui8 loc(#loc50)
// CHECK-NEXT:       %5 = sol.cast %c20_ui8 : ui8 to ui256 loc(#loc50)
// CHECK-NEXT:       sol.store %5, %4 : ui256, !sol.ptr<ui256, Storage> loc(#loc49)
// CHECK-NEXT:       %6 = sol.addr_of @dynArr_24 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:       %7 = sol.malloc zero_init :  !sol.array<? x ui256, Memory> loc(#loc51)
// CHECK-NEXT:       sol.copy %7, %6 : !sol.array<? x ui256, Memory>, !sol.array<? x ui256, Storage> loc(#loc51)
// CHECK-NEXT:       sol.return loc(#loc46)
// CHECK-NEXT:     } loc(#loc46)
// CHECK-NEXT:     sol.func @deleteDynElem_164() attributes {id = 164 : i64, orig_fn_type = () -> (), selector = -1665371042 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @dynArr_24 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:       %1 = sol.push %0 : !sol.array<? x ui256, Storage> -> !sol.ptr<ui256, Storage> loc(#loc53)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc54)
// CHECK-NEXT:       %2 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc54)
// CHECK-NEXT:       sol.store %2, %1 : ui256, !sol.ptr<ui256, Storage> loc(#loc53)
// CHECK-NEXT:       %3 = sol.addr_of @dynArr_24 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:       %4 = sol.push %3 : !sol.array<? x ui256, Storage> -> !sol.ptr<ui256, Storage> loc(#loc55)
// CHECK-NEXT:       %c2_ui8 = sol.constant 2 : ui8 loc(#loc56)
// CHECK-NEXT:       %5 = sol.cast %c2_ui8 : ui8 to ui256 loc(#loc56)
// CHECK-NEXT:       sol.store %5, %4 : ui256, !sol.ptr<ui256, Storage> loc(#loc55)
// CHECK-NEXT:       %6 = sol.addr_of @dynArr_24 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:       %7 = sol.push %6 : !sol.array<? x ui256, Storage> -> !sol.ptr<ui256, Storage> loc(#loc57)
// CHECK-NEXT:       %c3_ui8 = sol.constant 3 : ui8 loc(#loc58)
// CHECK-NEXT:       %8 = sol.cast %c3_ui8 : ui8 to ui256 loc(#loc58)
// CHECK-NEXT:       sol.store %8, %7 : ui256, !sol.ptr<ui256, Storage> loc(#loc57)
// CHECK-NEXT:       %9 = sol.addr_of @dynArr_24 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:       %c1_ui8_0 = sol.constant 1 : ui8 loc(#loc59)
// CHECK-NEXT:       %10 = sol.gep %9, %c1_ui8_0 : !sol.array<? x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc60)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc61)
// CHECK-NEXT:       sol.store %c0_ui256, %10 : ui256, !sol.ptr<ui256, Storage> loc(#loc61)
// CHECK-NEXT:       sol.return loc(#loc52)
// CHECK-NEXT:     } loc(#loc52)
// CHECK-NEXT:     sol.func @deleteLocal_179() -> ui256 attributes {id = 179 : i64, orig_fn_type = () -> ui256, selector = 1547838093 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %c99_ui8 = sol.constant 99 : ui8 loc(#loc63)
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc64)
// CHECK-NEXT:       %1 = sol.cast %c99_ui8 : ui8 to ui256 loc(#loc63)
// CHECK-NEXT:       sol.store %1, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc64)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc65)
// CHECK-NEXT:       sol.store %c0_ui256, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc65)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc66)
// CHECK-NEXT:       sol.return %2 : ui256 loc(#loc67)
// CHECK-NEXT:     } loc(#loc62)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:5:4)
// CHECK-NEXT: #loc3 = loc({{.*}}:6:4)
// CHECK-NEXT: #loc4 = loc({{.*}}:7:4)
// CHECK-NEXT: #loc5 = loc({{.*}}:8:4)
// CHECK-NEXT: #loc6 = loc({{.*}}:9:4)
// CHECK-NEXT: #loc7 = loc({{.*}}:10:4)
// CHECK-NEXT: #loc8 = loc({{.*}}:12:4)
// CHECK-NEXT: #loc9 = loc({{.*}}:13:4)
// CHECK-NEXT: #loc10 = loc({{.*}}:16:4)
// CHECK-NEXT: #loc11 = loc({{.*}}:17:8)
// CHECK-NEXT: #loc12 = loc({{.*}}:21:4)
// CHECK-NEXT: #loc13 = loc({{.*}}:22:8)
// CHECK-NEXT: #loc14 = loc({{.*}}:26:4)
// CHECK-NEXT: #loc15 = loc({{.*}}:27:8)
// CHECK-NEXT: #loc16 = loc({{.*}}:31:4)
// CHECK-NEXT: #loc17 = loc({{.*}}:32:8)
// CHECK-NEXT: #loc18 = loc({{.*}}:36:4)
// CHECK-NEXT: #loc19 = loc({{.*}}:37:8)
// CHECK-NEXT: #loc20 = loc({{.*}}:41:4)
// CHECK-NEXT: #loc21 = loc({{.*}}:42:8)
// CHECK-NEXT: #loc22 = loc({{.*}}:46:4)
// CHECK-NEXT: #loc23 = loc({{.*}}:47:18)
// CHECK-NEXT: #loc24 = loc({{.*}}:47:8)
// CHECK-NEXT: #loc25 = loc({{.*}}:47:23)
// CHECK-NEXT: #loc26 = loc({{.*}}:47:36)
// CHECK-NEXT: #loc27 = loc({{.*}}:47:26)
// CHECK-NEXT: #loc28 = loc({{.*}}:47:41)
// CHECK-NEXT: #loc29 = loc({{.*}}:47:54)
// CHECK-NEXT: #loc30 = loc({{.*}}:47:44)
// CHECK-NEXT: #loc31 = loc({{.*}}:47:59)
// CHECK-NEXT: #loc32 = loc({{.*}}:48:25)
// CHECK-NEXT: #loc33 = loc({{.*}}:48:15)
// CHECK-NEXT: #loc34 = loc({{.*}}:48:8)
// CHECK-NEXT: #loc35 = loc({{.*}}:52:4)
// CHECK-NEXT: #loc36 = loc({{.*}}:53:18)
// CHECK-NEXT: #loc37 = loc({{.*}}:53:8)
// CHECK-NEXT: #loc38 = loc({{.*}}:53:23)
// CHECK-NEXT: #loc39 = loc({{.*}}:53:36)
// CHECK-NEXT: #loc40 = loc({{.*}}:53:26)
// CHECK-NEXT: #loc41 = loc({{.*}}:53:41)
// CHECK-NEXT: #loc42 = loc({{.*}}:53:54)
// CHECK-NEXT: #loc43 = loc({{.*}}:53:44)
// CHECK-NEXT: #loc44 = loc({{.*}}:53:59)
// CHECK-NEXT: #loc45 = loc({{.*}}:54:8)
// CHECK-NEXT: #loc46 = loc({{.*}}:58:4)
// CHECK-NEXT: #loc47 = loc({{.*}}:59:8)
// CHECK-NEXT: #loc48 = loc({{.*}}:59:20)
// CHECK-NEXT: #loc49 = loc({{.*}}:59:25)
// CHECK-NEXT: #loc50 = loc({{.*}}:59:37)
// CHECK-NEXT: #loc51 = loc({{.*}}:60:8)
// CHECK-NEXT: #loc52 = loc({{.*}}:64:4)
// CHECK-NEXT: #loc53 = loc({{.*}}:65:8)
// CHECK-NEXT: #loc54 = loc({{.*}}:65:20)
// CHECK-NEXT: #loc55 = loc({{.*}}:65:24)
// CHECK-NEXT: #loc56 = loc({{.*}}:65:36)
// CHECK-NEXT: #loc57 = loc({{.*}}:65:40)
// CHECK-NEXT: #loc58 = loc({{.*}}:65:52)
// CHECK-NEXT: #loc59 = loc({{.*}}:66:22)
// CHECK-NEXT: #loc60 = loc({{.*}}:66:15)
// CHECK-NEXT: #loc61 = loc({{.*}}:66:8)
// CHECK-NEXT: #loc62 = loc({{.*}}:70:4)
// CHECK-NEXT: #loc63 = loc({{.*}}:71:17)
// CHECK-NEXT: #loc64 = loc({{.*}}:71:8)
// CHECK-NEXT: #loc65 = loc({{.*}}:72:8)
// CHECK-NEXT: #loc66 = loc({{.*}}:73:15)
// CHECK-NEXT: #loc67 = loc({{.*}}:73:8)
// CHECK-EMPTY:
