// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
  function f(uint a) public payable returns(uint) {
    a = this.f(a);
    return this.f{value: 7, gas: a}(a);
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Payable = #sol<StateMutability Payable>
// CHECK-NEXT: #Prague = #sol<EvmVersion Prague>
// CHECK-NEXT: #loc3 = loc({{.*}}:3:13)
// CHECK-NEXT: module attributes {sol.evm_version = #Prague} {
// CHECK-NEXT:   sol.contract @C_24 {
// CHECK-NEXT:     sol.func @f_23(%arg0: ui256 loc({{.*}}:3:13)) -> ui256 attributes {state_mutability = #Payable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:       %1 = sol.this loc(#loc4)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc5)
// CHECK-NEXT:       %3 = sol.gas loc(#loc4)
// CHECK-NEXT:       %4 = sol.conv_cast %3 : i256 -> ui256 loc(#loc4)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc4)
// CHECK-NEXT:       %status, %5 = sol.ext_call @f_23(%2) at %1 gas %4 value %c0_ui256 {callee_type = (ui256) -> ui256, selector = -1277270901 : i32} : (ui256) -> (i1, ui256) loc(#loc4)
// CHECK-NEXT:       sol.store %5, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc6)
// CHECK-NEXT:       %c7_ui8 = sol.constant 7 : ui8 loc(#loc7)
// CHECK-NEXT:       %6 = sol.cast %c7_ui8 : ui8 to ui256 loc(#loc7)
// CHECK-NEXT:       %7 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc8)
// CHECK-NEXT:       %8 = sol.this loc(#loc9)
// CHECK-NEXT:       %9 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc10)
// CHECK-NEXT:       %10 = sol.conv_cast %7 : ui256 -> ui256 loc(#loc9)
// CHECK-NEXT:       %status_0, %11 = sol.ext_call @f_23(%9) at %8 gas %10 value %6 {callee_type = (ui256) -> ui256, selector = -1277270901 : i32} : (ui256) -> (i1, ui256) loc(#loc9)
// CHECK-NEXT:       sol.return %11 : ui256 loc(#loc11)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:   } {interface_fns = [{selector = -1277270901 : i32, sym = @f_23, type = (ui256) -> ui256}], kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:3:2)
// CHECK-NEXT: #loc4 = loc({{.*}}:4:8)
// CHECK-NEXT: #loc5 = loc({{.*}}:4:15)
// CHECK-NEXT: #loc6 = loc({{.*}}:4:4)
// CHECK-NEXT: #loc7 = loc({{.*}}:5:25)
// CHECK-NEXT: #loc8 = loc({{.*}}:5:33)
// CHECK-NEXT: #loc9 = loc({{.*}}:5:11)
// CHECK-NEXT: #loc10 = loc({{.*}}:5:36)
// CHECK-NEXT: #loc11 = loc({{.*}}:5:4)
// CHECK-EMPTY:
