// RUN: solc --strict-assembly --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

object "Test" {
  code {
    function f() -> r {
      for { let i := 0 } lt(i, 4) { i := add(i, 1) } {
        if 0 {
          continue
        }
        if 1 {
          break
        }
      }
      r := 0
    }
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   sol.object @Test {
// CHECK-NEXT:     sol.func @f() -> i256 {
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc1)
// CHECK-NEXT:       %0 = llvm.alloca %c1_i256 x i256 {alignment = 32 : i64} : (i256) -> !llvm.ptr<i256> loc(#loc2)
// CHECK-NEXT:       %c1_i256_0 = arith.constant 1 : i256 loc(#loc3)
// CHECK-NEXT:       %1 = llvm.alloca %c1_i256_0 x i256 {alignment = 32 : i64} : (i256) -> !llvm.ptr<i256> loc(#loc4)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc5)
// CHECK-NEXT:       llvm.store %c0_i256, %1 {alignment = 32 : i64} : !llvm.ptr<i256> loc(#loc3)
// CHECK-NEXT:       sol.for cond {
// CHECK-NEXT:         %3 = llvm.load %1 {alignment = 32 : i64} : !llvm.ptr<i256> loc(#loc7)
// CHECK-NEXT:         %c4_i256 = arith.constant 4 : i256 loc(#loc8)
// CHECK-NEXT:         %4 = arith.cmpi ult, %3, %c4_i256 : i256 loc(#loc9)
// CHECK-NEXT:         sol.condition %4 loc(#loc9)
// CHECK-NEXT:       } body {
// CHECK-NEXT:         %c0_i256_2 = arith.constant 0 : i256 loc(#loc10)
// CHECK-NEXT:         %c0_i256_3 = arith.constant 0 : i256 loc(#loc10)
// CHECK-NEXT:         %3 = arith.cmpi ne, %c0_i256_2, %c0_i256_3 : i256 loc(#loc10)
// CHECK-NEXT:         sol.if %3 {
// CHECK-NEXT:           sol.continue loc(#loc12)
// CHECK-NEXT:         ^bb1:  // no predecessors
// CHECK-NEXT:           sol.yield loc(#loc11)
// CHECK-NEXT:         } else {
// CHECK-NEXT:         } loc(#loc11)
// CHECK-NEXT:         %c1_i256_4 = arith.constant 1 : i256 loc(#loc13)
// CHECK-NEXT:         %c0_i256_5 = arith.constant 0 : i256 loc(#loc13)
// CHECK-NEXT:         %4 = arith.cmpi ne, %c1_i256_4, %c0_i256_5 : i256 loc(#loc13)
// CHECK-NEXT:         sol.if %4 {
// CHECK-NEXT:           sol.break loc(#loc15)
// CHECK-NEXT:         ^bb1:  // no predecessors
// CHECK-NEXT:           sol.yield loc(#loc14)
// CHECK-NEXT:         } else {
// CHECK-NEXT:         } loc(#loc14)
// CHECK-NEXT:         sol.yield loc(#loc6)
// CHECK-NEXT:       } step {
// CHECK-NEXT:         %3 = llvm.load %1 {alignment = 32 : i64} : !llvm.ptr<i256> loc(#loc16)
// CHECK-NEXT:         %c1_i256_2 = arith.constant 1 : i256 loc(#loc17)
// CHECK-NEXT:         %4 = arith.addi %3, %c1_i256_2 : i256 loc(#loc18)
// CHECK-NEXT:         llvm.store %4, %1 {alignment = 32 : i64} : !llvm.ptr<i256> loc(#loc19)
// CHECK-NEXT:         sol.yield loc(#loc6)
// CHECK-NEXT:       } loc(#loc6)
// CHECK-NEXT:       %c0_i256_1 = arith.constant 0 : i256 loc(#loc20)
// CHECK-NEXT:       llvm.store %c0_i256_1, %0 {alignment = 32 : i64} : !llvm.ptr<i256> loc(#loc21)
// CHECK-NEXT:       %2 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr<i256> loc(#loc2)
// CHECK-NEXT:       sol.return %2 : i256 loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:4:4)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:20)
// CHECK-NEXT: #loc3 = loc({{.*}}:5:12)
// CHECK-NEXT: #loc4 = loc({{.*}}:5:16)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:21)
// CHECK-NEXT: #loc6 = loc({{.*}}:5:6)
// CHECK-NEXT: #loc7 = loc({{.*}}:5:28)
// CHECK-NEXT: #loc8 = loc({{.*}}:5:31)
// CHECK-NEXT: #loc9 = loc({{.*}}:5:25)
// CHECK-NEXT: #loc10 = loc({{.*}}:6:11)
// CHECK-NEXT: #loc11 = loc({{.*}}:6:8)
// CHECK-NEXT: #loc12 = loc({{.*}}:7:10)
// CHECK-NEXT: #loc13 = loc({{.*}}:9:11)
// CHECK-NEXT: #loc14 = loc({{.*}}:9:8)
// CHECK-NEXT: #loc15 = loc({{.*}}:10:10)
// CHECK-NEXT: #loc16 = loc({{.*}}:5:45)
// CHECK-NEXT: #loc17 = loc({{.*}}:5:48)
// CHECK-NEXT: #loc18 = loc({{.*}}:5:41)
// CHECK-NEXT: #loc19 = loc({{.*}}:5:36)
// CHECK-NEXT: #loc20 = loc({{.*}}:13:11)
// CHECK-NEXT: #loc21 = loc({{.*}}:13:6)
// CHECK-EMPTY:
