// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

pragma solidity ^0.8.0;

function add(uint a, uint b) pure returns (uint) {
  return a + b;
}

contract Test {
  function computeViaPtr() public pure returns (uint) {
    function (uint, uint) pure returns (uint) fp = add;
    return fp(3, 4);
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #Pure = #sol<StateMutability Pure>
// CHECK-NEXT: #loc3 = loc({{.*}}:4:13)
// CHECK-NEXT: #loc4 = loc({{.*}}:4:21)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @Test_39 {
// CHECK-NEXT:     sol.func @Test_39() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @add_15(%arg0: ui256 loc({{.*}}:4:13), %arg1: ui256 loc({{.*}}:4:21)) -> ui256 attributes {id = 15 : i64, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc4)
// CHECK-NEXT:       sol.store %arg1, %1 : ui256, !sol.ptr<ui256, Stack> loc(#loc4)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc5)
// CHECK-NEXT:       %3 = sol.load %1 : !sol.ptr<ui256, Stack>, ui256 loc(#loc6)
// CHECK-NEXT:       %4 = sol.cadd %2, %3 : ui256 loc(#loc5)
// CHECK-NEXT:       sol.return %4 : ui256 loc(#loc7)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     sol.func @computeViaPtr_38() -> ui256 attributes {id = 38 : i64, orig_fn_type = () -> ui256, selector = -1832775887 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.func_constant @add_15 : !sol.func_ref<(ui256, ui256) -> ui256> loc(#loc9)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.func_ref<(ui256, ui256) -> ui256>, Stack> loc(#loc10)
// CHECK-NEXT:       sol.store %0, %1 : !sol.func_ref<(ui256, ui256) -> ui256>, !sol.ptr<!sol.func_ref<(ui256, ui256) -> ui256>, Stack> loc(#loc10)
// CHECK-NEXT:       %c3_ui8 = sol.constant 3 : ui8 loc(#loc11)
// CHECK-NEXT:       %2 = sol.cast %c3_ui8 : ui8 to ui256 loc(#loc11)
// CHECK-NEXT:       %c4_ui8 = sol.constant 4 : ui8 loc(#loc12)
// CHECK-NEXT:       %3 = sol.cast %c4_ui8 : ui8 to ui256 loc(#loc12)
// CHECK-NEXT:       %4 = sol.load %1 : !sol.ptr<!sol.func_ref<(ui256, ui256) -> ui256>, Stack>, !sol.func_ref<(ui256, ui256) -> ui256> loc(#loc13)
// CHECK-NEXT:       %5 = sol.icall %4(%2, %3) : !sol.func_ref<(ui256, ui256) -> ui256>, (ui256, ui256) -> ui256 loc(#loc13)
// CHECK-NEXT:       sol.return %5 : ui256 loc(#loc14)
// CHECK-NEXT:     } loc(#loc8)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:8:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:0)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:9)
// CHECK-NEXT: #loc6 = loc({{.*}}:5:13)
// CHECK-NEXT: #loc7 = loc({{.*}}:5:2)
// CHECK-NEXT: #loc8 = loc({{.*}}:9:2)
// CHECK-NEXT: #loc9 = loc({{.*}}:10:51)
// CHECK-NEXT: #loc10 = loc({{.*}}:10:4)
// CHECK-NEXT: #loc11 = loc({{.*}}:11:14)
// CHECK-NEXT: #loc12 = loc({{.*}}:11:17)
// CHECK-NEXT: #loc13 = loc({{.*}}:11:11)
// CHECK-NEXT: #loc14 = loc({{.*}}:11:4)
// CHECK-EMPTY:
