// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract A {
  uint8 immutable a;
  constructor() {
    a = 4;
  }
}

contract B is A {
  uint8 immutable b;
  constructor() {
    b = 3;
  }
  function f() public view returns (uint8, uint8) {
    return (a, b);
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @A_11 {
// CHECK-NEXT:     sol.immutable @a_2 : ui8 loc(#loc2)
// CHECK-NEXT:     sol.func @_10() attributes {id = 10 : i64, kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @a_2 : !sol.ptr<ui8, Immutable> loc(#loc2)
// CHECK-NEXT:       %c4_ui8 = sol.constant 4 : ui8 loc(#loc4)
// CHECK-NEXT:       sol.store %c4_ui8, %0 : ui8, !sol.ptr<ui8, Immutable> loc(#loc5)
// CHECK-NEXT:       sol.return loc(#loc3)
// CHECK-NEXT:     } loc(#loc3)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:3:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:4:2)
// CHECK-NEXT: #loc4 = loc({{.*}}:5:8)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:4)
// CHECK-NEXT: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #View = #sol<StateMutability View>
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @B_36 {
// CHECK-NEXT:     sol.immutable @b_15 : ui8 loc(#loc2)
// CHECK-NEXT:     sol.immutable @a_2 : ui8 loc(#loc3)
// CHECK-NEXT:     sol.func @_23() attributes {id = 23 : i64, kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.call @_10() : () -> () loc(#loc4)
// CHECK-NEXT:       %0 = sol.addr_of @b_15 : !sol.ptr<ui8, Immutable> loc(#loc2)
// CHECK-NEXT:       %c3_ui8 = sol.constant 3 : ui8 loc(#loc5)
// CHECK-NEXT:       sol.store %c3_ui8, %0 : ui8, !sol.ptr<ui8, Immutable> loc(#loc6)
// CHECK-NEXT:       sol.return loc(#loc4)
// CHECK-NEXT:     } loc(#loc4)
// CHECK-NEXT:     sol.func @f_35() -> (ui8, ui8) attributes {id = 35 : i64, orig_fn_type = () -> (ui8, ui8), selector = 638722032 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.load_immutable @a_2 : ui8 loc(#loc3)
// CHECK-NEXT:       %1 = sol.load_immutable @b_15 : ui8 loc(#loc2)
// CHECK-NEXT:       sol.return %0, %1 : ui8, ui8 loc(#loc8)
// CHECK-NEXT:     } loc(#loc7)
// CHECK-NEXT:     sol.func @_10() attributes {id = 10 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @a_2 : !sol.ptr<ui8, Immutable> loc(#loc3)
// CHECK-NEXT:       %c4_ui8 = sol.constant 4 : ui8 loc(#loc10)
// CHECK-NEXT:       sol.store %c4_ui8, %0 : ui8, !sol.ptr<ui8, Immutable> loc(#loc11)
// CHECK-NEXT:       sol.return loc(#loc9)
// CHECK-NEXT:     } loc(#loc9)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:9:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:10:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:3:2)
// CHECK-NEXT: #loc4 = loc({{.*}}:11:2)
// CHECK-NEXT: #loc5 = loc({{.*}}:12:8)
// CHECK-NEXT: #loc6 = loc({{.*}}:12:4)
// CHECK-NEXT: #loc7 = loc({{.*}}:14:2)
// CHECK-NEXT: #loc8 = loc({{.*}}:15:4)
// CHECK-NEXT: #loc9 = loc({{.*}}:4:2)
// CHECK-NEXT: #loc10 = loc({{.*}}:5:8)
// CHECK-NEXT: #loc11 = loc({{.*}}:5:4)
// CHECK-EMPTY:
