// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

interface I {
  function h(uint x) external pure returns (uint);
}

contract D is I {
  uint state;
  function h(uint x) external pure returns (uint) { return x + 1; }
  function setState(uint x) external returns (uint) { state = x; return x; }
}

contract C {
  function f(uint a) internal returns (uint) { return a + 10; }
  function m(uint a) public returns (uint) {
    function(uint) internal returns (uint) p;
    p = f;
    return p(a);
  }

  I t;

  function call(uint x) public view returns (uint) {
    function(uint) external pure returns (uint) fp = t.h;
    return fp(x);
  }

  function callGas(uint x) public view returns (uint) {
    function(uint) external pure returns (uint) fp = t.h;
    return fp{gas: 100000}(x);
  }

  function tryCall(uint x) public returns (bool, uint) {
    function(uint) external pure returns (uint) fp = t.h;
    bool success;
    uint result;
    try fp(x) returns (uint r) {
      success = true;
      result = r;
    } catch {
      success = false;
      result = 0;
    }
    return (success, result);
  }

  function tryCallGas(uint x) public returns (bool, uint) {
    function(uint) external pure returns (uint) fp = t.h;
    bool success;
    uint result;
    try fp{gas: 100000}(x) returns (uint r) {
      success = true;
      result = r;
    } catch {
      success = false;
      result = 0;
    }
    return (success, result);
  }

  function callNonPure(uint x) public returns (uint) {
    function(uint) external returns (uint) fp = D(address(t)).setState;
    return fp(x);
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #Pure = #sol<StateMutability Pure>
// CHECK-NEXT: #loc4 = loc({{.*}}:8:13)
// CHECK-NEXT: #loc9 = loc({{.*}}:9:20)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @D_39 {
// CHECK-NEXT:     sol.state_var @state_12 slot 0 offset 0 : ui256 loc(#loc2)
// CHECK-NEXT:     sol.func @D_39() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @h_24(%arg0: ui256 loc({{.*}}:8:13)) -> ui256 attributes {id = 24 : i64, orig_fn_type = (ui256) -> ui256, selector = -879277782 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc4)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc4)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc5)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc6)
// CHECK-NEXT:       %2 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc6)
// CHECK-NEXT:       %3 = sol.cadd %1, %2 : ui256 loc(#loc5)
// CHECK-NEXT:       sol.return %3 : ui256 loc(#loc7)
// CHECK-NEXT:     } loc(#loc3)
// CHECK-NEXT:     sol.func @setState_38(%arg0: ui256 loc({{.*}}:9:20)) -> ui256 attributes {id = 38 : i64, orig_fn_type = (ui256) -> ui256, selector = -1444321609 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc9)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc9)
// CHECK-NEXT:       %1 = sol.addr_of @state_12 : !sol.ptr<ui256, Storage> loc(#loc2)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc10)
// CHECK-NEXT:       sol.store %2, %1 : ui256, !sol.ptr<ui256, Storage> loc(#loc11)
// CHECK-NEXT:       %3 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc12)
// CHECK-NEXT:       sol.return %3 : ui256 loc(#loc13)
// CHECK-NEXT:     } loc(#loc8)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:6:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:7:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:8:2)
// CHECK-NEXT: #loc5 = loc({{.*}}:8:59)
// CHECK-NEXT: #loc6 = loc({{.*}}:8:63)
// CHECK-NEXT: #loc7 = loc({{.*}}:8:52)
// CHECK-NEXT: #loc8 = loc({{.*}}:9:2)
// CHECK-NEXT: #loc10 = loc({{.*}}:9:62)
// CHECK-NEXT: #loc11 = loc({{.*}}:9:54)
// CHECK-NEXT: #loc12 = loc({{.*}}:9:72)
// CHECK-NEXT: #loc13 = loc({{.*}}:9:65)
// CHECK-NEXT: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #View = #sol<StateMutability View>
// CHECK-NEXT: #loc4 = loc({{.*}}:13:13)
// CHECK-NEXT: #loc9 = loc({{.*}}:14:13)
// CHECK-NEXT: #loc17 = loc({{.*}}:22:16)
// CHECK-NEXT: #loc24 = loc({{.*}}:27:19)
// CHECK-NEXT: #loc32 = loc({{.*}}:32:19)
// CHECK-NEXT: #loc52 = loc({{.*}}:46:22)
// CHECK-NEXT: #loc73 = loc({{.*}}:60:23)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @C_274 {
// CHECK-NEXT:     sol.state_var @t_79 slot 0 offset 0 : !sol.contract<"I_8"> loc(#loc2)
// CHECK-NEXT:     sol.func @C_274() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @f_51(%arg0: ui256 loc({{.*}}:13:13)) -> ui256 attributes {id = 51 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc4)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc4)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc5)
// CHECK-NEXT:       %c10_ui8 = sol.constant 10 : ui8 loc(#loc6)
// CHECK-NEXT:       %2 = sol.cast %c10_ui8 : ui8 to ui256 loc(#loc6)
// CHECK-NEXT:       %3 = sol.cadd %1, %2 : ui256 loc(#loc5)
// CHECK-NEXT:       sol.return %3 : ui256 loc(#loc7)
// CHECK-NEXT:     } loc(#loc3)
// CHECK-NEXT:     sol.func @m_76(%arg0: ui256 loc({{.*}}:14:13)) -> ui256 attributes {id = 76 : i64, orig_fn_type = (ui256) -> ui256, selector = 1855197366 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc9)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc9)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.func_ref<(ui256) -> ui256>, Stack> loc(#loc10)
// CHECK-NEXT:       %2 = sol.default_func_constant : !sol.func_ref<() -> ()> loc(#loc10)
// CHECK-NEXT:       sol.store %2, %1 : !sol.func_ref<() -> ()>, !sol.ptr<!sol.func_ref<(ui256) -> ui256>, Stack> loc(#loc10)
// CHECK-NEXT:       %3 = sol.func_constant @f_51 : !sol.func_ref<(ui256) -> ui256> loc(#loc11)
// CHECK-NEXT:       sol.store %3, %1 : !sol.func_ref<(ui256) -> ui256>, !sol.ptr<!sol.func_ref<(ui256) -> ui256>, Stack> loc(#loc12)
// CHECK-NEXT:       %4 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc13)
// CHECK-NEXT:       %5 = sol.load %1 : !sol.ptr<!sol.func_ref<(ui256) -> ui256>, Stack>, !sol.func_ref<(ui256) -> ui256> loc(#loc14)
// CHECK-NEXT:       %6 = sol.icall %5(%4) : !sol.func_ref<(ui256) -> ui256>, (ui256) -> ui256 loc(#loc14)
// CHECK-NEXT:       sol.return %6 : ui256 loc(#loc15)
// CHECK-NEXT:     } loc(#loc8)
// CHECK-NEXT:     sol.func @call_102(%arg0: ui256 loc({{.*}}:22:16)) -> ui256 attributes {id = 102 : i64, orig_fn_type = (ui256) -> ui256, selector = 722037030 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc17)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc17)
// CHECK-NEXT:       %1 = sol.addr_of @t_79 : !sol.ptr<!sol.contract<"I_8">, Storage> loc(#loc2)
// CHECK-NEXT:       %2 = sol.load %1 : !sol.ptr<!sol.contract<"I_8">, Storage>, !sol.contract<"I_8"> loc(#loc18)
// CHECK-NEXT:       %3 = sol.address_cast %2 : !sol.contract<"I_8"> to !sol.address loc(#loc18)
// CHECK-NEXT:       %4 = sol.ext_func_constant %3 {selector = -879277782 : i32} : !sol.address -> !sol.ext_func_ref<(ui256) -> ui256> loc(#loc18)
// CHECK-NEXT:       %5 = sol.alloca : !sol.ptr<!sol.ext_func_ref<(ui256) -> ui256>, Stack> loc(#loc19)
// CHECK-NEXT:       sol.store %4, %5 : !sol.ext_func_ref<(ui256) -> ui256>, !sol.ptr<!sol.ext_func_ref<(ui256) -> ui256>, Stack> loc(#loc19)
// CHECK-NEXT:       %6 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc20)
// CHECK-NEXT:       %7 = sol.load %5 : !sol.ptr<!sol.ext_func_ref<(ui256) -> ui256>, Stack>, !sol.ext_func_ref<(ui256) -> ui256> loc(#loc21)
// CHECK-NEXT:       %8 = sol.gasleft : ui256 loc(#loc21)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc21)
// CHECK-NEXT:       %9:2 = sol.ext_icall %7(%6) gas %8 value %c0_ui256 {static_call} : !sol.ext_func_ref<(ui256) -> ui256>, (ui256) -> (i1, ui256) loc(#loc21)
// CHECK-NEXT:       sol.return %9#1 : ui256 loc(#loc22)
// CHECK-NEXT:     } loc(#loc16)
// CHECK-NEXT:     sol.func @callGas_127(%arg0: ui256 loc({{.*}}:27:19)) -> ui256 attributes {id = 127 : i64, orig_fn_type = (ui256) -> ui256, selector = 1084980789 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc24)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc24)
// CHECK-NEXT:       %1 = sol.addr_of @t_79 : !sol.ptr<!sol.contract<"I_8">, Storage> loc(#loc2)
// CHECK-NEXT:       %2 = sol.load %1 : !sol.ptr<!sol.contract<"I_8">, Storage>, !sol.contract<"I_8"> loc(#loc25)
// CHECK-NEXT:       %3 = sol.address_cast %2 : !sol.contract<"I_8"> to !sol.address loc(#loc25)
// CHECK-NEXT:       %4 = sol.ext_func_constant %3 {selector = -879277782 : i32} : !sol.address -> !sol.ext_func_ref<(ui256) -> ui256> loc(#loc25)
// CHECK-NEXT:       %5 = sol.alloca : !sol.ptr<!sol.ext_func_ref<(ui256) -> ui256>, Stack> loc(#loc26)
// CHECK-NEXT:       sol.store %4, %5 : !sol.ext_func_ref<(ui256) -> ui256>, !sol.ptr<!sol.ext_func_ref<(ui256) -> ui256>, Stack> loc(#loc26)
// CHECK-NEXT:       %c100000_ui24 = sol.constant 100000 : ui24 loc(#loc27)
// CHECK-NEXT:       %6 = sol.cast %c100000_ui24 : ui24 to ui256 loc(#loc27)
// CHECK-NEXT:       %7 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc28)
// CHECK-NEXT:       %8 = sol.load %5 : !sol.ptr<!sol.ext_func_ref<(ui256) -> ui256>, Stack>, !sol.ext_func_ref<(ui256) -> ui256> loc(#loc29)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc29)
// CHECK-NEXT:       %9:2 = sol.ext_icall %8(%7) gas %6 value %c0_ui256 {static_call} : !sol.ext_func_ref<(ui256) -> ui256>, (ui256) -> (i1, ui256) loc(#loc29)
// CHECK-NEXT:       sol.return %9#1 : ui256 loc(#loc30)
// CHECK-NEXT:     } loc(#loc23)
// CHECK-NEXT:     sol.func @tryCall_185(%arg0: ui256 loc({{.*}}:32:19)) -> (i1, ui256) attributes {id = 185 : i64, orig_fn_type = (ui256) -> (i1, ui256), selector = 1065929330 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc32)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc32)
// CHECK-NEXT:       %1 = sol.addr_of @t_79 : !sol.ptr<!sol.contract<"I_8">, Storage> loc(#loc2)
// CHECK-NEXT:       %2 = sol.load %1 : !sol.ptr<!sol.contract<"I_8">, Storage>, !sol.contract<"I_8"> loc(#loc33)
// CHECK-NEXT:       %3 = sol.address_cast %2 : !sol.contract<"I_8"> to !sol.address loc(#loc33)
// CHECK-NEXT:       %4 = sol.ext_func_constant %3 {selector = -879277782 : i32} : !sol.address -> !sol.ext_func_ref<(ui256) -> ui256> loc(#loc33)
// CHECK-NEXT:       %5 = sol.alloca : !sol.ptr<!sol.ext_func_ref<(ui256) -> ui256>, Stack> loc(#loc34)
// CHECK-NEXT:       sol.store %4, %5 : !sol.ext_func_ref<(ui256) -> ui256>, !sol.ptr<!sol.ext_func_ref<(ui256) -> ui256>, Stack> loc(#loc34)
// CHECK-NEXT:       %6 = sol.alloca : !sol.ptr<i1, Stack> loc(#loc35)
// CHECK-NEXT:       %false = sol.constant false loc(#loc35)
// CHECK-NEXT:       sol.store %false, %6 : i1, !sol.ptr<i1, Stack> loc(#loc35)
// CHECK-NEXT:       %7 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc36)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc36)
// CHECK-NEXT:       sol.store %c0_ui256, %7 : ui256, !sol.ptr<ui256, Stack> loc(#loc36)
// CHECK-NEXT:       %8 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc37)
// CHECK-NEXT:       %9 = sol.load %5 : !sol.ptr<!sol.ext_func_ref<(ui256) -> ui256>, Stack>, !sol.ext_func_ref<(ui256) -> ui256> loc(#loc38)
// CHECK-NEXT:       %10 = sol.gasleft : ui256 loc(#loc38)
// CHECK-NEXT:       %c0_ui256_0 = sol.constant 0 : ui256 loc(#loc38)
// CHECK-NEXT:       %11:2 = sol.ext_icall %9(%8) gas %10 value %c0_ui256_0 {static_call, try_call} : !sol.ext_func_ref<(ui256) -> ui256>, (ui256) -> (i1, ui256) loc(#loc38)
// CHECK-NEXT:       sol.try %11#0 {
// CHECK-NEXT:         %14 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc40)
// CHECK-NEXT:         sol.store %11#1, %14 : ui256, !sol.ptr<ui256, Stack> loc(#loc40)
// CHECK-NEXT:         %true = sol.constant true loc(#loc41)
// CHECK-NEXT:         sol.store %true, %6 : i1, !sol.ptr<i1, Stack> loc(#loc42)
// CHECK-NEXT:         %15 = sol.load %14 : !sol.ptr<ui256, Stack>, ui256 loc(#loc43)
// CHECK-NEXT:         sol.store %15, %7 : ui256, !sol.ptr<ui256, Stack> loc(#loc44)
// CHECK-NEXT:         sol.yield loc(#loc39)
// CHECK-NEXT:       } panic {
// CHECK-NEXT:       } error {
// CHECK-NEXT:       } fallback {
// CHECK-NEXT:         %false_1 = sol.constant false loc(#loc45)
// CHECK-NEXT:         sol.store %false_1, %6 : i1, !sol.ptr<i1, Stack> loc(#loc46)
// CHECK-NEXT:         %c0_ui8 = sol.constant 0 : ui8 loc(#loc47)
// CHECK-NEXT:         %14 = sol.cast %c0_ui8 : ui8 to ui256 loc(#loc47)
// CHECK-NEXT:         sol.store %14, %7 : ui256, !sol.ptr<ui256, Stack> loc(#loc48)
// CHECK-NEXT:         sol.yield loc(#loc39)
// CHECK-NEXT:       } loc(#loc39)
// CHECK-NEXT:       %12 = sol.load %6 : !sol.ptr<i1, Stack>, i1 loc(#loc49)
// CHECK-NEXT:       %13 = sol.load %7 : !sol.ptr<ui256, Stack>, ui256 loc(#loc49)
// CHECK-NEXT:       sol.return %12, %13 : i1, ui256 loc(#loc50)
// CHECK-NEXT:     } loc(#loc31)
// CHECK-NEXT:     sol.func @tryCallGas_245(%arg0: ui256 loc({{.*}}:46:22)) -> (i1, ui256) attributes {id = 245 : i64, orig_fn_type = (ui256) -> (i1, ui256), selector = 1944045799 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc52)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc52)
// CHECK-NEXT:       %1 = sol.addr_of @t_79 : !sol.ptr<!sol.contract<"I_8">, Storage> loc(#loc2)
// CHECK-NEXT:       %2 = sol.load %1 : !sol.ptr<!sol.contract<"I_8">, Storage>, !sol.contract<"I_8"> loc(#loc53)
// CHECK-NEXT:       %3 = sol.address_cast %2 : !sol.contract<"I_8"> to !sol.address loc(#loc53)
// CHECK-NEXT:       %4 = sol.ext_func_constant %3 {selector = -879277782 : i32} : !sol.address -> !sol.ext_func_ref<(ui256) -> ui256> loc(#loc53)
// CHECK-NEXT:       %5 = sol.alloca : !sol.ptr<!sol.ext_func_ref<(ui256) -> ui256>, Stack> loc(#loc54)
// CHECK-NEXT:       sol.store %4, %5 : !sol.ext_func_ref<(ui256) -> ui256>, !sol.ptr<!sol.ext_func_ref<(ui256) -> ui256>, Stack> loc(#loc54)
// CHECK-NEXT:       %6 = sol.alloca : !sol.ptr<i1, Stack> loc(#loc55)
// CHECK-NEXT:       %false = sol.constant false loc(#loc55)
// CHECK-NEXT:       sol.store %false, %6 : i1, !sol.ptr<i1, Stack> loc(#loc55)
// CHECK-NEXT:       %7 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc56)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc56)
// CHECK-NEXT:       sol.store %c0_ui256, %7 : ui256, !sol.ptr<ui256, Stack> loc(#loc56)
// CHECK-NEXT:       %c100000_ui24 = sol.constant 100000 : ui24 loc(#loc57)
// CHECK-NEXT:       %8 = sol.cast %c100000_ui24 : ui24 to ui256 loc(#loc57)
// CHECK-NEXT:       %9 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc58)
// CHECK-NEXT:       %10 = sol.load %5 : !sol.ptr<!sol.ext_func_ref<(ui256) -> ui256>, Stack>, !sol.ext_func_ref<(ui256) -> ui256> loc(#loc59)
// CHECK-NEXT:       %c0_ui256_0 = sol.constant 0 : ui256 loc(#loc59)
// CHECK-NEXT:       %11:2 = sol.ext_icall %10(%9) gas %8 value %c0_ui256_0 {static_call, try_call} : !sol.ext_func_ref<(ui256) -> ui256>, (ui256) -> (i1, ui256) loc(#loc59)
// CHECK-NEXT:       sol.try %11#0 {
// CHECK-NEXT:         %14 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc61)
// CHECK-NEXT:         sol.store %11#1, %14 : ui256, !sol.ptr<ui256, Stack> loc(#loc61)
// CHECK-NEXT:         %true = sol.constant true loc(#loc62)
// CHECK-NEXT:         sol.store %true, %6 : i1, !sol.ptr<i1, Stack> loc(#loc63)
// CHECK-NEXT:         %15 = sol.load %14 : !sol.ptr<ui256, Stack>, ui256 loc(#loc64)
// CHECK-NEXT:         sol.store %15, %7 : ui256, !sol.ptr<ui256, Stack> loc(#loc65)
// CHECK-NEXT:         sol.yield loc(#loc60)
// CHECK-NEXT:       } panic {
// CHECK-NEXT:       } error {
// CHECK-NEXT:       } fallback {
// CHECK-NEXT:         %false_1 = sol.constant false loc(#loc66)
// CHECK-NEXT:         sol.store %false_1, %6 : i1, !sol.ptr<i1, Stack> loc(#loc67)
// CHECK-NEXT:         %c0_ui8 = sol.constant 0 : ui8 loc(#loc68)
// CHECK-NEXT:         %14 = sol.cast %c0_ui8 : ui8 to ui256 loc(#loc68)
// CHECK-NEXT:         sol.store %14, %7 : ui256, !sol.ptr<ui256, Stack> loc(#loc69)
// CHECK-NEXT:         sol.yield loc(#loc60)
// CHECK-NEXT:       } loc(#loc60)
// CHECK-NEXT:       %12 = sol.load %6 : !sol.ptr<i1, Stack>, i1 loc(#loc70)
// CHECK-NEXT:       %13 = sol.load %7 : !sol.ptr<ui256, Stack>, ui256 loc(#loc70)
// CHECK-NEXT:       sol.return %12, %13 : i1, ui256 loc(#loc71)
// CHECK-NEXT:     } loc(#loc51)
// CHECK-NEXT:     sol.func @callNonPure_273(%arg0: ui256 loc({{.*}}:60:23)) -> ui256 attributes {id = 273 : i64, orig_fn_type = (ui256) -> ui256, selector = -950325456 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc73)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc73)
// CHECK-NEXT:       %1 = sol.addr_of @t_79 : !sol.ptr<!sol.contract<"I_8">, Storage> loc(#loc2)
// CHECK-NEXT:       %2 = sol.load %1 : !sol.ptr<!sol.contract<"I_8">, Storage>, !sol.contract<"I_8"> loc(#loc74)
// CHECK-NEXT:       %3 = sol.address_cast %2 : !sol.contract<"I_8"> to !sol.address loc(#loc74)
// CHECK-NEXT:       %4 = sol.address_cast %3 : !sol.address to !sol.contract<"D_39"> loc(#loc74)
// CHECK-NEXT:       %5 = sol.address_cast %4 : !sol.contract<"D_39"> to !sol.address loc(#loc74)
// CHECK-NEXT:       %6 = sol.ext_func_constant %5 {selector = -1444321609 : i32} : !sol.address -> !sol.ext_func_ref<(ui256) -> ui256> loc(#loc75)
// CHECK-NEXT:       %7 = sol.alloca : !sol.ptr<!sol.ext_func_ref<(ui256) -> ui256>, Stack> loc(#loc76)
// CHECK-NEXT:       sol.store %6, %7 : !sol.ext_func_ref<(ui256) -> ui256>, !sol.ptr<!sol.ext_func_ref<(ui256) -> ui256>, Stack> loc(#loc76)
// CHECK-NEXT:       %8 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc77)
// CHECK-NEXT:       %9 = sol.load %7 : !sol.ptr<!sol.ext_func_ref<(ui256) -> ui256>, Stack>, !sol.ext_func_ref<(ui256) -> ui256> loc(#loc78)
// CHECK-NEXT:       %10 = sol.gasleft : ui256 loc(#loc78)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc78)
// CHECK-NEXT:       %11:2 = sol.ext_icall %9(%8) gas %10 value %c0_ui256 : !sol.ext_func_ref<(ui256) -> ui256>, (ui256) -> (i1, ui256) loc(#loc78)
// CHECK-NEXT:       sol.return %11#1 : ui256 loc(#loc79)
// CHECK-NEXT:     } loc(#loc72)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:12:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:20:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:13:2)
// CHECK-NEXT: #loc5 = loc({{.*}}:13:54)
// CHECK-NEXT: #loc6 = loc({{.*}}:13:58)
// CHECK-NEXT: #loc7 = loc({{.*}}:13:47)
// CHECK-NEXT: #loc8 = loc({{.*}}:14:2)
// CHECK-NEXT: #loc10 = loc({{.*}}:15:4)
// CHECK-NEXT: #loc11 = loc({{.*}}:16:8)
// CHECK-NEXT: #loc12 = loc({{.*}}:16:4)
// CHECK-NEXT: #loc13 = loc({{.*}}:17:13)
// CHECK-NEXT: #loc14 = loc({{.*}}:17:11)
// CHECK-NEXT: #loc15 = loc({{.*}}:17:4)
// CHECK-NEXT: #loc16 = loc({{.*}}:22:2)
// CHECK-NEXT: #loc18 = loc({{.*}}:23:53)
// CHECK-NEXT: #loc19 = loc({{.*}}:23:4)
// CHECK-NEXT: #loc20 = loc({{.*}}:24:14)
// CHECK-NEXT: #loc21 = loc({{.*}}:24:11)
// CHECK-NEXT: #loc22 = loc({{.*}}:24:4)
// CHECK-NEXT: #loc23 = loc({{.*}}:27:2)
// CHECK-NEXT: #loc25 = loc({{.*}}:28:53)
// CHECK-NEXT: #loc26 = loc({{.*}}:28:4)
// CHECK-NEXT: #loc27 = loc({{.*}}:29:19)
// CHECK-NEXT: #loc28 = loc({{.*}}:29:27)
// CHECK-NEXT: #loc29 = loc({{.*}}:29:11)
// CHECK-NEXT: #loc30 = loc({{.*}}:29:4)
// CHECK-NEXT: #loc31 = loc({{.*}}:32:2)
// CHECK-NEXT: #loc33 = loc({{.*}}:33:53)
// CHECK-NEXT: #loc34 = loc({{.*}}:33:4)
// CHECK-NEXT: #loc35 = loc({{.*}}:34:4)
// CHECK-NEXT: #loc36 = loc({{.*}}:35:4)
// CHECK-NEXT: #loc37 = loc({{.*}}:36:11)
// CHECK-NEXT: #loc38 = loc({{.*}}:36:8)
// CHECK-NEXT: #loc39 = loc({{.*}}:36:4)
// CHECK-NEXT: #loc40 = loc({{.*}}:36:23)
// CHECK-NEXT: #loc41 = loc({{.*}}:37:16)
// CHECK-NEXT: #loc42 = loc({{.*}}:37:6)
// CHECK-NEXT: #loc43 = loc({{.*}}:38:15)
// CHECK-NEXT: #loc44 = loc({{.*}}:38:6)
// CHECK-NEXT: #loc45 = loc({{.*}}:40:16)
// CHECK-NEXT: #loc46 = loc({{.*}}:40:6)
// CHECK-NEXT: #loc47 = loc({{.*}}:41:15)
// CHECK-NEXT: #loc48 = loc({{.*}}:41:6)
// CHECK-NEXT: #loc49 = loc({{.*}}:43:11)
// CHECK-NEXT: #loc50 = loc({{.*}}:43:4)
// CHECK-NEXT: #loc51 = loc({{.*}}:46:2)
// CHECK-NEXT: #loc53 = loc({{.*}}:47:53)
// CHECK-NEXT: #loc54 = loc({{.*}}:47:4)
// CHECK-NEXT: #loc55 = loc({{.*}}:48:4)
// CHECK-NEXT: #loc56 = loc({{.*}}:49:4)
// CHECK-NEXT: #loc57 = loc({{.*}}:50:16)
// CHECK-NEXT: #loc58 = loc({{.*}}:50:24)
// CHECK-NEXT: #loc59 = loc({{.*}}:50:8)
// CHECK-NEXT: #loc60 = loc({{.*}}:50:4)
// CHECK-NEXT: #loc61 = loc({{.*}}:50:36)
// CHECK-NEXT: #loc62 = loc({{.*}}:51:16)
// CHECK-NEXT: #loc63 = loc({{.*}}:51:6)
// CHECK-NEXT: #loc64 = loc({{.*}}:52:15)
// CHECK-NEXT: #loc65 = loc({{.*}}:52:6)
// CHECK-NEXT: #loc66 = loc({{.*}}:54:16)
// CHECK-NEXT: #loc67 = loc({{.*}}:54:6)
// CHECK-NEXT: #loc68 = loc({{.*}}:55:15)
// CHECK-NEXT: #loc69 = loc({{.*}}:55:6)
// CHECK-NEXT: #loc70 = loc({{.*}}:57:11)
// CHECK-NEXT: #loc71 = loc({{.*}}:57:4)
// CHECK-NEXT: #loc72 = loc({{.*}}:60:2)
// CHECK-NEXT: #loc74 = loc({{.*}}:61:58)
// CHECK-NEXT: #loc75 = loc({{.*}}:61:48)
// CHECK-NEXT: #loc76 = loc({{.*}}:61:4)
// CHECK-NEXT: #loc77 = loc({{.*}}:62:14)
// CHECK-NEXT: #loc78 = loc({{.*}}:62:11)
// CHECK-NEXT: #loc79 = loc({{.*}}:62:4)
// CHECK-EMPTY:
