// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

function ff() returns(uint) { return L.f(1); }

library L {
  function f(uint a) internal returns(uint) { return a + 1; }
  function g(uint a) public returns(uint) { return f(a) + ff(); }
}

contract C {
  function f() public returns(uint) { return L.f(1); }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Library = #sol<ContractKind Library>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #loc2 = loc({{.*}}:5:13)
// CHECK-NEXT: #loc12 = loc({{.*}}:6:13)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka} {
// CHECK-NEXT:   sol.func @f_23(%arg0: ui256 loc({{.*}}:5:13)) -> ui256 attributes {id = 23 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:     %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc2)
// CHECK-NEXT:     sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc2)
// CHECK-NEXT:     %1 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc3)
// CHECK-NEXT:     %c1_ui8 = sol.constant 1 : ui8 loc(#loc4)
// CHECK-NEXT:     %2 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc4)
// CHECK-NEXT:     %3 = sol.cadd %1, %2 : ui256 loc(#loc3)
// CHECK-NEXT:     sol.return %3 : ui256 loc(#loc5)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   sol.func @ff_11() -> ui256 attributes {id = 11 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:     %c1_ui8 = sol.constant 1 : ui8 loc(#loc7)
// CHECK-NEXT:     %0 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc7)
// CHECK-NEXT:     %1 = sol.call @f_23(%0) : (ui256) -> ui256 loc(#loc8)
// CHECK-NEXT:     sol.return %1 : ui256 loc(#loc9)
// CHECK-NEXT:   } loc(#loc6)
// CHECK-NEXT:   sol.contract @L_39 {
// CHECK-NEXT:     sol.func @f_23(%arg0: ui256 loc({{.*}}:5:13)) -> ui256 attributes {id = 23 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc2)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc2)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc3)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc4)
// CHECK-NEXT:       %2 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc4)
// CHECK-NEXT:       %3 = sol.cadd %1, %2 : ui256 loc(#loc3)
// CHECK-NEXT:       sol.return %3 : ui256 loc(#loc5)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @ff_11() -> ui256 attributes {id = 11 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc7)
// CHECK-NEXT:       %0 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc7)
// CHECK-NEXT:       %1 = sol.call @f_23(%0) : (ui256) -> ui256 loc(#loc8)
// CHECK-NEXT:       sol.return %1 : ui256 loc(#loc9)
// CHECK-NEXT:     } loc(#loc6)
// CHECK-NEXT:     sol.func @g_38(%arg0: ui256 loc({{.*}}:6:13)) -> ui256 attributes {id = 38 : i64, orig_fn_type = (ui256) -> ui256, selector = -467655094 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc12)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc12)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc13)
// CHECK-NEXT:       %2 = sol.call @f_23(%1) : (ui256) -> ui256 loc(#loc14)
// CHECK-NEXT:       %3 = sol.call @ff_11() : () -> ui256 loc(#loc15)
// CHECK-NEXT:       %4 = sol.cadd %2, %3 : ui256 loc(#loc14)
// CHECK-NEXT:       sol.return %4 : ui256 loc(#loc16)
// CHECK-NEXT:     } loc(#loc11)
// CHECK-NEXT:   } {kind = #Library} loc(#loc10)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:5:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:5:53)
// CHECK-NEXT: #loc4 = loc({{.*}}:5:57)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:46)
// CHECK-NEXT: #loc6 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc7 = loc({{.*}}:2:41)
// CHECK-NEXT: #loc8 = loc({{.*}}:2:37)
// CHECK-NEXT: #loc9 = loc({{.*}}:2:30)
// CHECK-NEXT: #loc10 = loc({{.*}}:4:0)
// CHECK-NEXT: #loc11 = loc({{.*}}:6:2)
// CHECK-NEXT: #loc13 = loc({{.*}}:6:53)
// CHECK-NEXT: #loc14 = loc({{.*}}:6:51)
// CHECK-NEXT: #loc15 = loc({{.*}}:6:58)
// CHECK-NEXT: #loc16 = loc({{.*}}:6:44)
// CHECK-NEXT: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #loc2 = loc({{.*}}:5:13)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka} {
// CHECK-NEXT:   sol.func @f_23(%arg0: ui256 loc({{.*}}:5:13)) -> ui256 attributes {id = 23 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:     %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc2)
// CHECK-NEXT:     sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc2)
// CHECK-NEXT:     %1 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc3)
// CHECK-NEXT:     %c1_ui8 = sol.constant 1 : ui8 loc(#loc4)
// CHECK-NEXT:     %2 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc4)
// CHECK-NEXT:     %3 = sol.cadd %1, %2 : ui256 loc(#loc3)
// CHECK-NEXT:     sol.return %3 : ui256 loc(#loc5)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   sol.func @ff_11() -> ui256 attributes {id = 11 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:     %c1_ui8 = sol.constant 1 : ui8 loc(#loc7)
// CHECK-NEXT:     %0 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc7)
// CHECK-NEXT:     %1 = sol.call @f_23(%0) : (ui256) -> ui256 loc(#loc8)
// CHECK-NEXT:     sol.return %1 : ui256 loc(#loc9)
// CHECK-NEXT:   } loc(#loc6)
// CHECK-NEXT:   sol.contract @C_51 {
// CHECK-NEXT:     sol.func @C_51() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc10)
// CHECK-NEXT:     } loc(#loc10)
// CHECK-NEXT:     sol.func @f_23(%arg0: ui256 loc({{.*}}:5:13)) -> ui256 attributes {id = 23 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc2)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc2)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc3)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc4)
// CHECK-NEXT:       %2 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc4)
// CHECK-NEXT:       %3 = sol.cadd %1, %2 : ui256 loc(#loc3)
// CHECK-NEXT:       sol.return %3 : ui256 loc(#loc5)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @f_50() -> ui256 attributes {id = 50 : i64, orig_fn_type = () -> ui256, selector = 638722032 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc12)
// CHECK-NEXT:       %0 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc12)
// CHECK-NEXT:       %1 = sol.call @f_23(%0) : (ui256) -> ui256 loc(#loc13)
// CHECK-NEXT:       sol.return %1 : ui256 loc(#loc14)
// CHECK-NEXT:     } loc(#loc11)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc10)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:5:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:5:53)
// CHECK-NEXT: #loc4 = loc({{.*}}:5:57)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:46)
// CHECK-NEXT: #loc6 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc7 = loc({{.*}}:2:41)
// CHECK-NEXT: #loc8 = loc({{.*}}:2:37)
// CHECK-NEXT: #loc9 = loc({{.*}}:2:30)
// CHECK-NEXT: #loc10 = loc({{.*}}:9:0)
// CHECK-NEXT: #loc11 = loc({{.*}}:10:2)
// CHECK-NEXT: #loc12 = loc({{.*}}:10:49)
// CHECK-NEXT: #loc13 = loc({{.*}}:10:45)
// CHECK-NEXT: #loc14 = loc({{.*}}:10:38)
// CHECK-EMPTY:
