// RUN: solc --mlir-action=print-init --mmlir=--mlir-print-debuginfo %s | FileCheck %s

contract C {
  enum E { A, B, C }

  function add(uint a, uint b) external pure returns (uint) {
    return a + b;
  }

  function loadMemoryByte(bytes memory data) external pure returns (bytes1) {
    return data[0];
  }

  function storeMemoryByte(bytes memory data, bytes1 value) external pure{
    data[0] = value;
  }

  function loadMemoryBool(bool[] memory values) external pure returns (bool) {
    return values[0];
  }

  function storeMemoryBool(bool[] memory values, bool value) external pure {
    values[0] = value;
  }

  function loadMemoryUint8(uint8[] memory values) external pure returns (uint8) {
    return values[0];
  }

  function storeMemoryUint8(uint8[] memory values, uint8 value) external pure {
    values[0] = value;
  }

  function loadMemoryInt8(int8[] memory values) external pure returns (int8) {
    return values[0];
  }

  function storeMemoryInt8(int8[] memory values, int8 value) external pure {
    values[0] = value;
  }

  function loadMemoryEnum(E[] memory values) external pure returns (uint8) {
    return uint8(values[0]);
  }

  function discardMemoryEnum(E[] memory values) external pure returns (uint8) {
    values[0];
    return 1;
  }

  function storeMemoryEnum(E[] memory values, E value) external pure {
    values[0] = value;
  }

  function loadMemoryAddress(address[] memory values) external pure returns (address) {
    return values[0];
  }

  function storeMemoryAddress(address[] memory values, address value) external pure {
    values[0] = value;
  }

  function loadMemoryBytes4(bytes4[] memory values) external pure returns (bytes4) {
    return values[0];
  }

  function storeMemoryBytes4(bytes4[] memory values, bytes4 value) external pure {
    values[0] = value;
  }

  function loadMemoryBytes31(bytes31[] memory values) external pure returns (bytes31) {
    return values[0];
  }

  function storeMemoryBytes31(bytes31[] memory values, bytes31 value) external pure {
    values[0] = value;
  }

  function loadMemoryFnPtrHelper(function(uint, uint) external pure returns (uint)[] memory values) external view returns (uint) {
    return values[0](20, 22);
  }

  function storeMemoryFnPtr(function(uint, uint) external pure returns (uint)[] memory values,
                            function(uint, uint) external pure returns (uint) value) external pure {
    values[0] = value;
  }

  function loadMemoryFnPtrSuccess() external returns (uint) {
    function(uint, uint) external pure returns (uint)[] memory values =
      new function(uint, uint) external pure returns (uint)[](1);
    values[0] = this.add;
    return this.loadMemoryFnPtrHelper(values);
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #Pure = #sol<StateMutability Pure>
// CHECK-NEXT: #View = #sol<StateMutability View>
// CHECK-NEXT: #loc3 = loc({{.*}}:5:15)
// CHECK-NEXT: #loc4 = loc({{.*}}:5:23)
// CHECK-NEXT: #loc9 = loc({{.*}}:9:26)
// CHECK-NEXT: #loc14 = loc({{.*}}:13:27)
// CHECK-NEXT: #loc15 = loc({{.*}}:13:46)
// CHECK-NEXT: #loc20 = loc({{.*}}:17:26)
// CHECK-NEXT: #loc25 = loc({{.*}}:21:27)
// CHECK-NEXT: #loc26 = loc({{.*}}:21:49)
// CHECK-NEXT: #loc31 = loc({{.*}}:25:27)
// CHECK-NEXT: #loc36 = loc({{.*}}:29:28)
// CHECK-NEXT: #loc37 = loc({{.*}}:29:51)
// CHECK-NEXT: #loc42 = loc({{.*}}:33:26)
// CHECK-NEXT: #loc47 = loc({{.*}}:37:27)
// CHECK-NEXT: #loc48 = loc({{.*}}:37:49)
// CHECK-NEXT: #loc53 = loc({{.*}}:41:26)
// CHECK-NEXT: #loc58 = loc({{.*}}:45:29)
// CHECK-NEXT: #loc64 = loc({{.*}}:50:27)
// CHECK-NEXT: #loc65 = loc({{.*}}:50:46)
// CHECK-NEXT: #loc70 = loc({{.*}}:54:29)
// CHECK-NEXT: #loc75 = loc({{.*}}:58:30)
// CHECK-NEXT: #loc76 = loc({{.*}}:58:55)
// CHECK-NEXT: #loc81 = loc({{.*}}:62:28)
// CHECK-NEXT: #loc86 = loc({{.*}}:66:29)
// CHECK-NEXT: #loc87 = loc({{.*}}:66:53)
// CHECK-NEXT: #loc92 = loc({{.*}}:70:29)
// CHECK-NEXT: #loc97 = loc({{.*}}:74:30)
// CHECK-NEXT: #loc98 = loc({{.*}}:74:55)
// CHECK-NEXT: #loc103 = loc({{.*}}:78:33)
// CHECK-NEXT: #loc110 = loc({{.*}}:82:28)
// CHECK-NEXT: #loc111 = loc({{.*}}:83:28)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @C_361 {
// CHECK-NEXT:     sol.func @C_361() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @add_18(%arg0: ui256 loc({{.*}}:5:15), %arg1: ui256 loc({{.*}}:5:23)) -> ui256 attributes {id = 18 : i64, orig_fn_type = (ui256, ui256) -> ui256, selector = 1997931255 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc4)
// CHECK-NEXT:       sol.store %arg1, %1 : ui256, !sol.ptr<ui256, Stack> loc(#loc4)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc5)
// CHECK-NEXT:       %3 = sol.load %1 : !sol.ptr<ui256, Stack>, ui256 loc(#loc6)
// CHECK-NEXT:       %4 = sol.cadd %2, %3 : ui256 loc(#loc5)
// CHECK-NEXT:       sol.return %4 : ui256 loc(#loc7)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     sol.func @loadMemoryByte_30(%arg0: !sol.string<Memory> loc({{.*}}:9:26)) -> !sol.fixedbytes<1> attributes {id = 30 : i64, orig_fn_type = (!sol.string<Memory>) -> !sol.fixedbytes<1>, selector = -1811238948 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc9)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc9)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<!sol.string<Memory>, Stack>, !sol.string<Memory> loc(#loc10)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc11)
// CHECK-NEXT:       %2 = sol.gep %1, %c0_ui8 : !sol.string<Memory>, ui8, !sol.ptr<!sol.byte, Memory> loc(#loc10)
// CHECK-NEXT:       %3 = sol.load %2 : !sol.ptr<!sol.byte, Memory>, !sol.byte loc(#loc10)
// CHECK-NEXT:       %4 = sol.bytes_cast %3 : !sol.byte to !sol.fixedbytes<1> loc(#loc10)
// CHECK-NEXT:       sol.return %4 : !sol.fixedbytes<1> loc(#loc12)
// CHECK-NEXT:     } loc(#loc8)
// CHECK-NEXT:     sol.func @storeMemoryByte_44(%arg0: !sol.string<Memory> loc({{.*}}:13:27), %arg1: !sol.fixedbytes<1> loc({{.*}}:13:46)) attributes {id = 44 : i64, orig_fn_type = (!sol.string<Memory>, !sol.fixedbytes<1>) -> (), selector = 88457174 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc14)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc14)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.fixedbytes<1>, Stack> loc(#loc15)
// CHECK-NEXT:       sol.store %arg1, %1 : !sol.fixedbytes<1>, !sol.ptr<!sol.fixedbytes<1>, Stack> loc(#loc15)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.string<Memory>, Stack>, !sol.string<Memory> loc(#loc16)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc17)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui8 : !sol.string<Memory>, ui8, !sol.ptr<!sol.byte, Memory> loc(#loc16)
// CHECK-NEXT:       %4 = sol.load %1 : !sol.ptr<!sol.fixedbytes<1>, Stack>, !sol.fixedbytes<1> loc(#loc18)
// CHECK-NEXT:       %5 = sol.bytes_cast %4 : !sol.fixedbytes<1> to !sol.byte loc(#loc18)
// CHECK-NEXT:       sol.store %5, %3 : !sol.byte, !sol.ptr<!sol.byte, Memory> loc(#loc16)
// CHECK-NEXT:       sol.return loc(#loc13)
// CHECK-NEXT:     } loc(#loc13)
// CHECK-NEXT:     sol.func @loadMemoryBool_57(%arg0: !sol.array<? x i1, Memory> loc({{.*}}:17:26)) -> i1 attributes {id = 57 : i64, orig_fn_type = (!sol.array<? x i1, Memory>) -> i1, selector = -61508420 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x i1, Memory>, Stack> loc(#loc20)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x i1, Memory>, !sol.ptr<!sol.array<? x i1, Memory>, Stack> loc(#loc20)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<!sol.array<? x i1, Memory>, Stack>, !sol.array<? x i1, Memory> loc(#loc21)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc22)
// CHECK-NEXT:       %2 = sol.gep %1, %c0_ui8 : !sol.array<? x i1, Memory>, ui8, !sol.ptr<i1, Memory> loc(#loc21)
// CHECK-NEXT:       %3 = sol.load %2 : !sol.ptr<i1, Memory>, i1 loc(#loc21)
// CHECK-NEXT:       sol.return %3 : i1 loc(#loc23)
// CHECK-NEXT:     } loc(#loc19)
// CHECK-NEXT:     sol.func @storeMemoryBool_72(%arg0: !sol.array<? x i1, Memory> loc({{.*}}:21:27), %arg1: i1 loc({{.*}}:21:49)) attributes {id = 72 : i64, orig_fn_type = (!sol.array<? x i1, Memory>, i1) -> (), selector = -711288960 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x i1, Memory>, Stack> loc(#loc25)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x i1, Memory>, !sol.ptr<!sol.array<? x i1, Memory>, Stack> loc(#loc25)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<i1, Stack> loc(#loc26)
// CHECK-NEXT:       sol.store %arg1, %1 : i1, !sol.ptr<i1, Stack> loc(#loc26)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.array<? x i1, Memory>, Stack>, !sol.array<? x i1, Memory> loc(#loc27)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc28)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui8 : !sol.array<? x i1, Memory>, ui8, !sol.ptr<i1, Memory> loc(#loc27)
// CHECK-NEXT:       %4 = sol.load %1 : !sol.ptr<i1, Stack>, i1 loc(#loc29)
// CHECK-NEXT:       sol.store %4, %3 : i1, !sol.ptr<i1, Memory> loc(#loc27)
// CHECK-NEXT:       sol.return loc(#loc24)
// CHECK-NEXT:     } loc(#loc24)
// CHECK-NEXT:     sol.func @loadMemoryUint8_85(%arg0: !sol.array<? x ui8, Memory> loc({{.*}}:25:27)) -> ui8 attributes {id = 85 : i64, orig_fn_type = (!sol.array<? x ui8, Memory>) -> ui8, selector = 2026252864 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x ui8, Memory>, Stack> loc(#loc31)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x ui8, Memory>, !sol.ptr<!sol.array<? x ui8, Memory>, Stack> loc(#loc31)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<!sol.array<? x ui8, Memory>, Stack>, !sol.array<? x ui8, Memory> loc(#loc32)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc33)
// CHECK-NEXT:       %2 = sol.gep %1, %c0_ui8 : !sol.array<? x ui8, Memory>, ui8, !sol.ptr<ui8, Memory> loc(#loc32)
// CHECK-NEXT:       %3 = sol.load %2 : !sol.ptr<ui8, Memory>, ui8 loc(#loc32)
// CHECK-NEXT:       sol.return %3 : ui8 loc(#loc34)
// CHECK-NEXT:     } loc(#loc30)
// CHECK-NEXT:     sol.func @storeMemoryUint8_100(%arg0: !sol.array<? x ui8, Memory> loc({{.*}}:29:28), %arg1: ui8 loc({{.*}}:29:51)) attributes {id = 100 : i64, orig_fn_type = (!sol.array<? x ui8, Memory>, ui8) -> (), selector = -1648330615 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x ui8, Memory>, Stack> loc(#loc36)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x ui8, Memory>, !sol.ptr<!sol.array<? x ui8, Memory>, Stack> loc(#loc36)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<ui8, Stack> loc(#loc37)
// CHECK-NEXT:       sol.store %arg1, %1 : ui8, !sol.ptr<ui8, Stack> loc(#loc37)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.array<? x ui8, Memory>, Stack>, !sol.array<? x ui8, Memory> loc(#loc38)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc39)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui8 : !sol.array<? x ui8, Memory>, ui8, !sol.ptr<ui8, Memory> loc(#loc38)
// CHECK-NEXT:       %4 = sol.load %1 : !sol.ptr<ui8, Stack>, ui8 loc(#loc40)
// CHECK-NEXT:       sol.store %4, %3 : ui8, !sol.ptr<ui8, Memory> loc(#loc38)
// CHECK-NEXT:       sol.return loc(#loc35)
// CHECK-NEXT:     } loc(#loc35)
// CHECK-NEXT:     sol.func @loadMemoryInt8_113(%arg0: !sol.array<? x si8, Memory> loc({{.*}}:33:26)) -> si8 attributes {id = 113 : i64, orig_fn_type = (!sol.array<? x si8, Memory>) -> si8, selector = -273897421 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x si8, Memory>, Stack> loc(#loc42)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x si8, Memory>, !sol.ptr<!sol.array<? x si8, Memory>, Stack> loc(#loc42)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<!sol.array<? x si8, Memory>, Stack>, !sol.array<? x si8, Memory> loc(#loc43)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc44)
// CHECK-NEXT:       %2 = sol.gep %1, %c0_ui8 : !sol.array<? x si8, Memory>, ui8, !sol.ptr<si8, Memory> loc(#loc43)
// CHECK-NEXT:       %3 = sol.load %2 : !sol.ptr<si8, Memory>, si8 loc(#loc43)
// CHECK-NEXT:       sol.return %3 : si8 loc(#loc45)
// CHECK-NEXT:     } loc(#loc41)
// CHECK-NEXT:     sol.func @storeMemoryInt8_128(%arg0: !sol.array<? x si8, Memory> loc({{.*}}:37:27), %arg1: si8 loc({{.*}}:37:49)) attributes {id = 128 : i64, orig_fn_type = (!sol.array<? x si8, Memory>, si8) -> (), selector = 171022261 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x si8, Memory>, Stack> loc(#loc47)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x si8, Memory>, !sol.ptr<!sol.array<? x si8, Memory>, Stack> loc(#loc47)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<si8, Stack> loc(#loc48)
// CHECK-NEXT:       sol.store %arg1, %1 : si8, !sol.ptr<si8, Stack> loc(#loc48)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.array<? x si8, Memory>, Stack>, !sol.array<? x si8, Memory> loc(#loc49)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc50)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui8 : !sol.array<? x si8, Memory>, ui8, !sol.ptr<si8, Memory> loc(#loc49)
// CHECK-NEXT:       %4 = sol.load %1 : !sol.ptr<si8, Stack>, si8 loc(#loc51)
// CHECK-NEXT:       sol.store %4, %3 : si8, !sol.ptr<si8, Memory> loc(#loc49)
// CHECK-NEXT:       sol.return loc(#loc46)
// CHECK-NEXT:     } loc(#loc46)
// CHECK-NEXT:     sol.func @loadMemoryEnum_145(%arg0: !sol.array<? x !sol.enum<2>, Memory> loc({{.*}}:41:26)) -> ui8 attributes {id = 145 : i64, orig_fn_type = (!sol.array<? x !sol.enum<2>, Memory>) -> ui8, selector = 334674616 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.enum<2>, Memory>, Stack> loc(#loc53)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.enum<2>, Memory>, !sol.ptr<!sol.array<? x !sol.enum<2>, Memory>, Stack> loc(#loc53)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.enum<2>, Memory>, Stack>, !sol.array<? x !sol.enum<2>, Memory> loc(#loc54)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc55)
// CHECK-NEXT:       %2 = sol.gep %1, %c0_ui8 : !sol.array<? x !sol.enum<2>, Memory>, ui8, !sol.ptr<!sol.enum<2>, Memory> loc(#loc54)
// CHECK-NEXT:       %3 = sol.load %2 : !sol.ptr<!sol.enum<2>, Memory>, !sol.enum<2> loc(#loc54)
// CHECK-NEXT:       %4 = sol.cast %3 : !sol.enum<2> to ui8 loc(#loc54)
// CHECK-NEXT:       sol.return %4 : ui8 loc(#loc56)
// CHECK-NEXT:     } loc(#loc52)
// CHECK-NEXT:     sol.func @discardMemoryEnum_161(%arg0: !sol.array<? x !sol.enum<2>, Memory> loc({{.*}}:45:29)) -> ui8 attributes {id = 161 : i64, orig_fn_type = (!sol.array<? x !sol.enum<2>, Memory>) -> ui8, selector = -307916275 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.enum<2>, Memory>, Stack> loc(#loc58)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.enum<2>, Memory>, !sol.ptr<!sol.array<? x !sol.enum<2>, Memory>, Stack> loc(#loc58)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.enum<2>, Memory>, Stack>, !sol.array<? x !sol.enum<2>, Memory> loc(#loc59)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc60)
// CHECK-NEXT:       %2 = sol.gep %1, %c0_ui8 : !sol.array<? x !sol.enum<2>, Memory>, ui8, !sol.ptr<!sol.enum<2>, Memory> loc(#loc59)
// CHECK-NEXT:       %3 = sol.load %2 : !sol.ptr<!sol.enum<2>, Memory>, !sol.enum<2> loc(#loc59)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc61)
// CHECK-NEXT:       sol.return %c1_ui8 : ui8 loc(#loc62)
// CHECK-NEXT:     } loc(#loc57)
// CHECK-NEXT:     sol.func @storeMemoryEnum_178(%arg0: !sol.array<? x !sol.enum<2>, Memory> loc({{.*}}:50:27), %arg1: !sol.enum<2> loc({{.*}}:50:46)) attributes {id = 178 : i64, orig_fn_type = (!sol.array<? x !sol.enum<2>, Memory>, !sol.enum<2>) -> (), selector = -1034093661 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.enum<2>, Memory>, Stack> loc(#loc64)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.enum<2>, Memory>, !sol.ptr<!sol.array<? x !sol.enum<2>, Memory>, Stack> loc(#loc64)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.enum<2>, Stack> loc(#loc65)
// CHECK-NEXT:       sol.store %arg1, %1 : !sol.enum<2>, !sol.ptr<!sol.enum<2>, Stack> loc(#loc65)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.enum<2>, Memory>, Stack>, !sol.array<? x !sol.enum<2>, Memory> loc(#loc66)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc67)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui8 : !sol.array<? x !sol.enum<2>, Memory>, ui8, !sol.ptr<!sol.enum<2>, Memory> loc(#loc66)
// CHECK-NEXT:       %4 = sol.load %1 : !sol.ptr<!sol.enum<2>, Stack>, !sol.enum<2> loc(#loc68)
// CHECK-NEXT:       sol.store %4, %3 : !sol.enum<2>, !sol.ptr<!sol.enum<2>, Memory> loc(#loc66)
// CHECK-NEXT:       sol.return loc(#loc63)
// CHECK-NEXT:     } loc(#loc63)
// CHECK-NEXT:     sol.func @loadMemoryAddress_191(%arg0: !sol.array<? x !sol.address, Memory> loc({{.*}}:54:29)) -> !sol.address attributes {id = 191 : i64, orig_fn_type = (!sol.array<? x !sol.address, Memory>) -> !sol.address, selector = 167399756 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.address, Memory>, Stack> loc(#loc70)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.address, Memory>, !sol.ptr<!sol.array<? x !sol.address, Memory>, Stack> loc(#loc70)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.address, Memory>, Stack>, !sol.array<? x !sol.address, Memory> loc(#loc71)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc72)
// CHECK-NEXT:       %2 = sol.gep %1, %c0_ui8 : !sol.array<? x !sol.address, Memory>, ui8, !sol.ptr<!sol.address, Memory> loc(#loc71)
// CHECK-NEXT:       %3 = sol.load %2 : !sol.ptr<!sol.address, Memory>, !sol.address loc(#loc71)
// CHECK-NEXT:       sol.return %3 : !sol.address loc(#loc73)
// CHECK-NEXT:     } loc(#loc69)
// CHECK-NEXT:     sol.func @storeMemoryAddress_206(%arg0: !sol.array<? x !sol.address, Memory> loc({{.*}}:58:30), %arg1: !sol.address loc({{.*}}:58:55)) attributes {id = 206 : i64, orig_fn_type = (!sol.array<? x !sol.address, Memory>, !sol.address) -> (), selector = 430267481 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.address, Memory>, Stack> loc(#loc75)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.address, Memory>, !sol.ptr<!sol.array<? x !sol.address, Memory>, Stack> loc(#loc75)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.address, Stack> loc(#loc76)
// CHECK-NEXT:       sol.store %arg1, %1 : !sol.address, !sol.ptr<!sol.address, Stack> loc(#loc76)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.address, Memory>, Stack>, !sol.array<? x !sol.address, Memory> loc(#loc77)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc78)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui8 : !sol.array<? x !sol.address, Memory>, ui8, !sol.ptr<!sol.address, Memory> loc(#loc77)
// CHECK-NEXT:       %4 = sol.load %1 : !sol.ptr<!sol.address, Stack>, !sol.address loc(#loc79)
// CHECK-NEXT:       sol.store %4, %3 : !sol.address, !sol.ptr<!sol.address, Memory> loc(#loc77)
// CHECK-NEXT:       sol.return loc(#loc74)
// CHECK-NEXT:     } loc(#loc74)
// CHECK-NEXT:     sol.func @loadMemoryBytes4_219(%arg0: !sol.array<? x !sol.fixedbytes<4>, Memory> loc({{.*}}:62:28)) -> !sol.fixedbytes<4> attributes {id = 219 : i64, orig_fn_type = (!sol.array<? x !sol.fixedbytes<4>, Memory>) -> !sol.fixedbytes<4>, selector = -103038451 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.fixedbytes<4>, Memory>, Stack> loc(#loc81)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.fixedbytes<4>, Memory>, !sol.ptr<!sol.array<? x !sol.fixedbytes<4>, Memory>, Stack> loc(#loc81)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.fixedbytes<4>, Memory>, Stack>, !sol.array<? x !sol.fixedbytes<4>, Memory> loc(#loc82)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc83)
// CHECK-NEXT:       %2 = sol.gep %1, %c0_ui8 : !sol.array<? x !sol.fixedbytes<4>, Memory>, ui8, !sol.ptr<!sol.fixedbytes<4>, Memory> loc(#loc82)
// CHECK-NEXT:       %3 = sol.load %2 : !sol.ptr<!sol.fixedbytes<4>, Memory>, !sol.fixedbytes<4> loc(#loc82)
// CHECK-NEXT:       sol.return %3 : !sol.fixedbytes<4> loc(#loc84)
// CHECK-NEXT:     } loc(#loc80)
// CHECK-NEXT:     sol.func @storeMemoryBytes4_234(%arg0: !sol.array<? x !sol.fixedbytes<4>, Memory> loc({{.*}}:66:29), %arg1: !sol.fixedbytes<4> loc({{.*}}:66:53)) attributes {id = 234 : i64, orig_fn_type = (!sol.array<? x !sol.fixedbytes<4>, Memory>, !sol.fixedbytes<4>) -> (), selector = 1228467273 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.fixedbytes<4>, Memory>, Stack> loc(#loc86)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.fixedbytes<4>, Memory>, !sol.ptr<!sol.array<? x !sol.fixedbytes<4>, Memory>, Stack> loc(#loc86)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.fixedbytes<4>, Stack> loc(#loc87)
// CHECK-NEXT:       sol.store %arg1, %1 : !sol.fixedbytes<4>, !sol.ptr<!sol.fixedbytes<4>, Stack> loc(#loc87)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.fixedbytes<4>, Memory>, Stack>, !sol.array<? x !sol.fixedbytes<4>, Memory> loc(#loc88)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc89)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui8 : !sol.array<? x !sol.fixedbytes<4>, Memory>, ui8, !sol.ptr<!sol.fixedbytes<4>, Memory> loc(#loc88)
// CHECK-NEXT:       %4 = sol.load %1 : !sol.ptr<!sol.fixedbytes<4>, Stack>, !sol.fixedbytes<4> loc(#loc90)
// CHECK-NEXT:       sol.store %4, %3 : !sol.fixedbytes<4>, !sol.ptr<!sol.fixedbytes<4>, Memory> loc(#loc88)
// CHECK-NEXT:       sol.return loc(#loc85)
// CHECK-NEXT:     } loc(#loc85)
// CHECK-NEXT:     sol.func @loadMemoryBytes31_247(%arg0: !sol.array<? x !sol.fixedbytes<31>, Memory> loc({{.*}}:70:29)) -> !sol.fixedbytes<31> attributes {id = 247 : i64, orig_fn_type = (!sol.array<? x !sol.fixedbytes<31>, Memory>) -> !sol.fixedbytes<31>, selector = 1942951072 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.fixedbytes<31>, Memory>, Stack> loc(#loc92)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.fixedbytes<31>, Memory>, !sol.ptr<!sol.array<? x !sol.fixedbytes<31>, Memory>, Stack> loc(#loc92)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.fixedbytes<31>, Memory>, Stack>, !sol.array<? x !sol.fixedbytes<31>, Memory> loc(#loc93)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc94)
// CHECK-NEXT:       %2 = sol.gep %1, %c0_ui8 : !sol.array<? x !sol.fixedbytes<31>, Memory>, ui8, !sol.ptr<!sol.fixedbytes<31>, Memory> loc(#loc93)
// CHECK-NEXT:       %3 = sol.load %2 : !sol.ptr<!sol.fixedbytes<31>, Memory>, !sol.fixedbytes<31> loc(#loc93)
// CHECK-NEXT:       sol.return %3 : !sol.fixedbytes<31> loc(#loc95)
// CHECK-NEXT:     } loc(#loc91)
// CHECK-NEXT:     sol.func @storeMemoryBytes31_262(%arg0: !sol.array<? x !sol.fixedbytes<31>, Memory> loc({{.*}}:74:30), %arg1: !sol.fixedbytes<31> loc({{.*}}:74:55)) attributes {id = 262 : i64, orig_fn_type = (!sol.array<? x !sol.fixedbytes<31>, Memory>, !sol.fixedbytes<31>) -> (), selector = 824981650 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.fixedbytes<31>, Memory>, Stack> loc(#loc97)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.fixedbytes<31>, Memory>, !sol.ptr<!sol.array<? x !sol.fixedbytes<31>, Memory>, Stack> loc(#loc97)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.fixedbytes<31>, Stack> loc(#loc98)
// CHECK-NEXT:       sol.store %arg1, %1 : !sol.fixedbytes<31>, !sol.ptr<!sol.fixedbytes<31>, Stack> loc(#loc98)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.fixedbytes<31>, Memory>, Stack>, !sol.array<? x !sol.fixedbytes<31>, Memory> loc(#loc99)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc100)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui8 : !sol.array<? x !sol.fixedbytes<31>, Memory>, ui8, !sol.ptr<!sol.fixedbytes<31>, Memory> loc(#loc99)
// CHECK-NEXT:       %4 = sol.load %1 : !sol.ptr<!sol.fixedbytes<31>, Stack>, !sol.fixedbytes<31> loc(#loc101)
// CHECK-NEXT:       sol.store %4, %3 : !sol.fixedbytes<31>, !sol.ptr<!sol.fixedbytes<31>, Memory> loc(#loc99)
// CHECK-NEXT:       sol.return loc(#loc96)
// CHECK-NEXT:     } loc(#loc96)
// CHECK-NEXT:     sol.func @loadMemoryFnPtrHelper_286(%arg0: !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc({{.*}}:78:33)) -> ui256 attributes {id = 286 : i64, orig_fn_type = (!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>) -> ui256, selector = 2039841618 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, Stack> loc(#loc103)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, Stack> loc(#loc103)
// CHECK-NEXT:       %c20_ui8 = sol.constant 20 : ui8 loc(#loc104)
// CHECK-NEXT:       %1 = sol.cast %c20_ui8 : ui8 to ui256 loc(#loc104)
// CHECK-NEXT:       %c22_ui8 = sol.constant 22 : ui8 loc(#loc105)
// CHECK-NEXT:       %2 = sol.cast %c22_ui8 : ui8 to ui256 loc(#loc105)
// CHECK-NEXT:       %3 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, Stack>, !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc(#loc106)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc107)
// CHECK-NEXT:       %4 = sol.gep %3, %c0_ui8 : !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, ui8, !sol.ptr<!sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc(#loc106)
// CHECK-NEXT:       %5 = sol.load %4 : !sol.ptr<!sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, !sol.ext_func_ref<(ui256, ui256) -> ui256> loc(#loc106)
// CHECK-NEXT:       %6 = sol.gasleft : ui256 loc(#loc106)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc106)
// CHECK-NEXT:       %7:2 = sol.ext_icall %5(%1, %2) gas %6 value %c0_ui256 {static_call} : !sol.ext_func_ref<(ui256, ui256) -> ui256>, (ui256, ui256) -> (i1, ui256) loc(#loc106)
// CHECK-NEXT:       sol.return %7#1 : ui256 loc(#loc108)
// CHECK-NEXT:     } loc(#loc102)
// CHECK-NEXT:     sol.func @storeMemoryFnPtr_317(%arg0: !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc({{.*}}:82:28), %arg1: !sol.ext_func_ref<(ui256, ui256) -> ui256> loc({{.*}}:83:28)) attributes {id = 317 : i64, orig_fn_type = (!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, !sol.ext_func_ref<(ui256, ui256) -> ui256>) -> (), selector = 435044947 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, Stack> loc(#loc110)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, Stack> loc(#loc110)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.ext_func_ref<(ui256, ui256) -> ui256>, Stack> loc(#loc111)
// CHECK-NEXT:       sol.store %arg1, %1 : !sol.ext_func_ref<(ui256, ui256) -> ui256>, !sol.ptr<!sol.ext_func_ref<(ui256, ui256) -> ui256>, Stack> loc(#loc111)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, Stack>, !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc(#loc112)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc113)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui8 : !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, ui8, !sol.ptr<!sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc(#loc112)
// CHECK-NEXT:       %4 = sol.load %1 : !sol.ptr<!sol.ext_func_ref<(ui256, ui256) -> ui256>, Stack>, !sol.ext_func_ref<(ui256, ui256) -> ui256> loc(#loc114)
// CHECK-NEXT:       sol.store %4, %3 : !sol.ext_func_ref<(ui256, ui256) -> ui256>, !sol.ptr<!sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc(#loc112)
// CHECK-NEXT:       sol.return loc(#loc109)
// CHECK-NEXT:     } loc(#loc109)
// CHECK-NEXT:     sol.func @loadMemoryFnPtrSuccess_360() -> ui256 attributes {id = 360 : i64, orig_fn_type = () -> ui256, selector = -413069888 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc116)
// CHECK-NEXT:       %0 = sol.malloc %c1_ui8 zero_init : ui8 !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc(#loc117)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, Stack> loc(#loc118)
// CHECK-NEXT:       sol.store %0, %1 : !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, Stack> loc(#loc118)
// CHECK-NEXT:       %2 = sol.load %1 : !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, Stack>, !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc(#loc119)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc120)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui8 : !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, ui8, !sol.ptr<!sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc(#loc119)
// CHECK-NEXT:       %4 = sol.this : !sol.contract<"C_361"> loc(#loc121)
// CHECK-NEXT:       %5 = sol.address_cast %4 : !sol.contract<"C_361"> to !sol.address loc(#loc121)
// CHECK-NEXT:       %6 = sol.ext_func_constant %5 {selector = 1997931255 : i32} : !sol.address -> !sol.ext_func_ref<(ui256, ui256) -> ui256> loc(#loc121)
// CHECK-NEXT:       sol.store %6, %3 : !sol.ext_func_ref<(ui256, ui256) -> ui256>, !sol.ptr<!sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc(#loc119)
// CHECK-NEXT:       %7 = sol.this : !sol.contract<"C_361"> loc(#loc122)
// CHECK-NEXT:       %8 = sol.address_cast %7 : !sol.contract<"C_361"> to !sol.address loc(#loc122)
// CHECK-NEXT:       %9 = sol.load %1 : !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, Stack>, !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc(#loc123)
// CHECK-NEXT:       %c2039841618_ui256 = sol.constant 2039841618 : ui256 loc(#loc122)
// CHECK-NEXT:       %10 = sol.gasleft : ui256 loc(#loc122)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc122)
// CHECK-NEXT:       %status, %outs = sol.ext_call "loadMemoryFnPtrHelper_286"(%9) at %8 gas %10 value %c0_ui256 selector %c2039841618_ui256 {callee_type = (!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>) -> ui256, static_call} : !sol.address, (!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>) -> (i1, ui256) loc(#loc122)
// CHECK-NEXT:       sol.return %outs : ui256 loc(#loc124)
// CHECK-NEXT:     } loc(#loc115)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:5:2)
// CHECK-NEXT: #loc5 = loc({{.*}}:6:11)
// CHECK-NEXT: #loc6 = loc({{.*}}:6:15)
// CHECK-NEXT: #loc7 = loc({{.*}}:6:4)
// CHECK-NEXT: #loc8 = loc({{.*}}:9:2)
// CHECK-NEXT: #loc10 = loc({{.*}}:10:11)
// CHECK-NEXT: #loc11 = loc({{.*}}:10:16)
// CHECK-NEXT: #loc12 = loc({{.*}}:10:4)
// CHECK-NEXT: #loc13 = loc({{.*}}:13:2)
// CHECK-NEXT: #loc16 = loc({{.*}}:14:4)
// CHECK-NEXT: #loc17 = loc({{.*}}:14:9)
// CHECK-NEXT: #loc18 = loc({{.*}}:14:14)
// CHECK-NEXT: #loc19 = loc({{.*}}:17:2)
// CHECK-NEXT: #loc21 = loc({{.*}}:18:11)
// CHECK-NEXT: #loc22 = loc({{.*}}:18:18)
// CHECK-NEXT: #loc23 = loc({{.*}}:18:4)
// CHECK-NEXT: #loc24 = loc({{.*}}:21:2)
// CHECK-NEXT: #loc27 = loc({{.*}}:22:4)
// CHECK-NEXT: #loc28 = loc({{.*}}:22:11)
// CHECK-NEXT: #loc29 = loc({{.*}}:22:16)
// CHECK-NEXT: #loc30 = loc({{.*}}:25:2)
// CHECK-NEXT: #loc32 = loc({{.*}}:26:11)
// CHECK-NEXT: #loc33 = loc({{.*}}:26:18)
// CHECK-NEXT: #loc34 = loc({{.*}}:26:4)
// CHECK-NEXT: #loc35 = loc({{.*}}:29:2)
// CHECK-NEXT: #loc38 = loc({{.*}}:30:4)
// CHECK-NEXT: #loc39 = loc({{.*}}:30:11)
// CHECK-NEXT: #loc40 = loc({{.*}}:30:16)
// CHECK-NEXT: #loc41 = loc({{.*}}:33:2)
// CHECK-NEXT: #loc43 = loc({{.*}}:34:11)
// CHECK-NEXT: #loc44 = loc({{.*}}:34:18)
// CHECK-NEXT: #loc45 = loc({{.*}}:34:4)
// CHECK-NEXT: #loc46 = loc({{.*}}:37:2)
// CHECK-NEXT: #loc49 = loc({{.*}}:38:4)
// CHECK-NEXT: #loc50 = loc({{.*}}:38:11)
// CHECK-NEXT: #loc51 = loc({{.*}}:38:16)
// CHECK-NEXT: #loc52 = loc({{.*}}:41:2)
// CHECK-NEXT: #loc54 = loc({{.*}}:42:17)
// CHECK-NEXT: #loc55 = loc({{.*}}:42:24)
// CHECK-NEXT: #loc56 = loc({{.*}}:42:4)
// CHECK-NEXT: #loc57 = loc({{.*}}:45:2)
// CHECK-NEXT: #loc59 = loc({{.*}}:46:4)
// CHECK-NEXT: #loc60 = loc({{.*}}:46:11)
// CHECK-NEXT: #loc61 = loc({{.*}}:47:11)
// CHECK-NEXT: #loc62 = loc({{.*}}:47:4)
// CHECK-NEXT: #loc63 = loc({{.*}}:50:2)
// CHECK-NEXT: #loc66 = loc({{.*}}:51:4)
// CHECK-NEXT: #loc67 = loc({{.*}}:51:11)
// CHECK-NEXT: #loc68 = loc({{.*}}:51:16)
// CHECK-NEXT: #loc69 = loc({{.*}}:54:2)
// CHECK-NEXT: #loc71 = loc({{.*}}:55:11)
// CHECK-NEXT: #loc72 = loc({{.*}}:55:18)
// CHECK-NEXT: #loc73 = loc({{.*}}:55:4)
// CHECK-NEXT: #loc74 = loc({{.*}}:58:2)
// CHECK-NEXT: #loc77 = loc({{.*}}:59:4)
// CHECK-NEXT: #loc78 = loc({{.*}}:59:11)
// CHECK-NEXT: #loc79 = loc({{.*}}:59:16)
// CHECK-NEXT: #loc80 = loc({{.*}}:62:2)
// CHECK-NEXT: #loc82 = loc({{.*}}:63:11)
// CHECK-NEXT: #loc83 = loc({{.*}}:63:18)
// CHECK-NEXT: #loc84 = loc({{.*}}:63:4)
// CHECK-NEXT: #loc85 = loc({{.*}}:66:2)
// CHECK-NEXT: #loc88 = loc({{.*}}:67:4)
// CHECK-NEXT: #loc89 = loc({{.*}}:67:11)
// CHECK-NEXT: #loc90 = loc({{.*}}:67:16)
// CHECK-NEXT: #loc91 = loc({{.*}}:70:2)
// CHECK-NEXT: #loc93 = loc({{.*}}:71:11)
// CHECK-NEXT: #loc94 = loc({{.*}}:71:18)
// CHECK-NEXT: #loc95 = loc({{.*}}:71:4)
// CHECK-NEXT: #loc96 = loc({{.*}}:74:2)
// CHECK-NEXT: #loc99 = loc({{.*}}:75:4)
// CHECK-NEXT: #loc100 = loc({{.*}}:75:11)
// CHECK-NEXT: #loc101 = loc({{.*}}:75:16)
// CHECK-NEXT: #loc102 = loc({{.*}}:78:2)
// CHECK-NEXT: #loc104 = loc({{.*}}:79:21)
// CHECK-NEXT: #loc105 = loc({{.*}}:79:25)
// CHECK-NEXT: #loc106 = loc({{.*}}:79:11)
// CHECK-NEXT: #loc107 = loc({{.*}}:79:18)
// CHECK-NEXT: #loc108 = loc({{.*}}:79:4)
// CHECK-NEXT: #loc109 = loc({{.*}}:82:2)
// CHECK-NEXT: #loc112 = loc({{.*}}:84:4)
// CHECK-NEXT: #loc113 = loc({{.*}}:84:11)
// CHECK-NEXT: #loc114 = loc({{.*}}:84:16)
// CHECK-NEXT: #loc115 = loc({{.*}}:87:2)
// CHECK-NEXT: #loc116 = loc({{.*}}:89:62)
// CHECK-NEXT: #loc117 = loc({{.*}}:89:6)
// CHECK-NEXT: #loc118 = loc({{.*}}:88:4)
// CHECK-NEXT: #loc119 = loc({{.*}}:90:4)
// CHECK-NEXT: #loc120 = loc({{.*}}:90:11)
// CHECK-NEXT: #loc121 = loc({{.*}}:90:16)
// CHECK-NEXT: #loc122 = loc({{.*}}:91:11)
// CHECK-NEXT: #loc123 = loc({{.*}}:91:38)
// CHECK-NEXT: #loc124 = loc({{.*}}:91:4)
// CHECK-EMPTY:
