// RUN: solc --mlir-action=print-init --mmlir=--mlir-print-debuginfo %s | FileCheck %s

contract C {
  enum E { A, B, C }

  function add(uint a, uint b) external pure returns (uint) {
    return a + b;
  }

  function loadCalldataByte(bytes calldata data) external pure returns (bytes1) {
    return data[0];
  }

  function loadCalldataBool(bool[] calldata values) external pure returns (bool) {
    return values[0];
  }

  function discardCalldataBool(bool[] calldata values) external pure returns (uint8) {
    values[0];
    return 1;
  }

  function loadCalldataUint8(uint8[] calldata values) external pure returns (uint8) {
    return values[0];
  }

  function loadCalldataInt8(int8[] calldata values) external pure returns (int8) {
    return values[0];
  }

  function loadCalldataEnum(E[] calldata values) external pure returns (uint8) {
    return uint8(values[0]);
  }

  function loadCalldataAddress(address[] calldata values) external pure returns (address) {
    return values[0];
  }

  function loadCalldataBytes4(bytes4[] calldata values) external pure returns (bytes4) {
    return values[0];
  }

  function loadCalldataBytes31(bytes31[] calldata values) external pure returns (bytes31) {
    return values[0];
  }

  function loadCalldataFnPtrHelper(function(uint, uint) external pure returns (uint)[] calldata values) external view returns (uint) {
    return values[0](20, 22);
  }

  function loadCalldataFnPtrSuccess() external returns (uint) {
    function(uint, uint) external pure returns (uint)[] memory values =
      new function(uint, uint) external pure returns (uint)[](1);
    values[0] = this.add;
    return this.loadCalldataFnPtrHelper(values);
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #Pure = #sol<StateMutability Pure>
// CHECK-NEXT: #View = #sol<StateMutability View>
// CHECK-NEXT: #loc3 = loc({{.*}}:5:15)
// CHECK-NEXT: #loc4 = loc({{.*}}:5:23)
// CHECK-NEXT: #loc10 = loc({{.*}}:9:28)
// CHECK-NEXT: #loc16 = loc({{.*}}:13:28)
// CHECK-NEXT: #loc22 = loc({{.*}}:17:31)
// CHECK-NEXT: #loc29 = loc({{.*}}:22:29)
// CHECK-NEXT: #loc35 = loc({{.*}}:26:28)
// CHECK-NEXT: #loc41 = loc({{.*}}:30:28)
// CHECK-NEXT: #loc47 = loc({{.*}}:34:31)
// CHECK-NEXT: #loc53 = loc({{.*}}:38:30)
// CHECK-NEXT: #loc59 = loc({{.*}}:42:31)
// CHECK-NEXT: #loc65 = loc({{.*}}:46:35)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @C_208 {
// CHECK-NEXT:     sol.func @C_208() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @add_18(%arg0: ui256 loc({{.*}}:5:15), %arg1: ui256 loc({{.*}}:5:23)) -> ui256 attributes {id = 18 : i64, orig_fn_type = (ui256, ui256) -> ui256, selector = 1997931255 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc4)
// CHECK-NEXT:       sol.store %arg1, %1 : ui256, !sol.ptr<ui256, Stack> loc(#loc4)
// CHECK-NEXT:       %2 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc5)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc5)
// CHECK-NEXT:       sol.store %c0_ui256, %2 : ui256, !sol.ptr<ui256, Stack> loc(#loc5)
// CHECK-NEXT:       %3 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc6)
// CHECK-NEXT:       %4 = sol.load %1 : !sol.ptr<ui256, Stack>, ui256 loc(#loc7)
// CHECK-NEXT:       %5 = sol.cadd %3, %4 : ui256 loc(#loc6)
// CHECK-NEXT:       sol.return %5 : ui256 loc(#loc8)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     sol.func @loadCalldataByte_30(%arg0: !sol.string<CallData> loc({{.*}}:9:28)) -> !sol.fixedbytes<1> attributes {id = 30 : i64, orig_fn_type = (!sol.string<CallData>) -> !sol.fixedbytes<1>, selector = 449335192 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<CallData>, Stack> loc(#loc10)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.string<CallData>, !sol.ptr<!sol.string<CallData>, Stack> loc(#loc10)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.fixedbytes<1>, Stack> loc(#loc11)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc11)
// CHECK-NEXT:       %2 = sol.bytes_cast %c0_ui8 : ui8 to !sol.fixedbytes<1> loc(#loc11)
// CHECK-NEXT:       sol.store %2, %1 : !sol.fixedbytes<1>, !sol.ptr<!sol.fixedbytes<1>, Stack> loc(#loc11)
// CHECK-NEXT:       %3 = sol.load %0 : !sol.ptr<!sol.string<CallData>, Stack>, !sol.string<CallData> loc(#loc12)
// CHECK-NEXT:       %c0_ui8_0 = sol.constant 0 : ui8 loc(#loc13)
// CHECK-NEXT:       %4 = sol.gep %3, %c0_ui8_0 : !sol.string<CallData>, ui8, !sol.ptr<!sol.byte, CallData> loc(#loc12)
// CHECK-NEXT:       %5 = sol.load %4 : !sol.ptr<!sol.byte, CallData>, !sol.byte loc(#loc12)
// CHECK-NEXT:       %6 = sol.bytes_cast %5 : !sol.byte to !sol.fixedbytes<1> loc(#loc12)
// CHECK-NEXT:       sol.return %6 : !sol.fixedbytes<1> loc(#loc14)
// CHECK-NEXT:     } loc(#loc9)
// CHECK-NEXT:     sol.func @loadCalldataBool_43(%arg0: !sol.array<? x i1, CallData> loc({{.*}}:13:28)) -> i1 attributes {id = 43 : i64, orig_fn_type = (!sol.array<? x i1, CallData>) -> i1, selector = 747334019 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x i1, CallData>, Stack> loc(#loc16)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x i1, CallData>, !sol.ptr<!sol.array<? x i1, CallData>, Stack> loc(#loc16)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<i1, Stack> loc(#loc17)
// CHECK-NEXT:       %false = sol.constant false loc(#loc17)
// CHECK-NEXT:       sol.store %false, %1 : i1, !sol.ptr<i1, Stack> loc(#loc17)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.array<? x i1, CallData>, Stack>, !sol.array<? x i1, CallData> loc(#loc18)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc19)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui8 : !sol.array<? x i1, CallData>, ui8, !sol.ptr<i1, CallData> loc(#loc18)
// CHECK-NEXT:       %4 = sol.load %3 : !sol.ptr<i1, CallData>, i1 loc(#loc18)
// CHECK-NEXT:       sol.return %4 : i1 loc(#loc20)
// CHECK-NEXT:     } loc(#loc15)
// CHECK-NEXT:     sol.func @discardCalldataBool_58(%arg0: !sol.array<? x i1, CallData> loc({{.*}}:17:31)) -> ui8 attributes {id = 58 : i64, orig_fn_type = (!sol.array<? x i1, CallData>) -> ui8, selector = 1564242350 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x i1, CallData>, Stack> loc(#loc22)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x i1, CallData>, !sol.ptr<!sol.array<? x i1, CallData>, Stack> loc(#loc22)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<ui8, Stack> loc(#loc23)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc23)
// CHECK-NEXT:       sol.store %c0_ui8, %1 : ui8, !sol.ptr<ui8, Stack> loc(#loc23)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.array<? x i1, CallData>, Stack>, !sol.array<? x i1, CallData> loc(#loc24)
// CHECK-NEXT:       %c0_ui8_0 = sol.constant 0 : ui8 loc(#loc25)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui8_0 : !sol.array<? x i1, CallData>, ui8, !sol.ptr<i1, CallData> loc(#loc24)
// CHECK-NEXT:       %4 = sol.load %3 : !sol.ptr<i1, CallData>, i1 loc(#loc24)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc26)
// CHECK-NEXT:       sol.return %c1_ui8 : ui8 loc(#loc27)
// CHECK-NEXT:     } loc(#loc21)
// CHECK-NEXT:     sol.func @loadCalldataUint8_71(%arg0: !sol.array<? x ui8, CallData> loc({{.*}}:22:29)) -> ui8 attributes {id = 71 : i64, orig_fn_type = (!sol.array<? x ui8, CallData>) -> ui8, selector = -684702892 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x ui8, CallData>, Stack> loc(#loc29)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x ui8, CallData>, !sol.ptr<!sol.array<? x ui8, CallData>, Stack> loc(#loc29)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<ui8, Stack> loc(#loc30)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc30)
// CHECK-NEXT:       sol.store %c0_ui8, %1 : ui8, !sol.ptr<ui8, Stack> loc(#loc30)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.array<? x ui8, CallData>, Stack>, !sol.array<? x ui8, CallData> loc(#loc31)
// CHECK-NEXT:       %c0_ui8_0 = sol.constant 0 : ui8 loc(#loc32)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui8_0 : !sol.array<? x ui8, CallData>, ui8, !sol.ptr<ui8, CallData> loc(#loc31)
// CHECK-NEXT:       %4 = sol.load %3 : !sol.ptr<ui8, CallData>, ui8 loc(#loc31)
// CHECK-NEXT:       sol.return %4 : ui8 loc(#loc33)
// CHECK-NEXT:     } loc(#loc28)
// CHECK-NEXT:     sol.func @loadCalldataInt8_84(%arg0: !sol.array<? x si8, CallData> loc({{.*}}:26:28)) -> si8 attributes {id = 84 : i64, orig_fn_type = (!sol.array<? x si8, CallData>) -> si8, selector = -165047358 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x si8, CallData>, Stack> loc(#loc35)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x si8, CallData>, !sol.ptr<!sol.array<? x si8, CallData>, Stack> loc(#loc35)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<si8, Stack> loc(#loc36)
// CHECK-NEXT:       %c0_si8 = sol.constant 0 : si8 loc(#loc36)
// CHECK-NEXT:       sol.store %c0_si8, %1 : si8, !sol.ptr<si8, Stack> loc(#loc36)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.array<? x si8, CallData>, Stack>, !sol.array<? x si8, CallData> loc(#loc37)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc38)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui8 : !sol.array<? x si8, CallData>, ui8, !sol.ptr<si8, CallData> loc(#loc37)
// CHECK-NEXT:       %4 = sol.load %3 : !sol.ptr<si8, CallData>, si8 loc(#loc37)
// CHECK-NEXT:       sol.return %4 : si8 loc(#loc39)
// CHECK-NEXT:     } loc(#loc34)
// CHECK-NEXT:     sol.func @loadCalldataEnum_101(%arg0: !sol.array<? x !sol.enum<2>, CallData> loc({{.*}}:30:28)) -> ui8 attributes {id = 101 : i64, orig_fn_type = (!sol.array<? x !sol.enum<2>, CallData>) -> ui8, selector = -1318146734 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.enum<2>, CallData>, Stack> loc(#loc41)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.enum<2>, CallData>, !sol.ptr<!sol.array<? x !sol.enum<2>, CallData>, Stack> loc(#loc41)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<ui8, Stack> loc(#loc42)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc42)
// CHECK-NEXT:       sol.store %c0_ui8, %1 : ui8, !sol.ptr<ui8, Stack> loc(#loc42)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.enum<2>, CallData>, Stack>, !sol.array<? x !sol.enum<2>, CallData> loc(#loc43)
// CHECK-NEXT:       %c0_ui8_0 = sol.constant 0 : ui8 loc(#loc44)
// CHECK-NEXT:       %3 = sol.gep %2, %c0_ui8_0 : !sol.array<? x !sol.enum<2>, CallData>, ui8, !sol.ptr<!sol.enum<2>, CallData> loc(#loc43)
// CHECK-NEXT:       %4 = sol.load %3 : !sol.ptr<!sol.enum<2>, CallData>, !sol.enum<2> loc(#loc43)
// CHECK-NEXT:       %5 = sol.enum_cast %4 : !sol.enum<2> to ui8 loc(#loc43)
// CHECK-NEXT:       sol.return %5 : ui8 loc(#loc45)
// CHECK-NEXT:     } loc(#loc40)
// CHECK-NEXT:     sol.func @loadCalldataAddress_114(%arg0: !sol.array<? x !sol.address, CallData> loc({{.*}}:34:31)) -> !sol.address attributes {id = 114 : i64, orig_fn_type = (!sol.array<? x !sol.address, CallData>) -> !sol.address, selector = -2116271283 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.address, CallData>, Stack> loc(#loc47)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.address, CallData>, !sol.ptr<!sol.array<? x !sol.address, CallData>, Stack> loc(#loc47)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.address, Stack> loc(#loc48)
// CHECK-NEXT:       %c0_ui160 = sol.constant 0 : ui160 loc(#loc48)
// CHECK-NEXT:       %2 = sol.address_cast %c0_ui160 : ui160 to !sol.address loc(#loc48)
// CHECK-NEXT:       sol.store %2, %1 : !sol.address, !sol.ptr<!sol.address, Stack> loc(#loc48)
// CHECK-NEXT:       %3 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.address, CallData>, Stack>, !sol.array<? x !sol.address, CallData> loc(#loc49)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc50)
// CHECK-NEXT:       %4 = sol.gep %3, %c0_ui8 : !sol.array<? x !sol.address, CallData>, ui8, !sol.ptr<!sol.address, CallData> loc(#loc49)
// CHECK-NEXT:       %5 = sol.load %4 : !sol.ptr<!sol.address, CallData>, !sol.address loc(#loc49)
// CHECK-NEXT:       sol.return %5 : !sol.address loc(#loc51)
// CHECK-NEXT:     } loc(#loc46)
// CHECK-NEXT:     sol.func @loadCalldataBytes4_127(%arg0: !sol.array<? x !sol.fixedbytes<4>, CallData> loc({{.*}}:38:30)) -> !sol.fixedbytes<4> attributes {id = 127 : i64, orig_fn_type = (!sol.array<? x !sol.fixedbytes<4>, CallData>) -> !sol.fixedbytes<4>, selector = -2073765807 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.fixedbytes<4>, CallData>, Stack> loc(#loc53)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.fixedbytes<4>, CallData>, !sol.ptr<!sol.array<? x !sol.fixedbytes<4>, CallData>, Stack> loc(#loc53)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.fixedbytes<4>, Stack> loc(#loc54)
// CHECK-NEXT:       %c0_ui32 = sol.constant 0 : ui32 loc(#loc54)
// CHECK-NEXT:       %2 = sol.bytes_cast %c0_ui32 : ui32 to !sol.fixedbytes<4> loc(#loc54)
// CHECK-NEXT:       sol.store %2, %1 : !sol.fixedbytes<4>, !sol.ptr<!sol.fixedbytes<4>, Stack> loc(#loc54)
// CHECK-NEXT:       %3 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.fixedbytes<4>, CallData>, Stack>, !sol.array<? x !sol.fixedbytes<4>, CallData> loc(#loc55)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc56)
// CHECK-NEXT:       %4 = sol.gep %3, %c0_ui8 : !sol.array<? x !sol.fixedbytes<4>, CallData>, ui8, !sol.ptr<!sol.fixedbytes<4>, CallData> loc(#loc55)
// CHECK-NEXT:       %5 = sol.load %4 : !sol.ptr<!sol.fixedbytes<4>, CallData>, !sol.fixedbytes<4> loc(#loc55)
// CHECK-NEXT:       sol.return %5 : !sol.fixedbytes<4> loc(#loc57)
// CHECK-NEXT:     } loc(#loc52)
// CHECK-NEXT:     sol.func @loadCalldataBytes31_140(%arg0: !sol.array<? x !sol.fixedbytes<31>, CallData> loc({{.*}}:42:31)) -> !sol.fixedbytes<31> attributes {id = 140 : i64, orig_fn_type = (!sol.array<? x !sol.fixedbytes<31>, CallData>) -> !sol.fixedbytes<31>, selector = 1395066653 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.fixedbytes<31>, CallData>, Stack> loc(#loc59)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.fixedbytes<31>, CallData>, !sol.ptr<!sol.array<? x !sol.fixedbytes<31>, CallData>, Stack> loc(#loc59)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.fixedbytes<31>, Stack> loc(#loc60)
// CHECK-NEXT:       %c0_ui248 = sol.constant 0 : ui248 loc(#loc60)
// CHECK-NEXT:       %2 = sol.bytes_cast %c0_ui248 : ui248 to !sol.fixedbytes<31> loc(#loc60)
// CHECK-NEXT:       sol.store %2, %1 : !sol.fixedbytes<31>, !sol.ptr<!sol.fixedbytes<31>, Stack> loc(#loc60)
// CHECK-NEXT:       %3 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.fixedbytes<31>, CallData>, Stack>, !sol.array<? x !sol.fixedbytes<31>, CallData> loc(#loc61)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc62)
// CHECK-NEXT:       %4 = sol.gep %3, %c0_ui8 : !sol.array<? x !sol.fixedbytes<31>, CallData>, ui8, !sol.ptr<!sol.fixedbytes<31>, CallData> loc(#loc61)
// CHECK-NEXT:       %5 = sol.load %4 : !sol.ptr<!sol.fixedbytes<31>, CallData>, !sol.fixedbytes<31> loc(#loc61)
// CHECK-NEXT:       sol.return %5 : !sol.fixedbytes<31> loc(#loc63)
// CHECK-NEXT:     } loc(#loc58)
// CHECK-NEXT:     sol.func @loadCalldataFnPtrHelper_164(%arg0: !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, CallData> loc({{.*}}:46:35)) -> ui256 attributes {id = 164 : i64, orig_fn_type = (!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, CallData>) -> ui256, selector = -685062729 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, CallData>, Stack> loc(#loc65)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, CallData>, !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, CallData>, Stack> loc(#loc65)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc66)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc66)
// CHECK-NEXT:       sol.store %c0_ui256, %1 : ui256, !sol.ptr<ui256, Stack> loc(#loc66)
// CHECK-NEXT:       %c20_ui8 = sol.constant 20 : ui8 loc(#loc67)
// CHECK-NEXT:       %2 = sol.cast %c20_ui8 : ui8 to ui256 loc(#loc67)
// CHECK-NEXT:       %c22_ui8 = sol.constant 22 : ui8 loc(#loc68)
// CHECK-NEXT:       %3 = sol.cast %c22_ui8 : ui8 to ui256 loc(#loc68)
// CHECK-NEXT:       %4 = sol.load %0 : !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, CallData>, Stack>, !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, CallData> loc(#loc69)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc70)
// CHECK-NEXT:       %5 = sol.gep %4, %c0_ui8 : !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, CallData>, ui8, !sol.ptr<!sol.ext_func_ref<(ui256, ui256) -> ui256>, CallData> loc(#loc69)
// CHECK-NEXT:       %6 = sol.load %5 : !sol.ptr<!sol.ext_func_ref<(ui256, ui256) -> ui256>, CallData>, !sol.ext_func_ref<(ui256, ui256) -> ui256> loc(#loc69)
// CHECK-NEXT:       %7 = sol.gasleft : ui256 loc(#loc69)
// CHECK-NEXT:       %c0_ui256_0 = sol.constant 0 : ui256 loc(#loc69)
// CHECK-NEXT:       %8:2 = sol.ext_icall %6(%2, %3) gas %7 value %c0_ui256_0 {static_call} : !sol.ext_func_ref<(ui256, ui256) -> ui256>, (ui256, ui256) -> (i1, ui256) loc(#loc69)
// CHECK-NEXT:       sol.return %8#1 : ui256 loc(#loc71)
// CHECK-NEXT:     } loc(#loc64)
// CHECK-NEXT:     sol.func @loadCalldataFnPtrSuccess_207() -> ui256 attributes {id = 207 : i64, orig_fn_type = () -> ui256, selector = -845520023 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc73)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc73)
// CHECK-NEXT:       sol.store %c0_ui256, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc73)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc74)
// CHECK-NEXT:       %1 = sol.malloc %c1_ui8 zero_init : ui8 !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc(#loc75)
// CHECK-NEXT:       %2 = sol.alloca : !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, Stack> loc(#loc76)
// CHECK-NEXT:       sol.store %1, %2 : !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, Stack> loc(#loc76)
// CHECK-NEXT:       %3 = sol.this : !sol.contract<"C_208"> loc(#loc77)
// CHECK-NEXT:       %4 = sol.address_cast %3 : !sol.contract<"C_208"> to !sol.address loc(#loc77)
// CHECK-NEXT:       %5 = sol.ext_func_constant %4 {selector = 1997931255 : i32} : !sol.address -> !sol.ext_func_ref<(ui256, ui256) -> ui256> loc(#loc77)
// CHECK-NEXT:       %6 = sol.load %2 : !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, Stack>, !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc(#loc78)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc79)
// CHECK-NEXT:       %7 = sol.gep %6, %c0_ui8 : !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, ui8, !sol.ptr<!sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc(#loc78)
// CHECK-NEXT:       sol.store %5, %7 : !sol.ext_func_ref<(ui256, ui256) -> ui256>, !sol.ptr<!sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc(#loc78)
// CHECK-NEXT:       %8 = sol.this : !sol.contract<"C_208"> loc(#loc80)
// CHECK-NEXT:       %9 = sol.address_cast %8 : !sol.contract<"C_208"> to !sol.address loc(#loc80)
// CHECK-NEXT:       %10 = sol.load %2 : !sol.ptr<!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>, Stack>, !sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory> loc(#loc81)
// CHECK-NEXT:       %c3609904567_ui256 = sol.constant 3609904567 : ui256 loc(#loc80)
// CHECK-NEXT:       %11 = sol.gasleft : ui256 loc(#loc80)
// CHECK-NEXT:       %c0_ui256_0 = sol.constant 0 : ui256 loc(#loc80)
// CHECK-NEXT:       %status, %outs = sol.ext_call "loadCalldataFnPtrHelper_164"(%10) at %9 gas %11 value %c0_ui256_0 selector %c3609904567_ui256 {callee_type = (!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>) -> ui256, static_call} : !sol.address, (!sol.array<? x !sol.ext_func_ref<(ui256, ui256) -> ui256>, Memory>) -> (i1, ui256) loc(#loc80)
// CHECK-NEXT:       sol.return %outs : ui256 loc(#loc82)
// CHECK-NEXT:     } loc(#loc72)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:5:2)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:54)
// CHECK-NEXT: #loc6 = loc({{.*}}:6:11)
// CHECK-NEXT: #loc7 = loc({{.*}}:6:15)
// CHECK-NEXT: #loc8 = loc({{.*}}:6:4)
// CHECK-NEXT: #loc9 = loc({{.*}}:9:2)
// CHECK-NEXT: #loc11 = loc({{.*}}:9:72)
// CHECK-NEXT: #loc12 = loc({{.*}}:10:11)
// CHECK-NEXT: #loc13 = loc({{.*}}:10:16)
// CHECK-NEXT: #loc14 = loc({{.*}}:10:4)
// CHECK-NEXT: #loc15 = loc({{.*}}:13:2)
// CHECK-NEXT: #loc17 = loc({{.*}}:13:75)
// CHECK-NEXT: #loc18 = loc({{.*}}:14:11)
// CHECK-NEXT: #loc19 = loc({{.*}}:14:18)
// CHECK-NEXT: #loc20 = loc({{.*}}:14:4)
// CHECK-NEXT: #loc21 = loc({{.*}}:17:2)
// CHECK-NEXT: #loc23 = loc({{.*}}:17:78)
// CHECK-NEXT: #loc24 = loc({{.*}}:18:4)
// CHECK-NEXT: #loc25 = loc({{.*}}:18:11)
// CHECK-NEXT: #loc26 = loc({{.*}}:19:11)
// CHECK-NEXT: #loc27 = loc({{.*}}:19:4)
// CHECK-NEXT: #loc28 = loc({{.*}}:22:2)
// CHECK-NEXT: #loc30 = loc({{.*}}:22:77)
// CHECK-NEXT: #loc31 = loc({{.*}}:23:11)
// CHECK-NEXT: #loc32 = loc({{.*}}:23:18)
// CHECK-NEXT: #loc33 = loc({{.*}}:23:4)
// CHECK-NEXT: #loc34 = loc({{.*}}:26:2)
// CHECK-NEXT: #loc36 = loc({{.*}}:26:75)
// CHECK-NEXT: #loc37 = loc({{.*}}:27:11)
// CHECK-NEXT: #loc38 = loc({{.*}}:27:18)
// CHECK-NEXT: #loc39 = loc({{.*}}:27:4)
// CHECK-NEXT: #loc40 = loc({{.*}}:30:2)
// CHECK-NEXT: #loc42 = loc({{.*}}:30:72)
// CHECK-NEXT: #loc43 = loc({{.*}}:31:17)
// CHECK-NEXT: #loc44 = loc({{.*}}:31:24)
// CHECK-NEXT: #loc45 = loc({{.*}}:31:4)
// CHECK-NEXT: #loc46 = loc({{.*}}:34:2)
// CHECK-NEXT: #loc48 = loc({{.*}}:34:81)
// CHECK-NEXT: #loc49 = loc({{.*}}:35:11)
// CHECK-NEXT: #loc50 = loc({{.*}}:35:18)
// CHECK-NEXT: #loc51 = loc({{.*}}:35:4)
// CHECK-NEXT: #loc52 = loc({{.*}}:38:2)
// CHECK-NEXT: #loc54 = loc({{.*}}:38:79)
// CHECK-NEXT: #loc55 = loc({{.*}}:39:11)
// CHECK-NEXT: #loc56 = loc({{.*}}:39:18)
// CHECK-NEXT: #loc57 = loc({{.*}}:39:4)
// CHECK-NEXT: #loc58 = loc({{.*}}:42:2)
// CHECK-NEXT: #loc60 = loc({{.*}}:42:81)
// CHECK-NEXT: #loc61 = loc({{.*}}:43:11)
// CHECK-NEXT: #loc62 = loc({{.*}}:43:18)
// CHECK-NEXT: #loc63 = loc({{.*}}:43:4)
// CHECK-NEXT: #loc64 = loc({{.*}}:46:2)
// CHECK-NEXT: #loc66 = loc({{.*}}:46:127)
// CHECK-NEXT: #loc67 = loc({{.*}}:47:21)
// CHECK-NEXT: #loc68 = loc({{.*}}:47:25)
// CHECK-NEXT: #loc69 = loc({{.*}}:47:11)
// CHECK-NEXT: #loc70 = loc({{.*}}:47:18)
// CHECK-NEXT: #loc71 = loc({{.*}}:47:4)
// CHECK-NEXT: #loc72 = loc({{.*}}:50:2)
// CHECK-NEXT: #loc73 = loc({{.*}}:50:56)
// CHECK-NEXT: #loc74 = loc({{.*}}:52:62)
// CHECK-NEXT: #loc75 = loc({{.*}}:52:6)
// CHECK-NEXT: #loc76 = loc({{.*}}:51:4)
// CHECK-NEXT: #loc77 = loc({{.*}}:53:16)
// CHECK-NEXT: #loc78 = loc({{.*}}:53:4)
// CHECK-NEXT: #loc79 = loc({{.*}}:53:11)
// CHECK-NEXT: #loc80 = loc({{.*}}:54:11)
// CHECK-NEXT: #loc81 = loc({{.*}}:54:40)
// CHECK-NEXT: #loc82 = loc({{.*}}:54:4)
// CHECK-EMPTY:
