// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

function f(bool a, bool b, bool c) returns (bool) {
  bool m = a && (b && c);
  bool n = a || (b || c);
  return m && n;
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #loc2 = loc({{.*}}:2:11)
// CHECK-NEXT: #loc3 = loc({{.*}}:2:19)
// CHECK-NEXT: #loc4 = loc({{.*}}:2:27)
// CHECK-NEXT: module attributes {sol.evm_version = #Osaka} {
// CHECK-NEXT:   sol.func @f_34(%arg0: i1 loc({{.*}}:2:11), %arg1: i1 loc({{.*}}:2:19), %arg2: i1 loc({{.*}}:2:27)) -> i1 attributes {id = 34 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:     %0 = sol.alloca : !sol.ptr<i1, Stack> loc(#loc2)
// CHECK-NEXT:     sol.store %arg0, %0 : i1, !sol.ptr<i1, Stack> loc(#loc2)
// CHECK-NEXT:     %1 = sol.alloca : !sol.ptr<i1, Stack> loc(#loc3)
// CHECK-NEXT:     sol.store %arg1, %1 : i1, !sol.ptr<i1, Stack> loc(#loc3)
// CHECK-NEXT:     %2 = sol.alloca : !sol.ptr<i1, Stack> loc(#loc4)
// CHECK-NEXT:     sol.store %arg2, %2 : i1, !sol.ptr<i1, Stack> loc(#loc4)
// CHECK-NEXT:     %3 = sol.load %0 : !sol.ptr<i1, Stack>, i1 loc(#loc5)
// CHECK-NEXT:     %4 = sol.alloca : !sol.ptr<i1, Stack> loc(#loc5)
// CHECK-NEXT:     %false = arith.constant false loc(#loc5)
// CHECK-NEXT:     sol.store %false, %4 : i1, !sol.ptr<i1, Stack> loc(#loc5)
// CHECK-NEXT:     sol.if %3 {
// CHECK-NEXT:       %14 = sol.load %1 : !sol.ptr<i1, Stack>, i1 loc(#loc6)
// CHECK-NEXT:       %15 = sol.alloca : !sol.ptr<i1, Stack> loc(#loc6)
// CHECK-NEXT:       %false_1 = arith.constant false loc(#loc6)
// CHECK-NEXT:       sol.store %false_1, %15 : i1, !sol.ptr<i1, Stack> loc(#loc6)
// CHECK-NEXT:       sol.if %14 {
// CHECK-NEXT:         %17 = sol.load %2 : !sol.ptr<i1, Stack>, i1 loc(#loc7)
// CHECK-NEXT:         sol.store %17, %15 : i1, !sol.ptr<i1, Stack> loc(#loc6)
// CHECK-NEXT:         sol.yield loc(#loc6)
// CHECK-NEXT:       } else {
// CHECK-NEXT:       } loc(#loc6)
// CHECK-NEXT:       %16 = sol.load %15 : !sol.ptr<i1, Stack>, i1 loc(#loc6)
// CHECK-NEXT:       sol.store %16, %4 : i1, !sol.ptr<i1, Stack> loc(#loc5)
// CHECK-NEXT:       sol.yield loc(#loc5)
// CHECK-NEXT:     } else {
// CHECK-NEXT:     } loc(#loc5)
// CHECK-NEXT:     %5 = sol.load %4 : !sol.ptr<i1, Stack>, i1 loc(#loc5)
// CHECK-NEXT:     %6 = sol.alloca : !sol.ptr<i1, Stack> loc(#loc8)
// CHECK-NEXT:     sol.store %5, %6 : i1, !sol.ptr<i1, Stack> loc(#loc8)
// CHECK-NEXT:     %7 = sol.load %0 : !sol.ptr<i1, Stack>, i1 loc(#loc9)
// CHECK-NEXT:     %8 = sol.alloca : !sol.ptr<i1, Stack> loc(#loc9)
// CHECK-NEXT:     sol.store %7, %8 : i1, !sol.ptr<i1, Stack> loc(#loc9)
// CHECK-NEXT:     sol.if %7 {
// CHECK-NEXT:       sol.yield loc(#loc9)
// CHECK-NEXT:     } else {
// CHECK-NEXT:       %14 = sol.load %1 : !sol.ptr<i1, Stack>, i1 loc(#loc10)
// CHECK-NEXT:       %15 = sol.alloca : !sol.ptr<i1, Stack> loc(#loc10)
// CHECK-NEXT:       sol.store %14, %15 : i1, !sol.ptr<i1, Stack> loc(#loc10)
// CHECK-NEXT:       sol.if %14 {
// CHECK-NEXT:         sol.yield loc(#loc10)
// CHECK-NEXT:       } else {
// CHECK-NEXT:         %17 = sol.load %2 : !sol.ptr<i1, Stack>, i1 loc(#loc11)
// CHECK-NEXT:         sol.store %17, %15 : i1, !sol.ptr<i1, Stack> loc(#loc10)
// CHECK-NEXT:         sol.yield loc(#loc10)
// CHECK-NEXT:       } loc(#loc10)
// CHECK-NEXT:       %16 = sol.load %15 : !sol.ptr<i1, Stack>, i1 loc(#loc10)
// CHECK-NEXT:       sol.store %16, %8 : i1, !sol.ptr<i1, Stack> loc(#loc9)
// CHECK-NEXT:       sol.yield loc(#loc9)
// CHECK-NEXT:     } loc(#loc9)
// CHECK-NEXT:     %9 = sol.load %8 : !sol.ptr<i1, Stack>, i1 loc(#loc9)
// CHECK-NEXT:     %10 = sol.alloca : !sol.ptr<i1, Stack> loc(#loc12)
// CHECK-NEXT:     sol.store %9, %10 : i1, !sol.ptr<i1, Stack> loc(#loc12)
// CHECK-NEXT:     %11 = sol.load %6 : !sol.ptr<i1, Stack>, i1 loc(#loc13)
// CHECK-NEXT:     %12 = sol.alloca : !sol.ptr<i1, Stack> loc(#loc13)
// CHECK-NEXT:     %false_0 = arith.constant false loc(#loc13)
// CHECK-NEXT:     sol.store %false_0, %12 : i1, !sol.ptr<i1, Stack> loc(#loc13)
// CHECK-NEXT:     sol.if %11 {
// CHECK-NEXT:       %14 = sol.load %10 : !sol.ptr<i1, Stack>, i1 loc(#loc14)
// CHECK-NEXT:       sol.store %14, %12 : i1, !sol.ptr<i1, Stack> loc(#loc13)
// CHECK-NEXT:       sol.yield loc(#loc13)
// CHECK-NEXT:     } else {
// CHECK-NEXT:     } loc(#loc13)
// CHECK-NEXT:     %13 = sol.load %12 : !sol.ptr<i1, Stack>, i1 loc(#loc13)
// CHECK-NEXT:     sol.return %13 : i1 loc(#loc15)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc5 = loc({{.*}}:3:11)
// CHECK-NEXT: #loc6 = loc({{.*}}:3:17)
// CHECK-NEXT: #loc7 = loc({{.*}}:3:22)
// CHECK-NEXT: #loc8 = loc({{.*}}:3:2)
// CHECK-NEXT: #loc9 = loc({{.*}}:4:11)
// CHECK-NEXT: #loc10 = loc({{.*}}:4:17)
// CHECK-NEXT: #loc11 = loc({{.*}}:4:22)
// CHECK-NEXT: #loc12 = loc({{.*}}:4:2)
// CHECK-NEXT: #loc13 = loc({{.*}}:5:9)
// CHECK-NEXT: #loc14 = loc({{.*}}:5:14)
// CHECK-NEXT: #loc15 = loc({{.*}}:5:2)
// CHECK-EMPTY:
