// FIXME:
// XFAIL: *
// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
  modifier m(uint a) { _; }
  modifier n(uint a) { _; f(a); }
  function f(uint a) m(a) n(a + 1) public {}
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Cancun = #sol<EvmVersion Cancun>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #loc3 = loc({{.*}}:5:13)
// CHECK-NEXT: #loc9 = loc({{.*}}:3:13)
// CHECK-NEXT: #loc12 = loc({{.*}}:4:13)
// CHECK-NEXT: module attributes {sol.evm_version = #Cancun} {
// CHECK-NEXT:   sol.contract @C_31 {
// CHECK-NEXT:     sol.func @f_30(%arg0: ui256 loc({{.*}}:5:13)) attributes {state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.modifier_call_blk {
// CHECK-NEXT:       ^bb0(%arg1: ui256 loc({{.*}}:5:13)):
// CHECK-NEXT:         sol.call @m_6(%arg1) : (ui256) -> () loc(#loc4)
// CHECK-NEXT:       } loc(#loc4)
// CHECK-NEXT:       sol.modifier_call_blk {
// CHECK-NEXT:       ^bb0(%arg1: ui256 loc({{.*}}:5:13)):
// CHECK-NEXT:         %c1_ui8 = sol.constant 1 : ui8 loc(#loc6)
// CHECK-NEXT:         %1 = sol.cast %c1_ui8 : ui8 to ui256 loc(#loc6)
// CHECK-NEXT:         %2 = sol.add %arg1, %1 : ui256 loc(#loc7)
// CHECK-NEXT:         sol.call @n_16(%2) : (ui256) -> () loc(#loc5)
// CHECK-NEXT:       } loc(#loc5)
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:       sol.return loc(#loc2)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     sol.modifier @m_6(%arg0: ui256 loc({{.*}}:3:13)) {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc9)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc9)
// CHECK-NEXT:       sol.placeholder loc(#loc10)
// CHECK-NEXT:       sol.return loc(#loc8)
// CHECK-NEXT:     } loc(#loc8)
// CHECK-NEXT:     sol.modifier @n_16(%arg0: ui256 loc({{.*}}:4:13)) {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc12)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc12)
// CHECK-NEXT:       sol.placeholder loc(#loc13)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc14)
// CHECK-NEXT:       sol.call @f_30(%1) : (ui256) -> () loc(#loc15)
// CHECK-NEXT:       sol.return loc(#loc11)
// CHECK-NEXT:     } loc(#loc11)
// CHECK-NEXT:   } {interface_fns = [{selector = -1277270901 : i32, sym = @f_30, type = (ui256) -> ()}], kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:5:2)
// CHECK-NEXT: #loc4 = loc({{.*}}:5:21)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:26)
// CHECK-NEXT: #loc6 = loc({{.*}}:5:32)
// CHECK-NEXT: #loc7 = loc({{.*}}:5:28)
// CHECK-NEXT: #loc8 = loc({{.*}}:3:2)
// CHECK-NEXT: #loc10 = loc({{.*}}:3:23)
// CHECK-NEXT: #loc11 = loc({{.*}}:4:2)
// CHECK-NEXT: #loc13 = loc({{.*}}:4:23)
// CHECK-NEXT: #loc14 = loc({{.*}}:4:28)
// CHECK-NEXT: #loc15 = loc({{.*}}:4:26)
// CHECK-EMPTY:
