// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
    function l(bytes20 x, uint8 y) public returns (bytes20) {
        return x << y;
    }
    function r(bytes20 x, uint8 y) public returns (bytes20) {
        return x >> y;
    }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #loc3 = loc({{.*}}:3:15)
// CHECK-NEXT: #loc4 = loc({{.*}}:3:26)
// CHECK-NEXT: #loc9 = loc({{.*}}:6:15)
// CHECK-NEXT: #loc10 = loc({{.*}}:6:26)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @C_29 {
// CHECK-NEXT:     sol.func @C_29() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @l_14(%arg0: !sol.fixedbytes<20> loc({{.*}}:3:15), %arg1: ui8 loc({{.*}}:3:26)) -> !sol.fixedbytes<20> attributes {id = 14 : i64, orig_fn_type = (!sol.fixedbytes<20>, ui8) -> !sol.fixedbytes<20>, selector = 929672590 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.fixedbytes<20>, Stack> loc(#loc3)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.fixedbytes<20>, !sol.ptr<!sol.fixedbytes<20>, Stack> loc(#loc3)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<ui8, Stack> loc(#loc4)
// CHECK-NEXT:       sol.store %arg1, %1 : ui8, !sol.ptr<ui8, Stack> loc(#loc4)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.fixedbytes<20>, Stack>, !sol.fixedbytes<20> loc(#loc5)
// CHECK-NEXT:       %3 = sol.load %1 : !sol.ptr<ui8, Stack>, ui8 loc(#loc6)
// CHECK-NEXT:       %4 = sol.shl %2, %3 : !sol.fixedbytes<20>, ui8 loc(#loc5)
// CHECK-NEXT:       sol.return %4 : !sol.fixedbytes<20> loc(#loc7)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     sol.func @r_28(%arg0: !sol.fixedbytes<20> loc({{.*}}:6:15), %arg1: ui8 loc({{.*}}:6:26)) -> !sol.fixedbytes<20> attributes {id = 28 : i64, orig_fn_type = (!sol.fixedbytes<20>, ui8) -> !sol.fixedbytes<20>, selector = 1006885945 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.fixedbytes<20>, Stack> loc(#loc9)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.fixedbytes<20>, !sol.ptr<!sol.fixedbytes<20>, Stack> loc(#loc9)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<ui8, Stack> loc(#loc10)
// CHECK-NEXT:       sol.store %arg1, %1 : ui8, !sol.ptr<ui8, Stack> loc(#loc10)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.fixedbytes<20>, Stack>, !sol.fixedbytes<20> loc(#loc11)
// CHECK-NEXT:       %3 = sol.load %1 : !sol.ptr<ui8, Stack>, ui8 loc(#loc12)
// CHECK-NEXT:       %4 = sol.shr %2, %3 : !sol.fixedbytes<20>, ui8 loc(#loc11)
// CHECK-NEXT:       sol.return %4 : !sol.fixedbytes<20> loc(#loc13)
// CHECK-NEXT:     } loc(#loc8)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:3:4)
// CHECK-NEXT: #loc5 = loc({{.*}}:4:15)
// CHECK-NEXT: #loc6 = loc({{.*}}:4:20)
// CHECK-NEXT: #loc7 = loc({{.*}}:4:8)
// CHECK-NEXT: #loc8 = loc({{.*}}:6:4)
// CHECK-NEXT: #loc11 = loc({{.*}}:7:15)
// CHECK-NEXT: #loc12 = loc({{.*}}:7:20)
// CHECK-NEXT: #loc13 = loc({{.*}}:7:8)
// CHECK-EMPTY:
