// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
  uint ui;
  mapping(address => uint) m0;
  mapping(address => mapping(address => uint256)) m1;
  mapping(C => uint) mc0;
  mapping(uint => C) mc1;
  string s;

  function get_ui() private returns (uint) { return ui; }
  function get_m0(address a) private returns (uint) { return m0[a]; }
  function get_m1(address a, address b) private returns (uint) { return m1[a][b]; }
  function get_mc0(C a) private returns (uint) { return mc0[a]; }
  function set_mc0(C a, uint v) private { mc0[a] = v; }
  function get_mc1(uint a) private returns (C) { return mc1[a]; }
  function set_mc1(uint a, C b) private { mc1[a] = b; }
  function get_s() private returns (string memory) { return s; }

  function set_s(string memory a) private { s = a; }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #loc12 = loc({{.*}}:11:18)
// CHECK-NEXT: #loc17 = loc({{.*}}:12:18)
// CHECK-NEXT: #loc18 = loc({{.*}}:12:29)
// CHECK-NEXT: #loc24 = loc({{.*}}:13:19)
// CHECK-NEXT: #loc29 = loc({{.*}}:14:19)
// CHECK-NEXT: #loc30 = loc({{.*}}:14:24)
// CHECK-NEXT: #loc35 = loc({{.*}}:15:19)
// CHECK-NEXT: #loc40 = loc({{.*}}:16:19)
// CHECK-NEXT: #loc41 = loc({{.*}}:16:27)
// CHECK-NEXT: #loc48 = loc({{.*}}:19:17)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka} {
// CHECK-NEXT:   sol.contract @C_135 {
// CHECK-NEXT:     sol.state_var @ui_2 slot 0 offset 0 : ui256 loc(#loc2)
// CHECK-NEXT:     sol.state_var @m0_6 slot 1 offset 0 : !sol.mapping<!sol.address, ui256> loc(#loc3)
// CHECK-NEXT:     sol.state_var @m1_12 slot 2 offset 0 : !sol.mapping<!sol.address, !sol.mapping<!sol.address, ui256>> loc(#loc4)
// CHECK-NEXT:     sol.state_var @mc0_17 slot 3 offset 0 : !sol.mapping<!sol.contract<"C_135">, ui256> loc(#loc5)
// CHECK-NEXT:     sol.state_var @mc1_22 slot 4 offset 0 : !sol.mapping<ui256, !sol.contract<"C_135">> loc(#loc6)
// CHECK-NEXT:     sol.state_var @s_24 slot 5 offset 0 : !sol.string<Storage> loc(#loc7)
// CHECK-NEXT:     sol.func @C_135() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @get_ui_32() -> ui256 attributes {id = 32 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @ui_2 : !sol.ptr<ui256, Storage> loc(#loc2)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<ui256, Storage>, ui256 loc(#loc9)
// CHECK-NEXT:       sol.return %1 : ui256 loc(#loc10)
// CHECK-NEXT:     } loc(#loc8)
// CHECK-NEXT:     sol.func @get_m0_44(%arg0: !sol.address loc({{.*}}:11:18)) -> ui256 attributes {id = 44 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.address, Stack> loc(#loc12)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.address, !sol.ptr<!sol.address, Stack> loc(#loc12)
// CHECK-NEXT:       %1 = sol.addr_of @m0_6 : !sol.mapping<!sol.address, ui256> loc(#loc3)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.address, Stack>, !sol.address loc(#loc13)
// CHECK-NEXT:       %3 = sol.map %1, %2 : !sol.mapping<!sol.address, ui256>, !sol.address, !sol.ptr<ui256, Storage> loc(#loc14)
// CHECK-NEXT:       %4 = sol.load %3 : !sol.ptr<ui256, Storage>, ui256 loc(#loc14)
// CHECK-NEXT:       sol.return %4 : ui256 loc(#loc15)
// CHECK-NEXT:     } loc(#loc11)
// CHECK-NEXT:     sol.func @get_m1_60(%arg0: !sol.address loc({{.*}}:12:18), %arg1: !sol.address loc({{.*}}:12:29)) -> ui256 attributes {id = 60 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.address, Stack> loc(#loc17)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.address, !sol.ptr<!sol.address, Stack> loc(#loc17)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.address, Stack> loc(#loc18)
// CHECK-NEXT:       sol.store %arg1, %1 : !sol.address, !sol.ptr<!sol.address, Stack> loc(#loc18)
// CHECK-NEXT:       %2 = sol.addr_of @m1_12 : !sol.mapping<!sol.address, !sol.mapping<!sol.address, ui256>> loc(#loc4)
// CHECK-NEXT:       %3 = sol.load %0 : !sol.ptr<!sol.address, Stack>, !sol.address loc(#loc19)
// CHECK-NEXT:       %4 = sol.map %2, %3 : !sol.mapping<!sol.address, !sol.mapping<!sol.address, ui256>>, !sol.address, !sol.mapping<!sol.address, ui256> loc(#loc20)
// CHECK-NEXT:       %5 = sol.load %1 : !sol.ptr<!sol.address, Stack>, !sol.address loc(#loc21)
// CHECK-NEXT:       %6 = sol.map %4, %5 : !sol.mapping<!sol.address, ui256>, !sol.address, !sol.ptr<ui256, Storage> loc(#loc20)
// CHECK-NEXT:       %7 = sol.load %6 : !sol.ptr<ui256, Storage>, ui256 loc(#loc20)
// CHECK-NEXT:       sol.return %7 : ui256 loc(#loc22)
// CHECK-NEXT:     } loc(#loc16)
// CHECK-NEXT:     sol.func @get_mc0_73(%arg0: !sol.contract<"C_135"> loc({{.*}}:13:19)) -> ui256 attributes {id = 73 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.contract<"C_135">, Stack> loc(#loc24)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.contract<"C_135">, !sol.ptr<!sol.contract<"C_135">, Stack> loc(#loc24)
// CHECK-NEXT:       %1 = sol.addr_of @mc0_17 : !sol.mapping<!sol.contract<"C_135">, ui256> loc(#loc5)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.contract<"C_135">, Stack>, !sol.contract<"C_135"> loc(#loc25)
// CHECK-NEXT:       %3 = sol.map %1, %2 : !sol.mapping<!sol.contract<"C_135">, ui256>, !sol.contract<"C_135">, !sol.ptr<ui256, Storage> loc(#loc26)
// CHECK-NEXT:       %4 = sol.load %3 : !sol.ptr<ui256, Storage>, ui256 loc(#loc26)
// CHECK-NEXT:       sol.return %4 : ui256 loc(#loc27)
// CHECK-NEXT:     } loc(#loc23)
// CHECK-NEXT:     sol.func @set_mc0_88(%arg0: !sol.contract<"C_135"> loc({{.*}}:14:19), %arg1: ui256 loc({{.*}}:14:24)) attributes {id = 88 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.contract<"C_135">, Stack> loc(#loc29)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.contract<"C_135">, !sol.ptr<!sol.contract<"C_135">, Stack> loc(#loc29)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc30)
// CHECK-NEXT:       sol.store %arg1, %1 : ui256, !sol.ptr<ui256, Stack> loc(#loc30)
// CHECK-NEXT:       %2 = sol.addr_of @mc0_17 : !sol.mapping<!sol.contract<"C_135">, ui256> loc(#loc5)
// CHECK-NEXT:       %3 = sol.load %0 : !sol.ptr<!sol.contract<"C_135">, Stack>, !sol.contract<"C_135"> loc(#loc31)
// CHECK-NEXT:       %4 = sol.map %2, %3 : !sol.mapping<!sol.contract<"C_135">, ui256>, !sol.contract<"C_135">, !sol.ptr<ui256, Storage> loc(#loc32)
// CHECK-NEXT:       %5 = sol.load %1 : !sol.ptr<ui256, Stack>, ui256 loc(#loc33)
// CHECK-NEXT:       sol.store %5, %4 : ui256, !sol.ptr<ui256, Storage> loc(#loc32)
// CHECK-NEXT:       sol.return loc(#loc28)
// CHECK-NEXT:     } loc(#loc28)
// CHECK-NEXT:     sol.func @get_mc1_101(%arg0: ui256 loc({{.*}}:15:19)) -> !sol.contract<"C_135"> attributes {id = 101 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc35)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc35)
// CHECK-NEXT:       %1 = sol.addr_of @mc1_22 : !sol.mapping<ui256, !sol.contract<"C_135">> loc(#loc6)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc36)
// CHECK-NEXT:       %3 = sol.map %1, %2 : !sol.mapping<ui256, !sol.contract<"C_135">>, ui256, !sol.ptr<!sol.contract<"C_135">, Storage> loc(#loc37)
// CHECK-NEXT:       %4 = sol.load %3 : !sol.ptr<!sol.contract<"C_135">, Storage>, !sol.contract<"C_135"> loc(#loc37)
// CHECK-NEXT:       sol.return %4 : !sol.contract<"C_135"> loc(#loc38)
// CHECK-NEXT:     } loc(#loc34)
// CHECK-NEXT:     sol.func @set_mc1_116(%arg0: ui256 loc({{.*}}:16:19), %arg1: !sol.contract<"C_135"> loc({{.*}}:16:27)) attributes {id = 116 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc40)
// CHECK-NEXT:       sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc40)
// CHECK-NEXT:       %1 = sol.alloca : !sol.ptr<!sol.contract<"C_135">, Stack> loc(#loc41)
// CHECK-NEXT:       sol.store %arg1, %1 : !sol.contract<"C_135">, !sol.ptr<!sol.contract<"C_135">, Stack> loc(#loc41)
// CHECK-NEXT:       %2 = sol.addr_of @mc1_22 : !sol.mapping<ui256, !sol.contract<"C_135">> loc(#loc6)
// CHECK-NEXT:       %3 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc42)
// CHECK-NEXT:       %4 = sol.map %2, %3 : !sol.mapping<ui256, !sol.contract<"C_135">>, ui256, !sol.ptr<!sol.contract<"C_135">, Storage> loc(#loc43)
// CHECK-NEXT:       %5 = sol.load %1 : !sol.ptr<!sol.contract<"C_135">, Stack>, !sol.contract<"C_135"> loc(#loc44)
// CHECK-NEXT:       sol.store %5, %4 : !sol.contract<"C_135">, !sol.ptr<!sol.contract<"C_135">, Storage> loc(#loc43)
// CHECK-NEXT:       sol.return loc(#loc39)
// CHECK-NEXT:     } loc(#loc39)
// CHECK-NEXT:     sol.func @get_s_124() -> !sol.string<Memory> attributes {id = 124 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @s_24 : !sol.string<Storage> loc(#loc7)
// CHECK-NEXT:       %1 = sol.data_loc_cast %0 : !sol.string<Storage>, !sol.string<Memory> loc(#loc7)
// CHECK-NEXT:       sol.return %1 : !sol.string<Memory> loc(#loc46)
// CHECK-NEXT:     } loc(#loc45)
// CHECK-NEXT:     sol.func @set_s_134(%arg0: !sol.string<Memory> loc({{.*}}:19:17)) attributes {id = 134 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc48)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc48)
// CHECK-NEXT:       %1 = sol.addr_of @s_24 : !sol.string<Storage> loc(#loc7)
// CHECK-NEXT:       %2 = sol.load %0 : !sol.ptr<!sol.string<Memory>, Stack>, !sol.string<Memory> loc(#loc49)
// CHECK-NEXT:       sol.copy %2, %1 : !sol.string<Memory>, !sol.string<Storage> loc(#loc50)
// CHECK-NEXT:       sol.return loc(#loc47)
// CHECK-NEXT:     } loc(#loc47)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:3:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:4:2)
// CHECK-NEXT: #loc4 = loc({{.*}}:5:2)
// CHECK-NEXT: #loc5 = loc({{.*}}:6:2)
// CHECK-NEXT: #loc6 = loc({{.*}}:7:2)
// CHECK-NEXT: #loc7 = loc({{.*}}:8:2)
// CHECK-NEXT: #loc8 = loc({{.*}}:10:2)
// CHECK-NEXT: #loc9 = loc({{.*}}:10:52)
// CHECK-NEXT: #loc10 = loc({{.*}}:10:45)
// CHECK-NEXT: #loc11 = loc({{.*}}:11:2)
// CHECK-NEXT: #loc13 = loc({{.*}}:11:64)
// CHECK-NEXT: #loc14 = loc({{.*}}:11:61)
// CHECK-NEXT: #loc15 = loc({{.*}}:11:54)
// CHECK-NEXT: #loc16 = loc({{.*}}:12:2)
// CHECK-NEXT: #loc19 = loc({{.*}}:12:75)
// CHECK-NEXT: #loc20 = loc({{.*}}:12:72)
// CHECK-NEXT: #loc21 = loc({{.*}}:12:78)
// CHECK-NEXT: #loc22 = loc({{.*}}:12:65)
// CHECK-NEXT: #loc23 = loc({{.*}}:13:2)
// CHECK-NEXT: #loc25 = loc({{.*}}:13:60)
// CHECK-NEXT: #loc26 = loc({{.*}}:13:56)
// CHECK-NEXT: #loc27 = loc({{.*}}:13:49)
// CHECK-NEXT: #loc28 = loc({{.*}}:14:2)
// CHECK-NEXT: #loc31 = loc({{.*}}:14:46)
// CHECK-NEXT: #loc32 = loc({{.*}}:14:42)
// CHECK-NEXT: #loc33 = loc({{.*}}:14:51)
// CHECK-NEXT: #loc34 = loc({{.*}}:15:2)
// CHECK-NEXT: #loc36 = loc({{.*}}:15:60)
// CHECK-NEXT: #loc37 = loc({{.*}}:15:56)
// CHECK-NEXT: #loc38 = loc({{.*}}:15:49)
// CHECK-NEXT: #loc39 = loc({{.*}}:16:2)
// CHECK-NEXT: #loc42 = loc({{.*}}:16:46)
// CHECK-NEXT: #loc43 = loc({{.*}}:16:42)
// CHECK-NEXT: #loc44 = loc({{.*}}:16:51)
// CHECK-NEXT: #loc45 = loc({{.*}}:17:2)
// CHECK-NEXT: #loc46 = loc({{.*}}:17:53)
// CHECK-NEXT: #loc47 = loc({{.*}}:19:2)
// CHECK-NEXT: #loc49 = loc({{.*}}:19:48)
// CHECK-NEXT: #loc50 = loc({{.*}}:19:44)
// CHECK-EMPTY:
