// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
  // Non-packed arrays
  uint256[] arr256;
  uint256[4] staticArr256;

  // Packed arrays
  uint8[] arr8;
  uint8[4] staticArr8;

  function rw() public {
    arr256.push(1);
    arr256.pop();
    staticArr256[0] = staticArr256[1];

    arr8.push(1);
    arr8.pop();
    staticArr8[0] = staticArr8[1];
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka} {
// CHECK-NEXT:   sol.contract @C_57 {
// CHECK-NEXT:     sol.state_var @arr256_3 slot 0 offset 0 : !sol.array<? x ui256, Storage> loc(#loc2)
// CHECK-NEXT:     sol.state_var @staticArr256_7 slot 1 offset 0 : !sol.array<4 x ui256, Storage> loc(#loc3)
// CHECK-NEXT:     sol.state_var @arr8_10 slot 5 offset 0 : !sol.array<? x ui8, Storage> loc(#loc4)
// CHECK-NEXT:     sol.state_var @staticArr8_14 slot 6 offset 0 : !sol.array<4 x ui8, Storage> loc(#loc5)
// CHECK-NEXT:     sol.func @C_57() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @rw_56() attributes {id = 56 : i64, orig_fn_type = () -> (), selector = -1813835346 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.addr_of @arr256_3 : !sol.array<? x ui256, Storage> loc(#loc2)
// CHECK-NEXT:       %1 = sol.push %0 : !sol.array<? x ui256, Storage> -> !sol.ptr<ui256, Storage> loc(#loc7)
// CHECK-NEXT:       %c1_ui8 = sol.constant 1 : ui8 loc(#loc8)
// CHECK-NEXT:       sol.store %c1_ui8, %1 : ui8, !sol.ptr<ui256, Storage> loc(#loc7)
// CHECK-NEXT:       %2 = sol.addr_of @arr256_3 : !sol.array<? x ui256, Storage> loc(#loc2)
// CHECK-NEXT:       sol.pop %2 : !sol.array<? x ui256, Storage> loc(#loc9)
// CHECK-NEXT:       %3 = sol.addr_of @staticArr256_7 : !sol.array<4 x ui256, Storage> loc(#loc3)
// CHECK-NEXT:       %c0_ui8 = sol.constant 0 : ui8 loc(#loc10)
// CHECK-NEXT:       %4 = sol.gep %3, %c0_ui8 : !sol.array<4 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc11)
// CHECK-NEXT:       %5 = sol.addr_of @staticArr256_7 : !sol.array<4 x ui256, Storage> loc(#loc3)
// CHECK-NEXT:       %c1_ui8_0 = sol.constant 1 : ui8 loc(#loc12)
// CHECK-NEXT:       %6 = sol.gep %5, %c1_ui8_0 : !sol.array<4 x ui256, Storage>, ui8, !sol.ptr<ui256, Storage> loc(#loc13)
// CHECK-NEXT:       %7 = sol.load %6 : !sol.ptr<ui256, Storage>, ui256 loc(#loc13)
// CHECK-NEXT:       sol.store %7, %4 : ui256, !sol.ptr<ui256, Storage> loc(#loc11)
// CHECK-NEXT:       %8 = sol.addr_of @arr8_10 : !sol.array<? x ui8, Storage> loc(#loc4)
// CHECK-NEXT:       %9 = sol.push %8 : !sol.array<? x ui8, Storage> -> !sol.ptr<ui8, Storage> loc(#loc14)
// CHECK-NEXT:       %c1_ui8_1 = sol.constant 1 : ui8 loc(#loc15)
// CHECK-NEXT:       sol.store %c1_ui8_1, %9 : ui8, !sol.ptr<ui8, Storage> loc(#loc14)
// CHECK-NEXT:       %10 = sol.addr_of @arr8_10 : !sol.array<? x ui8, Storage> loc(#loc4)
// CHECK-NEXT:       sol.pop %10 : !sol.array<? x ui8, Storage> loc(#loc16)
// CHECK-NEXT:       %11 = sol.addr_of @staticArr8_14 : !sol.array<4 x ui8, Storage> loc(#loc5)
// CHECK-NEXT:       %c0_ui8_2 = sol.constant 0 : ui8 loc(#loc17)
// CHECK-NEXT:       %12 = sol.gep %11, %c0_ui8_2 : !sol.array<4 x ui8, Storage>, ui8, !sol.ptr<ui8, Storage> loc(#loc18)
// CHECK-NEXT:       %13 = sol.addr_of @staticArr8_14 : !sol.array<4 x ui8, Storage> loc(#loc5)
// CHECK-NEXT:       %c1_ui8_3 = sol.constant 1 : ui8 loc(#loc19)
// CHECK-NEXT:       %14 = sol.gep %13, %c1_ui8_3 : !sol.array<4 x ui8, Storage>, ui8, !sol.ptr<ui8, Storage> loc(#loc20)
// CHECK-NEXT:       %15 = sol.load %14 : !sol.ptr<ui8, Storage>, ui8 loc(#loc20)
// CHECK-NEXT:       sol.store %15, %12 : ui8, !sol.ptr<ui8, Storage> loc(#loc18)
// CHECK-NEXT:       sol.return loc(#loc6)
// CHECK-NEXT:     } loc(#loc6)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:5:2)
// CHECK-NEXT: #loc4 = loc({{.*}}:8:2)
// CHECK-NEXT: #loc5 = loc({{.*}}:9:2)
// CHECK-NEXT: #loc6 = loc({{.*}}:11:2)
// CHECK-NEXT: #loc7 = loc({{.*}}:12:4)
// CHECK-NEXT: #loc8 = loc({{.*}}:12:16)
// CHECK-NEXT: #loc9 = loc({{.*}}:13:4)
// CHECK-NEXT: #loc10 = loc({{.*}}:14:17)
// CHECK-NEXT: #loc11 = loc({{.*}}:14:4)
// CHECK-NEXT: #loc12 = loc({{.*}}:14:35)
// CHECK-NEXT: #loc13 = loc({{.*}}:14:22)
// CHECK-NEXT: #loc14 = loc({{.*}}:16:4)
// CHECK-NEXT: #loc15 = loc({{.*}}:16:14)
// CHECK-NEXT: #loc16 = loc({{.*}}:17:4)
// CHECK-NEXT: #loc17 = loc({{.*}}:18:15)
// CHECK-NEXT: #loc18 = loc({{.*}}:18:4)
// CHECK-NEXT: #loc19 = loc({{.*}}:18:31)
// CHECK-NEXT: #loc20 = loc({{.*}}:18:20)
// CHECK-EMPTY:
