// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

struct S {
    uint256 a;      // member 0
    uint256[2] b;   // member 1
    uint256 c;      // member 2
}

function getC(S calldata s) pure returns (uint256) { return s.c; }
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #Pure = #sol<StateMutability Pure>
// CHECK-NEXT: #loc2 = loc({{.*}}:11:14)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.func @getC_22(%arg0: !sol.struct<(ui256, !sol.array<2 x ui256, CallData>, ui256), CallData> loc({{.*}}:11:14)) -> ui256 attributes {id = 22 : i64, state_mutability = #Pure} {
// CHECK-NEXT:     %0 = sol.alloca : !sol.ptr<!sol.struct<(ui256, !sol.array<2 x ui256, CallData>, ui256), CallData>, Stack> loc(#loc2)
// CHECK-NEXT:     sol.store %arg0, %0 : !sol.struct<(ui256, !sol.array<2 x ui256, CallData>, ui256), CallData>, !sol.ptr<!sol.struct<(ui256, !sol.array<2 x ui256, CallData>, ui256), CallData>, Stack> loc(#loc2)
// CHECK-NEXT:     %c2_ui64 = sol.constant 2 : ui64 loc(#loc3)
// CHECK-NEXT:     %1 = sol.load %0 : !sol.ptr<!sol.struct<(ui256, !sol.array<2 x ui256, CallData>, ui256), CallData>, Stack>, !sol.struct<(ui256, !sol.array<2 x ui256, CallData>, ui256), CallData> loc(#loc3)
// CHECK-NEXT:     %2 = sol.gep %1, %c2_ui64 : !sol.struct<(ui256, !sol.array<2 x ui256, CallData>, ui256), CallData>, ui64, !sol.ptr<ui256, CallData> loc(#loc3)
// CHECK-NEXT:     %3 = sol.load %2 : !sol.ptr<ui256, CallData>, ui256 loc(#loc3)
// CHECK-NEXT:     sol.return %3 : ui256 loc(#loc4)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:11:0)
// CHECK-NEXT: #loc3 = loc({{.*}}:11:60)
// CHECK-NEXT: #loc4 = loc({{.*}}:11:53)
// CHECK-EMPTY:
