// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

struct S {
  uint256 a;
  uint256 b;
}

function positional() returns (uint256, uint256) {
  S memory s = S(7, 11);
  return (s.a, s.b);
}

function named() returns (uint256, uint256) {
  S memory s = S({b: 13, a: 17});
  return (s.a, s.b);
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.func @positional_27() -> (ui256, ui256) attributes {id = 27 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:     %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc2)
// CHECK-NEXT:     %c0_ui256 = sol.constant 0 : ui256 loc(#loc2)
// CHECK-NEXT:     sol.store %c0_ui256, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc2)
// CHECK-NEXT:     %1 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:     %c0_ui256_0 = sol.constant 0 : ui256 loc(#loc3)
// CHECK-NEXT:     sol.store %c0_ui256_0, %1 : ui256, !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:     %2 = sol.malloc :  !sol.struct<(ui256, ui256), Memory> loc(#loc4)
// CHECK-NEXT:     %c0_ui64 = sol.constant 0 : ui64 loc(#loc4)
// CHECK-NEXT:     %3 = sol.gep %2, %c0_ui64 : !sol.struct<(ui256, ui256), Memory>, ui64, !sol.ptr<ui256, Memory> loc(#loc4)
// CHECK-NEXT:     %c7_ui8 = sol.constant 7 : ui8 loc(#loc5)
// CHECK-NEXT:     %4 = sol.cast %c7_ui8 : ui8 to ui256 loc(#loc5)
// CHECK-NEXT:     sol.store %4, %3 : ui256, !sol.ptr<ui256, Memory> loc(#loc4)
// CHECK-NEXT:     %c1_ui64 = sol.constant 1 : ui64 loc(#loc4)
// CHECK-NEXT:     %5 = sol.gep %2, %c1_ui64 : !sol.struct<(ui256, ui256), Memory>, ui64, !sol.ptr<ui256, Memory> loc(#loc4)
// CHECK-NEXT:     %c11_ui8 = sol.constant 11 : ui8 loc(#loc6)
// CHECK-NEXT:     %6 = sol.cast %c11_ui8 : ui8 to ui256 loc(#loc6)
// CHECK-NEXT:     sol.store %6, %5 : ui256, !sol.ptr<ui256, Memory> loc(#loc4)
// CHECK-NEXT:     %7 = sol.alloca : !sol.ptr<!sol.struct<(ui256, ui256), Memory>, Stack> loc(#loc7)
// CHECK-NEXT:     sol.store %2, %7 : !sol.struct<(ui256, ui256), Memory>, !sol.ptr<!sol.struct<(ui256, ui256), Memory>, Stack> loc(#loc7)
// CHECK-NEXT:     %c0_ui64_1 = sol.constant 0 : ui64 loc(#loc8)
// CHECK-NEXT:     %8 = sol.load %7 : !sol.ptr<!sol.struct<(ui256, ui256), Memory>, Stack>, !sol.struct<(ui256, ui256), Memory> loc(#loc8)
// CHECK-NEXT:     %9 = sol.gep %8, %c0_ui64_1 : !sol.struct<(ui256, ui256), Memory>, ui64, !sol.ptr<ui256, Memory> loc(#loc8)
// CHECK-NEXT:     %c1_ui64_2 = sol.constant 1 : ui64 loc(#loc9)
// CHECK-NEXT:     %10 = sol.load %7 : !sol.ptr<!sol.struct<(ui256, ui256), Memory>, Stack>, !sol.struct<(ui256, ui256), Memory> loc(#loc9)
// CHECK-NEXT:     %11 = sol.gep %10, %c1_ui64_2 : !sol.struct<(ui256, ui256), Memory>, ui64, !sol.ptr<ui256, Memory> loc(#loc9)
// CHECK-NEXT:     %12 = sol.load %9 : !sol.ptr<ui256, Memory>, ui256 loc(#loc10)
// CHECK-NEXT:     %13 = sol.load %11 : !sol.ptr<ui256, Memory>, ui256 loc(#loc10)
// CHECK-NEXT:     sol.return %12, %13 : ui256, ui256 loc(#loc11)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   sol.func @named_49() -> (ui256, ui256) attributes {id = 49 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:     %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc13)
// CHECK-NEXT:     %c0_ui256 = sol.constant 0 : ui256 loc(#loc13)
// CHECK-NEXT:     sol.store %c0_ui256, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc13)
// CHECK-NEXT:     %1 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc14)
// CHECK-NEXT:     %c0_ui256_0 = sol.constant 0 : ui256 loc(#loc14)
// CHECK-NEXT:     sol.store %c0_ui256_0, %1 : ui256, !sol.ptr<ui256, Stack> loc(#loc14)
// CHECK-NEXT:     %2 = sol.malloc :  !sol.struct<(ui256, ui256), Memory> loc(#loc15)
// CHECK-NEXT:     %c0_ui64 = sol.constant 0 : ui64 loc(#loc15)
// CHECK-NEXT:     %3 = sol.gep %2, %c0_ui64 : !sol.struct<(ui256, ui256), Memory>, ui64, !sol.ptr<ui256, Memory> loc(#loc15)
// CHECK-NEXT:     %c17_ui8 = sol.constant 17 : ui8 loc(#loc16)
// CHECK-NEXT:     %4 = sol.cast %c17_ui8 : ui8 to ui256 loc(#loc16)
// CHECK-NEXT:     sol.store %4, %3 : ui256, !sol.ptr<ui256, Memory> loc(#loc15)
// CHECK-NEXT:     %c1_ui64 = sol.constant 1 : ui64 loc(#loc15)
// CHECK-NEXT:     %5 = sol.gep %2, %c1_ui64 : !sol.struct<(ui256, ui256), Memory>, ui64, !sol.ptr<ui256, Memory> loc(#loc15)
// CHECK-NEXT:     %c13_ui8 = sol.constant 13 : ui8 loc(#loc17)
// CHECK-NEXT:     %6 = sol.cast %c13_ui8 : ui8 to ui256 loc(#loc17)
// CHECK-NEXT:     sol.store %6, %5 : ui256, !sol.ptr<ui256, Memory> loc(#loc15)
// CHECK-NEXT:     %7 = sol.alloca : !sol.ptr<!sol.struct<(ui256, ui256), Memory>, Stack> loc(#loc18)
// CHECK-NEXT:     sol.store %2, %7 : !sol.struct<(ui256, ui256), Memory>, !sol.ptr<!sol.struct<(ui256, ui256), Memory>, Stack> loc(#loc18)
// CHECK-NEXT:     %c0_ui64_1 = sol.constant 0 : ui64 loc(#loc19)
// CHECK-NEXT:     %8 = sol.load %7 : !sol.ptr<!sol.struct<(ui256, ui256), Memory>, Stack>, !sol.struct<(ui256, ui256), Memory> loc(#loc19)
// CHECK-NEXT:     %9 = sol.gep %8, %c0_ui64_1 : !sol.struct<(ui256, ui256), Memory>, ui64, !sol.ptr<ui256, Memory> loc(#loc19)
// CHECK-NEXT:     %c1_ui64_2 = sol.constant 1 : ui64 loc(#loc20)
// CHECK-NEXT:     %10 = sol.load %7 : !sol.ptr<!sol.struct<(ui256, ui256), Memory>, Stack>, !sol.struct<(ui256, ui256), Memory> loc(#loc20)
// CHECK-NEXT:     %11 = sol.gep %10, %c1_ui64_2 : !sol.struct<(ui256, ui256), Memory>, ui64, !sol.ptr<ui256, Memory> loc(#loc20)
// CHECK-NEXT:     %12 = sol.load %9 : !sol.ptr<ui256, Memory>, ui256 loc(#loc21)
// CHECK-NEXT:     %13 = sol.load %11 : !sol.ptr<ui256, Memory>, ui256 loc(#loc21)
// CHECK-NEXT:     sol.return %12, %13 : ui256, ui256 loc(#loc22)
// CHECK-NEXT:   } loc(#loc12)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:7:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:7:31)
// CHECK-NEXT: #loc3 = loc({{.*}}:7:40)
// CHECK-NEXT: #loc4 = loc({{.*}}:8:15)
// CHECK-NEXT: #loc5 = loc({{.*}}:8:17)
// CHECK-NEXT: #loc6 = loc({{.*}}:8:20)
// CHECK-NEXT: #loc7 = loc({{.*}}:8:2)
// CHECK-NEXT: #loc8 = loc({{.*}}:9:10)
// CHECK-NEXT: #loc9 = loc({{.*}}:9:15)
// CHECK-NEXT: #loc10 = loc({{.*}}:9:9)
// CHECK-NEXT: #loc11 = loc({{.*}}:9:2)
// CHECK-NEXT: #loc12 = loc({{.*}}:12:0)
// CHECK-NEXT: #loc13 = loc({{.*}}:12:26)
// CHECK-NEXT: #loc14 = loc({{.*}}:12:35)
// CHECK-NEXT: #loc15 = loc({{.*}}:13:15)
// CHECK-NEXT: #loc16 = loc({{.*}}:13:28)
// CHECK-NEXT: #loc17 = loc({{.*}}:13:21)
// CHECK-NEXT: #loc18 = loc({{.*}}:13:2)
// CHECK-NEXT: #loc19 = loc({{.*}}:14:10)
// CHECK-NEXT: #loc20 = loc({{.*}}:14:15)
// CHECK-NEXT: #loc21 = loc({{.*}}:14:9)
// CHECK-NEXT: #loc22 = loc({{.*}}:14:2)
// CHECK-EMPTY:
