// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
    function origin() public view returns (address) { return tx.origin; }
    function gasprice() public view returns (uint) { return tx.gasprice; }
    function callvalue() public payable returns (uint) { return msg.value; }
    function sig() public pure returns (bytes4) { return msg.sig; }
    function basefee() public view returns (uint) { return block.basefee; }
    function blobbasefee() public view returns (uint) { return block.blobbasefee; }
    function chainid() public view returns (uint) { return block.chainid; }
    function coinbase() public view returns (address) { return block.coinbase; }
    function coinbase_payable() public view returns (address payable) { return block.coinbase; }
    function difficulty() public view returns (uint) { return block.difficulty; }
    function gaslimit() public view returns (uint) { return block.gaslimit; }
    function blocknumber() public view returns (uint) { return block.number; }
    function prevrandao() public view returns (uint) { return block.prevrandao; }
    function timestamp() public view returns (uint) { return block.timestamp; }
    function gasleft_() public view returns (uint) { return gasleft(); }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #Payable = #sol<StateMutability Payable>
// CHECK-NEXT: #Pure = #sol<StateMutability Pure>
// CHECK-NEXT: #View = #sol<StateMutability View>
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @C_136 {
// CHECK-NEXT:     sol.func @C_136() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @origin_9() -> !sol.address attributes {id = 9 : i64, orig_fn_type = () -> !sol.address, selector = -1819582670 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.origin : !sol.address loc(#loc3)
// CHECK-NEXT:       sol.return %0 : !sol.address loc(#loc4)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     sol.func @gasprice_18() -> ui256 attributes {id = 18 : i64, orig_fn_type = () -> ui256, selector = 1858220755 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.gasprice : ui256 loc(#loc6)
// CHECK-NEXT:       sol.return %0 : ui256 loc(#loc7)
// CHECK-NEXT:     } loc(#loc5)
// CHECK-NEXT:     sol.func @callvalue_27() -> ui256 attributes {id = 27 : i64, orig_fn_type = () -> ui256, selector = -1461124476 : i32, state_mutability = #Payable} {
// CHECK-NEXT:       %0 = sol.callvalue : ui256 loc(#loc9)
// CHECK-NEXT:       sol.return %0 : ui256 loc(#loc10)
// CHECK-NEXT:     } loc(#loc8)
// CHECK-NEXT:     sol.func @sig_36() -> !sol.bytes<4> attributes {id = 36 : i64, orig_fn_type = () -> !sol.bytes<4>, selector = 10945179 : i32, state_mutability = #Pure} {
// CHECK-NEXT:       %0 = sol.sig : !sol.bytes<4> loc(#loc12)
// CHECK-NEXT:       sol.return %0 : !sol.bytes<4> loc(#loc13)
// CHECK-NEXT:     } loc(#loc11)
// CHECK-NEXT:     sol.func @basefee_45() -> ui256 attributes {id = 45 : i64, orig_fn_type = () -> ui256, selector = 1559382377 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.basefee : ui256 loc(#loc15)
// CHECK-NEXT:       sol.return %0 : ui256 loc(#loc16)
// CHECK-NEXT:     } loc(#loc14)
// CHECK-NEXT:     sol.func @blobbasefee_54() -> ui256 attributes {id = 54 : i64, orig_fn_type = () -> ui256, selector = -1324892143 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.blobbasefee : ui256 loc(#loc18)
// CHECK-NEXT:       sol.return %0 : ui256 loc(#loc19)
// CHECK-NEXT:     } loc(#loc17)
// CHECK-NEXT:     sol.func @chainid_63() -> ui256 attributes {id = 63 : i64, orig_fn_type = () -> ui256, selector = -846948338 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.chainid : ui256 loc(#loc21)
// CHECK-NEXT:       sol.return %0 : ui256 loc(#loc22)
// CHECK-NEXT:     } loc(#loc20)
// CHECK-NEXT:     sol.func @coinbase_72() -> !sol.address attributes {id = 72 : i64, orig_fn_type = () -> !sol.address, selector = -1498543444 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.coinbase : !sol.address<payable> loc(#loc24)
// CHECK-NEXT:       %1 = sol.address_cast %0 : !sol.address<payable> to !sol.address loc(#loc24)
// CHECK-NEXT:       sol.return %1 : !sol.address loc(#loc25)
// CHECK-NEXT:     } loc(#loc23)
// CHECK-NEXT:     sol.func @coinbase_payable_81() -> !sol.address<payable> attributes {id = 81 : i64, orig_fn_type = () -> !sol.address<payable>, selector = -2116720752 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.coinbase : !sol.address<payable> loc(#loc27)
// CHECK-NEXT:       sol.return %0 : !sol.address<payable> loc(#loc28)
// CHECK-NEXT:     } loc(#loc26)
// CHECK-NEXT:     sol.func @difficulty_90() -> ui256 attributes {id = 90 : i64, orig_fn_type = () -> ui256, selector = 432727138 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.difficulty : ui256 loc(#loc30)
// CHECK-NEXT:       sol.return %0 : ui256 loc(#loc31)
// CHECK-NEXT:     } loc(#loc29)
// CHECK-NEXT:     sol.func @gaslimit_99() -> ui256 attributes {id = 99 : i64, orig_fn_type = () -> ui256, selector = 712124473 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.gaslimit : ui256 loc(#loc33)
// CHECK-NEXT:       sol.return %0 : ui256 loc(#loc34)
// CHECK-NEXT:     } loc(#loc32)
// CHECK-NEXT:     sol.func @blocknumber_108() -> ui256 attributes {id = 108 : i64, orig_fn_type = () -> ui256, selector = 84288071 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.blocknumber : ui256 loc(#loc36)
// CHECK-NEXT:       sol.return %0 : ui256 loc(#loc37)
// CHECK-NEXT:     } loc(#loc35)
// CHECK-NEXT:     sol.func @prevrandao_117() -> ui256 attributes {id = 117 : i64, orig_fn_type = () -> ui256, selector = 1145652076 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.prevrandao : ui256 loc(#loc39)
// CHECK-NEXT:       sol.return %0 : ui256 loc(#loc40)
// CHECK-NEXT:     } loc(#loc38)
// CHECK-NEXT:     sol.func @timestamp_126() -> ui256 attributes {id = 126 : i64, orig_fn_type = () -> ui256, selector = -1207470102 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.timestamp : ui256 loc(#loc42)
// CHECK-NEXT:       sol.return %0 : ui256 loc(#loc43)
// CHECK-NEXT:     } loc(#loc41)
// CHECK-NEXT:     sol.func @gasleft__135() -> ui256 attributes {id = 135 : i64, orig_fn_type = () -> ui256, selector = 1512270606 : i32, state_mutability = #View} {
// CHECK-NEXT:       %0 = sol.gasleft : ui256 loc(#loc45)
// CHECK-NEXT:       sol.return %0 : ui256 loc(#loc46)
// CHECK-NEXT:     } loc(#loc44)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:3:4)
// CHECK-NEXT: #loc3 = loc({{.*}}:3:61)
// CHECK-NEXT: #loc4 = loc({{.*}}:3:54)
// CHECK-NEXT: #loc5 = loc({{.*}}:4:4)
// CHECK-NEXT: #loc6 = loc({{.*}}:4:60)
// CHECK-NEXT: #loc7 = loc({{.*}}:4:53)
// CHECK-NEXT: #loc8 = loc({{.*}}:5:4)
// CHECK-NEXT: #loc9 = loc({{.*}}:5:64)
// CHECK-NEXT: #loc10 = loc({{.*}}:5:57)
// CHECK-NEXT: #loc11 = loc({{.*}}:6:4)
// CHECK-NEXT: #loc12 = loc({{.*}}:6:57)
// CHECK-NEXT: #loc13 = loc({{.*}}:6:50)
// CHECK-NEXT: #loc14 = loc({{.*}}:7:4)
// CHECK-NEXT: #loc15 = loc({{.*}}:7:59)
// CHECK-NEXT: #loc16 = loc({{.*}}:7:52)
// CHECK-NEXT: #loc17 = loc({{.*}}:8:4)
// CHECK-NEXT: #loc18 = loc({{.*}}:8:63)
// CHECK-NEXT: #loc19 = loc({{.*}}:8:56)
// CHECK-NEXT: #loc20 = loc({{.*}}:9:4)
// CHECK-NEXT: #loc21 = loc({{.*}}:9:59)
// CHECK-NEXT: #loc22 = loc({{.*}}:9:52)
// CHECK-NEXT: #loc23 = loc({{.*}}:10:4)
// CHECK-NEXT: #loc24 = loc({{.*}}:10:63)
// CHECK-NEXT: #loc25 = loc({{.*}}:10:56)
// CHECK-NEXT: #loc26 = loc({{.*}}:11:4)
// CHECK-NEXT: #loc27 = loc({{.*}}:11:79)
// CHECK-NEXT: #loc28 = loc({{.*}}:11:72)
// CHECK-NEXT: #loc29 = loc({{.*}}:12:4)
// CHECK-NEXT: #loc30 = loc({{.*}}:12:62)
// CHECK-NEXT: #loc31 = loc({{.*}}:12:55)
// CHECK-NEXT: #loc32 = loc({{.*}}:13:4)
// CHECK-NEXT: #loc33 = loc({{.*}}:13:60)
// CHECK-NEXT: #loc34 = loc({{.*}}:13:53)
// CHECK-NEXT: #loc35 = loc({{.*}}:14:4)
// CHECK-NEXT: #loc36 = loc({{.*}}:14:63)
// CHECK-NEXT: #loc37 = loc({{.*}}:14:56)
// CHECK-NEXT: #loc38 = loc({{.*}}:15:4)
// CHECK-NEXT: #loc39 = loc({{.*}}:15:62)
// CHECK-NEXT: #loc40 = loc({{.*}}:15:55)
// CHECK-NEXT: #loc41 = loc({{.*}}:16:4)
// CHECK-NEXT: #loc42 = loc({{.*}}:16:61)
// CHECK-NEXT: #loc43 = loc({{.*}}:16:54)
// CHECK-NEXT: #loc44 = loc({{.*}}:17:4)
// CHECK-NEXT: #loc45 = loc({{.*}}:17:60)
// CHECK-NEXT: #loc46 = loc({{.*}}:17:53)
// CHECK-EMPTY:
