// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract A {
  function f() public {}
}

function creation_code() returns (bytes memory) {
  return type(A).creationCode;
}

function creation_code_length() returns (uint256) {
  return type(A).creationCode.length;
}

function runtime_code() returns (bytes memory) {
  return type(A).runtimeCode;
}

function runtime_code_length() returns (uint256) {
  return type(A).runtimeCode.length;
}

contract Test {
  function callCreationCode() public returns (bytes memory) { return creation_code(); }
  function callCreationCodeLength() public returns (uint256) { return creation_code_length(); }
  function callRuntimeCode() public returns (bytes memory) { return runtime_code(); }
  function callRuntimeCodeLength() public returns (uint256) { return runtime_code_length(); }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @A_5 {
// CHECK-NEXT:     sol.func @A_5() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @f_4() attributes {id = 4 : i64, orig_fn_type = () -> (), selector = 638722032 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc2)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:3:2)
// CHECK-NEXT: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.contract @Test_88 {
// CHECK-NEXT:     sol.func @Test_88() attributes {kind = #Constructor, orig_fn_type = () -> (), state_mutability = #NonPayable} {
// CHECK-NEXT:       sol.return loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     sol.func @creation_code_16() -> !sol.string<Memory> attributes {id = 16 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc3)
// CHECK-NEXT:       %1 = sol.malloc :  !sol.string<Memory> loc(#loc3)
// CHECK-NEXT:       sol.store %1, %0 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc3)
// CHECK-NEXT:       %2 = sol.object_code "A_5" : !sol.string<Memory> loc(#loc4)
// CHECK-NEXT:       sol.return %2 : !sol.string<Memory> loc(#loc5)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     sol.func @callCreationCode_60() -> !sol.string<Memory> attributes {id = 60 : i64, orig_fn_type = () -> !sol.string<Memory>, selector = -1631948747 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc7)
// CHECK-NEXT:       %1 = sol.malloc :  !sol.string<Memory> loc(#loc7)
// CHECK-NEXT:       sol.store %1, %0 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc7)
// CHECK-NEXT:       %2 = sol.call @creation_code_16() : () -> !sol.string<Memory> loc(#loc8)
// CHECK-NEXT:       sol.return %2 : !sol.string<Memory> loc(#loc9)
// CHECK-NEXT:     } loc(#loc6)
// CHECK-NEXT:     sol.func @creation_code_length_28() -> ui256 attributes {id = 28 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc11)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc11)
// CHECK-NEXT:       sol.store %c0_ui256, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc11)
// CHECK-NEXT:       %1 = sol.object_code "A_5" : !sol.string<Memory> loc(#loc12)
// CHECK-NEXT:       %2 = sol.length %1 : !sol.string<Memory> loc(#loc12)
// CHECK-NEXT:       sol.return %2 : ui256 loc(#loc13)
// CHECK-NEXT:     } loc(#loc10)
// CHECK-NEXT:     sol.func @callCreationCodeLength_69() -> ui256 attributes {id = 69 : i64, orig_fn_type = () -> ui256, selector = 1046849386 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc15)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc15)
// CHECK-NEXT:       sol.store %c0_ui256, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc15)
// CHECK-NEXT:       %1 = sol.call @creation_code_length_28() : () -> ui256 loc(#loc16)
// CHECK-NEXT:       sol.return %1 : ui256 loc(#loc17)
// CHECK-NEXT:     } loc(#loc14)
// CHECK-NEXT:     sol.func @runtime_code_39() -> !sol.string<Memory> attributes {id = 39 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc19)
// CHECK-NEXT:       %1 = sol.malloc :  !sol.string<Memory> loc(#loc19)
// CHECK-NEXT:       sol.store %1, %0 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc19)
// CHECK-NEXT:       %2 = sol.object_code "A_5_deployed" : !sol.string<Memory> loc(#loc20)
// CHECK-NEXT:       sol.return %2 : !sol.string<Memory> loc(#loc21)
// CHECK-NEXT:     } loc(#loc18)
// CHECK-NEXT:     sol.func @callRuntimeCode_78() -> !sol.string<Memory> attributes {id = 78 : i64, orig_fn_type = () -> !sol.string<Memory>, selector = -1038060182 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc23)
// CHECK-NEXT:       %1 = sol.malloc :  !sol.string<Memory> loc(#loc23)
// CHECK-NEXT:       sol.store %1, %0 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc23)
// CHECK-NEXT:       %2 = sol.call @runtime_code_39() : () -> !sol.string<Memory> loc(#loc24)
// CHECK-NEXT:       sol.return %2 : !sol.string<Memory> loc(#loc25)
// CHECK-NEXT:     } loc(#loc22)
// CHECK-NEXT:     sol.func @runtime_code_length_51() -> ui256 attributes {id = 51 : i64, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc27)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc27)
// CHECK-NEXT:       sol.store %c0_ui256, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc27)
// CHECK-NEXT:       %1 = sol.object_code "A_5_deployed" : !sol.string<Memory> loc(#loc28)
// CHECK-NEXT:       %2 = sol.length %1 : !sol.string<Memory> loc(#loc28)
// CHECK-NEXT:       sol.return %2 : ui256 loc(#loc29)
// CHECK-NEXT:     } loc(#loc26)
// CHECK-NEXT:     sol.func @callRuntimeCodeLength_87() -> ui256 attributes {id = 87 : i64, orig_fn_type = () -> ui256, selector = 1999193425 : i32, state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc31)
// CHECK-NEXT:       %c0_ui256 = sol.constant 0 : ui256 loc(#loc31)
// CHECK-NEXT:       sol.store %c0_ui256, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc31)
// CHECK-NEXT:       %1 = sol.call @runtime_code_length_51() : () -> ui256 loc(#loc32)
// CHECK-NEXT:       sol.return %1 : ui256 loc(#loc33)
// CHECK-NEXT:     } loc(#loc30)
// CHECK-NEXT:   } {kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:22:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:6:0)
// CHECK-NEXT: #loc3 = loc({{.*}}:6:34)
// CHECK-NEXT: #loc4 = loc({{.*}}:7:9)
// CHECK-NEXT: #loc5 = loc({{.*}}:7:2)
// CHECK-NEXT: #loc6 = loc({{.*}}:23:2)
// CHECK-NEXT: #loc7 = loc({{.*}}:23:46)
// CHECK-NEXT: #loc8 = loc({{.*}}:23:69)
// CHECK-NEXT: #loc9 = loc({{.*}}:23:62)
// CHECK-NEXT: #loc10 = loc({{.*}}:10:0)
// CHECK-NEXT: #loc11 = loc({{.*}}:10:41)
// CHECK-NEXT: #loc12 = loc({{.*}}:11:9)
// CHECK-NEXT: #loc13 = loc({{.*}}:11:2)
// CHECK-NEXT: #loc14 = loc({{.*}}:24:2)
// CHECK-NEXT: #loc15 = loc({{.*}}:24:52)
// CHECK-NEXT: #loc16 = loc({{.*}}:24:70)
// CHECK-NEXT: #loc17 = loc({{.*}}:24:63)
// CHECK-NEXT: #loc18 = loc({{.*}}:14:0)
// CHECK-NEXT: #loc19 = loc({{.*}}:14:33)
// CHECK-NEXT: #loc20 = loc({{.*}}:15:9)
// CHECK-NEXT: #loc21 = loc({{.*}}:15:2)
// CHECK-NEXT: #loc22 = loc({{.*}}:25:2)
// CHECK-NEXT: #loc23 = loc({{.*}}:25:45)
// CHECK-NEXT: #loc24 = loc({{.*}}:25:68)
// CHECK-NEXT: #loc25 = loc({{.*}}:25:61)
// CHECK-NEXT: #loc26 = loc({{.*}}:18:0)
// CHECK-NEXT: #loc27 = loc({{.*}}:18:40)
// CHECK-NEXT: #loc28 = loc({{.*}}:19:9)
// CHECK-NEXT: #loc29 = loc({{.*}}:19:2)
// CHECK-NEXT: #loc30 = loc({{.*}}:26:2)
// CHECK-NEXT: #loc31 = loc({{.*}}:26:51)
// CHECK-NEXT: #loc32 = loc({{.*}}:26:69)
// CHECK-NEXT: #loc33 = loc({{.*}}:26:62)
// CHECK-EMPTY:
