// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

type Price is uint128;

function wrap_price(uint128 x) pure returns (Price) {
  return Price.wrap(x);
}

function unwrap_price(Price p) pure returns (uint128) {
  return Price.unwrap(p);
}

using {add as +} for Price global;

function add(Price a, Price b) pure returns (Price) {
  return Price.wrap(Price.unwrap(a) + Price.unwrap(b));
}

function use_operator(Price a, Price b) pure returns (Price) {
  return a + b;
}

// NOTE: Assertions have been autogenerated
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #Pure = #sol<StateMutability Pure>
// CHECK-NEXT: #loc2 = loc({{.*}}:4:20)
// CHECK-NEXT: #loc6 = loc({{.*}}:8:22)
// CHECK-NEXT: #loc10 = loc({{.*}}:14:13)
// CHECK-NEXT: #loc11 = loc({{.*}}:14:22)
// CHECK-NEXT: #loc17 = loc({{.*}}:18:22)
// CHECK-NEXT: #loc18 = loc({{.*}}:18:31)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   sol.func @wrap_price_16(%arg0: ui128 loc({{.*}}:4:20)) -> ui128 attributes {id = 16 : i64, state_mutability = #Pure} {
// CHECK-NEXT:     %0 = sol.alloca : !sol.ptr<ui128, Stack> loc(#loc2)
// CHECK-NEXT:     sol.store %arg0, %0 : ui128, !sol.ptr<ui128, Stack> loc(#loc2)
// CHECK-NEXT:     %1 = sol.load %0 : !sol.ptr<ui128, Stack>, ui128 loc(#loc3)
// CHECK-NEXT:     sol.return %1 : ui128 loc(#loc4)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   sol.func @unwrap_price_30(%arg0: ui128 loc({{.*}}:8:22)) -> ui128 attributes {id = 30 : i64, state_mutability = #Pure} {
// CHECK-NEXT:     %0 = sol.alloca : !sol.ptr<ui128, Stack> loc(#loc6)
// CHECK-NEXT:     sol.store %arg0, %0 : ui128, !sol.ptr<ui128, Stack> loc(#loc6)
// CHECK-NEXT:     %1 = sol.load %0 : !sol.ptr<ui128, Stack>, ui128 loc(#loc7)
// CHECK-NEXT:     sol.return %1 : ui128 loc(#loc8)
// CHECK-NEXT:   } loc(#loc5)
// CHECK-NEXT:   sol.func @add_60(%arg0: ui128 loc({{.*}}:14:13), %arg1: ui128 loc({{.*}}:14:22)) -> ui128 attributes {id = 60 : i64, state_mutability = #Pure} {
// CHECK-NEXT:     %0 = sol.alloca : !sol.ptr<ui128, Stack> loc(#loc10)
// CHECK-NEXT:     sol.store %arg0, %0 : ui128, !sol.ptr<ui128, Stack> loc(#loc10)
// CHECK-NEXT:     %1 = sol.alloca : !sol.ptr<ui128, Stack> loc(#loc11)
// CHECK-NEXT:     sol.store %arg1, %1 : ui128, !sol.ptr<ui128, Stack> loc(#loc11)
// CHECK-NEXT:     %2 = sol.load %0 : !sol.ptr<ui128, Stack>, ui128 loc(#loc12)
// CHECK-NEXT:     %3 = sol.load %1 : !sol.ptr<ui128, Stack>, ui128 loc(#loc13)
// CHECK-NEXT:     %4 = sol.cadd %2, %3 : ui128 loc(#loc14)
// CHECK-NEXT:     sol.return %4 : ui128 loc(#loc15)
// CHECK-NEXT:   } loc(#loc9)
// CHECK-NEXT:   sol.func @use_operator_77(%arg0: ui128 loc({{.*}}:18:22), %arg1: ui128 loc({{.*}}:18:31)) -> ui128 attributes {id = 77 : i64, state_mutability = #Pure} {
// CHECK-NEXT:     %0 = sol.alloca : !sol.ptr<ui128, Stack> loc(#loc17)
// CHECK-NEXT:     sol.store %arg0, %0 : ui128, !sol.ptr<ui128, Stack> loc(#loc17)
// CHECK-NEXT:     %1 = sol.alloca : !sol.ptr<ui128, Stack> loc(#loc18)
// CHECK-NEXT:     sol.store %arg1, %1 : ui128, !sol.ptr<ui128, Stack> loc(#loc18)
// CHECK-NEXT:     %2 = sol.load %0 : !sol.ptr<ui128, Stack>, ui128 loc(#loc19)
// CHECK-NEXT:     %3 = sol.load %1 : !sol.ptr<ui128, Stack>, ui128 loc(#loc20)
// CHECK-NEXT:     %4 = sol.call @add_60(%2, %3) : (ui128, ui128) -> ui128 loc(#loc19)
// CHECK-NEXT:     sol.return %4 : ui128 loc(#loc21)
// CHECK-NEXT:   } loc(#loc16)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:4:0)
// CHECK-NEXT: #loc3 = loc({{.*}}:5:20)
// CHECK-NEXT: #loc4 = loc({{.*}}:5:2)
// CHECK-NEXT: #loc5 = loc({{.*}}:8:0)
// CHECK-NEXT: #loc7 = loc({{.*}}:9:22)
// CHECK-NEXT: #loc8 = loc({{.*}}:9:2)
// CHECK-NEXT: #loc9 = loc({{.*}}:14:0)
// CHECK-NEXT: #loc12 = loc({{.*}}:15:33)
// CHECK-NEXT: #loc13 = loc({{.*}}:15:51)
// CHECK-NEXT: #loc14 = loc({{.*}}:15:20)
// CHECK-NEXT: #loc15 = loc({{.*}}:15:2)
// CHECK-NEXT: #loc16 = loc({{.*}}:18:0)
// CHECK-NEXT: #loc19 = loc({{.*}}:19:9)
// CHECK-NEXT: #loc20 = loc({{.*}}:19:13)
// CHECK-NEXT: #loc21 = loc({{.*}}:19:2)
// CHECK-EMPTY:
