// RUN: sol-opt -sol-licm %s | FileCheck %s

module {

sol.func @f(%a: !sol.ptr<ui256, Storage>) {
  %c0 = sol.constant 0 : ui256
  %c1 = arith.constant 1 : index
  %c5 = arith.constant 5 : index
  scf.for %i = %c1 to %c5 step %c1 {
    %a.ld = sol.load %a : !sol.ptr<ui256, Storage>, ui256
  }
  scf.for %i = %c5 to %c5 step %c1 {
    %a.ld = sol.load %a : !sol.ptr<ui256, Storage>, ui256
  }
  scf.for %i = %c1 to %c5 step %c1 {
    %a.ld = sol.load %a : !sol.ptr<ui256, Storage>, ui256
    sol.store %c0, %a : ui256, !sol.ptr<ui256, Storage>
  }
  sol.return
}

}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   sol.func @f(%arg0: !sol.ptr<ui256, Storage>) {
// CHECK-NEXT:     %c0_ui256 = sol.constant 0 : ui256
// CHECK-NEXT:     %c1 = arith.constant 1 : index
// CHECK-NEXT:     %c5 = arith.constant 5 : index
// CHECK-NEXT:     %0 = sol.load %arg0 : !sol.ptr<ui256, Storage>, ui256
// CHECK-NEXT:     scf.for %arg1 = %c1 to %c5 step %c1 {
// CHECK-NEXT:     }
// CHECK-NEXT:     scf.for %arg1 = %c5 to %c5 step %c1 {
// CHECK-NEXT:       %1 = sol.load %arg0 : !sol.ptr<ui256, Storage>, ui256
// CHECK-NEXT:     }
// CHECK-NEXT:     scf.for %arg1 = %c1 to %c5 step %c1 {
// CHECK-NEXT:       %1 = sol.load %arg0 : !sol.ptr<ui256, Storage>, ui256
// CHECK-NEXT:       sol.store %c0_ui256, %arg0 : ui256, !sol.ptr<ui256, Storage>
// CHECK-NEXT:     }
// CHECK-NEXT:     sol.return
// CHECK-NEXT:   }
// CHECK-NEXT: }
// CHECK-EMPTY:
// CHECK-EMPTY:
