// RUN: solc --mlir-action=print-std-mlir --mlir-target=evm --mmlir --mlir-print-debuginfo %s | FileCheck %s

pragma solidity ^0.8.0;

enum Direction { North, South, East, West }

struct Inner {
    uint256 x;
    bool[][] flags;
}

struct C {
    uint8   a;
    uint72[2] c72;
    bytes19 b;
    bytes17[3] c;
    string  d;
    uint256[] e;
    uint256 f;
    bool    flag;
    Direction direction;
    Inner   inner;
    address[2] fixedAddrArr;
    function(uint256) external fn_uint;
}

contract ClearTest {
    C[] arr;

    function pop() public { arr.pop(); }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #loc3 = loc({{.*}}:29:28)
// CHECK-NEXT: module @ClearTest_65 attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:     %c65_i256 = arith.constant 65 : i256 loc(#loc)
// CHECK-NEXT:     %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:     %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:     %c18446744073709551615_i256 = arith.constant 18446744073709551615 : i256 loc(#loc)
// CHECK-NEXT:     %c-32_i256 = arith.constant -32 : i256 loc(#loc)
// CHECK-NEXT:     %c31_i256 = arith.constant 31 : i256 loc(#loc)
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:     %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %1 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %2 = arith.cmpi ne, %1, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:     cf.cond_br %2, ^bb1, ^bb2 loc(#loc1)
// CHECK-NEXT:   ^bb1:  // pred: ^bb0
// CHECK-NEXT:     %3 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%3, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     cf.br ^bb2 loc(#loc1)
// CHECK-NEXT:   ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:     %4 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["ClearTest_65"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %5 = "llvm.intrcall"() <{id = 4042 : i32, name = "evm.codesize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %6 = arith.subi %5, %4 : i256 loc(#loc1)
// CHECK-NEXT:     %7 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %8 = llvm.load %7 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %9 = arith.addi %6, %c31_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %10 = arith.andi %9, %c-32_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %11 = arith.addi %8, %10 : i256 loc(#loc1)
// CHECK-NEXT:     %12 = arith.cmpi ugt, %11, %c18446744073709551615_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %13 = arith.cmpi ult, %11, %8 : i256 loc(#loc1)
// CHECK-NEXT:     %14 = arith.ori %12, %13 : i1 loc(#loc1)
// CHECK-NEXT:     cf.cond_br %14, ^bb3, ^bb4 loc(#loc1)
// CHECK-NEXT:   ^bb3:  // pred: ^bb2
// CHECK-NEXT:     %15 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %15 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %16 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c65_i256, %16 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %17 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%17, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     cf.br ^bb4 loc(#loc1)
// CHECK-NEXT:   ^bb4:  // 2 preds: ^bb2, ^bb3
// CHECK-NEXT:     %18 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %11, %18 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %19 = llvm.inttoptr %8 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %20 = llvm.inttoptr %4 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%19, %20, %6) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @ClearTest_65() : () -> () loc(#loc1)
// CHECK-NEXT:     %21 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %22 = llvm.load %21 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %23 = "llvm.intrcall"() <{id = 4046 : i32, metadata = ["ClearTest_65_deployed"], name = "evm.dataoffset"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %24 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["ClearTest_65_deployed"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %25 = llvm.inttoptr %22 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %26 = llvm.inttoptr %23 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%25, %26, %24) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     %27 = llvm.inttoptr %22 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%27, %24) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @ClearTest_65() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     return loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   module @ClearTest_65_deployed attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:     func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c224_i256 = arith.constant 224 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:       %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:       %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %1 = "llvm.intrcall"() <{id = 4038 : i32, name = "evm.calldatasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %2 = arith.cmpi uge, %1, %c4_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %2, ^bb1, ^bb5 loc(#loc1)
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %3 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<2> loc(#loc1)
// CHECK-NEXT:       %4 = llvm.load %3 {alignment = 1 : i64} : !llvm.ptr<2> -> i256 loc(#loc1)
// CHECK-NEXT:       %5 = arith.shrui %4, %c224_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.switch %5 : i256, [
// CHECK-NEXT:         default: ^bb5,
// CHECK-NEXT:         2766988588: ^bb2
// CHECK-NEXT:       ] loc(#loc1)
// CHECK-NEXT:     ^bb2:  // pred: ^bb1
// CHECK-NEXT:       %6 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %7 = arith.cmpi ne, %6, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %7, ^bb3, ^bb4 loc(#loc1)
// CHECK-NEXT:     ^bb3:  // pred: ^bb2
// CHECK-NEXT:       %8 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%8, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb4 loc(#loc1)
// CHECK-NEXT:     ^bb4:  // 2 preds: ^bb2, ^bb3
// CHECK-NEXT:       call @pop_64() : () -> () loc(#loc1)
// CHECK-NEXT:       %9 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %10 = llvm.load %9 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %11 = llvm.inttoptr %10 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%11, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb5 loc(#loc1)
// CHECK-NEXT:     ^bb5:  // 3 preds: ^bb0, ^bb1, ^bb4
// CHECK-NEXT:       %12 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%12, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @pop_64() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c13_i256 = arith.constant 13 : i256 loc(#loc)
// CHECK-NEXT:       %c11_i256 = arith.constant 11 : i256 loc(#loc)
// CHECK-NEXT:       %c5_i256 = arith.constant 5 : i256 loc(#loc)
// CHECK-NEXT:       %c14_i256 = arith.constant 14 : i256 loc(#loc)
// CHECK-NEXT:       %c12_i256 = arith.constant 12 : i256 loc(#loc)
// CHECK-NEXT:       %c10_i256 = arith.constant 10 : i256 loc(#loc)
// CHECK-NEXT:       %c9_i256 = arith.constant 9 : i256 loc(#loc)
// CHECK-NEXT:       %c8_i256 = arith.constant 8 : i256 loc(#loc)
// CHECK-NEXT:       %c7_i256 = arith.constant 7 : i256 loc(#loc)
// CHECK-NEXT:       %c31_i256 = arith.constant 31 : i256 loc(#loc)
// CHECK-NEXT:       %c34_i256 = arith.constant 34 : i256 loc(#loc)
// CHECK-NEXT:       %c127_i256 = arith.constant 127 : i256 loc(#loc)
// CHECK-NEXT:       %c6_i256 = arith.constant 6 : i256 loc(#loc)
// CHECK-NEXT:       %c3_i256 = arith.constant 3 : i256 loc(#loc)
// CHECK-NEXT:       %c2_i256 = arith.constant 2 : i256 loc(#loc)
// CHECK-NEXT:       %c15_i256 = arith.constant 15 : i256 loc(#loc)
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:       %c49_i256 = arith.constant 49 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:       %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc3)
// CHECK-NEXT:       %2 = arith.cmpi eq, %1, %c0_i256 : i256 loc(#loc3)
// CHECK-NEXT:       cf.cond_br %2, ^bb1, ^bb2 loc(#loc3)
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %3 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %3 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       %4 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       llvm.store %c49_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       %5 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       "llvm.intrcall"(%5, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc3)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc3)
// CHECK-NEXT:       cf.br ^bb2 loc(#loc3)
// CHECK-NEXT:     ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:       %6 = arith.subi %1, %c1_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %7 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %7 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       %8 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       %9 = "llvm.intrcall"(%8, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc3)
// CHECK-NEXT:       %10 = arith.muli %6, %c15_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %11 = arith.addi %9, %10 : i256 loc(#loc3)
// CHECK-NEXT:       %12 = llvm.inttoptr %11 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %12 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %13 = arith.addi %11, %c1_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %14 = llvm.inttoptr %13 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %14 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %15 = arith.addi %11, %c2_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %16 = llvm.inttoptr %15 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %16 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %17 = arith.addi %11, %c3_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %18 = llvm.inttoptr %17 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %18 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %19 = arith.addi %11, %c4_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %20 = llvm.inttoptr %19 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %20 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %21 = arith.addi %11, %c5_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %22 = llvm.inttoptr %21 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %22 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %23 = arith.addi %11, %c6_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %24 = llvm.inttoptr %23 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %25 = llvm.load %24 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc3)
// CHECK-NEXT:       %26 = arith.shrui %25, %c1_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %27 = arith.andi %25, %c1_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %28 = arith.cmpi eq, %27, %c0_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %29 = arith.andi %26, %c127_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %30 = arith.select %28, %29, %26 : i256 loc(#loc3)
// CHECK-NEXT:       %31 = arith.cmpi ult, %30, %c32_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %32 = arith.extui %31 : i1 to i256 loc(#loc3)
// CHECK-NEXT:       %33 = arith.cmpi eq, %27, %32 : i256 loc(#loc3)
// CHECK-NEXT:       cf.cond_br %33, ^bb3, ^bb4 loc(#loc3)
// CHECK-NEXT:     ^bb3:  // pred: ^bb2
// CHECK-NEXT:       %34 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %34 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       %35 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       llvm.store %c34_i256, %35 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       %36 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       "llvm.intrcall"(%36, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc3)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc3)
// CHECK-NEXT:       cf.br ^bb4 loc(#loc3)
// CHECK-NEXT:     ^bb4:  // 2 preds: ^bb2, ^bb3
// CHECK-NEXT:       %37 = arith.cmpi ugt, %30, %c31_i256 : i256 loc(#loc3)
// CHECK-NEXT:       cf.cond_br %37, ^bb5, ^bb8 loc(#loc3)
// CHECK-NEXT:     ^bb5:  // pred: ^bb4
// CHECK-NEXT:       %38 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       llvm.store %23, %38 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       %39 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       %40 = "llvm.intrcall"(%39, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc3)
// CHECK-NEXT:       %41 = arith.addi %30, %c31_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %42 = arith.divui %41, %c32_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %43 = arith.addi %40, %42 : i256 loc(#loc3)
// CHECK-NEXT:       cf.br ^bb6(%40 : i256) loc(#loc3)
// CHECK-NEXT:     ^bb6(%44: i256 loc({{.*}}:29:28)):  // 2 preds: ^bb5, ^bb7
// CHECK-NEXT:       %45 = arith.cmpi ult, %44, %43 : i256 loc(#loc3)
// CHECK-NEXT:       cf.cond_br %45, ^bb7(%44 : i256), ^bb8 loc(#loc3)
// CHECK-NEXT:     ^bb7(%46: i256 loc({{.*}}:29:28)):  // pred: ^bb6
// CHECK-NEXT:       %47 = llvm.inttoptr %46 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %47 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %48 = arith.addi %46, %c1_i256 : i256 loc(#loc3)
// CHECK-NEXT:       cf.br ^bb6(%48 : i256) loc(#loc3)
// CHECK-NEXT:     ^bb8:  // 2 preds: ^bb4, ^bb6
// CHECK-NEXT:       %49 = llvm.inttoptr %23 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %49 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %50 = arith.addi %11, %c7_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %51 = llvm.inttoptr %50 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %52 = llvm.load %51 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc3)
// CHECK-NEXT:       %53 = llvm.inttoptr %50 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %53 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %54 = arith.cmpi ugt, %52, %c0_i256 : i256 loc(#loc3)
// CHECK-NEXT:       cf.cond_br %54, ^bb9, ^bb12 loc(#loc3)
// CHECK-NEXT:     ^bb9:  // pred: ^bb8
// CHECK-NEXT:       %55 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       llvm.store %50, %55 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       %56 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       %57 = "llvm.intrcall"(%56, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc3)
// CHECK-NEXT:       cf.br ^bb10(%c0_i256 : i256) loc(#loc3)
// CHECK-NEXT:     ^bb10(%58: i256 loc({{.*}}:29:28)):  // 2 preds: ^bb9, ^bb11
// CHECK-NEXT:       %59 = arith.cmpi ult, %58, %52 : i256 loc(#loc3)
// CHECK-NEXT:       cf.cond_br %59, ^bb11(%58 : i256), ^bb12 loc(#loc3)
// CHECK-NEXT:     ^bb11(%60: i256 loc({{.*}}:29:28)):  // pred: ^bb10
// CHECK-NEXT:       %61 = arith.addi %57, %60 : i256 loc(#loc3)
// CHECK-NEXT:       %62 = llvm.inttoptr %61 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %62 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %63 = arith.addi %60, %c1_i256 : i256 loc(#loc3)
// CHECK-NEXT:       cf.br ^bb10(%63 : i256) loc(#loc3)
// CHECK-NEXT:     ^bb12:  // 2 preds: ^bb8, ^bb10
// CHECK-NEXT:       %64 = arith.addi %11, %c8_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %65 = llvm.inttoptr %64 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %65 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %66 = arith.addi %11, %c9_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %67 = llvm.inttoptr %66 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %67 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %68 = arith.addi %11, %c10_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %69 = llvm.inttoptr %68 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %69 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %70 = arith.addi %11, %c11_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %71 = llvm.inttoptr %70 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %72 = llvm.load %71 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc3)
// CHECK-NEXT:       %73 = llvm.inttoptr %70 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %73 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %74 = arith.cmpi ugt, %72, %c0_i256 : i256 loc(#loc3)
// CHECK-NEXT:       cf.cond_br %74, ^bb13, ^bb20 loc(#loc3)
// CHECK-NEXT:     ^bb13:  // pred: ^bb12
// CHECK-NEXT:       %75 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       llvm.store %70, %75 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       %76 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       %77 = "llvm.intrcall"(%76, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc3)
// CHECK-NEXT:       cf.br ^bb14(%c0_i256 : i256) loc(#loc3)
// CHECK-NEXT:     ^bb14(%78: i256 loc({{.*}}:29:28)):  // 2 preds: ^bb13, ^bb19
// CHECK-NEXT:       %79 = arith.cmpi ult, %78, %72 : i256 loc(#loc3)
// CHECK-NEXT:       cf.cond_br %79, ^bb15(%78 : i256), ^bb20 loc(#loc3)
// CHECK-NEXT:     ^bb15(%80: i256 loc({{.*}}:29:28)):  // pred: ^bb14
// CHECK-NEXT:       %81 = arith.addi %77, %80 : i256 loc(#loc3)
// CHECK-NEXT:       %82 = llvm.inttoptr %81 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %83 = llvm.load %82 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc3)
// CHECK-NEXT:       %84 = llvm.inttoptr %81 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %84 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %85 = arith.cmpi ugt, %83, %c0_i256 : i256 loc(#loc3)
// CHECK-NEXT:       cf.cond_br %85, ^bb16, ^bb19(%80 : i256) loc(#loc3)
// CHECK-NEXT:     ^bb16:  // pred: ^bb15
// CHECK-NEXT:       %86 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       llvm.store %81, %86 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       %87 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:       %88 = "llvm.intrcall"(%87, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc3)
// CHECK-NEXT:       %89 = arith.addi %83, %c31_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %90 = arith.divui %89, %c32_i256 : i256 loc(#loc3)
// CHECK-NEXT:       cf.br ^bb17(%c0_i256 : i256) loc(#loc3)
// CHECK-NEXT:     ^bb17(%91: i256 loc({{.*}}:29:28)):  // 2 preds: ^bb16, ^bb18
// CHECK-NEXT:       %92 = arith.cmpi ult, %91, %90 : i256 loc(#loc3)
// CHECK-NEXT:       cf.cond_br %92, ^bb18(%91 : i256), ^bb19(%80 : i256) loc(#loc3)
// CHECK-NEXT:     ^bb18(%93: i256 loc({{.*}}:29:28)):  // pred: ^bb17
// CHECK-NEXT:       %94 = arith.addi %88, %93 : i256 loc(#loc3)
// CHECK-NEXT:       %95 = llvm.inttoptr %94 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %95 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %96 = arith.addi %93, %c1_i256 : i256 loc(#loc3)
// CHECK-NEXT:       cf.br ^bb17(%96 : i256) loc(#loc3)
// CHECK-NEXT:     ^bb19(%97: i256 loc({{.*}}:29:28)):  // 2 preds: ^bb15, ^bb17
// CHECK-NEXT:       %98 = arith.addi %97, %c1_i256 : i256 loc(#loc3)
// CHECK-NEXT:       cf.br ^bb14(%98 : i256) loc(#loc3)
// CHECK-NEXT:     ^bb20:  // 2 preds: ^bb12, ^bb14
// CHECK-NEXT:       %99 = arith.addi %11, %c12_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %100 = llvm.inttoptr %99 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %100 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %101 = arith.addi %11, %c13_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %102 = llvm.inttoptr %101 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %102 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %103 = arith.addi %11, %c14_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %104 = llvm.inttoptr %103 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %104 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %105 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       llvm.store %6, %105 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       return loc(#loc2)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:26:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:29:4)
// CHECK-EMPTY:
