// RUN: solc --mlir-action=print-std-mlir --mlir-target=evm --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
  function b1() public returns (bytes1) {
    bytes1 x = "a";
    return x;
  }

  function b4Short() public returns (bytes4) {
    bytes4 x = "ab";
    return x;
  }

  function b4Full() public returns (bytes4) {
    bytes4 x = "wxyz";
    return x;
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module @C_37 attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:     %c65_i256 = arith.constant 65 : i256 loc(#loc)
// CHECK-NEXT:     %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:     %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:     %c18446744073709551615_i256 = arith.constant 18446744073709551615 : i256 loc(#loc)
// CHECK-NEXT:     %c-32_i256 = arith.constant -32 : i256 loc(#loc)
// CHECK-NEXT:     %c31_i256 = arith.constant 31 : i256 loc(#loc)
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %0 = "llvm.intrcall"() <{id = 4070 : i32, name = "evm.memoryguard"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %1 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %0, %1 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %2 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %3 = arith.cmpi ne, %2, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:     cf.cond_br %3, ^bb1, ^bb2 loc(#loc1)
// CHECK-NEXT:   ^bb1:  // pred: ^bb0
// CHECK-NEXT:     %4 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%4, %c0_i256) <{id = 4081 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     cf.br ^bb2 loc(#loc1)
// CHECK-NEXT:   ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:     %5 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["C_37"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %6 = "llvm.intrcall"() <{id = 4042 : i32, name = "evm.codesize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %7 = arith.subi %6, %5 : i256 loc(#loc1)
// CHECK-NEXT:     %8 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %9 = llvm.load %8 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %10 = arith.addi %7, %c31_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %11 = arith.andi %10, %c-32_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %12 = arith.addi %9, %11 : i256 loc(#loc1)
// CHECK-NEXT:     %13 = arith.cmpi ugt, %12, %c18446744073709551615_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %14 = arith.cmpi ult, %12, %9 : i256 loc(#loc1)
// CHECK-NEXT:     %15 = arith.ori %13, %14 : i1 loc(#loc1)
// CHECK-NEXT:     cf.cond_br %15, ^bb3, ^bb4 loc(#loc1)
// CHECK-NEXT:   ^bb3:  // pred: ^bb2
// CHECK-NEXT:     %16 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %16 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %17 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c65_i256, %17 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %18 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%18, %c36_i256) <{id = 4081 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     cf.br ^bb4 loc(#loc1)
// CHECK-NEXT:   ^bb4:  // 2 preds: ^bb2, ^bb3
// CHECK-NEXT:     %19 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %12, %19 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %20 = llvm.inttoptr %9 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %21 = llvm.inttoptr %5 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%20, %21, %7) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @C_37() : () -> () loc(#loc1)
// CHECK-NEXT:     %22 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %23 = llvm.load %22 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %24 = "llvm.intrcall"() <{id = 4046 : i32, metadata = ["C_37_deployed"], name = "evm.dataoffset"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %25 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["C_37_deployed"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %26 = llvm.inttoptr %23 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %27 = llvm.inttoptr %24 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%26, %27, %25) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     %28 = llvm.inttoptr %23 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%28, %25) <{id = 4079 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @C_37() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     return loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   module @C_37_deployed attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:     func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c-26959946667150639794667015087019630673637144422540572481103610249216_i256 = arith.constant -26959946667150639794667015087019630673637144422540572481103610249216 : i256 loc(#loc)
// CHECK-NEXT:       %c-452312848583266388373324160190187140051835877600158453279131187530910662656_i256 = arith.constant -452312848583266388373324160190187140051835877600158453279131187530910662656 : i256 loc(#loc)
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:       %c224_i256 = arith.constant 224 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:       %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:       %0 = "llvm.intrcall"() <{id = 4070 : i32, name = "evm.memoryguard"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %1 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %0, %1 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %2 = "llvm.intrcall"() <{id = 4038 : i32, name = "evm.calldatasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %3 = arith.cmpi uge, %2, %c4_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %3, ^bb1, ^bb11 loc(#loc1)
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %4 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<2> loc(#loc1)
// CHECK-NEXT:       %5 = llvm.load %4 {alignment = 1 : i64} : !llvm.ptr<2> -> i256 loc(#loc1)
// CHECK-NEXT:       %6 = arith.shrui %5, %c224_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.switch %6 : i256, [
// CHECK-NEXT:         default: ^bb11,
// CHECK-NEXT:         3997782018: ^bb2,
// CHECK-NEXT:         1123875165: ^bb5,
// CHECK-NEXT:         1360033110: ^bb8
// CHECK-NEXT:       ] loc(#loc1)
// CHECK-NEXT:     ^bb2:  // pred: ^bb1
// CHECK-NEXT:       %7 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %8 = arith.cmpi ne, %7, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %8, ^bb3, ^bb4 loc(#loc1)
// CHECK-NEXT:     ^bb3:  // pred: ^bb2
// CHECK-NEXT:       %9 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%9, %c0_i256) <{id = 4081 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb4 loc(#loc1)
// CHECK-NEXT:     ^bb4:  // 2 preds: ^bb2, ^bb3
// CHECK-NEXT:       %10 = call @b1_12() : () -> i256 loc(#loc1)
// CHECK-NEXT:       %11 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %12 = llvm.load %11 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %13 = arith.andi %10, %c-452312848583266388373324160190187140051835877600158453279131187530910662656_i256 : i256 loc(#loc1)
// CHECK-NEXT:       %14 = llvm.inttoptr %12 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %13, %14 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %15 = llvm.inttoptr %12 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%15, %c32_i256) <{id = 4079 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb11 loc(#loc1)
// CHECK-NEXT:     ^bb5:  // pred: ^bb1
// CHECK-NEXT:       %16 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %17 = arith.cmpi ne, %16, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %17, ^bb6, ^bb7 loc(#loc1)
// CHECK-NEXT:     ^bb6:  // pred: ^bb5
// CHECK-NEXT:       %18 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%18, %c0_i256) <{id = 4081 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb7 loc(#loc1)
// CHECK-NEXT:     ^bb7:  // 2 preds: ^bb5, ^bb6
// CHECK-NEXT:       %19 = call @b4Short_24() : () -> i256 loc(#loc1)
// CHECK-NEXT:       %20 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %21 = llvm.load %20 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %22 = arith.andi %19, %c-26959946667150639794667015087019630673637144422540572481103610249216_i256 : i256 loc(#loc1)
// CHECK-NEXT:       %23 = llvm.inttoptr %21 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %22, %23 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %24 = llvm.inttoptr %21 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%24, %c32_i256) <{id = 4079 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb11 loc(#loc1)
// CHECK-NEXT:     ^bb8:  // pred: ^bb1
// CHECK-NEXT:       %25 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %26 = arith.cmpi ne, %25, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %26, ^bb9, ^bb10 loc(#loc1)
// CHECK-NEXT:     ^bb9:  // pred: ^bb8
// CHECK-NEXT:       %27 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%27, %c0_i256) <{id = 4081 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb10 loc(#loc1)
// CHECK-NEXT:     ^bb10:  // 2 preds: ^bb8, ^bb9
// CHECK-NEXT:       %28 = call @b4Full_36() : () -> i256 loc(#loc1)
// CHECK-NEXT:       %29 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %30 = llvm.load %29 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %31 = arith.andi %28, %c-26959946667150639794667015087019630673637144422540572481103610249216_i256 : i256 loc(#loc1)
// CHECK-NEXT:       %32 = llvm.inttoptr %30 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %31, %32 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %33 = llvm.inttoptr %30 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%33, %c32_i256) <{id = 4079 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb11 loc(#loc1)
// CHECK-NEXT:     ^bb11:  // 5 preds: ^bb0, ^bb1, ^bb4, ^bb7, ^bb10
// CHECK-NEXT:       %34 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%34, %c0_i256) <{id = 4081 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @b4Full_36() -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c54038089029603561386571905317556596024542456269961182381914221420405013348352_i256 = arith.constant 54038089029603561386571905317556596024542456269961182381914221420405013348352 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc3)
// CHECK-NEXT:       %1 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc4)
// CHECK-NEXT:       llvm.store %c54038089029603561386571905317556596024542456269961182381914221420405013348352_i256, %1 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc4)
// CHECK-NEXT:       %2 = llvm.load %1 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc5)
// CHECK-NEXT:       return %2 : i256 loc(#loc6)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     func.func @b4Short_24() -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c44047497324925121336511606693520958599579173549109180625971642598225011015680_i256 = arith.constant 44047497324925121336511606693520958599579173549109180625971642598225011015680 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc8)
// CHECK-NEXT:       llvm.store %c0_i256, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc8)
// CHECK-NEXT:       %1 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc9)
// CHECK-NEXT:       llvm.store %c44047497324925121336511606693520958599579173549109180625971642598225011015680_i256, %1 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc9)
// CHECK-NEXT:       %2 = llvm.load %1 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc10)
// CHECK-NEXT:       return %2 : i256 loc(#loc11)
// CHECK-NEXT:     } loc(#loc7)
// CHECK-NEXT:     func.func @b1_12() -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c43874346312576839672212443538448152585028080127215369968075725190498334277632_i256 = arith.constant 43874346312576839672212443538448152585028080127215369968075725190498334277632 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc13)
// CHECK-NEXT:       llvm.store %c0_i256, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc13)
// CHECK-NEXT:       %1 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc14)
// CHECK-NEXT:       llvm.store %c43874346312576839672212443538448152585028080127215369968075725190498334277632_i256, %1 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc14)
// CHECK-NEXT:       %2 = llvm.load %1 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc15)
// CHECK-NEXT:       return %2 : i256 loc(#loc16)
// CHECK-NEXT:     } loc(#loc12)
// CHECK-NEXT:     llvm.module_flags [#llvm.mlir.module_flag<error, "evm-memory-guard", 128 : i64>, #llvm.mlir.module_flag<error, "evm-stack-region-size", 0 : i64>] loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   llvm.module_flags [#llvm.mlir.module_flag<error, "evm-memory-guard", 128 : i64>, #llvm.mlir.module_flag<error, "evm-stack-region-size", 0 : i64>] loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:13:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:13:36)
// CHECK-NEXT: #loc4 = loc({{.*}}:14:4)
// CHECK-NEXT: #loc5 = loc({{.*}}:15:11)
// CHECK-NEXT: #loc6 = loc({{.*}}:15:4)
// CHECK-NEXT: #loc7 = loc({{.*}}:8:2)
// CHECK-NEXT: #loc8 = loc({{.*}}:8:37)
// CHECK-NEXT: #loc9 = loc({{.*}}:9:4)
// CHECK-NEXT: #loc10 = loc({{.*}}:10:11)
// CHECK-NEXT: #loc11 = loc({{.*}}:10:4)
// CHECK-NEXT: #loc12 = loc({{.*}}:3:2)
// CHECK-NEXT: #loc13 = loc({{.*}}:3:32)
// CHECK-NEXT: #loc14 = loc({{.*}}:4:4)
// CHECK-NEXT: #loc15 = loc({{.*}}:5:11)
// CHECK-NEXT: #loc16 = loc({{.*}}:5:4)
// CHECK-EMPTY:
