// RUN: solc --mlir-action=print-std-mlir --mlir-target=evm --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract A {}

contract B is A {
  function b_to_a() external returns (A) {
    return A(this);
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module @A_1 attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka} {
// CHECK-NEXT:   func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:     %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %1 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %2 = arith.cmpi ne, %1, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:     scf.if %2 {
// CHECK-NEXT:       %19 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%19, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       func.call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     %3 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["A_1"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %4 = "llvm.intrcall"() <{id = 4042 : i32, name = "evm.codesize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %5 = arith.subi %4, %3 : i256 loc(#loc1)
// CHECK-NEXT:     %6 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %7 = llvm.load %6 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %8 = arith.addi %7, %5 : i256 loc(#loc1)
// CHECK-NEXT:     %9 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %8, %9 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %10 = llvm.inttoptr %7 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %11 = llvm.inttoptr %3 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%10, %11, %5) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @A_1() : () -> () loc(#loc1)
// CHECK-NEXT:     %12 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %13 = llvm.load %12 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %14 = "llvm.intrcall"() <{id = 4046 : i32, metadata = ["A_1_deployed"], name = "evm.dataoffset"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %15 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["A_1_deployed"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %16 = llvm.inttoptr %13 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %17 = llvm.inttoptr %14 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%16, %17, %15) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     %18 = llvm.inttoptr %13 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%18, %15) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @A_1() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     return loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   module @A_1_deployed attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka} {
// CHECK-NEXT:     func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:       %c64_i256 = arith.constant 64 : i256 loc(#loc1)
// CHECK-NEXT:       %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %1 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%1, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module @B_15 attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka} {
// CHECK-NEXT:   func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:     %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %1 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %2 = arith.cmpi ne, %1, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:     scf.if %2 {
// CHECK-NEXT:       %19 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%19, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       func.call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     %3 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["B_15"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %4 = "llvm.intrcall"() <{id = 4042 : i32, name = "evm.codesize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %5 = arith.subi %4, %3 : i256 loc(#loc1)
// CHECK-NEXT:     %6 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %7 = llvm.load %6 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %8 = arith.addi %7, %5 : i256 loc(#loc1)
// CHECK-NEXT:     %9 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %8, %9 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %10 = llvm.inttoptr %7 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %11 = llvm.inttoptr %3 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%10, %11, %5) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @B_15() : () -> () loc(#loc1)
// CHECK-NEXT:     %12 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %13 = llvm.load %12 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %14 = "llvm.intrcall"() <{id = 4046 : i32, metadata = ["B_15_deployed"], name = "evm.dataoffset"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %15 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["B_15_deployed"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %16 = llvm.inttoptr %13 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %17 = llvm.inttoptr %14 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%16, %17, %15) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     %18 = llvm.inttoptr %13 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%18, %15) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @B_15() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     return loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   module @B_15_deployed attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka} {
// CHECK-NEXT:     func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c1461501637330902918203684832716283019655932542975_i256 = arith.constant 1461501637330902918203684832716283019655932542975 : i256 loc(#loc)
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:       %c224_i256 = arith.constant 224 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:       %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:       %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %1 = "llvm.intrcall"() <{id = 4038 : i32, name = "evm.calldatasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %2 = arith.cmpi uge, %1, %c4_i256 : i256 loc(#loc1)
// CHECK-NEXT:       scf.if %2 {
// CHECK-NEXT:         %4 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<2> loc(#loc1)
// CHECK-NEXT:         %5 = llvm.load %4 {alignment = 1 : i64} : !llvm.ptr<2> -> i256 loc(#loc1)
// CHECK-NEXT:         %6 = arith.shrui %5, %c224_i256 : i256 loc(#loc1)
// CHECK-NEXT:         %7 = arith.trunci %6 : i256 to i32 loc(#loc1)
// CHECK-NEXT:         scf.int_switch %7 : i32
// CHECK-NEXT:         case -393463113 {
// CHECK-NEXT:           %8 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:           %9 = arith.cmpi ne, %8, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:           scf.if %9 {
// CHECK-NEXT:             %16 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:             "llvm.intrcall"(%16, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:             func.call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:           } loc(#loc1)
// CHECK-NEXT:           %10 = func.call @b_to_a_14() : () -> i256 loc(#loc1)
// CHECK-NEXT:           %11 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:           %12 = llvm.load %11 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:           %13 = arith.andi %10, %c1461501637330902918203684832716283019655932542975_i256 : i256 loc(#loc1)
// CHECK-NEXT:           %14 = llvm.inttoptr %12 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:           llvm.store %13, %14 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:           %15 = llvm.inttoptr %12 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:           "llvm.intrcall"(%15, %c32_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:           func.call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:           scf.yield loc(#loc1)
// CHECK-NEXT:         }
// CHECK-NEXT:         default {
// CHECK-NEXT:           scf.yield loc(#loc1)
// CHECK-NEXT:         } loc(#loc1)
// CHECK-NEXT:       } loc(#loc1)
// CHECK-NEXT:       %3 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%3, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @b_to_a_14() -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c1461501637330902918203684832716283019655932542975_i256 = arith.constant 1461501637330902918203684832716283019655932542975 : i256 loc(#loc)
// CHECK-NEXT:       %0 = "llvm.intrcall"() <{id = 4028 : i32, name = "evm.address"}> : () -> i256 loc(#loc3)
// CHECK-NEXT:       %1 = arith.andi %0, %c1461501637330902918203684832716283019655932542975_i256 : i256 loc(#loc3)
// CHECK-NEXT:       return %1 : i256 loc(#loc4)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:4:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:5:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:6:13)
// CHECK-NEXT: #loc4 = loc({{.*}}:6:4)
// CHECK-EMPTY:
