// RUN: solc --mlir-action=print-std-mlir --mlir-target=evm --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
  uint m;
  constructor(uint a) {
    m = a;
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Cancun = #sol<EvmVersion Cancun>
// CHECK-NEXT: #Constructor = #sol<FunctionKind Constructor>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: module @C_13 attributes {sol.evm_version = #Cancun} {
// CHECK-NEXT:   func.func private @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func private @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c32_i256 = arith.constant 32 : i256 loc(#loc1)
// CHECK-NEXT:     %c24_i256 = arith.constant 24 : i256 loc(#loc1)
// CHECK-NEXT:     %c65_i256 = arith.constant 65 : i256 loc(#loc1)
// CHECK-NEXT:     %c4_i256 = arith.constant 4 : i256 loc(#loc1)
// CHECK-NEXT:     %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc1)
// CHECK-NEXT:     %c18446744073709551615_i256 = arith.constant 18446744073709551615 : i256 loc(#loc1)
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc1)
// CHECK-NEXT:     %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc1)
// CHECK-NEXT:     %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %1 = "llvm.intrcall"() <{id = 3216 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %2 = arith.cmpi ne, %1, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:     scf.if %2 {
// CHECK-NEXT:       %25 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%25, %c0_i256) <{id = 3254 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       func.call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     %3 = "llvm.intrcall"() <{id = 3223 : i32, metadata = ["C_13"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %4 = "llvm.intrcall"() <{id = 3218 : i32, name = "evm.codesize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %5 = arith.subi %4, %3 : i256 loc(#loc1)
// CHECK-NEXT:     %6 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %7 = llvm.load %6 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %8 = arith.addi %7, %5 : i256 loc(#loc1)
// CHECK-NEXT:     %9 = arith.cmpi ugt, %8, %c18446744073709551615_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %10 = arith.cmpi ult, %8, %7 : i256 loc(#loc1)
// CHECK-NEXT:     %11 = arith.ori %9, %10 : i1 loc(#loc1)
// CHECK-NEXT:     scf.if %11 {
// CHECK-NEXT:       %25 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %25 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %26 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %c65_i256, %26 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %27 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%27, %c24_i256) <{id = 3254 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       func.call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     %12 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %8, %12 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %13 = llvm.inttoptr %7 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %14 = llvm.inttoptr %3 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%13, %14, %5) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     %15 = arith.cmpi slt, %5, %c32_i256 : i256 loc(#loc1)
// CHECK-NEXT:     scf.if %15 {
// CHECK-NEXT:       %25 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%25, %c0_i256) <{id = 3254 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       func.call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     %16 = llvm.inttoptr %7 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %17 = llvm.load %16 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     call @_12(%17) : (i256) -> () loc(#loc1)
// CHECK-NEXT:     %18 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %19 = llvm.load %18 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %20 = "llvm.intrcall"() <{id = 3222 : i32, metadata = ["C_13_deployed"], name = "evm.dataoffset"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %21 = "llvm.intrcall"() <{id = 3223 : i32, metadata = ["C_13_deployed"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %22 = llvm.inttoptr %19 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %23 = llvm.inttoptr %20 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%22, %23, %21) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     %24 = llvm.inttoptr %19 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%24, %21) <{id = 3252 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @_12(%arg0: i256 loc(unknown)) attributes {kind = #Constructor, llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"], state_mutability = #NonPayable} {
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc3)
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc4)
// CHECK-NEXT:     %0 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr<i256> loc(#loc4)
// CHECK-NEXT:     llvm.store %arg0, %0 {alignment = 32 : i64} : !llvm.ptr<i256> loc(#loc4)
// CHECK-NEXT:     %1 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr<i256> loc(#loc5)
// CHECK-NEXT:     %2 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<5> loc(#loc6)
// CHECK-NEXT:     llvm.store %1, %2 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc6)
// CHECK-NEXT:     return loc(#loc2)
// CHECK-NEXT:   } loc(#loc2)
// CHECK-NEXT:   module @C_13_deployed {
// CHECK-NEXT:     func.func private @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func private @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc1)
// CHECK-NEXT:       %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:       %c64_i256 = arith.constant 64 : i256 loc(#loc1)
// CHECK-NEXT:       %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %1 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%1, %c0_i256) <{id = 3254 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:3:2)
// CHECK-NEXT: #loc4 = loc({{.*}}:4:14)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:8)
// CHECK-NEXT: #loc6 = loc({{.*}}:5:4)
// CHECK-EMPTY:
