// RUN: solc --mlir-action=print-std-mlir --mlir-target=evm --mmlir --mlir-print-debuginfo %s | FileCheck %s

uint256 constant BASE = 50;

contract A {
  uint256 a;
}

contract C is A layout at BASE * 2 {
  uint8 b;
  uint8 c;
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module @A_6 attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:     %c65_i256 = arith.constant 65 : i256 loc(#loc)
// CHECK-NEXT:     %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:     %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:     %c18446744073709551615_i256 = arith.constant 18446744073709551615 : i256 loc(#loc)
// CHECK-NEXT:     %c-32_i256 = arith.constant -32 : i256 loc(#loc)
// CHECK-NEXT:     %c31_i256 = arith.constant 31 : i256 loc(#loc)
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %0 = "llvm.intrcall"() <{id = 4070 : i32, name = "evm.memoryguard"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %1 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %0, %1 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %2 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %3 = arith.cmpi ne, %2, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:     cf.cond_br %3, ^bb1, ^bb2 loc(#loc1)
// CHECK-NEXT:   ^bb1:  // pred: ^bb0
// CHECK-NEXT:     %4 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%4, %c0_i256) <{id = 4081 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     cf.br ^bb2 loc(#loc1)
// CHECK-NEXT:   ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:     %5 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["A_6"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %6 = "llvm.intrcall"() <{id = 4042 : i32, name = "evm.codesize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %7 = arith.subi %6, %5 : i256 loc(#loc1)
// CHECK-NEXT:     %8 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %9 = llvm.load %8 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %10 = arith.addi %7, %c31_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %11 = arith.andi %10, %c-32_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %12 = arith.addi %9, %11 : i256 loc(#loc1)
// CHECK-NEXT:     %13 = arith.cmpi ugt, %12, %c18446744073709551615_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %14 = arith.cmpi ult, %12, %9 : i256 loc(#loc1)
// CHECK-NEXT:     %15 = arith.ori %13, %14 : i1 loc(#loc1)
// CHECK-NEXT:     cf.cond_br %15, ^bb3, ^bb4 loc(#loc1)
// CHECK-NEXT:   ^bb3:  // pred: ^bb2
// CHECK-NEXT:     %16 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %16 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %17 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c65_i256, %17 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %18 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%18, %c36_i256) <{id = 4081 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     cf.br ^bb4 loc(#loc1)
// CHECK-NEXT:   ^bb4:  // 2 preds: ^bb2, ^bb3
// CHECK-NEXT:     %19 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %12, %19 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %20 = llvm.inttoptr %9 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %21 = llvm.inttoptr %5 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%20, %21, %7) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @A_6() : () -> () loc(#loc1)
// CHECK-NEXT:     %22 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %23 = llvm.load %22 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %24 = "llvm.intrcall"() <{id = 4046 : i32, metadata = ["A_6_deployed"], name = "evm.dataoffset"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %25 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["A_6_deployed"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %26 = llvm.inttoptr %23 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %27 = llvm.inttoptr %24 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%26, %27, %25) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     %28 = llvm.inttoptr %23 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%28, %25) <{id = 4079 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @A_6() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     return loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   module @A_6_deployed attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:     func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:       %0 = "llvm.intrcall"() <{id = 4070 : i32, name = "evm.memoryguard"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %1 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %0, %1 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %2 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%2, %c0_i256) <{id = 4081 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     llvm.module_flags [#llvm.mlir.module_flag<error, "evm-memory-guard", 128 : i64>, #llvm.mlir.module_flag<error, "evm-stack-region-size", 0 : i64>] loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   llvm.module_flags [#llvm.mlir.module_flag<error, "evm-memory-guard", 128 : i64>, #llvm.mlir.module_flag<error, "evm-stack-region-size", 0 : i64>] loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:4:0)
// CHECK-NEXT: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module @C_17 attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:     %c65_i256 = arith.constant 65 : i256 loc(#loc)
// CHECK-NEXT:     %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:     %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:     %c18446744073709551615_i256 = arith.constant 18446744073709551615 : i256 loc(#loc)
// CHECK-NEXT:     %c-32_i256 = arith.constant -32 : i256 loc(#loc)
// CHECK-NEXT:     %c31_i256 = arith.constant 31 : i256 loc(#loc)
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %0 = "llvm.intrcall"() <{id = 4070 : i32, name = "evm.memoryguard"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %1 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %0, %1 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %2 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %3 = arith.cmpi ne, %2, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:     cf.cond_br %3, ^bb1, ^bb2 loc(#loc1)
// CHECK-NEXT:   ^bb1:  // pred: ^bb0
// CHECK-NEXT:     %4 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%4, %c0_i256) <{id = 4081 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     cf.br ^bb2 loc(#loc1)
// CHECK-NEXT:   ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:     %5 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["C_17"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %6 = "llvm.intrcall"() <{id = 4042 : i32, name = "evm.codesize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %7 = arith.subi %6, %5 : i256 loc(#loc1)
// CHECK-NEXT:     %8 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %9 = llvm.load %8 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %10 = arith.addi %7, %c31_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %11 = arith.andi %10, %c-32_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %12 = arith.addi %9, %11 : i256 loc(#loc1)
// CHECK-NEXT:     %13 = arith.cmpi ugt, %12, %c18446744073709551615_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %14 = arith.cmpi ult, %12, %9 : i256 loc(#loc1)
// CHECK-NEXT:     %15 = arith.ori %13, %14 : i1 loc(#loc1)
// CHECK-NEXT:     cf.cond_br %15, ^bb3, ^bb4 loc(#loc1)
// CHECK-NEXT:   ^bb3:  // pred: ^bb2
// CHECK-NEXT:     %16 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %16 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %17 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c65_i256, %17 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %18 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%18, %c36_i256) <{id = 4081 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     cf.br ^bb4 loc(#loc1)
// CHECK-NEXT:   ^bb4:  // 2 preds: ^bb2, ^bb3
// CHECK-NEXT:     %19 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %12, %19 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %20 = llvm.inttoptr %9 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %21 = llvm.inttoptr %5 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%20, %21, %7) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @C_17() : () -> () loc(#loc1)
// CHECK-NEXT:     %22 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %23 = llvm.load %22 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %24 = "llvm.intrcall"() <{id = 4046 : i32, metadata = ["C_17_deployed"], name = "evm.dataoffset"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %25 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["C_17_deployed"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %26 = llvm.inttoptr %23 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %27 = llvm.inttoptr %24 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%26, %27, %25) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     %28 = llvm.inttoptr %23 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%28, %25) <{id = 4079 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @C_17() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     return loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   module @C_17_deployed attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:     func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:       %0 = "llvm.intrcall"() <{id = 4070 : i32, name = "evm.memoryguard"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %1 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %0, %1 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %2 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%2, %c0_i256) <{id = 4081 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     llvm.module_flags [#llvm.mlir.module_flag<error, "evm-memory-guard", 128 : i64>, #llvm.mlir.module_flag<error, "evm-stack-region-size", 0 : i64>] loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   llvm.module_flags [#llvm.mlir.module_flag<error, "evm-memory-guard", 128 : i64>, #llvm.mlir.module_flag<error, "evm-stack-region-size", 0 : i64>] loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:8:0)
// CHECK-EMPTY:
