// RUN: solc --mlir-action=print-std-mlir --mlir-target=evm --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract Delete {
    enum Status { Active, Inactive, Pending }

    uint    uintVar;
    bool    boolVar;
    address addrVar;
    bytes32 bytesVar;
    int16   intVar;
    Status  enumVar;

    uint[3] staticArr;
    uint[]  dynArr;

    // delete on a uint state variable resets it to 0.
    function deleteUint() public {
        delete uintVar;
    }

    // delete on a bool resets it to false.
    function deleteBool() public {
        delete boolVar;
    }

    // delete on an address resets it to address(0).
    function deleteAddr() public {
        delete addrVar;
    }

    // delete on bytes32 resets it to 0.
    function deleteBytes() public {
        delete bytesVar;
    }

    // delete on a signed integer resets it to 0.
    function deleteInt() public {
        delete intVar;
    }

    // delete on an enum resets it to its first member (ordinal 0).
    function deleteEnum() public {
        delete enumVar;
    }

    // delete on a single element of a static array → sol.store of zero.
    function deleteStaticElem() public {
        staticArr[0] = 1; staticArr[1] = 2; staticArr[2] = 3;
        delete staticArr[1];
    }

    // delete on a whole static array → sol.copy from zero-init Memory array.
    function deleteStaticArr() public {
        staticArr[0] = 1; staticArr[1] = 2; staticArr[2] = 3;
        delete staticArr;
    }

    // delete on a dynamic storage array → sol.copy from zero-init Memory array.
    function deleteDynArr() public {
        dynArr.push(10); dynArr.push(20);
        delete dynArr;
    }

    // delete on an element of a dynamic storage array → sol.store of zero.
    function deleteDynElem() public {
        dynArr.push(1); dynArr.push(2); dynArr.push(3);
        delete dynArr[1];
    }

    // delete on a local (stack) variable → sol.store of zero.
    function deleteLocal() public pure returns (uint) {
        uint v = 99;
        delete v;
        return v;
    }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #loc16 = loc({{.*}}:60:8)
// CHECK-NEXT: #loc21 = loc({{.*}}:54:8)
// CHECK-NEXT: module @Delete_180 attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:     %c65_i256 = arith.constant 65 : i256 loc(#loc)
// CHECK-NEXT:     %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:     %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:     %c18446744073709551615_i256 = arith.constant 18446744073709551615 : i256 loc(#loc)
// CHECK-NEXT:     %c-32_i256 = arith.constant -32 : i256 loc(#loc)
// CHECK-NEXT:     %c31_i256 = arith.constant 31 : i256 loc(#loc)
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:     %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %1 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %2 = arith.cmpi ne, %1, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:     cf.cond_br %2, ^bb1, ^bb2 loc(#loc1)
// CHECK-NEXT:   ^bb1:  // pred: ^bb0
// CHECK-NEXT:     %3 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%3, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     cf.br ^bb2 loc(#loc1)
// CHECK-NEXT:   ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:     %4 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["Delete_180"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %5 = "llvm.intrcall"() <{id = 4042 : i32, name = "evm.codesize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %6 = arith.subi %5, %4 : i256 loc(#loc1)
// CHECK-NEXT:     %7 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %8 = llvm.load %7 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %9 = arith.addi %6, %c31_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %10 = arith.andi %9, %c-32_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %11 = arith.addi %8, %10 : i256 loc(#loc1)
// CHECK-NEXT:     %12 = arith.cmpi ugt, %11, %c18446744073709551615_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %13 = arith.cmpi ult, %11, %8 : i256 loc(#loc1)
// CHECK-NEXT:     %14 = arith.ori %12, %13 : i1 loc(#loc1)
// CHECK-NEXT:     cf.cond_br %14, ^bb3, ^bb4 loc(#loc1)
// CHECK-NEXT:   ^bb3:  // pred: ^bb2
// CHECK-NEXT:     %15 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %15 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %16 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c65_i256, %16 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %17 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%17, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     cf.br ^bb4 loc(#loc1)
// CHECK-NEXT:   ^bb4:  // 2 preds: ^bb2, ^bb3
// CHECK-NEXT:     %18 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %11, %18 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %19 = llvm.inttoptr %8 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %20 = llvm.inttoptr %4 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%19, %20, %6) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @Delete_180() : () -> () loc(#loc1)
// CHECK-NEXT:     %21 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %22 = llvm.load %21 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %23 = "llvm.intrcall"() <{id = 4046 : i32, metadata = ["Delete_180_deployed"], name = "evm.dataoffset"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %24 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["Delete_180_deployed"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %25 = llvm.inttoptr %22 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %26 = llvm.inttoptr %23 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%25, %26, %24) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     %27 = llvm.inttoptr %22 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%27, %24) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @Delete_180() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     return loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   module @Delete_180_deployed attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:     func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:       %c224_i256 = arith.constant 224 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:       %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:       %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %1 = "llvm.intrcall"() <{id = 4038 : i32, name = "evm.calldatasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %2 = arith.cmpi uge, %1, %c4_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %2, ^bb1, ^bb35 loc(#loc1)
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %3 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<2> loc(#loc1)
// CHECK-NEXT:       %4 = llvm.load %3 {alignment = 1 : i64} : !llvm.ptr<2> -> i256 loc(#loc1)
// CHECK-NEXT:       %5 = arith.shrui %4, %c224_i256 : i256 loc(#loc1)
// CHECK-NEXT:       %6 = arith.trunci %5 : i256 to i32 loc(#loc1)
// CHECK-NEXT:       cf.switch %6 : i32, [
// CHECK-NEXT:         default: ^bb35,
// CHECK-NEXT:         3642045259: ^bb2,
// CHECK-NEXT:         1278930689: ^bb5,
// CHECK-NEXT:         1553010268: ^bb8,
// CHECK-NEXT:         87269612: ^bb11,
// CHECK-NEXT:         2865208348: ^bb14,
// CHECK-NEXT:         140565673: ^bb17,
// CHECK-NEXT:         2422417391: ^bb20,
// CHECK-NEXT:         1898683568: ^bb23,
// CHECK-NEXT:         4079894127: ^bb26,
// CHECK-NEXT:         2629596254: ^bb29,
// CHECK-NEXT:         1547838093: ^bb32
// CHECK-NEXT:       ] loc(#loc1)
// CHECK-NEXT:     ^bb2:  // pred: ^bb1
// CHECK-NEXT:       %7 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %8 = arith.cmpi ne, %7, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %8, ^bb3, ^bb4 loc(#loc1)
// CHECK-NEXT:     ^bb3:  // pred: ^bb2
// CHECK-NEXT:       %9 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%9, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb4 loc(#loc1)
// CHECK-NEXT:     ^bb4:  // 2 preds: ^bb2, ^bb3
// CHECK-NEXT:       call @deleteUint_31() : () -> () loc(#loc1)
// CHECK-NEXT:       %10 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %11 = llvm.load %10 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %12 = llvm.inttoptr %11 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%12, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb35 loc(#loc1)
// CHECK-NEXT:     ^bb5:  // pred: ^bb1
// CHECK-NEXT:       %13 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %14 = arith.cmpi ne, %13, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %14, ^bb6, ^bb7 loc(#loc1)
// CHECK-NEXT:     ^bb6:  // pred: ^bb5
// CHECK-NEXT:       %15 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%15, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb7 loc(#loc1)
// CHECK-NEXT:     ^bb7:  // 2 preds: ^bb5, ^bb6
// CHECK-NEXT:       call @deleteBool_38() : () -> () loc(#loc1)
// CHECK-NEXT:       %16 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %17 = llvm.load %16 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %18 = llvm.inttoptr %17 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%18, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb35 loc(#loc1)
// CHECK-NEXT:     ^bb8:  // pred: ^bb1
// CHECK-NEXT:       %19 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %20 = arith.cmpi ne, %19, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %20, ^bb9, ^bb10 loc(#loc1)
// CHECK-NEXT:     ^bb9:  // pred: ^bb8
// CHECK-NEXT:       %21 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%21, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb10 loc(#loc1)
// CHECK-NEXT:     ^bb10:  // 2 preds: ^bb8, ^bb9
// CHECK-NEXT:       call @deleteAddr_45() : () -> () loc(#loc1)
// CHECK-NEXT:       %22 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %23 = llvm.load %22 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %24 = llvm.inttoptr %23 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%24, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb35 loc(#loc1)
// CHECK-NEXT:     ^bb11:  // pred: ^bb1
// CHECK-NEXT:       %25 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %26 = arith.cmpi ne, %25, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %26, ^bb12, ^bb13 loc(#loc1)
// CHECK-NEXT:     ^bb12:  // pred: ^bb11
// CHECK-NEXT:       %27 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%27, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb13 loc(#loc1)
// CHECK-NEXT:     ^bb13:  // 2 preds: ^bb11, ^bb12
// CHECK-NEXT:       call @deleteBytes_52() : () -> () loc(#loc1)
// CHECK-NEXT:       %28 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %29 = llvm.load %28 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %30 = llvm.inttoptr %29 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%30, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb35 loc(#loc1)
// CHECK-NEXT:     ^bb14:  // pred: ^bb1
// CHECK-NEXT:       %31 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %32 = arith.cmpi ne, %31, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %32, ^bb15, ^bb16 loc(#loc1)
// CHECK-NEXT:     ^bb15:  // pred: ^bb14
// CHECK-NEXT:       %33 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%33, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb16 loc(#loc1)
// CHECK-NEXT:     ^bb16:  // 2 preds: ^bb14, ^bb15
// CHECK-NEXT:       call @deleteInt_59() : () -> () loc(#loc1)
// CHECK-NEXT:       %34 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %35 = llvm.load %34 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %36 = llvm.inttoptr %35 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%36, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb35 loc(#loc1)
// CHECK-NEXT:     ^bb17:  // pred: ^bb1
// CHECK-NEXT:       %37 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %38 = arith.cmpi ne, %37, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %38, ^bb18, ^bb19 loc(#loc1)
// CHECK-NEXT:     ^bb18:  // pred: ^bb17
// CHECK-NEXT:       %39 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%39, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb19 loc(#loc1)
// CHECK-NEXT:     ^bb19:  // 2 preds: ^bb17, ^bb18
// CHECK-NEXT:       call @deleteEnum_66() : () -> () loc(#loc1)
// CHECK-NEXT:       %40 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %41 = llvm.load %40 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %42 = llvm.inttoptr %41 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%42, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb35 loc(#loc1)
// CHECK-NEXT:     ^bb20:  // pred: ^bb1
// CHECK-NEXT:       %43 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %44 = arith.cmpi ne, %43, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %44, ^bb21, ^bb22 loc(#loc1)
// CHECK-NEXT:     ^bb21:  // pred: ^bb20
// CHECK-NEXT:       %45 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%45, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb22 loc(#loc1)
// CHECK-NEXT:     ^bb22:  // 2 preds: ^bb20, ^bb21
// CHECK-NEXT:       call @deleteStaticElem_93() : () -> () loc(#loc1)
// CHECK-NEXT:       %46 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %47 = llvm.load %46 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %48 = llvm.inttoptr %47 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%48, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb35 loc(#loc1)
// CHECK-NEXT:     ^bb23:  // pred: ^bb1
// CHECK-NEXT:       %49 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %50 = arith.cmpi ne, %49, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %50, ^bb24, ^bb25 loc(#loc1)
// CHECK-NEXT:     ^bb24:  // pred: ^bb23
// CHECK-NEXT:       %51 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%51, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb25 loc(#loc1)
// CHECK-NEXT:     ^bb25:  // 2 preds: ^bb23, ^bb24
// CHECK-NEXT:       call @deleteStaticArr_118() : () -> () loc(#loc1)
// CHECK-NEXT:       %52 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %53 = llvm.load %52 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %54 = llvm.inttoptr %53 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%54, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb35 loc(#loc1)
// CHECK-NEXT:     ^bb26:  // pred: ^bb1
// CHECK-NEXT:       %55 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %56 = arith.cmpi ne, %55, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %56, ^bb27, ^bb28 loc(#loc1)
// CHECK-NEXT:     ^bb27:  // pred: ^bb26
// CHECK-NEXT:       %57 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%57, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb28 loc(#loc1)
// CHECK-NEXT:     ^bb28:  // 2 preds: ^bb26, ^bb27
// CHECK-NEXT:       call @deleteDynArr_137() : () -> () loc(#loc1)
// CHECK-NEXT:       %58 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %59 = llvm.load %58 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %60 = llvm.inttoptr %59 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%60, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb35 loc(#loc1)
// CHECK-NEXT:     ^bb29:  // pred: ^bb1
// CHECK-NEXT:       %61 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %62 = arith.cmpi ne, %61, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %62, ^bb30, ^bb31 loc(#loc1)
// CHECK-NEXT:     ^bb30:  // pred: ^bb29
// CHECK-NEXT:       %63 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%63, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb31 loc(#loc1)
// CHECK-NEXT:     ^bb31:  // 2 preds: ^bb29, ^bb30
// CHECK-NEXT:       call @deleteDynElem_164() : () -> () loc(#loc1)
// CHECK-NEXT:       %64 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %65 = llvm.load %64 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %66 = llvm.inttoptr %65 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%66, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb35 loc(#loc1)
// CHECK-NEXT:     ^bb32:  // pred: ^bb1
// CHECK-NEXT:       %67 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %68 = arith.cmpi ne, %67, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %68, ^bb33, ^bb34 loc(#loc1)
// CHECK-NEXT:     ^bb33:  // pred: ^bb32
// CHECK-NEXT:       %69 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%69, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb34 loc(#loc1)
// CHECK-NEXT:     ^bb34:  // 2 preds: ^bb32, ^bb33
// CHECK-NEXT:       %70 = call @deleteLocal_179() : () -> i256 loc(#loc1)
// CHECK-NEXT:       %71 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %72 = llvm.load %71 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %73 = llvm.inttoptr %72 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %70, %73 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %74 = llvm.inttoptr %72 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%74, %c32_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb35 loc(#loc1)
// CHECK-NEXT:     ^bb35:  // 13 preds: ^bb0, ^bb1, ^bb4, ^bb7, ^bb10, ^bb13, ^bb16, ^bb19, ^bb22, ^bb25, ^bb28, ^bb31, ^bb34
// CHECK-NEXT:       %75 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%75, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @deleteLocal_179() -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c99_i256 = arith.constant 99 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc3)
// CHECK-NEXT:       %0 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc3)
// CHECK-NEXT:       llvm.store %c99_i256, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc3)
// CHECK-NEXT:       llvm.store %c0_i256, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc4)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc5)
// CHECK-NEXT:       return %1 : i256 loc(#loc6)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     func.func @deleteDynElem_164() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c3_i256 = arith.constant 3 : i256 loc(#loc)
// CHECK-NEXT:       %c2_i256 = arith.constant 2 : i256 loc(#loc)
// CHECK-NEXT:       %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:       %c50_i256 = arith.constant 50 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:       %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c7_i256 = arith.constant 7 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc8)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc8)
// CHECK-NEXT:       %2 = arith.addi %1, %c1_i256 : i256 loc(#loc8)
// CHECK-NEXT:       %3 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc8)
// CHECK-NEXT:       llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc8)
// CHECK-NEXT:       %4 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc8)
// CHECK-NEXT:       llvm.store %c7_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc8)
// CHECK-NEXT:       %5 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc8)
// CHECK-NEXT:       %6 = "llvm.intrcall"(%5, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc8)
// CHECK-NEXT:       %7 = arith.addi %6, %1 : i256 loc(#loc8)
// CHECK-NEXT:       %8 = llvm.inttoptr %7 : i256 to !llvm.ptr<5> loc(#loc8)
// CHECK-NEXT:       llvm.store %c1_i256, %8 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc8)
// CHECK-NEXT:       %9 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc9)
// CHECK-NEXT:       %10 = llvm.load %9 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc9)
// CHECK-NEXT:       %11 = arith.addi %10, %c1_i256 : i256 loc(#loc9)
// CHECK-NEXT:       %12 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc9)
// CHECK-NEXT:       llvm.store %11, %12 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc9)
// CHECK-NEXT:       %13 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc9)
// CHECK-NEXT:       llvm.store %c7_i256, %13 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc9)
// CHECK-NEXT:       %14 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc9)
// CHECK-NEXT:       %15 = "llvm.intrcall"(%14, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc9)
// CHECK-NEXT:       %16 = arith.addi %15, %10 : i256 loc(#loc9)
// CHECK-NEXT:       %17 = llvm.inttoptr %16 : i256 to !llvm.ptr<5> loc(#loc9)
// CHECK-NEXT:       llvm.store %c2_i256, %17 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc9)
// CHECK-NEXT:       %18 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc10)
// CHECK-NEXT:       %19 = llvm.load %18 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc10)
// CHECK-NEXT:       %20 = arith.addi %19, %c1_i256 : i256 loc(#loc10)
// CHECK-NEXT:       %21 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc10)
// CHECK-NEXT:       llvm.store %20, %21 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc10)
// CHECK-NEXT:       %22 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc10)
// CHECK-NEXT:       llvm.store %c7_i256, %22 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc10)
// CHECK-NEXT:       %23 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc10)
// CHECK-NEXT:       %24 = "llvm.intrcall"(%23, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc10)
// CHECK-NEXT:       %25 = arith.addi %24, %19 : i256 loc(#loc10)
// CHECK-NEXT:       %26 = llvm.inttoptr %25 : i256 to !llvm.ptr<5> loc(#loc10)
// CHECK-NEXT:       llvm.store %c3_i256, %26 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc10)
// CHECK-NEXT:       %27 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc11)
// CHECK-NEXT:       %28 = llvm.load %27 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc11)
// CHECK-NEXT:       %29 = arith.cmpi ule, %28, %c1_i256 : i256 loc(#loc11)
// CHECK-NEXT:       cf.cond_br %29, ^bb1, ^bb2 loc(#loc11)
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %30 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc11)
// CHECK-NEXT:       llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %30 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc11)
// CHECK-NEXT:       %31 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc11)
// CHECK-NEXT:       llvm.store %c50_i256, %31 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc11)
// CHECK-NEXT:       %32 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc11)
// CHECK-NEXT:       "llvm.intrcall"(%32, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc11)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc11)
// CHECK-NEXT:       cf.br ^bb2 loc(#loc11)
// CHECK-NEXT:     ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:       %33 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc11)
// CHECK-NEXT:       llvm.store %c7_i256, %33 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc11)
// CHECK-NEXT:       %34 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc11)
// CHECK-NEXT:       %35 = "llvm.intrcall"(%34, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc11)
// CHECK-NEXT:       %36 = arith.addi %35, %c1_i256 : i256 loc(#loc11)
// CHECK-NEXT:       %37 = llvm.inttoptr %36 : i256 to !llvm.ptr<5> loc(#loc12)
// CHECK-NEXT:       llvm.store %c0_i256, %37 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc12)
// CHECK-NEXT:       return loc(#loc7)
// CHECK-NEXT:     } loc(#loc7)
// CHECK-NEXT:     func.func @deleteDynArr_137() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c128_i256 = arith.constant 128 : i256 loc(#loc)
// CHECK-NEXT:       %c20_i256 = arith.constant 20 : i256 loc(#loc)
// CHECK-NEXT:       %c10_i256 = arith.constant 10 : i256 loc(#loc)
// CHECK-NEXT:       %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:       %c65_i256 = arith.constant 65 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:       %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:       %c18446744073709551615_i256 = arith.constant 18446744073709551615 : i256 loc(#loc)
// CHECK-NEXT:       %c96_i256 = arith.constant 96 : i256 loc(#loc)
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %c7_i256 = arith.constant 7 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc14)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc14)
// CHECK-NEXT:       %2 = arith.addi %1, %c1_i256 : i256 loc(#loc14)
// CHECK-NEXT:       %3 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc14)
// CHECK-NEXT:       llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc14)
// CHECK-NEXT:       %4 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc14)
// CHECK-NEXT:       llvm.store %c7_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc14)
// CHECK-NEXT:       %5 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc14)
// CHECK-NEXT:       %6 = "llvm.intrcall"(%5, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc14)
// CHECK-NEXT:       %7 = arith.addi %6, %1 : i256 loc(#loc14)
// CHECK-NEXT:       %8 = llvm.inttoptr %7 : i256 to !llvm.ptr<5> loc(#loc14)
// CHECK-NEXT:       llvm.store %c10_i256, %8 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc14)
// CHECK-NEXT:       %9 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc15)
// CHECK-NEXT:       %10 = llvm.load %9 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc15)
// CHECK-NEXT:       %11 = arith.addi %10, %c1_i256 : i256 loc(#loc15)
// CHECK-NEXT:       %12 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc15)
// CHECK-NEXT:       llvm.store %11, %12 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc15)
// CHECK-NEXT:       %13 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc15)
// CHECK-NEXT:       llvm.store %c7_i256, %13 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc15)
// CHECK-NEXT:       %14 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc15)
// CHECK-NEXT:       %15 = "llvm.intrcall"(%14, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc15)
// CHECK-NEXT:       %16 = arith.addi %15, %10 : i256 loc(#loc15)
// CHECK-NEXT:       %17 = llvm.inttoptr %16 : i256 to !llvm.ptr<5> loc(#loc15)
// CHECK-NEXT:       llvm.store %c20_i256, %17 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc15)
// CHECK-NEXT:       %18 = llvm.inttoptr %c96_i256 : i256 to !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       %19 = llvm.load %18 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc16)
// CHECK-NEXT:       %20 = arith.cmpi ugt, %19, %c18446744073709551615_i256 : i256 loc(#loc16)
// CHECK-NEXT:       cf.cond_br %20, ^bb1, ^bb2 loc(#loc16)
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %21 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %21 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       %22 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       llvm.store %c65_i256, %22 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       %23 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       "llvm.intrcall"(%23, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc16)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc16)
// CHECK-NEXT:       cf.br ^bb2 loc(#loc16)
// CHECK-NEXT:     ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:       %24 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc16)
// CHECK-NEXT:       %25 = llvm.load %24 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc16)
// CHECK-NEXT:       %26 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc16)
// CHECK-NEXT:       llvm.store %19, %26 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc16)
// CHECK-NEXT:       %27 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       llvm.store %c7_i256, %27 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       %28 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       %29 = "llvm.intrcall"(%28, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc16)
// CHECK-NEXT:       %30 = arith.cmpi ult, %19, %25 : i256 loc(#loc16)
// CHECK-NEXT:       cf.cond_br %30, ^bb3, ^bb6 loc(#loc16)
// CHECK-NEXT:     ^bb3:  // pred: ^bb2
// CHECK-NEXT:       %31 = arith.addi %29, %19 : i256 loc(#loc16)
// CHECK-NEXT:       %32 = arith.addi %29, %25 : i256 loc(#loc16)
// CHECK-NEXT:       %33 = arith.subi %32, %31 : i256 loc(#loc16)
// CHECK-NEXT:       cf.br ^bb4(%c0_i256 : i256) loc(#loc16)
// CHECK-NEXT:     ^bb4(%34: i256 loc({{.*}}:60:8)):  // 2 preds: ^bb3, ^bb5
// CHECK-NEXT:       %35 = arith.cmpi ult, %34, %33 : i256 loc(#loc16)
// CHECK-NEXT:       cf.cond_br %35, ^bb5(%34 : i256), ^bb6 loc(#loc16)
// CHECK-NEXT:     ^bb5(%36: i256 loc({{.*}}:60:8)):  // pred: ^bb4
// CHECK-NEXT:       %37 = arith.addi %31, %36 : i256 loc(#loc16)
// CHECK-NEXT:       %38 = llvm.inttoptr %37 : i256 to !llvm.ptr<5> loc(#loc16)
// CHECK-NEXT:       llvm.store %c0_i256, %38 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc16)
// CHECK-NEXT:       %39 = arith.addi %36, %c1_i256 : i256 loc(#loc16)
// CHECK-NEXT:       cf.br ^bb4(%39 : i256) loc(#loc16)
// CHECK-NEXT:     ^bb6:  // 2 preds: ^bb2, ^bb4
// CHECK-NEXT:       %40 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       llvm.store %c7_i256, %40 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       %41 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       %42 = "llvm.intrcall"(%41, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc16)
// CHECK-NEXT:       cf.br ^bb7(%c0_i256 : i256) loc(#loc16)
// CHECK-NEXT:     ^bb7(%43: i256 loc({{.*}}:60:8)):  // 2 preds: ^bb6, ^bb8
// CHECK-NEXT:       %44 = arith.cmpi ult, %43, %19 : i256 loc(#loc16)
// CHECK-NEXT:       cf.cond_br %44, ^bb8(%43 : i256), ^bb9 loc(#loc16)
// CHECK-NEXT:     ^bb8(%45: i256 loc({{.*}}:60:8)):  // pred: ^bb7
// CHECK-NEXT:       %46 = arith.muli %45, %c32_i256 : i256 loc(#loc16)
// CHECK-NEXT:       %47 = arith.addi %46, %c128_i256 : i256 loc(#loc16)
// CHECK-NEXT:       %48 = arith.addi %42, %45 : i256 loc(#loc16)
// CHECK-NEXT:       %49 = llvm.inttoptr %47 : i256 to !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       %50 = llvm.load %49 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc16)
// CHECK-NEXT:       %51 = llvm.inttoptr %48 : i256 to !llvm.ptr<5> loc(#loc16)
// CHECK-NEXT:       llvm.store %50, %51 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc16)
// CHECK-NEXT:       %52 = arith.addi %45, %c1_i256 : i256 loc(#loc16)
// CHECK-NEXT:       cf.br ^bb7(%52 : i256) loc(#loc16)
// CHECK-NEXT:     ^bb9:  // pred: ^bb7
// CHECK-NEXT:       return loc(#loc13)
// CHECK-NEXT:     } loc(#loc13)
// CHECK-NEXT:     func.func @deleteStaticArr_118() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c6_i256 = arith.constant 6 : i256 loc(#loc)
// CHECK-NEXT:       %c2_i256 = arith.constant 2 : i256 loc(#loc)
// CHECK-NEXT:       %c5_i256 = arith.constant 5 : i256 loc(#loc)
// CHECK-NEXT:       %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:       %c65_i256 = arith.constant 65 : i256 loc(#loc)
// CHECK-NEXT:       %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c18446744073709551615_i256 = arith.constant 18446744073709551615 : i256 loc(#loc)
// CHECK-NEXT:       %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:       %c96_i256 = arith.constant 96 : i256 loc(#loc)
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:       %c3_i256 = arith.constant 3 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<5> loc(#loc18)
// CHECK-NEXT:       llvm.store %c1_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc18)
// CHECK-NEXT:       %1 = llvm.inttoptr %c5_i256 : i256 to !llvm.ptr<5> loc(#loc19)
// CHECK-NEXT:       llvm.store %c2_i256, %1 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc19)
// CHECK-NEXT:       %2 = llvm.inttoptr %c6_i256 : i256 to !llvm.ptr<5> loc(#loc20)
// CHECK-NEXT:       llvm.store %c3_i256, %2 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc20)
// CHECK-NEXT:       %3 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc21)
// CHECK-NEXT:       %4 = llvm.load %3 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc21)
// CHECK-NEXT:       %5 = arith.addi %4, %c96_i256 : i256 loc(#loc21)
// CHECK-NEXT:       %6 = arith.cmpi ugt, %5, %c18446744073709551615_i256 : i256 loc(#loc21)
// CHECK-NEXT:       %7 = arith.cmpi ult, %5, %4 : i256 loc(#loc21)
// CHECK-NEXT:       %8 = arith.ori %6, %7 : i1 loc(#loc21)
// CHECK-NEXT:       cf.cond_br %8, ^bb1, ^bb2 loc(#loc21)
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %9 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc21)
// CHECK-NEXT:       llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %9 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc21)
// CHECK-NEXT:       %10 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc21)
// CHECK-NEXT:       llvm.store %c65_i256, %10 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc21)
// CHECK-NEXT:       %11 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc21)
// CHECK-NEXT:       "llvm.intrcall"(%11, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc21)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc21)
// CHECK-NEXT:       cf.br ^bb2 loc(#loc21)
// CHECK-NEXT:     ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:       %12 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc21)
// CHECK-NEXT:       llvm.store %5, %12 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc21)
// CHECK-NEXT:       %13 = "llvm.intrcall"() <{id = 4038 : i32, name = "evm.calldatasize"}> : () -> i256 loc(#loc21)
// CHECK-NEXT:       %14 = llvm.inttoptr %4 : i256 to !llvm.ptr<1> loc(#loc21)
// CHECK-NEXT:       %15 = llvm.inttoptr %13 : i256 to !llvm.ptr<2> loc(#loc21)
// CHECK-NEXT:       "llvm.intr.memcpy"(%14, %15, %c96_i256) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<2>, i256) -> () loc(#loc21)
// CHECK-NEXT:       cf.br ^bb3(%c0_i256 : i256) loc(#loc21)
// CHECK-NEXT:     ^bb3(%16: i256 loc({{.*}}:54:8)):  // 2 preds: ^bb2, ^bb4
// CHECK-NEXT:       %17 = arith.cmpi ult, %16, %c3_i256 : i256 loc(#loc21)
// CHECK-NEXT:       cf.cond_br %17, ^bb4(%16 : i256), ^bb5 loc(#loc21)
// CHECK-NEXT:     ^bb4(%18: i256 loc({{.*}}:54:8)):  // pred: ^bb3
// CHECK-NEXT:       %19 = arith.muli %18, %c32_i256 : i256 loc(#loc21)
// CHECK-NEXT:       %20 = arith.addi %4, %19 : i256 loc(#loc21)
// CHECK-NEXT:       %21 = arith.addi %18, %c4_i256 : i256 loc(#loc21)
// CHECK-NEXT:       %22 = llvm.inttoptr %20 : i256 to !llvm.ptr<1> loc(#loc21)
// CHECK-NEXT:       %23 = llvm.load %22 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc21)
// CHECK-NEXT:       %24 = llvm.inttoptr %21 : i256 to !llvm.ptr<5> loc(#loc21)
// CHECK-NEXT:       llvm.store %23, %24 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc21)
// CHECK-NEXT:       %25 = arith.addi %18, %c1_i256 : i256 loc(#loc21)
// CHECK-NEXT:       cf.br ^bb3(%25 : i256) loc(#loc21)
// CHECK-NEXT:     ^bb5:  // pred: ^bb3
// CHECK-NEXT:       return loc(#loc17)
// CHECK-NEXT:     } loc(#loc17)
// CHECK-NEXT:     func.func @deleteStaticElem_93() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c3_i256 = arith.constant 3 : i256 loc(#loc)
// CHECK-NEXT:       %c6_i256 = arith.constant 6 : i256 loc(#loc)
// CHECK-NEXT:       %c2_i256 = arith.constant 2 : i256 loc(#loc)
// CHECK-NEXT:       %c5_i256 = arith.constant 5 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc23)
// CHECK-NEXT:       %0 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<5> loc(#loc23)
// CHECK-NEXT:       llvm.store %c1_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc23)
// CHECK-NEXT:       %1 = llvm.inttoptr %c5_i256 : i256 to !llvm.ptr<5> loc(#loc24)
// CHECK-NEXT:       llvm.store %c2_i256, %1 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc24)
// CHECK-NEXT:       %2 = llvm.inttoptr %c6_i256 : i256 to !llvm.ptr<5> loc(#loc25)
// CHECK-NEXT:       llvm.store %c3_i256, %2 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc25)
// CHECK-NEXT:       %3 = llvm.inttoptr %c5_i256 : i256 to !llvm.ptr<5> loc(#loc26)
// CHECK-NEXT:       llvm.store %c0_i256, %3 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc26)
// CHECK-NEXT:       return loc(#loc22)
// CHECK-NEXT:     } loc(#loc22)
// CHECK-NEXT:     func.func @deleteEnum_66() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c-16711681_i256 = arith.constant -16711681 : i256 loc(#loc)
// CHECK-NEXT:       %c3_i256 = arith.constant 3 : i256 loc(#loc28)
// CHECK-NEXT:       %0 = llvm.inttoptr %c3_i256 : i256 to !llvm.ptr<5> loc(#loc29)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc29)
// CHECK-NEXT:       %2 = arith.andi %1, %c-16711681_i256 : i256 loc(#loc29)
// CHECK-NEXT:       %3 = llvm.inttoptr %c3_i256 : i256 to !llvm.ptr<5> loc(#loc29)
// CHECK-NEXT:       llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc29)
// CHECK-NEXT:       return loc(#loc27)
// CHECK-NEXT:     } loc(#loc27)
// CHECK-NEXT:     func.func @deleteInt_59() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c-65536_i256 = arith.constant -65536 : i256 loc(#loc)
// CHECK-NEXT:       %c3_i256 = arith.constant 3 : i256 loc(#loc31)
// CHECK-NEXT:       %0 = llvm.inttoptr %c3_i256 : i256 to !llvm.ptr<5> loc(#loc32)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc32)
// CHECK-NEXT:       %2 = arith.andi %1, %c-65536_i256 : i256 loc(#loc32)
// CHECK-NEXT:       %3 = llvm.inttoptr %c3_i256 : i256 to !llvm.ptr<5> loc(#loc32)
// CHECK-NEXT:       llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc32)
// CHECK-NEXT:       return loc(#loc30)
// CHECK-NEXT:     } loc(#loc30)
// CHECK-NEXT:     func.func @deleteBytes_52() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c2_i256 = arith.constant 2 : i256 loc(#loc34)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc35)
// CHECK-NEXT:       %0 = llvm.inttoptr %c2_i256 : i256 to !llvm.ptr<5> loc(#loc35)
// CHECK-NEXT:       llvm.store %c0_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc35)
// CHECK-NEXT:       return loc(#loc33)
// CHECK-NEXT:     } loc(#loc33)
// CHECK-NEXT:     func.func @deleteAddr_45() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c-374144419156711147060143317175368453031918731001601_i256 = arith.constant -374144419156711147060143317175368453031918731001601 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c1_i256 : i256 to !llvm.ptr<5> loc(#loc37)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc37)
// CHECK-NEXT:       %2 = arith.andi %1, %c-374144419156711147060143317175368453031918731001601_i256 : i256 loc(#loc37)
// CHECK-NEXT:       %3 = llvm.inttoptr %c1_i256 : i256 to !llvm.ptr<5> loc(#loc37)
// CHECK-NEXT:       llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc37)
// CHECK-NEXT:       return loc(#loc36)
// CHECK-NEXT:     } loc(#loc36)
// CHECK-NEXT:     func.func @deleteBool_38() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c-256_i256 = arith.constant -256 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc39)
// CHECK-NEXT:       %0 = llvm.inttoptr %c1_i256 : i256 to !llvm.ptr<5> loc(#loc40)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc40)
// CHECK-NEXT:       %2 = arith.andi %1, %c-256_i256 : i256 loc(#loc40)
// CHECK-NEXT:       %3 = llvm.inttoptr %c1_i256 : i256 to !llvm.ptr<5> loc(#loc40)
// CHECK-NEXT:       llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc40)
// CHECK-NEXT:       return loc(#loc38)
// CHECK-NEXT:     } loc(#loc38)
// CHECK-NEXT:     func.func @deleteUint_31() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<5> loc(#loc42)
// CHECK-NEXT:       llvm.store %c0_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc42)
// CHECK-NEXT:       return loc(#loc41)
// CHECK-NEXT:     } loc(#loc41)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:70:4)
// CHECK-NEXT: #loc3 = loc({{.*}}:71:8)
// CHECK-NEXT: #loc4 = loc({{.*}}:72:8)
// CHECK-NEXT: #loc5 = loc({{.*}}:73:15)
// CHECK-NEXT: #loc6 = loc({{.*}}:73:8)
// CHECK-NEXT: #loc7 = loc({{.*}}:64:4)
// CHECK-NEXT: #loc8 = loc({{.*}}:65:8)
// CHECK-NEXT: #loc9 = loc({{.*}}:65:24)
// CHECK-NEXT: #loc10 = loc({{.*}}:65:40)
// CHECK-NEXT: #loc11 = loc({{.*}}:66:15)
// CHECK-NEXT: #loc12 = loc({{.*}}:66:8)
// CHECK-NEXT: #loc13 = loc({{.*}}:58:4)
// CHECK-NEXT: #loc14 = loc({{.*}}:59:8)
// CHECK-NEXT: #loc15 = loc({{.*}}:59:25)
// CHECK-NEXT: #loc17 = loc({{.*}}:52:4)
// CHECK-NEXT: #loc18 = loc({{.*}}:53:8)
// CHECK-NEXT: #loc19 = loc({{.*}}:53:26)
// CHECK-NEXT: #loc20 = loc({{.*}}:53:44)
// CHECK-NEXT: #loc22 = loc({{.*}}:46:4)
// CHECK-NEXT: #loc23 = loc({{.*}}:47:8)
// CHECK-NEXT: #loc24 = loc({{.*}}:47:26)
// CHECK-NEXT: #loc25 = loc({{.*}}:47:44)
// CHECK-NEXT: #loc26 = loc({{.*}}:48:8)
// CHECK-NEXT: #loc27 = loc({{.*}}:41:4)
// CHECK-NEXT: #loc28 = loc({{.*}}:10:4)
// CHECK-NEXT: #loc29 = loc({{.*}}:42:8)
// CHECK-NEXT: #loc30 = loc({{.*}}:36:4)
// CHECK-NEXT: #loc31 = loc({{.*}}:9:4)
// CHECK-NEXT: #loc32 = loc({{.*}}:37:8)
// CHECK-NEXT: #loc33 = loc({{.*}}:31:4)
// CHECK-NEXT: #loc34 = loc({{.*}}:8:4)
// CHECK-NEXT: #loc35 = loc({{.*}}:32:8)
// CHECK-NEXT: #loc36 = loc({{.*}}:26:4)
// CHECK-NEXT: #loc37 = loc({{.*}}:27:8)
// CHECK-NEXT: #loc38 = loc({{.*}}:21:4)
// CHECK-NEXT: #loc39 = loc({{.*}}:6:4)
// CHECK-NEXT: #loc40 = loc({{.*}}:22:8)
// CHECK-NEXT: #loc41 = loc({{.*}}:16:4)
// CHECK-NEXT: #loc42 = loc({{.*}}:17:8)
// CHECK-EMPTY:
