// RUN: solc --mlir-action=print-std-mlir --mlir-target=evm --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract Delete {
    enum Status { Active, Inactive, Pending }

    struct Point { uint x; uint y; }
    struct WithMap { uint id; mapping(uint => uint) m; }
    struct Mixed {
        uint[3] fixedArr;
        uint[]  dynamicArr;
        mapping(uint => uint) m;
        address owner;
        bool    active;
    }

    uint    uintVar;
    bool    boolVar;
    address addrVar;
    bytes32 bytesVar;
    int16   intVar;
    Status  enumVar;

    uint[3] staticArr;
    uint[]  dynArr;

    Point[]   pointArr;
    Point[2]  pointFixed;
    WithMap[] withMapArr;
    mapping(uint => uint)[]   mapArr;
    mapping(uint => uint)[][] mapArr2D;
    Mixed   mixedS;
    WithMap withMapS;

    // delete on a uint state variable resets it to 0.
    function deleteUint() public {
        delete uintVar;
    }

    // delete on a bool resets it to false.
    function deleteBool() public {
        delete boolVar;
    }

    // delete on an address resets it to address(0).
    function deleteAddr() public {
        delete addrVar;
    }

    // delete on bytes32 resets it to 0.
    function deleteBytes() public {
        delete bytesVar;
    }

    // delete on a signed integer resets it to 0.
    function deleteInt() public {
        delete intVar;
    }

    // delete on an enum resets it to its first member (ordinal 0).
    function deleteEnum() public {
        delete enumVar;
    }

    // delete on a single element of a static array → sol.store of zero.
    function deleteStaticElem() public {
        staticArr[0] = 1; staticArr[1] = 2; staticArr[2] = 3;
        delete staticArr[1];
    }

    // delete on a whole static array → sol.delete clears all element slots.
    function deleteStaticArr() public {
        staticArr[0] = 1; staticArr[1] = 2; staticArr[2] = 3;
        delete staticArr;
    }

    // delete on a dynamic storage array → sol.delete clears length and data.
    function deleteDynArr() public {
        dynArr.push(10); dynArr.push(20);
        delete dynArr;
    }

    // delete on an element of a dynamic storage array → sol.store of zero.
    function deleteDynElem() public {
        dynArr.push(1); dynArr.push(2); dynArr.push(3);
        delete dynArr[1];
    }

    // delete on a local (stack) variable → sol.store of zero.
    function deleteLocal() public pure returns (uint) {
        uint v = 99;
        delete v;
        return v;
    }

    // delete on a dynamic array of value structs → clears each element's slots.
    function deletePointArr() public {
        delete pointArr;
    }

    // delete on a static array of value structs → clears all element slots.
    function deletePointFixed() public {
        delete pointFixed;
    }

    // delete on a dynamic array of structs containing a mapping → clears the
    // value members of each element; mapping members are skipped.
    function deleteWithMapArr() public {
        delete withMapArr;
    }

    // delete on a dynamic array of mappings → clears the length only; the
    // mapping element base-slots are never written.
    function deleteMapArr() public {
        delete mapArr;
    }

    // delete on a nested dynamic array of mappings → clears the outer length
    // and each inner array length; mapping base-slots are skipped.
    function deleteMapArr2D() public {
        delete mapArr2D;
    }

    // delete on a struct mixing static array, dynamic array, mapping and value
    // members → clears every value/array member; the mapping is skipped.
    function deleteMixedStruct() public {
        delete mixedS;
    }

    // delete on a struct with a value member and a mapping → clears the value
    // member; the mapping member is skipped.
    function deleteWithMapStruct() public {
        delete withMapS;
    }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #loc4 = loc({{.*}}:131:8)
// CHECK-NEXT: #loc7 = loc({{.*}}:125:8)
// CHECK-NEXT: #loc10 = loc({{.*}}:119:8)
// CHECK-NEXT: #loc16 = loc({{.*}}:107:8)
// CHECK-NEXT: #loc19 = loc({{.*}}:101:8)
// CHECK-NEXT: #loc22 = loc({{.*}}:96:8)
// CHECK-NEXT: #loc37 = loc({{.*}}:78:8)
// CHECK-NEXT: #loc42 = loc({{.*}}:72:8)
// CHECK-NEXT: #loop_unroll = #llvm.loop_unroll<full = true>
// CHECK-NEXT: #loop_annotation = #llvm.loop_annotation<unroll = #loop_unroll>
// CHECK-NEXT: module @Delete_287 attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:     %c65_i256 = arith.constant 65 : i256 loc(#loc)
// CHECK-NEXT:     %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:     %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:     %c18446744073709551615_i256 = arith.constant 18446744073709551615 : i256 loc(#loc)
// CHECK-NEXT:     %c-32_i256 = arith.constant -32 : i256 loc(#loc)
// CHECK-NEXT:     %c31_i256 = arith.constant 31 : i256 loc(#loc)
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:     %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %1 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %2 = arith.cmpi ne, %1, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:     cf.cond_br %2, ^bb1, ^bb2 loc(#loc1)
// CHECK-NEXT:   ^bb1:  // pred: ^bb0
// CHECK-NEXT:     %3 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%3, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     cf.br ^bb2 loc(#loc1)
// CHECK-NEXT:   ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:     %4 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["Delete_287"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %5 = "llvm.intrcall"() <{id = 4042 : i32, name = "evm.codesize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %6 = arith.subi %5, %4 : i256 loc(#loc1)
// CHECK-NEXT:     %7 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %8 = llvm.load %7 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %9 = arith.addi %6, %c31_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %10 = arith.andi %9, %c-32_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %11 = arith.addi %8, %10 : i256 loc(#loc1)
// CHECK-NEXT:     %12 = arith.cmpi ugt, %11, %c18446744073709551615_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %13 = arith.cmpi ult, %11, %8 : i256 loc(#loc1)
// CHECK-NEXT:     %14 = arith.ori %12, %13 : i1 loc(#loc1)
// CHECK-NEXT:     cf.cond_br %14, ^bb3, ^bb4 loc(#loc1)
// CHECK-NEXT:   ^bb3:  // pred: ^bb2
// CHECK-NEXT:     %15 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %15 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %16 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c65_i256, %16 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %17 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%17, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     cf.br ^bb4 loc(#loc1)
// CHECK-NEXT:   ^bb4:  // 2 preds: ^bb2, ^bb3
// CHECK-NEXT:     %18 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %11, %18 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %19 = llvm.inttoptr %8 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %20 = llvm.inttoptr %4 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%19, %20, %6) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @Delete_287() : () -> () loc(#loc1)
// CHECK-NEXT:     %21 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %22 = llvm.load %21 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %23 = "llvm.intrcall"() <{id = 4046 : i32, metadata = ["Delete_287_deployed"], name = "evm.dataoffset"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %24 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["Delete_287_deployed"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %25 = llvm.inttoptr %22 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %26 = llvm.inttoptr %23 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%25, %26, %24) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     %27 = llvm.inttoptr %22 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%27, %24) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @Delete_287() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     return loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   module @Delete_287_deployed attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:     func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:       %c224_i256 = arith.constant 224 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:       %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:       %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %1 = "llvm.intrcall"() <{id = 4038 : i32, name = "evm.calldatasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %2 = arith.cmpi uge, %1, %c4_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %2, ^bb1, ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %3 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<2> loc(#loc1)
// CHECK-NEXT:       %4 = llvm.load %3 {alignment = 1 : i64} : !llvm.ptr<2> -> i256 loc(#loc1)
// CHECK-NEXT:       %5 = arith.shrui %4, %c224_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.switch %5 : i256, [
// CHECK-NEXT:         default: ^bb56,
// CHECK-NEXT:         3642045259: ^bb2,
// CHECK-NEXT:         1278930689: ^bb5,
// CHECK-NEXT:         1553010268: ^bb8,
// CHECK-NEXT:         87269612: ^bb11,
// CHECK-NEXT:         2865208348: ^bb14,
// CHECK-NEXT:         140565673: ^bb17,
// CHECK-NEXT:         2422417391: ^bb20,
// CHECK-NEXT:         1898683568: ^bb23,
// CHECK-NEXT:         4079894127: ^bb26,
// CHECK-NEXT:         2629596254: ^bb29,
// CHECK-NEXT:         1547838093: ^bb32,
// CHECK-NEXT:         1318596472: ^bb35,
// CHECK-NEXT:         1080472298: ^bb38,
// CHECK-NEXT:         3113340590: ^bb41,
// CHECK-NEXT:         3261112258: ^bb44,
// CHECK-NEXT:         3871045154: ^bb47,
// CHECK-NEXT:         1662523059: ^bb50,
// CHECK-NEXT:         122150337: ^bb53
// CHECK-NEXT:       ] loc(#loc1)
// CHECK-NEXT:     ^bb2:  // pred: ^bb1
// CHECK-NEXT:       %6 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %7 = arith.cmpi ne, %6, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %7, ^bb3, ^bb4 loc(#loc1)
// CHECK-NEXT:     ^bb3:  // pred: ^bb2
// CHECK-NEXT:       %8 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%8, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb4 loc(#loc1)
// CHECK-NEXT:     ^bb4:  // 2 preds: ^bb2, ^bb3
// CHECK-NEXT:       call @deleteUint_89() : () -> () loc(#loc1)
// CHECK-NEXT:       %9 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %10 = llvm.load %9 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %11 = llvm.inttoptr %10 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%11, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb5:  // pred: ^bb1
// CHECK-NEXT:       %12 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %13 = arith.cmpi ne, %12, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %13, ^bb6, ^bb7 loc(#loc1)
// CHECK-NEXT:     ^bb6:  // pred: ^bb5
// CHECK-NEXT:       %14 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%14, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb7 loc(#loc1)
// CHECK-NEXT:     ^bb7:  // 2 preds: ^bb5, ^bb6
// CHECK-NEXT:       call @deleteBool_96() : () -> () loc(#loc1)
// CHECK-NEXT:       %15 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %16 = llvm.load %15 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %17 = llvm.inttoptr %16 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%17, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb8:  // pred: ^bb1
// CHECK-NEXT:       %18 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %19 = arith.cmpi ne, %18, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %19, ^bb9, ^bb10 loc(#loc1)
// CHECK-NEXT:     ^bb9:  // pred: ^bb8
// CHECK-NEXT:       %20 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%20, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb10 loc(#loc1)
// CHECK-NEXT:     ^bb10:  // 2 preds: ^bb8, ^bb9
// CHECK-NEXT:       call @deleteAddr_103() : () -> () loc(#loc1)
// CHECK-NEXT:       %21 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %22 = llvm.load %21 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %23 = llvm.inttoptr %22 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%23, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb11:  // pred: ^bb1
// CHECK-NEXT:       %24 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %25 = arith.cmpi ne, %24, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %25, ^bb12, ^bb13 loc(#loc1)
// CHECK-NEXT:     ^bb12:  // pred: ^bb11
// CHECK-NEXT:       %26 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%26, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb13 loc(#loc1)
// CHECK-NEXT:     ^bb13:  // 2 preds: ^bb11, ^bb12
// CHECK-NEXT:       call @deleteBytes_110() : () -> () loc(#loc1)
// CHECK-NEXT:       %27 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %28 = llvm.load %27 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %29 = llvm.inttoptr %28 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%29, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb14:  // pred: ^bb1
// CHECK-NEXT:       %30 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %31 = arith.cmpi ne, %30, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %31, ^bb15, ^bb16 loc(#loc1)
// CHECK-NEXT:     ^bb15:  // pred: ^bb14
// CHECK-NEXT:       %32 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%32, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb16 loc(#loc1)
// CHECK-NEXT:     ^bb16:  // 2 preds: ^bb14, ^bb15
// CHECK-NEXT:       call @deleteInt_117() : () -> () loc(#loc1)
// CHECK-NEXT:       %33 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %34 = llvm.load %33 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %35 = llvm.inttoptr %34 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%35, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb17:  // pred: ^bb1
// CHECK-NEXT:       %36 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %37 = arith.cmpi ne, %36, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %37, ^bb18, ^bb19 loc(#loc1)
// CHECK-NEXT:     ^bb18:  // pred: ^bb17
// CHECK-NEXT:       %38 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%38, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb19 loc(#loc1)
// CHECK-NEXT:     ^bb19:  // 2 preds: ^bb17, ^bb18
// CHECK-NEXT:       call @deleteEnum_124() : () -> () loc(#loc1)
// CHECK-NEXT:       %39 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %40 = llvm.load %39 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %41 = llvm.inttoptr %40 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%41, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb20:  // pred: ^bb1
// CHECK-NEXT:       %42 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %43 = arith.cmpi ne, %42, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %43, ^bb21, ^bb22 loc(#loc1)
// CHECK-NEXT:     ^bb21:  // pred: ^bb20
// CHECK-NEXT:       %44 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%44, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb22 loc(#loc1)
// CHECK-NEXT:     ^bb22:  // 2 preds: ^bb20, ^bb21
// CHECK-NEXT:       call @deleteStaticElem_151() : () -> () loc(#loc1)
// CHECK-NEXT:       %45 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %46 = llvm.load %45 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %47 = llvm.inttoptr %46 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%47, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb23:  // pred: ^bb1
// CHECK-NEXT:       %48 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %49 = arith.cmpi ne, %48, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %49, ^bb24, ^bb25 loc(#loc1)
// CHECK-NEXT:     ^bb24:  // pred: ^bb23
// CHECK-NEXT:       %50 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%50, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb25 loc(#loc1)
// CHECK-NEXT:     ^bb25:  // 2 preds: ^bb23, ^bb24
// CHECK-NEXT:       call @deleteStaticArr_176() : () -> () loc(#loc1)
// CHECK-NEXT:       %51 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %52 = llvm.load %51 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %53 = llvm.inttoptr %52 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%53, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb26:  // pred: ^bb1
// CHECK-NEXT:       %54 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %55 = arith.cmpi ne, %54, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %55, ^bb27, ^bb28 loc(#loc1)
// CHECK-NEXT:     ^bb27:  // pred: ^bb26
// CHECK-NEXT:       %56 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%56, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb28 loc(#loc1)
// CHECK-NEXT:     ^bb28:  // 2 preds: ^bb26, ^bb27
// CHECK-NEXT:       call @deleteDynArr_195() : () -> () loc(#loc1)
// CHECK-NEXT:       %57 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %58 = llvm.load %57 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %59 = llvm.inttoptr %58 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%59, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb29:  // pred: ^bb1
// CHECK-NEXT:       %60 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %61 = arith.cmpi ne, %60, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %61, ^bb30, ^bb31 loc(#loc1)
// CHECK-NEXT:     ^bb30:  // pred: ^bb29
// CHECK-NEXT:       %62 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%62, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb31 loc(#loc1)
// CHECK-NEXT:     ^bb31:  // 2 preds: ^bb29, ^bb30
// CHECK-NEXT:       call @deleteDynElem_222() : () -> () loc(#loc1)
// CHECK-NEXT:       %63 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %64 = llvm.load %63 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %65 = llvm.inttoptr %64 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%65, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb32:  // pred: ^bb1
// CHECK-NEXT:       %66 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %67 = arith.cmpi ne, %66, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %67, ^bb33, ^bb34 loc(#loc1)
// CHECK-NEXT:     ^bb33:  // pred: ^bb32
// CHECK-NEXT:       %68 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%68, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb34 loc(#loc1)
// CHECK-NEXT:     ^bb34:  // 2 preds: ^bb32, ^bb33
// CHECK-NEXT:       %69 = call @deleteLocal_237() : () -> i256 loc(#loc1)
// CHECK-NEXT:       %70 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %71 = llvm.load %70 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %72 = llvm.inttoptr %71 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %69, %72 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %73 = llvm.inttoptr %71 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%73, %c32_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb35:  // pred: ^bb1
// CHECK-NEXT:       %74 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %75 = arith.cmpi ne, %74, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %75, ^bb36, ^bb37 loc(#loc1)
// CHECK-NEXT:     ^bb36:  // pred: ^bb35
// CHECK-NEXT:       %76 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%76, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb37 loc(#loc1)
// CHECK-NEXT:     ^bb37:  // 2 preds: ^bb35, ^bb36
// CHECK-NEXT:       call @deletePointArr_244() : () -> () loc(#loc1)
// CHECK-NEXT:       %77 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %78 = llvm.load %77 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %79 = llvm.inttoptr %78 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%79, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb38:  // pred: ^bb1
// CHECK-NEXT:       %80 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %81 = arith.cmpi ne, %80, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %81, ^bb39, ^bb40 loc(#loc1)
// CHECK-NEXT:     ^bb39:  // pred: ^bb38
// CHECK-NEXT:       %82 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%82, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb40 loc(#loc1)
// CHECK-NEXT:     ^bb40:  // 2 preds: ^bb38, ^bb39
// CHECK-NEXT:       call @deletePointFixed_251() : () -> () loc(#loc1)
// CHECK-NEXT:       %83 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %84 = llvm.load %83 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %85 = llvm.inttoptr %84 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%85, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb41:  // pred: ^bb1
// CHECK-NEXT:       %86 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %87 = arith.cmpi ne, %86, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %87, ^bb42, ^bb43 loc(#loc1)
// CHECK-NEXT:     ^bb42:  // pred: ^bb41
// CHECK-NEXT:       %88 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%88, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb43 loc(#loc1)
// CHECK-NEXT:     ^bb43:  // 2 preds: ^bb41, ^bb42
// CHECK-NEXT:       call @deleteWithMapArr_258() : () -> () loc(#loc1)
// CHECK-NEXT:       %89 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %90 = llvm.load %89 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %91 = llvm.inttoptr %90 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%91, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb44:  // pred: ^bb1
// CHECK-NEXT:       %92 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %93 = arith.cmpi ne, %92, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %93, ^bb45, ^bb46 loc(#loc1)
// CHECK-NEXT:     ^bb45:  // pred: ^bb44
// CHECK-NEXT:       %94 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%94, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb46 loc(#loc1)
// CHECK-NEXT:     ^bb46:  // 2 preds: ^bb44, ^bb45
// CHECK-NEXT:       call @deleteMapArr_265() : () -> () loc(#loc1)
// CHECK-NEXT:       %95 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %96 = llvm.load %95 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %97 = llvm.inttoptr %96 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%97, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb47:  // pred: ^bb1
// CHECK-NEXT:       %98 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %99 = arith.cmpi ne, %98, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %99, ^bb48, ^bb49 loc(#loc1)
// CHECK-NEXT:     ^bb48:  // pred: ^bb47
// CHECK-NEXT:       %100 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%100, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb49 loc(#loc1)
// CHECK-NEXT:     ^bb49:  // 2 preds: ^bb47, ^bb48
// CHECK-NEXT:       call @deleteMapArr2D_272() : () -> () loc(#loc1)
// CHECK-NEXT:       %101 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %102 = llvm.load %101 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %103 = llvm.inttoptr %102 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%103, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb50:  // pred: ^bb1
// CHECK-NEXT:       %104 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %105 = arith.cmpi ne, %104, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %105, ^bb51, ^bb52 loc(#loc1)
// CHECK-NEXT:     ^bb51:  // pred: ^bb50
// CHECK-NEXT:       %106 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%106, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb52 loc(#loc1)
// CHECK-NEXT:     ^bb52:  // 2 preds: ^bb50, ^bb51
// CHECK-NEXT:       call @deleteMixedStruct_279() : () -> () loc(#loc1)
// CHECK-NEXT:       %107 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %108 = llvm.load %107 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %109 = llvm.inttoptr %108 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%109, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb53:  // pred: ^bb1
// CHECK-NEXT:       %110 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %111 = arith.cmpi ne, %110, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:       cf.cond_br %111, ^bb54, ^bb55 loc(#loc1)
// CHECK-NEXT:     ^bb54:  // pred: ^bb53
// CHECK-NEXT:       %112 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%112, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb55 loc(#loc1)
// CHECK-NEXT:     ^bb55:  // 2 preds: ^bb53, ^bb54
// CHECK-NEXT:       call @deleteWithMapStruct_286() : () -> () loc(#loc1)
// CHECK-NEXT:       %113 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %114 = llvm.load %113 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:       %115 = llvm.inttoptr %114 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%115, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       cf.br ^bb56 loc(#loc1)
// CHECK-NEXT:     ^bb56:  // 20 preds: ^bb0, ^bb1, ^bb4, ^bb7, ^bb10, ^bb13, ^bb16, ^bb19, ^bb22, ^bb25, ^bb28, ^bb31, ^bb34, ^bb37, ^bb40, ^bb43, ^bb46, ^bb49, ^bb52, ^bb55
// CHECK-NEXT:       %116 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%116, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @deleteWithMapStruct_286() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %c22_i256 = arith.constant 22 : i256 loc(#loc3)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       cf.br ^bb1(%c0_i256 : i256) loc(#loc4)
// CHECK-NEXT:     ^bb1(%0: i256 loc({{.*}}:131:8)):  // 2 preds: ^bb0, ^bb2
// CHECK-NEXT:       %1 = arith.cmpi ult, %0, %c1_i256 : i256 loc(#loc4)
// CHECK-NEXT:       cf.cond_br %1, ^bb2(%0 : i256), ^bb3 loc(#loc4)
// CHECK-NEXT:     ^bb2(%2: i256 loc({{.*}}:131:8)):  // pred: ^bb1
// CHECK-NEXT:       %3 = arith.addi %2, %c22_i256 : i256 loc(#loc4)
// CHECK-NEXT:       %4 = llvm.inttoptr %3 : i256 to !llvm.ptr<5> loc(#loc4)
// CHECK-NEXT:       llvm.store %c0_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc4)
// CHECK-NEXT:       %5 = arith.addi %2, %c1_i256 : i256 loc(#loc4)
// CHECK-NEXT:       cf.br ^bb1(%5 : i256) {loop_annotation = #loop_annotation} loc(#loc4)
// CHECK-NEXT:     ^bb3:  // pred: ^bb1
// CHECK-NEXT:       return loc(#loc2)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     func.func @deleteMixedStruct_279() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c21_i256 = arith.constant 21 : i256 loc(#loc)
// CHECK-NEXT:       %c19_i256 = arith.constant 19 : i256 loc(#loc)
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %c3_i256 = arith.constant 3 : i256 loc(#loc)
// CHECK-NEXT:       %c16_i256 = arith.constant 16 : i256 loc(#loc6)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       cf.br ^bb1(%c0_i256 : i256) loc(#loc7)
// CHECK-NEXT:     ^bb1(%0: i256 loc({{.*}}:125:8)):  // 2 preds: ^bb0, ^bb2
// CHECK-NEXT:       %1 = arith.cmpi ult, %0, %c3_i256 : i256 loc(#loc7)
// CHECK-NEXT:       cf.cond_br %1, ^bb2(%0 : i256), ^bb3 loc(#loc7)
// CHECK-NEXT:     ^bb2(%2: i256 loc({{.*}}:125:8)):  // pred: ^bb1
// CHECK-NEXT:       %3 = arith.addi %2, %c16_i256 : i256 loc(#loc7)
// CHECK-NEXT:       %4 = llvm.inttoptr %3 : i256 to !llvm.ptr<5> loc(#loc7)
// CHECK-NEXT:       llvm.store %c0_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc7)
// CHECK-NEXT:       %5 = arith.addi %2, %c1_i256 : i256 loc(#loc7)
// CHECK-NEXT:       cf.br ^bb1(%5 : i256) {loop_annotation = #loop_annotation} loc(#loc7)
// CHECK-NEXT:     ^bb3:  // pred: ^bb1
// CHECK-NEXT:       %6 = llvm.inttoptr %c19_i256 : i256 to !llvm.ptr<5> loc(#loc7)
// CHECK-NEXT:       %7 = llvm.load %6 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc7)
// CHECK-NEXT:       %8 = llvm.inttoptr %c19_i256 : i256 to !llvm.ptr<5> loc(#loc7)
// CHECK-NEXT:       llvm.store %c0_i256, %8 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc7)
// CHECK-NEXT:       %9 = arith.cmpi ugt, %7, %c0_i256 : i256 loc(#loc7)
// CHECK-NEXT:       cf.cond_br %9, ^bb4, ^bb10(%c0_i256 : i256) loc(#loc7)
// CHECK-NEXT:     ^bb4:  // pred: ^bb3
// CHECK-NEXT:       %10 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc7)
// CHECK-NEXT:       llvm.store %c19_i256, %10 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc7)
// CHECK-NEXT:       %11 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc7)
// CHECK-NEXT:       %12 = "llvm.intrcall"(%11, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc7)
// CHECK-NEXT:       cf.br ^bb5(%c0_i256 : i256) loc(#loc7)
// CHECK-NEXT:     ^bb5(%13: i256 loc({{.*}}:125:8)):  // 2 preds: ^bb4, ^bb9
// CHECK-NEXT:       %14 = arith.cmpi ult, %13, %7 : i256 loc(#loc7)
// CHECK-NEXT:       cf.cond_br %14, ^bb6(%13 : i256), ^bb10(%c0_i256 : i256) loc(#loc7)
// CHECK-NEXT:     ^bb6(%15: i256 loc({{.*}}:125:8)):  // pred: ^bb5
// CHECK-NEXT:       %16 = arith.addi %12, %15 : i256 loc(#loc7)
// CHECK-NEXT:       cf.br ^bb7(%c0_i256 : i256) loc(#loc7)
// CHECK-NEXT:     ^bb7(%17: i256 loc({{.*}}:125:8)):  // 2 preds: ^bb6, ^bb8
// CHECK-NEXT:       %18 = arith.cmpi ult, %17, %c1_i256 : i256 loc(#loc7)
// CHECK-NEXT:       cf.cond_br %18, ^bb8(%17 : i256), ^bb9(%15 : i256) loc(#loc7)
// CHECK-NEXT:     ^bb8(%19: i256 loc({{.*}}:125:8)):  // pred: ^bb7
// CHECK-NEXT:       %20 = arith.addi %16, %19 : i256 loc(#loc7)
// CHECK-NEXT:       %21 = llvm.inttoptr %20 : i256 to !llvm.ptr<5> loc(#loc7)
// CHECK-NEXT:       llvm.store %c0_i256, %21 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc7)
// CHECK-NEXT:       %22 = arith.addi %19, %c1_i256 : i256 loc(#loc7)
// CHECK-NEXT:       cf.br ^bb7(%22 : i256) {loop_annotation = #loop_annotation} loc(#loc7)
// CHECK-NEXT:     ^bb9(%23: i256 loc({{.*}}:125:8)):  // pred: ^bb7
// CHECK-NEXT:       %24 = arith.addi %23, %c1_i256 : i256 loc(#loc7)
// CHECK-NEXT:       cf.br ^bb5(%24 : i256) loc(#loc7)
// CHECK-NEXT:     ^bb10(%25: i256 loc({{.*}}:125:8)):  // 3 preds: ^bb3, ^bb5, ^bb11
// CHECK-NEXT:       %26 = arith.cmpi ult, %25, %c1_i256 : i256 loc(#loc7)
// CHECK-NEXT:       cf.cond_br %26, ^bb11(%25 : i256), ^bb12 loc(#loc7)
// CHECK-NEXT:     ^bb11(%27: i256 loc({{.*}}:125:8)):  // pred: ^bb10
// CHECK-NEXT:       %28 = arith.addi %27, %c21_i256 : i256 loc(#loc7)
// CHECK-NEXT:       %29 = llvm.inttoptr %28 : i256 to !llvm.ptr<5> loc(#loc7)
// CHECK-NEXT:       llvm.store %c0_i256, %29 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc7)
// CHECK-NEXT:       %30 = arith.addi %27, %c1_i256 : i256 loc(#loc7)
// CHECK-NEXT:       cf.br ^bb10(%30 : i256) {loop_annotation = #loop_annotation} loc(#loc7)
// CHECK-NEXT:     ^bb12:  // pred: ^bb10
// CHECK-NEXT:       return loc(#loc5)
// CHECK-NEXT:     } loc(#loc5)
// CHECK-NEXT:     func.func @deleteMapArr2D_272() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c15_i256 = arith.constant 15 : i256 loc(#loc9)
// CHECK-NEXT:       %0 = llvm.inttoptr %c15_i256 : i256 to !llvm.ptr<5> loc(#loc10)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc10)
// CHECK-NEXT:       %2 = llvm.inttoptr %c15_i256 : i256 to !llvm.ptr<5> loc(#loc10)
// CHECK-NEXT:       llvm.store %c0_i256, %2 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc10)
// CHECK-NEXT:       %3 = arith.cmpi ugt, %1, %c0_i256 : i256 loc(#loc10)
// CHECK-NEXT:       cf.cond_br %3, ^bb1, ^bb4 loc(#loc10)
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %4 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc10)
// CHECK-NEXT:       llvm.store %c15_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc10)
// CHECK-NEXT:       %5 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc10)
// CHECK-NEXT:       %6 = "llvm.intrcall"(%5, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc10)
// CHECK-NEXT:       cf.br ^bb2(%c0_i256 : i256) loc(#loc10)
// CHECK-NEXT:     ^bb2(%7: i256 loc({{.*}}:119:8)):  // 2 preds: ^bb1, ^bb3
// CHECK-NEXT:       %8 = arith.cmpi ult, %7, %1 : i256 loc(#loc10)
// CHECK-NEXT:       cf.cond_br %8, ^bb3(%7 : i256), ^bb4 loc(#loc10)
// CHECK-NEXT:     ^bb3(%9: i256 loc({{.*}}:119:8)):  // pred: ^bb2
// CHECK-NEXT:       %10 = arith.addi %6, %9 : i256 loc(#loc10)
// CHECK-NEXT:       %11 = llvm.inttoptr %10 : i256 to !llvm.ptr<5> loc(#loc10)
// CHECK-NEXT:       llvm.store %c0_i256, %11 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc10)
// CHECK-NEXT:       %12 = arith.addi %9, %c1_i256 : i256 loc(#loc10)
// CHECK-NEXT:       cf.br ^bb2(%12 : i256) loc(#loc10)
// CHECK-NEXT:     ^bb4:  // 2 preds: ^bb0, ^bb2
// CHECK-NEXT:       return loc(#loc8)
// CHECK-NEXT:     } loc(#loc8)
// CHECK-NEXT:     func.func @deleteMapArr_265() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c14_i256 = arith.constant 14 : i256 loc(#loc12)
// CHECK-NEXT:       %0 = llvm.inttoptr %c14_i256 : i256 to !llvm.ptr<5> loc(#loc13)
// CHECK-NEXT:       llvm.store %c0_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc13)
// CHECK-NEXT:       return loc(#loc11)
// CHECK-NEXT:     } loc(#loc11)
// CHECK-NEXT:     func.func @deleteWithMapArr_258() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %c2_i256 = arith.constant 2 : i256 loc(#loc)
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c13_i256 = arith.constant 13 : i256 loc(#loc15)
// CHECK-NEXT:       %0 = llvm.inttoptr %c13_i256 : i256 to !llvm.ptr<5> loc(#loc16)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc16)
// CHECK-NEXT:       %2 = llvm.inttoptr %c13_i256 : i256 to !llvm.ptr<5> loc(#loc16)
// CHECK-NEXT:       llvm.store %c0_i256, %2 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc16)
// CHECK-NEXT:       %3 = arith.cmpi ugt, %1, %c0_i256 : i256 loc(#loc16)
// CHECK-NEXT:       cf.cond_br %3, ^bb1, ^bb7 loc(#loc16)
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %4 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       llvm.store %c13_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       %5 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc16)
// CHECK-NEXT:       %6 = "llvm.intrcall"(%5, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc16)
// CHECK-NEXT:       %7 = arith.muli %1, %c2_i256 : i256 loc(#loc16)
// CHECK-NEXT:       cf.br ^bb2(%c0_i256 : i256) loc(#loc16)
// CHECK-NEXT:     ^bb2(%8: i256 loc({{.*}}:107:8)):  // 2 preds: ^bb1, ^bb6
// CHECK-NEXT:       %9 = arith.cmpi ult, %8, %7 : i256 loc(#loc16)
// CHECK-NEXT:       cf.cond_br %9, ^bb3(%8 : i256), ^bb7 loc(#loc16)
// CHECK-NEXT:     ^bb3(%10: i256 loc({{.*}}:107:8)):  // pred: ^bb2
// CHECK-NEXT:       %11 = arith.addi %6, %10 : i256 loc(#loc16)
// CHECK-NEXT:       cf.br ^bb4(%c0_i256 : i256) loc(#loc16)
// CHECK-NEXT:     ^bb4(%12: i256 loc({{.*}}:107:8)):  // 2 preds: ^bb3, ^bb5
// CHECK-NEXT:       %13 = arith.cmpi ult, %12, %c1_i256 : i256 loc(#loc16)
// CHECK-NEXT:       cf.cond_br %13, ^bb5(%12 : i256), ^bb6 loc(#loc16)
// CHECK-NEXT:     ^bb5(%14: i256 loc({{.*}}:107:8)):  // pred: ^bb4
// CHECK-NEXT:       %15 = arith.addi %11, %14 : i256 loc(#loc16)
// CHECK-NEXT:       %16 = llvm.inttoptr %15 : i256 to !llvm.ptr<5> loc(#loc16)
// CHECK-NEXT:       llvm.store %c0_i256, %16 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc16)
// CHECK-NEXT:       %17 = arith.addi %14, %c1_i256 : i256 loc(#loc16)
// CHECK-NEXT:       cf.br ^bb4(%17 : i256) {loop_annotation = #loop_annotation} loc(#loc16)
// CHECK-NEXT:     ^bb6:  // pred: ^bb4
// CHECK-NEXT:       %18 = arith.addi %10, %c2_i256 : i256 loc(#loc16)
// CHECK-NEXT:       cf.br ^bb2(%18 : i256) loc(#loc16)
// CHECK-NEXT:     ^bb7:  // 2 preds: ^bb0, ^bb2
// CHECK-NEXT:       return loc(#loc14)
// CHECK-NEXT:     } loc(#loc14)
// CHECK-NEXT:     func.func @deletePointFixed_251() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c9_i256 = arith.constant 9 : i256 loc(#loc18)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc19)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc19)
// CHECK-NEXT:       cf.br ^bb1(%c0_i256 : i256) loc(#loc19)
// CHECK-NEXT:     ^bb1(%0: i256 loc({{.*}}:101:8)):  // 2 preds: ^bb0, ^bb2
// CHECK-NEXT:       %1 = arith.cmpi ult, %0, %c4_i256 : i256 loc(#loc19)
// CHECK-NEXT:       cf.cond_br %1, ^bb2(%0 : i256), ^bb3 loc(#loc19)
// CHECK-NEXT:     ^bb2(%2: i256 loc({{.*}}:101:8)):  // pred: ^bb1
// CHECK-NEXT:       %3 = arith.addi %2, %c9_i256 : i256 loc(#loc19)
// CHECK-NEXT:       %4 = llvm.inttoptr %3 : i256 to !llvm.ptr<5> loc(#loc19)
// CHECK-NEXT:       llvm.store %c0_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc19)
// CHECK-NEXT:       %5 = arith.addi %2, %c1_i256 : i256 loc(#loc19)
// CHECK-NEXT:       cf.br ^bb1(%5 : i256) {loop_annotation = #loop_annotation} loc(#loc19)
// CHECK-NEXT:     ^bb3:  // pred: ^bb1
// CHECK-NEXT:       return loc(#loc17)
// CHECK-NEXT:     } loc(#loc17)
// CHECK-NEXT:     func.func @deletePointArr_244() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %c2_i256 = arith.constant 2 : i256 loc(#loc)
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c8_i256 = arith.constant 8 : i256 loc(#loc21)
// CHECK-NEXT:       %0 = llvm.inttoptr %c8_i256 : i256 to !llvm.ptr<5> loc(#loc22)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc22)
// CHECK-NEXT:       %2 = llvm.inttoptr %c8_i256 : i256 to !llvm.ptr<5> loc(#loc22)
// CHECK-NEXT:       llvm.store %c0_i256, %2 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc22)
// CHECK-NEXT:       %3 = arith.cmpi ugt, %1, %c0_i256 : i256 loc(#loc22)
// CHECK-NEXT:       cf.cond_br %3, ^bb1, ^bb10 loc(#loc22)
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %4 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc22)
// CHECK-NEXT:       llvm.store %c8_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc22)
// CHECK-NEXT:       %5 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc22)
// CHECK-NEXT:       %6 = "llvm.intrcall"(%5, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc22)
// CHECK-NEXT:       %7 = arith.muli %1, %c2_i256 : i256 loc(#loc22)
// CHECK-NEXT:       cf.br ^bb2(%c0_i256 : i256) loc(#loc22)
// CHECK-NEXT:     ^bb2(%8: i256 loc({{.*}}:96:8)):  // 2 preds: ^bb1, ^bb9
// CHECK-NEXT:       %9 = arith.cmpi ult, %8, %7 : i256 loc(#loc22)
// CHECK-NEXT:       cf.cond_br %9, ^bb3(%8 : i256), ^bb10 loc(#loc22)
// CHECK-NEXT:     ^bb3(%10: i256 loc({{.*}}:96:8)):  // pred: ^bb2
// CHECK-NEXT:       %11 = arith.addi %6, %10 : i256 loc(#loc22)
// CHECK-NEXT:       cf.br ^bb4(%c0_i256 : i256) loc(#loc22)
// CHECK-NEXT:     ^bb4(%12: i256 loc({{.*}}:96:8)):  // 2 preds: ^bb3, ^bb5
// CHECK-NEXT:       %13 = arith.cmpi ult, %12, %c1_i256 : i256 loc(#loc22)
// CHECK-NEXT:       cf.cond_br %13, ^bb5(%12 : i256), ^bb6 loc(#loc22)
// CHECK-NEXT:     ^bb5(%14: i256 loc({{.*}}:96:8)):  // pred: ^bb4
// CHECK-NEXT:       %15 = arith.addi %11, %14 : i256 loc(#loc22)
// CHECK-NEXT:       %16 = llvm.inttoptr %15 : i256 to !llvm.ptr<5> loc(#loc22)
// CHECK-NEXT:       llvm.store %c0_i256, %16 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc22)
// CHECK-NEXT:       %17 = arith.addi %14, %c1_i256 : i256 loc(#loc22)
// CHECK-NEXT:       cf.br ^bb4(%17 : i256) {loop_annotation = #loop_annotation} loc(#loc22)
// CHECK-NEXT:     ^bb6:  // pred: ^bb4
// CHECK-NEXT:       %18 = arith.addi %11, %c1_i256 : i256 loc(#loc22)
// CHECK-NEXT:       cf.br ^bb7(%c0_i256 : i256) loc(#loc22)
// CHECK-NEXT:     ^bb7(%19: i256 loc({{.*}}:96:8)):  // 2 preds: ^bb6, ^bb8
// CHECK-NEXT:       %20 = arith.cmpi ult, %19, %c1_i256 : i256 loc(#loc22)
// CHECK-NEXT:       cf.cond_br %20, ^bb8(%19 : i256), ^bb9(%10 : i256) loc(#loc22)
// CHECK-NEXT:     ^bb8(%21: i256 loc({{.*}}:96:8)):  // pred: ^bb7
// CHECK-NEXT:       %22 = arith.addi %18, %21 : i256 loc(#loc22)
// CHECK-NEXT:       %23 = llvm.inttoptr %22 : i256 to !llvm.ptr<5> loc(#loc22)
// CHECK-NEXT:       llvm.store %c0_i256, %23 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc22)
// CHECK-NEXT:       %24 = arith.addi %21, %c1_i256 : i256 loc(#loc22)
// CHECK-NEXT:       cf.br ^bb7(%24 : i256) {loop_annotation = #loop_annotation} loc(#loc22)
// CHECK-NEXT:     ^bb9(%25: i256 loc({{.*}}:96:8)):  // pred: ^bb7
// CHECK-NEXT:       %26 = arith.addi %25, %c2_i256 : i256 loc(#loc22)
// CHECK-NEXT:       cf.br ^bb2(%26 : i256) loc(#loc22)
// CHECK-NEXT:     ^bb10:  // 2 preds: ^bb0, ^bb2
// CHECK-NEXT:       return loc(#loc20)
// CHECK-NEXT:     } loc(#loc20)
// CHECK-NEXT:     func.func @deleteLocal_237() -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c99_i256 = arith.constant 99 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc24)
// CHECK-NEXT:       %0 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc24)
// CHECK-NEXT:       llvm.store %c99_i256, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc24)
// CHECK-NEXT:       llvm.store %c0_i256, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc25)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc26)
// CHECK-NEXT:       return %1 : i256 loc(#loc27)
// CHECK-NEXT:     } loc(#loc23)
// CHECK-NEXT:     func.func @deleteDynElem_222() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c3_i256 = arith.constant 3 : i256 loc(#loc)
// CHECK-NEXT:       %c2_i256 = arith.constant 2 : i256 loc(#loc)
// CHECK-NEXT:       %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:       %c50_i256 = arith.constant 50 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:       %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c7_i256 = arith.constant 7 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc29)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc29)
// CHECK-NEXT:       %2 = arith.addi %1, %c1_i256 : i256 loc(#loc29)
// CHECK-NEXT:       %3 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc29)
// CHECK-NEXT:       llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc29)
// CHECK-NEXT:       %4 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc29)
// CHECK-NEXT:       llvm.store %c7_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc29)
// CHECK-NEXT:       %5 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc29)
// CHECK-NEXT:       %6 = "llvm.intrcall"(%5, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc29)
// CHECK-NEXT:       %7 = arith.addi %6, %1 : i256 loc(#loc29)
// CHECK-NEXT:       %8 = llvm.inttoptr %7 : i256 to !llvm.ptr<5> loc(#loc29)
// CHECK-NEXT:       llvm.store %c1_i256, %8 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc29)
// CHECK-NEXT:       %9 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc30)
// CHECK-NEXT:       %10 = llvm.load %9 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc30)
// CHECK-NEXT:       %11 = arith.addi %10, %c1_i256 : i256 loc(#loc30)
// CHECK-NEXT:       %12 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc30)
// CHECK-NEXT:       llvm.store %11, %12 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc30)
// CHECK-NEXT:       %13 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc30)
// CHECK-NEXT:       llvm.store %c7_i256, %13 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc30)
// CHECK-NEXT:       %14 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc30)
// CHECK-NEXT:       %15 = "llvm.intrcall"(%14, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc30)
// CHECK-NEXT:       %16 = arith.addi %15, %10 : i256 loc(#loc30)
// CHECK-NEXT:       %17 = llvm.inttoptr %16 : i256 to !llvm.ptr<5> loc(#loc30)
// CHECK-NEXT:       llvm.store %c2_i256, %17 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc30)
// CHECK-NEXT:       %18 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc31)
// CHECK-NEXT:       %19 = llvm.load %18 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc31)
// CHECK-NEXT:       %20 = arith.addi %19, %c1_i256 : i256 loc(#loc31)
// CHECK-NEXT:       %21 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc31)
// CHECK-NEXT:       llvm.store %20, %21 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc31)
// CHECK-NEXT:       %22 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc31)
// CHECK-NEXT:       llvm.store %c7_i256, %22 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc31)
// CHECK-NEXT:       %23 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc31)
// CHECK-NEXT:       %24 = "llvm.intrcall"(%23, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc31)
// CHECK-NEXT:       %25 = arith.addi %24, %19 : i256 loc(#loc31)
// CHECK-NEXT:       %26 = llvm.inttoptr %25 : i256 to !llvm.ptr<5> loc(#loc31)
// CHECK-NEXT:       llvm.store %c3_i256, %26 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc31)
// CHECK-NEXT:       %27 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc32)
// CHECK-NEXT:       %28 = llvm.load %27 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc32)
// CHECK-NEXT:       %29 = arith.cmpi ule, %28, %c1_i256 : i256 loc(#loc32)
// CHECK-NEXT:       cf.cond_br %29, ^bb1, ^bb2 loc(#loc32)
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %30 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc32)
// CHECK-NEXT:       llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %30 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc32)
// CHECK-NEXT:       %31 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc32)
// CHECK-NEXT:       llvm.store %c50_i256, %31 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc32)
// CHECK-NEXT:       %32 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc32)
// CHECK-NEXT:       "llvm.intrcall"(%32, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc32)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc32)
// CHECK-NEXT:       cf.br ^bb2 loc(#loc32)
// CHECK-NEXT:     ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:       %33 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc32)
// CHECK-NEXT:       llvm.store %c7_i256, %33 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc32)
// CHECK-NEXT:       %34 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc32)
// CHECK-NEXT:       %35 = "llvm.intrcall"(%34, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc32)
// CHECK-NEXT:       %36 = arith.addi %35, %c1_i256 : i256 loc(#loc32)
// CHECK-NEXT:       %37 = llvm.inttoptr %36 : i256 to !llvm.ptr<5> loc(#loc33)
// CHECK-NEXT:       llvm.store %c0_i256, %37 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc33)
// CHECK-NEXT:       return loc(#loc28)
// CHECK-NEXT:     } loc(#loc28)
// CHECK-NEXT:     func.func @deleteDynArr_195() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c20_i256 = arith.constant 20 : i256 loc(#loc)
// CHECK-NEXT:       %c10_i256 = arith.constant 10 : i256 loc(#loc)
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %c7_i256 = arith.constant 7 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc35)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc35)
// CHECK-NEXT:       %2 = arith.addi %1, %c1_i256 : i256 loc(#loc35)
// CHECK-NEXT:       %3 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc35)
// CHECK-NEXT:       llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc35)
// CHECK-NEXT:       %4 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc35)
// CHECK-NEXT:       llvm.store %c7_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc35)
// CHECK-NEXT:       %5 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc35)
// CHECK-NEXT:       %6 = "llvm.intrcall"(%5, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc35)
// CHECK-NEXT:       %7 = arith.addi %6, %1 : i256 loc(#loc35)
// CHECK-NEXT:       %8 = llvm.inttoptr %7 : i256 to !llvm.ptr<5> loc(#loc35)
// CHECK-NEXT:       llvm.store %c10_i256, %8 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc35)
// CHECK-NEXT:       %9 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc36)
// CHECK-NEXT:       %10 = llvm.load %9 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc36)
// CHECK-NEXT:       %11 = arith.addi %10, %c1_i256 : i256 loc(#loc36)
// CHECK-NEXT:       %12 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc36)
// CHECK-NEXT:       llvm.store %11, %12 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc36)
// CHECK-NEXT:       %13 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc36)
// CHECK-NEXT:       llvm.store %c7_i256, %13 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc36)
// CHECK-NEXT:       %14 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc36)
// CHECK-NEXT:       %15 = "llvm.intrcall"(%14, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc36)
// CHECK-NEXT:       %16 = arith.addi %15, %10 : i256 loc(#loc36)
// CHECK-NEXT:       %17 = llvm.inttoptr %16 : i256 to !llvm.ptr<5> loc(#loc36)
// CHECK-NEXT:       llvm.store %c20_i256, %17 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc36)
// CHECK-NEXT:       %18 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc37)
// CHECK-NEXT:       %19 = llvm.load %18 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc37)
// CHECK-NEXT:       %20 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc37)
// CHECK-NEXT:       llvm.store %c0_i256, %20 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc37)
// CHECK-NEXT:       %21 = arith.cmpi ugt, %19, %c0_i256 : i256 loc(#loc37)
// CHECK-NEXT:       cf.cond_br %21, ^bb1, ^bb7 loc(#loc37)
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %22 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc37)
// CHECK-NEXT:       llvm.store %c7_i256, %22 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc37)
// CHECK-NEXT:       %23 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc37)
// CHECK-NEXT:       %24 = "llvm.intrcall"(%23, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc37)
// CHECK-NEXT:       cf.br ^bb2(%c0_i256 : i256) loc(#loc37)
// CHECK-NEXT:     ^bb2(%25: i256 loc({{.*}}:78:8)):  // 2 preds: ^bb1, ^bb6
// CHECK-NEXT:       %26 = arith.cmpi ult, %25, %19 : i256 loc(#loc37)
// CHECK-NEXT:       cf.cond_br %26, ^bb3(%25 : i256), ^bb7 loc(#loc37)
// CHECK-NEXT:     ^bb3(%27: i256 loc({{.*}}:78:8)):  // pred: ^bb2
// CHECK-NEXT:       %28 = arith.addi %24, %27 : i256 loc(#loc37)
// CHECK-NEXT:       cf.br ^bb4(%c0_i256 : i256) loc(#loc37)
// CHECK-NEXT:     ^bb4(%29: i256 loc({{.*}}:78:8)):  // 2 preds: ^bb3, ^bb5
// CHECK-NEXT:       %30 = arith.cmpi ult, %29, %c1_i256 : i256 loc(#loc37)
// CHECK-NEXT:       cf.cond_br %30, ^bb5(%29 : i256), ^bb6(%27 : i256) loc(#loc37)
// CHECK-NEXT:     ^bb5(%31: i256 loc({{.*}}:78:8)):  // pred: ^bb4
// CHECK-NEXT:       %32 = arith.addi %28, %31 : i256 loc(#loc37)
// CHECK-NEXT:       %33 = llvm.inttoptr %32 : i256 to !llvm.ptr<5> loc(#loc37)
// CHECK-NEXT:       llvm.store %c0_i256, %33 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc37)
// CHECK-NEXT:       %34 = arith.addi %31, %c1_i256 : i256 loc(#loc37)
// CHECK-NEXT:       cf.br ^bb4(%34 : i256) {loop_annotation = #loop_annotation} loc(#loc37)
// CHECK-NEXT:     ^bb6(%35: i256 loc({{.*}}:78:8)):  // pred: ^bb4
// CHECK-NEXT:       %36 = arith.addi %35, %c1_i256 : i256 loc(#loc37)
// CHECK-NEXT:       cf.br ^bb2(%36 : i256) loc(#loc37)
// CHECK-NEXT:     ^bb7:  // 2 preds: ^bb0, ^bb2
// CHECK-NEXT:       return loc(#loc34)
// CHECK-NEXT:     } loc(#loc34)
// CHECK-NEXT:     func.func @deleteStaticArr_176() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c6_i256 = arith.constant 6 : i256 loc(#loc)
// CHECK-NEXT:       %c2_i256 = arith.constant 2 : i256 loc(#loc)
// CHECK-NEXT:       %c5_i256 = arith.constant 5 : i256 loc(#loc)
// CHECK-NEXT:       %c3_i256 = arith.constant 3 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<5> loc(#loc39)
// CHECK-NEXT:       llvm.store %c1_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc39)
// CHECK-NEXT:       %1 = llvm.inttoptr %c5_i256 : i256 to !llvm.ptr<5> loc(#loc40)
// CHECK-NEXT:       llvm.store %c2_i256, %1 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc40)
// CHECK-NEXT:       %2 = llvm.inttoptr %c6_i256 : i256 to !llvm.ptr<5> loc(#loc41)
// CHECK-NEXT:       llvm.store %c3_i256, %2 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc41)
// CHECK-NEXT:       cf.br ^bb1(%c0_i256 : i256) loc(#loc42)
// CHECK-NEXT:     ^bb1(%3: i256 loc({{.*}}:72:8)):  // 2 preds: ^bb0, ^bb2
// CHECK-NEXT:       %4 = arith.cmpi ult, %3, %c3_i256 : i256 loc(#loc42)
// CHECK-NEXT:       cf.cond_br %4, ^bb2(%3 : i256), ^bb3 loc(#loc42)
// CHECK-NEXT:     ^bb2(%5: i256 loc({{.*}}:72:8)):  // pred: ^bb1
// CHECK-NEXT:       %6 = arith.addi %5, %c4_i256 : i256 loc(#loc42)
// CHECK-NEXT:       %7 = llvm.inttoptr %6 : i256 to !llvm.ptr<5> loc(#loc42)
// CHECK-NEXT:       llvm.store %c0_i256, %7 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc42)
// CHECK-NEXT:       %8 = arith.addi %5, %c1_i256 : i256 loc(#loc42)
// CHECK-NEXT:       cf.br ^bb1(%8 : i256) {loop_annotation = #loop_annotation} loc(#loc42)
// CHECK-NEXT:     ^bb3:  // pred: ^bb1
// CHECK-NEXT:       return loc(#loc38)
// CHECK-NEXT:     } loc(#loc38)
// CHECK-NEXT:     func.func @deleteStaticElem_151() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c3_i256 = arith.constant 3 : i256 loc(#loc)
// CHECK-NEXT:       %c6_i256 = arith.constant 6 : i256 loc(#loc)
// CHECK-NEXT:       %c2_i256 = arith.constant 2 : i256 loc(#loc)
// CHECK-NEXT:       %c5_i256 = arith.constant 5 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc44)
// CHECK-NEXT:       %0 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<5> loc(#loc44)
// CHECK-NEXT:       llvm.store %c1_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc44)
// CHECK-NEXT:       %1 = llvm.inttoptr %c5_i256 : i256 to !llvm.ptr<5> loc(#loc45)
// CHECK-NEXT:       llvm.store %c2_i256, %1 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc45)
// CHECK-NEXT:       %2 = llvm.inttoptr %c6_i256 : i256 to !llvm.ptr<5> loc(#loc46)
// CHECK-NEXT:       llvm.store %c3_i256, %2 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc46)
// CHECK-NEXT:       %3 = llvm.inttoptr %c5_i256 : i256 to !llvm.ptr<5> loc(#loc47)
// CHECK-NEXT:       llvm.store %c0_i256, %3 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc47)
// CHECK-NEXT:       return loc(#loc43)
// CHECK-NEXT:     } loc(#loc43)
// CHECK-NEXT:     func.func @deleteEnum_124() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c-16711681_i256 = arith.constant -16711681 : i256 loc(#loc)
// CHECK-NEXT:       %c3_i256 = arith.constant 3 : i256 loc(#loc49)
// CHECK-NEXT:       %0 = llvm.inttoptr %c3_i256 : i256 to !llvm.ptr<5> loc(#loc50)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc50)
// CHECK-NEXT:       %2 = arith.andi %1, %c-16711681_i256 : i256 loc(#loc50)
// CHECK-NEXT:       %3 = llvm.inttoptr %c3_i256 : i256 to !llvm.ptr<5> loc(#loc50)
// CHECK-NEXT:       llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc50)
// CHECK-NEXT:       return loc(#loc48)
// CHECK-NEXT:     } loc(#loc48)
// CHECK-NEXT:     func.func @deleteInt_117() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c-65536_i256 = arith.constant -65536 : i256 loc(#loc)
// CHECK-NEXT:       %c65535_i256 = arith.constant 65535 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c3_i256 = arith.constant 3 : i256 loc(#loc52)
// CHECK-NEXT:       %0 = "llvm.intrcall"(%c1_i256, %c0_i256) <{id = 4088 : i32, name = "evm.signextend"}> : (i256, i256) -> i256 loc(#loc53)
// CHECK-NEXT:       %1 = arith.andi %0, %c65535_i256 : i256 loc(#loc53)
// CHECK-NEXT:       %2 = llvm.inttoptr %c3_i256 : i256 to !llvm.ptr<5> loc(#loc53)
// CHECK-NEXT:       %3 = llvm.load %2 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc53)
// CHECK-NEXT:       %4 = arith.andi %3, %c-65536_i256 : i256 loc(#loc53)
// CHECK-NEXT:       %5 = arith.ori %4, %1 : i256 loc(#loc53)
// CHECK-NEXT:       %6 = llvm.inttoptr %c3_i256 : i256 to !llvm.ptr<5> loc(#loc53)
// CHECK-NEXT:       llvm.store %5, %6 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc53)
// CHECK-NEXT:       return loc(#loc51)
// CHECK-NEXT:     } loc(#loc51)
// CHECK-NEXT:     func.func @deleteBytes_110() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c2_i256 = arith.constant 2 : i256 loc(#loc55)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc56)
// CHECK-NEXT:       %0 = llvm.inttoptr %c2_i256 : i256 to !llvm.ptr<5> loc(#loc56)
// CHECK-NEXT:       llvm.store %c0_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc56)
// CHECK-NEXT:       return loc(#loc54)
// CHECK-NEXT:     } loc(#loc54)
// CHECK-NEXT:     func.func @deleteAddr_103() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c-374144419156711147060143317175368453031918731001601_i256 = arith.constant -374144419156711147060143317175368453031918731001601 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c1_i256 : i256 to !llvm.ptr<5> loc(#loc58)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc58)
// CHECK-NEXT:       %2 = arith.andi %1, %c-374144419156711147060143317175368453031918731001601_i256 : i256 loc(#loc58)
// CHECK-NEXT:       %3 = llvm.inttoptr %c1_i256 : i256 to !llvm.ptr<5> loc(#loc58)
// CHECK-NEXT:       llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc58)
// CHECK-NEXT:       return loc(#loc57)
// CHECK-NEXT:     } loc(#loc57)
// CHECK-NEXT:     func.func @deleteBool_96() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c-256_i256 = arith.constant -256 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc60)
// CHECK-NEXT:       %0 = llvm.inttoptr %c1_i256 : i256 to !llvm.ptr<5> loc(#loc61)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc61)
// CHECK-NEXT:       %2 = arith.andi %1, %c-256_i256 : i256 loc(#loc61)
// CHECK-NEXT:       %3 = llvm.inttoptr %c1_i256 : i256 to !llvm.ptr<5> loc(#loc61)
// CHECK-NEXT:       llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc61)
// CHECK-NEXT:       return loc(#loc59)
// CHECK-NEXT:     } loc(#loc59)
// CHECK-NEXT:     func.func @deleteUint_89() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<5> loc(#loc63)
// CHECK-NEXT:       llvm.store %c0_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc63)
// CHECK-NEXT:       return loc(#loc62)
// CHECK-NEXT:     } loc(#loc62)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:130:4)
// CHECK-NEXT: #loc3 = loc({{.*}}:31:4)
// CHECK-NEXT: #loc5 = loc({{.*}}:124:4)
// CHECK-NEXT: #loc6 = loc({{.*}}:30:4)
// CHECK-NEXT: #loc8 = loc({{.*}}:118:4)
// CHECK-NEXT: #loc9 = loc({{.*}}:29:4)
// CHECK-NEXT: #loc11 = loc({{.*}}:112:4)
// CHECK-NEXT: #loc12 = loc({{.*}}:28:4)
// CHECK-NEXT: #loc13 = loc({{.*}}:113:8)
// CHECK-NEXT: #loc14 = loc({{.*}}:106:4)
// CHECK-NEXT: #loc15 = loc({{.*}}:27:4)
// CHECK-NEXT: #loc17 = loc({{.*}}:100:4)
// CHECK-NEXT: #loc18 = loc({{.*}}:26:4)
// CHECK-NEXT: #loc20 = loc({{.*}}:95:4)
// CHECK-NEXT: #loc21 = loc({{.*}}:25:4)
// CHECK-NEXT: #loc23 = loc({{.*}}:88:4)
// CHECK-NEXT: #loc24 = loc({{.*}}:89:8)
// CHECK-NEXT: #loc25 = loc({{.*}}:90:8)
// CHECK-NEXT: #loc26 = loc({{.*}}:91:15)
// CHECK-NEXT: #loc27 = loc({{.*}}:91:8)
// CHECK-NEXT: #loc28 = loc({{.*}}:82:4)
// CHECK-NEXT: #loc29 = loc({{.*}}:83:8)
// CHECK-NEXT: #loc30 = loc({{.*}}:83:24)
// CHECK-NEXT: #loc31 = loc({{.*}}:83:40)
// CHECK-NEXT: #loc32 = loc({{.*}}:84:15)
// CHECK-NEXT: #loc33 = loc({{.*}}:84:8)
// CHECK-NEXT: #loc34 = loc({{.*}}:76:4)
// CHECK-NEXT: #loc35 = loc({{.*}}:77:8)
// CHECK-NEXT: #loc36 = loc({{.*}}:77:25)
// CHECK-NEXT: #loc38 = loc({{.*}}:70:4)
// CHECK-NEXT: #loc39 = loc({{.*}}:71:8)
// CHECK-NEXT: #loc40 = loc({{.*}}:71:26)
// CHECK-NEXT: #loc41 = loc({{.*}}:71:44)
// CHECK-NEXT: #loc43 = loc({{.*}}:64:4)
// CHECK-NEXT: #loc44 = loc({{.*}}:65:8)
// CHECK-NEXT: #loc45 = loc({{.*}}:65:26)
// CHECK-NEXT: #loc46 = loc({{.*}}:65:44)
// CHECK-NEXT: #loc47 = loc({{.*}}:66:8)
// CHECK-NEXT: #loc48 = loc({{.*}}:59:4)
// CHECK-NEXT: #loc49 = loc({{.*}}:20:4)
// CHECK-NEXT: #loc50 = loc({{.*}}:60:8)
// CHECK-NEXT: #loc51 = loc({{.*}}:54:4)
// CHECK-NEXT: #loc52 = loc({{.*}}:19:4)
// CHECK-NEXT: #loc53 = loc({{.*}}:55:8)
// CHECK-NEXT: #loc54 = loc({{.*}}:49:4)
// CHECK-NEXT: #loc55 = loc({{.*}}:18:4)
// CHECK-NEXT: #loc56 = loc({{.*}}:50:8)
// CHECK-NEXT: #loc57 = loc({{.*}}:44:4)
// CHECK-NEXT: #loc58 = loc({{.*}}:45:8)
// CHECK-NEXT: #loc59 = loc({{.*}}:39:4)
// CHECK-NEXT: #loc60 = loc({{.*}}:16:4)
// CHECK-NEXT: #loc61 = loc({{.*}}:40:8)
// CHECK-NEXT: #loc62 = loc({{.*}}:34:4)
// CHECK-NEXT: #loc63 = loc({{.*}}:35:8)
// CHECK-EMPTY:
