// RUN: solc --mlir-action=print-std-mlir --mlir-target=evm --mmlir --mlir-print-debuginfo %s | FileCheck %s

enum E { A, B, C }

function cmp(E a, E b) returns (bool, bool) {
  return (a == b, a < b);
}

function fromUint(uint x) returns (E) {
  return E(x);
}

function toUint(E x) returns (uint) {
  return uint(x);
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #loc3 = loc({{.*}}:4:13)
// CHECK-NEXT: #loc4 = loc({{.*}}:4:18)
// CHECK-NEXT: #loc11 = loc({{.*}}:8:18)
// CHECK-NEXT: #loc14 = loc({{.*}}:12:16)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka} {
// CHECK-NEXT:   func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @cmp_26(%arg0: i256 loc({{.*}}:4:13), %arg1: i256 loc({{.*}}:4:18)) -> (i1, i1) attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc3)
// CHECK-NEXT:     llvm.store %arg0, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc3)
// CHECK-NEXT:     %1 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc4)
// CHECK-NEXT:     llvm.store %arg1, %1 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc4)
// CHECK-NEXT:     %2 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc5)
// CHECK-NEXT:     %3 = llvm.load %1 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc6)
// CHECK-NEXT:     %4 = arith.cmpi eq, %2, %3 : i256 loc(#loc5)
// CHECK-NEXT:     %5 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc7)
// CHECK-NEXT:     %6 = llvm.load %1 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc8)
// CHECK-NEXT:     %7 = arith.cmpi ult, %5, %6 : i256 loc(#loc7)
// CHECK-NEXT:     return %4, %7 : i1, i1 loc(#loc9)
// CHECK-NEXT:   } loc(#loc2)
// CHECK-NEXT:   func.func @fromUint_39(%arg0: i256 loc({{.*}}:8:18)) -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:     %c33_i256 = arith.constant 33 : i256 loc(#loc)
// CHECK-NEXT:     %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:     %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:     %c2_i256 = arith.constant 2 : i256 loc(#loc)
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc11)
// CHECK-NEXT:     %0 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc11)
// CHECK-NEXT:     llvm.store %arg0, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc11)
// CHECK-NEXT:     %1 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc1)
// CHECK-NEXT:     %2 = arith.cmpi ugt, %1, %c2_i256 : i256 loc(#loc1)
// CHECK-NEXT:     scf.if %2 {
// CHECK-NEXT:       %3 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %3 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %4 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %c33_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %5 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%5, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       func.call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     return %1 : i256 loc(#loc12)
// CHECK-NEXT:   } loc(#loc10)
// CHECK-NEXT:   func.func @toUint_53(%arg0: i256 loc({{.*}}:12:16)) -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc14)
// CHECK-NEXT:     %0 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc14)
// CHECK-NEXT:     llvm.store %arg0, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc14)
// CHECK-NEXT:     %1 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc15)
// CHECK-NEXT:     return %1 : i256 loc(#loc16)
// CHECK-NEXT:   } loc(#loc13)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:9:11)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:0)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:10)
// CHECK-NEXT: #loc6 = loc({{.*}}:5:15)
// CHECK-NEXT: #loc7 = loc({{.*}}:5:18)
// CHECK-NEXT: #loc8 = loc({{.*}}:5:22)
// CHECK-NEXT: #loc9 = loc({{.*}}:5:2)
// CHECK-NEXT: #loc10 = loc({{.*}}:8:0)
// CHECK-NEXT: #loc12 = loc({{.*}}:9:2)
// CHECK-NEXT: #loc13 = loc({{.*}}:12:0)
// CHECK-NEXT: #loc15 = loc({{.*}}:13:14)
// CHECK-NEXT: #loc16 = loc({{.*}}:13:2)
// CHECK-EMPTY:
