// RUN: solc --mlir-target=evm --mlir-action=print-std-mlir %s | FileCheck %s

contract C {
  uint[] sa;
  uint[] sb;

  function slotRewrite() public returns (uint) {
    sa.push(1);
    sb.push(2);
    uint[] storage p = sa;
    assembly { p.slot := sb.slot }
    return p[0];
  }

  function memRewrite() public pure returns (uint) {
    bytes memory a = hex"aa";
    bytes memory b = hex"bbcc";
    assembly { a := b }
    return a.length;
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module @C_55 attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     llvm.unreachable
// CHECK-NEXT:   }
// CHECK-NEXT:   func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c36_i256 = arith.constant 36 : i256
// CHECK-NEXT:     %c65_i256 = arith.constant 65 : i256
// CHECK-NEXT:     %c4_i256 = arith.constant 4 : i256
// CHECK-NEXT:     %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256
// CHECK-NEXT:     %c18446744073709551615_i256 = arith.constant 18446744073709551615 : i256
// CHECK-NEXT:     %c-32_i256 = arith.constant -32 : i256
// CHECK-NEXT:     %c31_i256 = arith.constant 31 : i256
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256
// CHECK-NEXT:     %c128_i256 = arith.constant 128 : i256
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256
// CHECK-NEXT:     %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:     llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:     %1 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256
// CHECK-NEXT:     %2 = arith.cmpi ne, %1, %c0_i256 : i256
// CHECK-NEXT:     cf.cond_br %2, ^bb1, ^bb2
// CHECK-NEXT:   ^bb1:  // pred: ^bb0
// CHECK-NEXT:     %3 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:     "llvm.intrcall"(%3, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> ()
// CHECK-NEXT:     call @".unreachable"() : () -> ()
// CHECK-NEXT:     cf.br ^bb2
// CHECK-NEXT:   ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:     %4 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["C_55"], name = "evm.datasize"}> : () -> i256
// CHECK-NEXT:     %5 = "llvm.intrcall"() <{id = 4042 : i32, name = "evm.codesize"}> : () -> i256
// CHECK-NEXT:     %6 = arith.subi %5, %4 : i256
// CHECK-NEXT:     %7 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:     %8 = llvm.load %7 {alignment = 1 : i64} : !llvm.ptr<1> -> i256
// CHECK-NEXT:     %9 = arith.addi %6, %c31_i256 : i256
// CHECK-NEXT:     %10 = arith.andi %9, %c-32_i256 : i256
// CHECK-NEXT:     %11 = arith.addi %8, %10 : i256
// CHECK-NEXT:     %12 = arith.cmpi ugt, %11, %c18446744073709551615_i256 : i256
// CHECK-NEXT:     %13 = arith.cmpi ult, %11, %8 : i256
// CHECK-NEXT:     %14 = arith.ori %12, %13 : i1
// CHECK-NEXT:     cf.cond_br %14, ^bb3, ^bb4
// CHECK-NEXT:   ^bb3:  // pred: ^bb2
// CHECK-NEXT:     %15 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:     llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %15 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:     %16 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:     llvm.store %c65_i256, %16 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:     %17 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:     "llvm.intrcall"(%17, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> ()
// CHECK-NEXT:     call @".unreachable"() : () -> ()
// CHECK-NEXT:     cf.br ^bb4
// CHECK-NEXT:   ^bb4:  // 2 preds: ^bb2, ^bb3
// CHECK-NEXT:     %18 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:     llvm.store %11, %18 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:     %19 = llvm.inttoptr %8 : i256 to !llvm.ptr<1>
// CHECK-NEXT:     %20 = llvm.inttoptr %4 : i256 to !llvm.ptr<4>
// CHECK-NEXT:     "llvm.intr.memcpy"(%19, %20, %6) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> ()
// CHECK-NEXT:     call @C_55() : () -> ()
// CHECK-NEXT:     %21 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:     %22 = llvm.load %21 {alignment = 1 : i64} : !llvm.ptr<1> -> i256
// CHECK-NEXT:     %23 = "llvm.intrcall"() <{id = 4046 : i32, metadata = ["C_55_deployed"], name = "evm.dataoffset"}> : () -> i256
// CHECK-NEXT:     %24 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["C_55_deployed"], name = "evm.datasize"}> : () -> i256
// CHECK-NEXT:     %25 = llvm.inttoptr %22 : i256 to !llvm.ptr<1>
// CHECK-NEXT:     %26 = llvm.inttoptr %23 : i256 to !llvm.ptr<4>
// CHECK-NEXT:     "llvm.intr.memcpy"(%25, %26, %24) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> ()
// CHECK-NEXT:     %27 = llvm.inttoptr %22 : i256 to !llvm.ptr<1>
// CHECK-NEXT:     "llvm.intrcall"(%27, %24) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> ()
// CHECK-NEXT:     call @".unreachable"() : () -> ()
// CHECK-NEXT:     llvm.unreachable
// CHECK-NEXT:   }
// CHECK-NEXT:   func.func @C_55() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     return
// CHECK-NEXT:   }
// CHECK-NEXT:   module @C_55_deployed attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:     func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       llvm.unreachable
// CHECK-NEXT:     }
// CHECK-NEXT:     func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256
// CHECK-NEXT:       %c224_i256 = arith.constant 224 : i256
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256
// CHECK-NEXT:       %c128_i256 = arith.constant 128 : i256
// CHECK-NEXT:       %c64_i256 = arith.constant 64 : i256
// CHECK-NEXT:       %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %1 = "llvm.intrcall"() <{id = 4038 : i32, name = "evm.calldatasize"}> : () -> i256
// CHECK-NEXT:       %2 = arith.cmpi uge, %1, %c4_i256 : i256
// CHECK-NEXT:       cf.cond_br %2, ^bb1, ^bb8
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %3 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<2>
// CHECK-NEXT:       %4 = llvm.load %3 {alignment = 1 : i64} : !llvm.ptr<2> -> i256
// CHECK-NEXT:       %5 = arith.shrui %4, %c224_i256 : i256
// CHECK-NEXT:       cf.switch %5 : i256, [
// CHECK-NEXT:         default: ^bb8,
// CHECK-NEXT:         747285107: ^bb2,
// CHECK-NEXT:         1542083971: ^bb5
// CHECK-NEXT:       ]
// CHECK-NEXT:     ^bb2:  // pred: ^bb1
// CHECK-NEXT:       %6 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256
// CHECK-NEXT:       %7 = arith.cmpi ne, %6, %c0_i256 : i256
// CHECK-NEXT:       cf.cond_br %7, ^bb3, ^bb4
// CHECK-NEXT:     ^bb3:  // pred: ^bb2
// CHECK-NEXT:       %8 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       "llvm.intrcall"(%8, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> ()
// CHECK-NEXT:       call @".unreachable"() : () -> ()
// CHECK-NEXT:       cf.br ^bb4
// CHECK-NEXT:     ^bb4:  // 2 preds: ^bb2, ^bb3
// CHECK-NEXT:       %9 = call @slotRewrite_36() : () -> i256
// CHECK-NEXT:       %10 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       %11 = llvm.load %10 {alignment = 1 : i64} : !llvm.ptr<1> -> i256
// CHECK-NEXT:       %12 = llvm.inttoptr %11 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %9, %12 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %13 = llvm.inttoptr %11 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       "llvm.intrcall"(%13, %c32_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> ()
// CHECK-NEXT:       call @".unreachable"() : () -> ()
// CHECK-NEXT:       cf.br ^bb8
// CHECK-NEXT:     ^bb5:  // pred: ^bb1
// CHECK-NEXT:       %14 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256
// CHECK-NEXT:       %15 = arith.cmpi ne, %14, %c0_i256 : i256
// CHECK-NEXT:       cf.cond_br %15, ^bb6, ^bb7
// CHECK-NEXT:     ^bb6:  // pred: ^bb5
// CHECK-NEXT:       %16 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       "llvm.intrcall"(%16, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> ()
// CHECK-NEXT:       call @".unreachable"() : () -> ()
// CHECK-NEXT:       cf.br ^bb7
// CHECK-NEXT:     ^bb7:  // 2 preds: ^bb5, ^bb6
// CHECK-NEXT:       %17 = call @memRewrite_54() : () -> i256
// CHECK-NEXT:       %18 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       %19 = llvm.load %18 {alignment = 1 : i64} : !llvm.ptr<1> -> i256
// CHECK-NEXT:       %20 = llvm.inttoptr %19 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %17, %20 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %21 = llvm.inttoptr %19 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       "llvm.intrcall"(%21, %c32_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> ()
// CHECK-NEXT:       call @".unreachable"() : () -> ()
// CHECK-NEXT:       cf.br ^bb8
// CHECK-NEXT:     ^bb8:  // 4 preds: ^bb0, ^bb1, ^bb4, ^bb7
// CHECK-NEXT:       %22 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       "llvm.intrcall"(%22, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> ()
// CHECK-NEXT:       call @".unreachable"() : () -> ()
// CHECK-NEXT:       llvm.unreachable
// CHECK-NEXT:     }
// CHECK-NEXT:     func.func @memRewrite_54() -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c-30849149751030590394524374362971357286347868839448307008803244274569141288960_i256 = arith.constant -30849149751030590394524374362971357286347868839448307008803244274569141288960 : i256
// CHECK-NEXT:       %c2_i256 = arith.constant 2 : i256
// CHECK-NEXT:       %c-38898904978160909400105877776356094044457885473613626982005282127658316988416_i256 = arith.constant -38898904978160909400105877776356094044457885473613626982005282127658316988416 : i256
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256
// CHECK-NEXT:       %c36_i256 = arith.constant 36 : i256
// CHECK-NEXT:       %c65_i256 = arith.constant 65 : i256
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256
// CHECK-NEXT:       %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256
// CHECK-NEXT:       %c18446744073709551615_i256 = arith.constant 18446744073709551615 : i256
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256
// CHECK-NEXT:       %c64_i256 = arith.constant 64 : i256
// CHECK-NEXT:       %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<1> -> i256
// CHECK-NEXT:       %2 = arith.addi %1, %c64_i256 : i256
// CHECK-NEXT:       %3 = arith.cmpi ugt, %2, %c18446744073709551615_i256 : i256
// CHECK-NEXT:       %4 = arith.cmpi ult, %2, %1 : i256
// CHECK-NEXT:       %5 = arith.ori %3, %4 : i1
// CHECK-NEXT:       cf.cond_br %5, ^bb1, ^bb2
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %6 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %6 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %7 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %c65_i256, %7 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %8 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       "llvm.intrcall"(%8, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> ()
// CHECK-NEXT:       call @".unreachable"() : () -> ()
// CHECK-NEXT:       cf.br ^bb2
// CHECK-NEXT:     ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:       %9 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %2, %9 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %10 = llvm.inttoptr %1 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %c1_i256, %10 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %11 = arith.addi %1, %c32_i256 : i256
// CHECK-NEXT:       %12 = llvm.inttoptr %11 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %c-38898904978160909400105877776356094044457885473613626982005282127658316988416_i256, %12 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %13 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr
// CHECK-NEXT:       llvm.store %1, %13 {alignment = 32 : i64} : i256, !llvm.ptr
// CHECK-NEXT:       %14 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       %15 = llvm.load %14 {alignment = 1 : i64} : !llvm.ptr<1> -> i256
// CHECK-NEXT:       %16 = arith.addi %15, %c64_i256 : i256
// CHECK-NEXT:       %17 = arith.cmpi ugt, %16, %c18446744073709551615_i256 : i256
// CHECK-NEXT:       %18 = arith.cmpi ult, %16, %15 : i256
// CHECK-NEXT:       %19 = arith.ori %17, %18 : i1
// CHECK-NEXT:       cf.cond_br %19, ^bb3, ^bb4
// CHECK-NEXT:     ^bb3:  // pred: ^bb2
// CHECK-NEXT:       %20 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %20 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %21 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %c65_i256, %21 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %22 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       "llvm.intrcall"(%22, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> ()
// CHECK-NEXT:       call @".unreachable"() : () -> ()
// CHECK-NEXT:       cf.br ^bb4
// CHECK-NEXT:     ^bb4:  // 2 preds: ^bb2, ^bb3
// CHECK-NEXT:       %23 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %16, %23 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %24 = llvm.inttoptr %15 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %c2_i256, %24 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %25 = arith.addi %15, %c32_i256 : i256
// CHECK-NEXT:       %26 = llvm.inttoptr %25 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %c-30849149751030590394524374362971357286347868839448307008803244274569141288960_i256, %26 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %27 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr
// CHECK-NEXT:       llvm.store %15, %27 {alignment = 32 : i64} : i256, !llvm.ptr
// CHECK-NEXT:       %28 = llvm.load %27 {alignment = 32 : i64} : !llvm.ptr -> i256
// CHECK-NEXT:       llvm.store %28, %13 {alignment = 32 : i64} : i256, !llvm.ptr
// CHECK-NEXT:       %29 = llvm.load %13 {alignment = 32 : i64} : !llvm.ptr -> i256
// CHECK-NEXT:       %30 = llvm.inttoptr %29 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       %31 = llvm.load %30 {alignment = 1 : i64} : !llvm.ptr<1> -> i256
// CHECK-NEXT:       return %31 : i256
// CHECK-NEXT:     }
// CHECK-NEXT:     func.func @slotRewrite_36() -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c2_i256 = arith.constant 2 : i256
// CHECK-NEXT:       %c36_i256 = arith.constant 36 : i256
// CHECK-NEXT:       %c50_i256 = arith.constant 50 : i256
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256
// CHECK-NEXT:       %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256
// CHECK-NEXT:       %0 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<5>
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256
// CHECK-NEXT:       %2 = arith.addi %1, %c1_i256 : i256
// CHECK-NEXT:       %3 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<5>
// CHECK-NEXT:       llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<5>
// CHECK-NEXT:       %4 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %c0_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %5 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       %6 = "llvm.intrcall"(%5, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256
// CHECK-NEXT:       %7 = arith.addi %6, %1 : i256
// CHECK-NEXT:       %8 = llvm.inttoptr %7 : i256 to !llvm.ptr<5>
// CHECK-NEXT:       llvm.store %c1_i256, %8 {alignment = 1 : i64} : i256, !llvm.ptr<5>
// CHECK-NEXT:       %9 = llvm.inttoptr %c1_i256 : i256 to !llvm.ptr<5>
// CHECK-NEXT:       %10 = llvm.load %9 {alignment = 1 : i64} : !llvm.ptr<5> -> i256
// CHECK-NEXT:       %11 = arith.addi %10, %c1_i256 : i256
// CHECK-NEXT:       %12 = llvm.inttoptr %c1_i256 : i256 to !llvm.ptr<5>
// CHECK-NEXT:       llvm.store %11, %12 {alignment = 1 : i64} : i256, !llvm.ptr<5>
// CHECK-NEXT:       %13 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %c1_i256, %13 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %14 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       %15 = "llvm.intrcall"(%14, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256
// CHECK-NEXT:       %16 = arith.addi %15, %10 : i256
// CHECK-NEXT:       %17 = llvm.inttoptr %16 : i256 to !llvm.ptr<5>
// CHECK-NEXT:       llvm.store %c2_i256, %17 {alignment = 1 : i64} : i256, !llvm.ptr<5>
// CHECK-NEXT:       %18 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr
// CHECK-NEXT:       llvm.store %c0_i256, %18 {alignment = 32 : i64} : i256, !llvm.ptr
// CHECK-NEXT:       llvm.store %c1_i256, %18 {alignment = 32 : i64} : i256, !llvm.ptr
// CHECK-NEXT:       %19 = llvm.load %18 {alignment = 32 : i64} : !llvm.ptr -> i256
// CHECK-NEXT:       %20 = llvm.inttoptr %19 : i256 to !llvm.ptr<5>
// CHECK-NEXT:       %21 = llvm.load %20 {alignment = 1 : i64} : !llvm.ptr<5> -> i256
// CHECK-NEXT:       %22 = arith.cmpi ule, %21, %c0_i256 : i256
// CHECK-NEXT:       cf.cond_br %22, ^bb1, ^bb2
// CHECK-NEXT:     ^bb1:  // pred: ^bb0
// CHECK-NEXT:       %23 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %23 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %24 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %c50_i256, %24 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %25 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       "llvm.intrcall"(%25, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> ()
// CHECK-NEXT:       call @".unreachable"() : () -> ()
// CHECK-NEXT:       cf.br ^bb2
// CHECK-NEXT:     ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:       %26 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       llvm.store %19, %26 {alignment = 1 : i64} : i256, !llvm.ptr<1>
// CHECK-NEXT:       %27 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1>
// CHECK-NEXT:       %28 = "llvm.intrcall"(%27, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256
// CHECK-NEXT:       %29 = llvm.inttoptr %28 : i256 to !llvm.ptr<5>
// CHECK-NEXT:       %30 = llvm.load %29 {alignment = 1 : i64} : !llvm.ptr<5> -> i256
// CHECK-NEXT:       return %30 : i256
// CHECK-NEXT:     }
// CHECK-NEXT:   }
// CHECK-NEXT: }
// CHECK-EMPTY:
