// RUN: solc --mlir-action=print-std-mlir --mmlir --mlir-print-debuginfo %s | FileCheck %s

struct S {
  function(uint) external pure returns (uint) fp;
  uint256 x;
}

function structGet(S memory s) returns (function(uint) external pure returns (uint)) {
  return s.fp;
}

function structSet(S memory s, function(uint) external pure returns (uint) fp) {
  s.fp = fp;
}

function arrayGet(function(uint) external pure returns (uint)[3] memory a, uint i) returns (function(uint) external pure returns (uint)) {
  return a[i];
}

function arraySet(function(uint) external pure returns (uint)[3] memory a, uint i, function(uint) external pure returns (uint) fp) {
  a[i] = fp;
}

function zeroInitFnptr() pure returns (function(uint) external pure returns (uint)) {
  function(uint) external pure returns (uint) fp;
  return fp;
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: #loc3 = loc({{.*}}:7:19)
// CHECK-NEXT: #loc7 = loc({{.*}}:11:19)
// CHECK-NEXT: #loc8 = loc({{.*}}:11:31)
// CHECK-NEXT: #loc12 = loc({{.*}}:15:18)
// CHECK-NEXT: #loc13 = loc({{.*}}:15:75)
// CHECK-NEXT: #loc17 = loc({{.*}}:19:18)
// CHECK-NEXT: #loc18 = loc({{.*}}:19:75)
// CHECK-NEXT: #loc19 = loc({{.*}}:19:83)
// CHECK-NEXT: module attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @structGet_29(%arg0: i256 loc({{.*}}:7:19)) -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc3)
// CHECK-NEXT:     %0 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc3)
// CHECK-NEXT:     llvm.store %arg0, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc3)
// CHECK-NEXT:     %1 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc4)
// CHECK-NEXT:     %2 = llvm.inttoptr %1 : i256 to !llvm.ptr<1> loc(#loc4)
// CHECK-NEXT:     %3 = llvm.load %2 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc4)
// CHECK-NEXT:     return %3 : i256 loc(#loc5)
// CHECK-NEXT:   } loc(#loc2)
// CHECK-NEXT:   func.func @structSet_50(%arg0: i256 loc({{.*}}:11:19), %arg1: i256 loc({{.*}}:11:31)) attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c-18446744073709551616_i256 = arith.constant -18446744073709551616 : i256 loc(#loc)
// CHECK-NEXT:     %c96_i256 = arith.constant 96 : i256 loc(#loc)
// CHECK-NEXT:     %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:     %c4294967295_i256 = arith.constant 4294967295 : i256 loc(#loc)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc7)
// CHECK-NEXT:     llvm.store %arg0, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc7)
// CHECK-NEXT:     %1 = llvm.alloca %c1_i256 x !llvm.struct<(i256, i256)> : (i256) -> !llvm.ptr loc(#loc8)
// CHECK-NEXT:     %2 = llvm.getelementptr %1[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i256, i256)> loc(#loc8)
// CHECK-NEXT:     %3 = llvm.getelementptr %1[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i256, i256)> loc(#loc8)
// CHECK-NEXT:     %4 = arith.shrui %arg1, %c64_i256 : i256 loc(#loc8)
// CHECK-NEXT:     %5 = arith.andi %4, %c4294967295_i256 : i256 loc(#loc8)
// CHECK-NEXT:     %6 = arith.shrui %4, %c32_i256 : i256 loc(#loc8)
// CHECK-NEXT:     llvm.store %6, %2 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc8)
// CHECK-NEXT:     llvm.store %5, %3 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc8)
// CHECK-NEXT:     %7 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc9)
// CHECK-NEXT:     %8 = llvm.getelementptr %1[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i256, i256)> loc(#loc10)
// CHECK-NEXT:     %9 = llvm.getelementptr %1[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i256, i256)> loc(#loc10)
// CHECK-NEXT:     %10 = llvm.load %8 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc10)
// CHECK-NEXT:     %11 = llvm.load %9 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc10)
// CHECK-NEXT:     %12 = arith.shli %10, %c96_i256 : i256 loc(#loc10)
// CHECK-NEXT:     %13 = arith.shli %11, %c64_i256 : i256 loc(#loc10)
// CHECK-NEXT:     %14 = arith.ori %12, %13 : i256 loc(#loc10)
// CHECK-NEXT:     %15 = arith.andi %14, %c-18446744073709551616_i256 : i256 loc(#loc9)
// CHECK-NEXT:     %16 = llvm.inttoptr %7 : i256 to !llvm.ptr<1> loc(#loc9)
// CHECK-NEXT:     llvm.store %15, %16 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc9)
// CHECK-NEXT:     return loc(#loc6)
// CHECK-NEXT:   } loc(#loc6)
// CHECK-NEXT:   func.func @arrayGet_78(%arg0: i256 loc({{.*}}:15:18), %arg1: i256 loc({{.*}}:15:75)) -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:     %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:     %c50_i256 = arith.constant 50 : i256 loc(#loc)
// CHECK-NEXT:     %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:     %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:     %c3_i256 = arith.constant 3 : i256 loc(#loc)
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc12)
// CHECK-NEXT:     llvm.store %arg0, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc12)
// CHECK-NEXT:     %1 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc13)
// CHECK-NEXT:     llvm.store %arg1, %1 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc13)
// CHECK-NEXT:     %2 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc1)
// CHECK-NEXT:     %3 = llvm.load %1 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc14)
// CHECK-NEXT:     %4 = arith.cmpi uge, %3, %c3_i256 : i256 loc(#loc1)
// CHECK-NEXT:     cf.cond_br %4, ^bb1, ^bb2 loc(#loc1)
// CHECK-NEXT:   ^bb1:  // pred: ^bb0
// CHECK-NEXT:     %5 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %5 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %6 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c50_i256, %6 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %7 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%7, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     cf.br ^bb2 loc(#loc1)
// CHECK-NEXT:   ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:     %8 = arith.muli %3, %c32_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %9 = arith.addi %2, %8 : i256 loc(#loc1)
// CHECK-NEXT:     %10 = llvm.inttoptr %9 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %11 = llvm.load %10 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     return %11 : i256 loc(#loc15)
// CHECK-NEXT:   } loc(#loc11)
// CHECK-NEXT:   func.func @arraySet_108(%arg0: i256 loc({{.*}}:19:18), %arg1: i256 loc({{.*}}:19:75), %arg2: i256 loc({{.*}}:19:83)) attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c-18446744073709551616_i256 = arith.constant -18446744073709551616 : i256 loc(#loc)
// CHECK-NEXT:     %c96_i256 = arith.constant 96 : i256 loc(#loc)
// CHECK-NEXT:     %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:     %c50_i256 = arith.constant 50 : i256 loc(#loc)
// CHECK-NEXT:     %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:     %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:     %c3_i256 = arith.constant 3 : i256 loc(#loc)
// CHECK-NEXT:     %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:     %c4294967295_i256 = arith.constant 4294967295 : i256 loc(#loc)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc17)
// CHECK-NEXT:     llvm.store %arg0, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc17)
// CHECK-NEXT:     %1 = llvm.alloca %c1_i256 x i256 : (i256) -> !llvm.ptr loc(#loc18)
// CHECK-NEXT:     llvm.store %arg1, %1 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc18)
// CHECK-NEXT:     %2 = llvm.alloca %c1_i256 x !llvm.struct<(i256, i256)> : (i256) -> !llvm.ptr loc(#loc19)
// CHECK-NEXT:     %3 = llvm.getelementptr %2[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i256, i256)> loc(#loc19)
// CHECK-NEXT:     %4 = llvm.getelementptr %2[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i256, i256)> loc(#loc19)
// CHECK-NEXT:     %5 = arith.shrui %arg2, %c64_i256 : i256 loc(#loc19)
// CHECK-NEXT:     %6 = arith.andi %5, %c4294967295_i256 : i256 loc(#loc19)
// CHECK-NEXT:     %7 = arith.shrui %5, %c32_i256 : i256 loc(#loc19)
// CHECK-NEXT:     llvm.store %7, %3 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc19)
// CHECK-NEXT:     llvm.store %6, %4 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc19)
// CHECK-NEXT:     %8 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc20)
// CHECK-NEXT:     %9 = llvm.load %1 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc21)
// CHECK-NEXT:     %10 = arith.cmpi uge, %9, %c3_i256 : i256 loc(#loc20)
// CHECK-NEXT:     cf.cond_br %10, ^bb1, ^bb2 loc(#loc20)
// CHECK-NEXT:   ^bb1:  // pred: ^bb0
// CHECK-NEXT:     %11 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:     llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %11 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:     %12 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:     llvm.store %c50_i256, %12 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:     %13 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:     "llvm.intrcall"(%13, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc20)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc20)
// CHECK-NEXT:     cf.br ^bb2 loc(#loc20)
// CHECK-NEXT:   ^bb2:  // 2 preds: ^bb0, ^bb1
// CHECK-NEXT:     %14 = arith.muli %9, %c32_i256 : i256 loc(#loc20)
// CHECK-NEXT:     %15 = arith.addi %8, %14 : i256 loc(#loc20)
// CHECK-NEXT:     %16 = llvm.getelementptr %2[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i256, i256)> loc(#loc22)
// CHECK-NEXT:     %17 = llvm.getelementptr %2[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i256, i256)> loc(#loc22)
// CHECK-NEXT:     %18 = llvm.load %16 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc22)
// CHECK-NEXT:     %19 = llvm.load %17 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc22)
// CHECK-NEXT:     %20 = arith.shli %18, %c96_i256 : i256 loc(#loc22)
// CHECK-NEXT:     %21 = arith.shli %19, %c64_i256 : i256 loc(#loc22)
// CHECK-NEXT:     %22 = arith.ori %20, %21 : i256 loc(#loc22)
// CHECK-NEXT:     %23 = arith.andi %22, %c-18446744073709551616_i256 : i256 loc(#loc20)
// CHECK-NEXT:     %24 = llvm.inttoptr %15 : i256 to !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:     llvm.store %23, %24 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:     return loc(#loc16)
// CHECK-NEXT:   } loc(#loc16)
// CHECK-NEXT:   func.func @zeroInitFnptr_131() -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:     %c96_i256 = arith.constant 96 : i256 loc(#loc)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc24)
// CHECK-NEXT:     %0 = llvm.alloca %c1_i256 x !llvm.struct<(i256, i256)> : (i256) -> !llvm.ptr loc(#loc24)
// CHECK-NEXT:     %1 = llvm.getelementptr %0[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i256, i256)> loc(#loc24)
// CHECK-NEXT:     %2 = llvm.getelementptr %0[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i256, i256)> loc(#loc24)
// CHECK-NEXT:     llvm.store %c0_i256, %1 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc24)
// CHECK-NEXT:     llvm.store %c0_i256, %2 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc24)
// CHECK-NEXT:     %3 = llvm.getelementptr %0[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i256, i256)> loc(#loc25)
// CHECK-NEXT:     %4 = llvm.getelementptr %0[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i256, i256)> loc(#loc25)
// CHECK-NEXT:     %5 = llvm.load %3 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc25)
// CHECK-NEXT:     %6 = llvm.load %4 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc25)
// CHECK-NEXT:     %7 = arith.shli %5, %c96_i256 : i256 loc(#loc25)
// CHECK-NEXT:     %8 = arith.shli %6, %c64_i256 : i256 loc(#loc25)
// CHECK-NEXT:     %9 = arith.ori %7, %8 : i256 loc(#loc25)
// CHECK-NEXT:     return %9 : i256 loc(#loc26)
// CHECK-NEXT:   } loc(#loc23)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:16:9)
// CHECK-NEXT: #loc2 = loc({{.*}}:7:0)
// CHECK-NEXT: #loc4 = loc({{.*}}:8:9)
// CHECK-NEXT: #loc5 = loc({{.*}}:8:2)
// CHECK-NEXT: #loc6 = loc({{.*}}:11:0)
// CHECK-NEXT: #loc9 = loc({{.*}}:12:2)
// CHECK-NEXT: #loc10 = loc({{.*}}:12:9)
// CHECK-NEXT: #loc11 = loc({{.*}}:15:0)
// CHECK-NEXT: #loc14 = loc({{.*}}:16:11)
// CHECK-NEXT: #loc15 = loc({{.*}}:16:2)
// CHECK-NEXT: #loc16 = loc({{.*}}:19:0)
// CHECK-NEXT: #loc20 = loc({{.*}}:20:2)
// CHECK-NEXT: #loc21 = loc({{.*}}:20:4)
// CHECK-NEXT: #loc22 = loc({{.*}}:20:9)
// CHECK-NEXT: #loc23 = loc({{.*}}:23:0)
// CHECK-NEXT: #loc24 = loc({{.*}}:24:2)
// CHECK-NEXT: #loc25 = loc({{.*}}:25:9)
// CHECK-NEXT: #loc26 = loc({{.*}}:25:2)
// CHECK-EMPTY:
