// RUN: solc --mlir-action=print-std-mlir --mlir-target=evm --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
  // Packed struct
  struct Packed {
    uint8 a;
    uint8 b;
    uint16 c;
  }
  Packed packed;

  // Non-packed struct
  struct NonPacked {
    uint256 x;
    uint256 y;
  }
  NonPacked nonPacked;

  // Nested struct
  struct Inner {
    uint8 x;
    uint8 y;
  }
  struct Outer {
    Inner inner;
    uint8 z;
  }
  Outer nested;

  // Mixed struct (value + reference types)
  struct Mixed {
    uint8 x;
    uint256[] arr;
    uint8 y;
  }
  Mixed mixed;

  // Struct with contract-typed field
  struct ContractRef {
    uint96 x;
    C c;
  }
  ContractRef contractRef;

  // Nested struct where inner has a dynamic member.
  struct InnerDynamic {
    uint256 a;
    uint128 b;
    string note;
  }
  struct OuterDynamic {
    uint256 left;
    InnerDynamic inner;
    uint256 right;
  }
  OuterDynamic nestedDynamic;

  // Packed fixed-array member followed by scalar member.
  struct FixedArrayTail {
    uint8[4] a;
    uint256 tail;
  }
  FixedArrayTail fixedArrayTail;
  uint256 fixedArrayTailPad0;
  uint256 fixedArrayTailPad1;
  uint256 fixedArrayTailGuard;

  function rw() public {
    packed.a = packed.b;
    nonPacked.x = nonPacked.y;
    nested.inner.x = nested.z;
    mixed.x = mixed.y;
    mixed.arr.push(1);
    contractRef.x = contractRef.x;
    contractRef.c = C(address(this));
    nestedDynamic.left = 100;
    nestedDynamic.inner.a = 201;
    nestedDynamic.inner.b = 202;
    nestedDynamic.inner.note = "in";
    nestedDynamic.right = 300;
    nestedDynamic.inner.a = nestedDynamic.right;

    fixedArrayTail.a[0] = 1;
    fixedArrayTail.a[1] = 2;
    fixedArrayTail.a[2] = 3;
    fixedArrayTail.a[3] = 4;
    fixedArrayTailGuard = 0xaaaa;
    fixedArrayTail.tail = 0xbbbb;
    fixedArrayTailPad0 = fixedArrayTail.tail;
    fixedArrayTailPad1 = fixedArrayTailGuard;
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Default = #sol<RevertStrings Default>
// CHECK-NEXT: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module @C_243 attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:   func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:     %c65_i256 = arith.constant 65 : i256 loc(#loc)
// CHECK-NEXT:     %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:     %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:     %c18446744073709551615_i256 = arith.constant 18446744073709551615 : i256 loc(#loc)
// CHECK-NEXT:     %c-32_i256 = arith.constant -32 : i256 loc(#loc)
// CHECK-NEXT:     %c31_i256 = arith.constant 31 : i256 loc(#loc)
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:     %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %1 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %2 = arith.cmpi ne, %1, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:     scf.if %2 {
// CHECK-NEXT:       %24 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%24, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       func.call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     %3 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["C_243"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %4 = "llvm.intrcall"() <{id = 4042 : i32, name = "evm.codesize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %5 = arith.subi %4, %3 : i256 loc(#loc1)
// CHECK-NEXT:     %6 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %7 = llvm.load %6 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %8 = arith.addi %5, %c31_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %9 = arith.andi %8, %c-32_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %10 = arith.addi %7, %9 : i256 loc(#loc1)
// CHECK-NEXT:     %11 = arith.cmpi ugt, %10, %c18446744073709551615_i256 : i256 loc(#loc1)
// CHECK-NEXT:     %12 = arith.cmpi ult, %10, %7 : i256 loc(#loc1)
// CHECK-NEXT:     %13 = arith.ori %11, %12 : i1 loc(#loc1)
// CHECK-NEXT:     scf.if %13 {
// CHECK-NEXT:       %24 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %24 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %25 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %c65_i256, %25 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %26 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%26, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       func.call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     %14 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %10, %14 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %15 = llvm.inttoptr %7 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %16 = llvm.inttoptr %3 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%15, %16, %5) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @C_243() : () -> () loc(#loc1)
// CHECK-NEXT:     %17 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %18 = llvm.load %17 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %19 = "llvm.intrcall"() <{id = 4046 : i32, metadata = ["C_243_deployed"], name = "evm.dataoffset"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %20 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["C_243_deployed"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %21 = llvm.inttoptr %18 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %22 = llvm.inttoptr %19 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%21, %22, %20) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     %23 = llvm.inttoptr %18 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%23, %20) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @C_243() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     return loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   module @C_243_deployed attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka, sol.revert_strings = #Default} {
// CHECK-NEXT:     func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c224_i256 = arith.constant 224 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:       %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:       %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %1 = "llvm.intrcall"() <{id = 4038 : i32, name = "evm.calldatasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:       %2 = arith.cmpi uge, %1, %c4_i256 : i256 loc(#loc1)
// CHECK-NEXT:       scf.if %2 {
// CHECK-NEXT:         %4 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<2> loc(#loc1)
// CHECK-NEXT:         %5 = llvm.load %4 {alignment = 1 : i64} : !llvm.ptr<2> -> i256 loc(#loc1)
// CHECK-NEXT:         %6 = arith.shrui %5, %c224_i256 : i256 loc(#loc1)
// CHECK-NEXT:         %7 = arith.trunci %6 : i256 to i32 loc(#loc1)
// CHECK-NEXT:         scf.int_switch %7 : i32
// CHECK-NEXT:         case -1813835346 {
// CHECK-NEXT:           %8 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:           %9 = arith.cmpi ne, %8, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:           scf.if %9 {
// CHECK-NEXT:             %13 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:             "llvm.intrcall"(%13, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:             func.call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:           } loc(#loc1)
// CHECK-NEXT:           func.call @rw_242() : () -> () loc(#loc1)
// CHECK-NEXT:           %10 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:           %11 = llvm.load %10 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:           %12 = llvm.inttoptr %11 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:           "llvm.intrcall"(%12, %c0_i256) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:           func.call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:           scf.yield loc(#loc1)
// CHECK-NEXT:         }
// CHECK-NEXT:         default {
// CHECK-NEXT:           scf.yield loc(#loc1)
// CHECK-NEXT:         } loc(#loc1)
// CHECK-NEXT:       } loc(#loc1)
// CHECK-NEXT:       %3 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%3, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @rw_242() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c48059_i256 = arith.constant 48059 : i256 loc(#loc)
// CHECK-NEXT:       %c15_i256 = arith.constant 15 : i256 loc(#loc)
// CHECK-NEXT:       %c43690_i256 = arith.constant 43690 : i256 loc(#loc)
// CHECK-NEXT:       %c67108864_i256 = arith.constant 67108864 : i256 loc(#loc)
// CHECK-NEXT:       %c-4278190081_i256 = arith.constant -4278190081 : i256 loc(#loc)
// CHECK-NEXT:       %c196608_i256 = arith.constant 196608 : i256 loc(#loc)
// CHECK-NEXT:       %c-16711681_i256 = arith.constant -16711681 : i256 loc(#loc)
// CHECK-NEXT:       %c512_i256 = arith.constant 512 : i256 loc(#loc)
// CHECK-NEXT:       %c-65281_i256 = arith.constant -65281 : i256 loc(#loc)
// CHECK-NEXT:       %c300_i256 = arith.constant 300 : i256 loc(#loc)
// CHECK-NEXT:       %c13_i256 = arith.constant 13 : i256 loc(#loc)
// CHECK-NEXT:       %c12_i256 = arith.constant 12 : i256 loc(#loc)
// CHECK-NEXT:       %c-340282366920938463463374607431768211456_i256 = arith.constant -340282366920938463463374607431768211456 : i256 loc(#loc)
// CHECK-NEXT:       %c202_i256 = arith.constant 202 : i256 loc(#loc)
// CHECK-NEXT:       %c11_i256 = arith.constant 11 : i256 loc(#loc)
// CHECK-NEXT:       %c201_i256 = arith.constant 201 : i256 loc(#loc)
// CHECK-NEXT:       %c10_i256 = arith.constant 10 : i256 loc(#loc)
// CHECK-NEXT:       %c100_i256 = arith.constant 100 : i256 loc(#loc)
// CHECK-NEXT:       %c79228162514264337593543950335_i256 = arith.constant 79228162514264337593543950335 : i256 loc(#loc)
// CHECK-NEXT:       %c96_i256 = arith.constant 96 : i256 loc(#loc)
// CHECK-NEXT:       %c-79228162514264337593543950336_i256 = arith.constant -79228162514264337593543950336 : i256 loc(#loc)
// CHECK-NEXT:       %c6_i256 = arith.constant 6 : i256 loc(#loc)
// CHECK-NEXT:       %c7_i256 = arith.constant 7 : i256 loc(#loc)
// CHECK-NEXT:       %c-256_i256 = arith.constant -256 : i256 loc(#loc)
// CHECK-NEXT:       %c17_i256 = arith.constant 17 : i256 loc(#loc)
// CHECK-NEXT:       %c16_i256 = arith.constant 16 : i256 loc(#loc)
// CHECK-NEXT:       %c18_i256 = arith.constant 18 : i256 loc(#loc)
// CHECK-NEXT:       %c14_i256 = arith.constant 14 : i256 loc(#loc)
// CHECK-NEXT:       %c256_i256 = arith.constant 256 : i256 loc(#loc)
// CHECK-NEXT:       %c32 = arith.constant 32 : index loc(#loc)
// CHECK-NEXT:       %c0 = arith.constant 0 : index loc(#loc)
// CHECK-NEXT:       %c1 = arith.constant 1 : index loc(#loc)
// CHECK-NEXT:       %c34_i256 = arith.constant 34 : i256 loc(#loc)
// CHECK-NEXT:       %c127_i256 = arith.constant 127 : i256 loc(#loc)
// CHECK-NEXT:       %c47687202278368593055453199545051370742183790376672955679702151372887807754240_i256 = arith.constant 47687202278368593055453199545051370742183790376672955679702151372887807754240 : i256 loc(#loc)
// CHECK-NEXT:       %c36_i256 = arith.constant 36 : i256 loc(#loc)
// CHECK-NEXT:       %c65_i256 = arith.constant 65 : i256 loc(#loc)
// CHECK-NEXT:       %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:       %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256 = arith.constant 35408467139433450592217433187231851964531694900788300625387963629091585785856 : i256 loc(#loc)
// CHECK-NEXT:       %c18446744073709551615_i256 = arith.constant 18446744073709551615 : i256 loc(#loc)
// CHECK-NEXT:       %c-32_i256 = arith.constant -32 : i256 loc(#loc)
// CHECK-NEXT:       %c31_i256 = arith.constant 31 : i256 loc(#loc)
// CHECK-NEXT:       %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:       %c9_i256 = arith.constant 9 : i256 loc(#loc)
// CHECK-NEXT:       %c1461501637330902918203684832716283019655932542975_i256 = arith.constant 1461501637330902918203684832716283019655932542975 : i256 loc(#loc)
// CHECK-NEXT:       %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:       %c2_i256 = arith.constant 2 : i256 loc(#loc)
// CHECK-NEXT:       %c5_i256 = arith.constant 5 : i256 loc(#loc)
// CHECK-NEXT:       %c3_i256 = arith.constant 3 : i256 loc(#loc)
// CHECK-NEXT:       %c-1_i256 = arith.constant -1 : i256 loc(#loc)
// CHECK-NEXT:       %c8_i256 = arith.constant 8 : i256 loc(#loc)
// CHECK-NEXT:       %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %0 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<5> loc(#loc3)
// CHECK-NEXT:       %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc3)
// CHECK-NEXT:       %2 = arith.shrui %1, %c8_i256 : i256 loc(#loc3)
// CHECK-NEXT:       %3 = arith.trunci %2 : i256 to i8 loc(#loc3)
// CHECK-NEXT:       %4 = arith.extui %3 : i8 to i256 loc(#loc4)
// CHECK-NEXT:       %5 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<5> loc(#loc4)
// CHECK-NEXT:       %6 = llvm.load %5 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc4)
// CHECK-NEXT:       %7 = arith.andi %6, %c-256_i256 : i256 loc(#loc4)
// CHECK-NEXT:       %8 = arith.ori %7, %4 : i256 loc(#loc4)
// CHECK-NEXT:       %9 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<5> loc(#loc4)
// CHECK-NEXT:       llvm.store %8, %9 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc4)
// CHECK-NEXT:       %10 = llvm.inttoptr %c2_i256 : i256 to !llvm.ptr<5> loc(#loc5)
// CHECK-NEXT:       %11 = llvm.load %10 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc5)
// CHECK-NEXT:       %12 = llvm.inttoptr %c1_i256 : i256 to !llvm.ptr<5> loc(#loc6)
// CHECK-NEXT:       llvm.store %11, %12 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc6)
// CHECK-NEXT:       %13 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<5> loc(#loc7)
// CHECK-NEXT:       %14 = llvm.load %13 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc7)
// CHECK-NEXT:       %15 = arith.trunci %14 : i256 to i8 loc(#loc7)
// CHECK-NEXT:       %16 = arith.extui %15 : i8 to i256 loc(#loc8)
// CHECK-NEXT:       %17 = llvm.inttoptr %c3_i256 : i256 to !llvm.ptr<5> loc(#loc8)
// CHECK-NEXT:       %18 = llvm.load %17 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc8)
// CHECK-NEXT:       %19 = arith.andi %18, %c-256_i256 : i256 loc(#loc8)
// CHECK-NEXT:       %20 = arith.ori %19, %16 : i256 loc(#loc8)
// CHECK-NEXT:       %21 = llvm.inttoptr %c3_i256 : i256 to !llvm.ptr<5> loc(#loc8)
// CHECK-NEXT:       llvm.store %20, %21 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc8)
// CHECK-NEXT:       %22 = llvm.inttoptr %c7_i256 : i256 to !llvm.ptr<5> loc(#loc9)
// CHECK-NEXT:       %23 = llvm.load %22 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc9)
// CHECK-NEXT:       %24 = arith.trunci %23 : i256 to i8 loc(#loc9)
// CHECK-NEXT:       %25 = arith.extui %24 : i8 to i256 loc(#loc10)
// CHECK-NEXT:       %26 = llvm.inttoptr %c5_i256 : i256 to !llvm.ptr<5> loc(#loc10)
// CHECK-NEXT:       %27 = llvm.load %26 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc10)
// CHECK-NEXT:       %28 = arith.andi %27, %c-256_i256 : i256 loc(#loc10)
// CHECK-NEXT:       %29 = arith.ori %28, %25 : i256 loc(#loc10)
// CHECK-NEXT:       %30 = llvm.inttoptr %c5_i256 : i256 to !llvm.ptr<5> loc(#loc10)
// CHECK-NEXT:       llvm.store %29, %30 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc10)
// CHECK-NEXT:       %31 = llvm.inttoptr %c6_i256 : i256 to !llvm.ptr<5> loc(#loc11)
// CHECK-NEXT:       %32 = llvm.load %31 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc11)
// CHECK-NEXT:       %33 = arith.addi %32, %c1_i256 : i256 loc(#loc11)
// CHECK-NEXT:       %34 = llvm.inttoptr %c6_i256 : i256 to !llvm.ptr<5> loc(#loc11)
// CHECK-NEXT:       llvm.store %33, %34 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc11)
// CHECK-NEXT:       %35 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc11)
// CHECK-NEXT:       llvm.store %c6_i256, %35 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc11)
// CHECK-NEXT:       %36 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc11)
// CHECK-NEXT:       %37 = "llvm.intrcall"(%36, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc11)
// CHECK-NEXT:       %38 = arith.addi %37, %32 : i256 loc(#loc11)
// CHECK-NEXT:       %39 = llvm.inttoptr %38 : i256 to !llvm.ptr<5> loc(#loc11)
// CHECK-NEXT:       llvm.store %c1_i256, %39 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc11)
// CHECK-NEXT:       %40 = llvm.inttoptr %c8_i256 : i256 to !llvm.ptr<5> loc(#loc12)
// CHECK-NEXT:       %41 = llvm.load %40 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc12)
// CHECK-NEXT:       %42 = arith.trunci %41 : i256 to i96 loc(#loc12)
// CHECK-NEXT:       %43 = arith.extui %42 : i96 to i256 loc(#loc13)
// CHECK-NEXT:       %44 = llvm.inttoptr %c8_i256 : i256 to !llvm.ptr<5> loc(#loc13)
// CHECK-NEXT:       %45 = llvm.load %44 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc13)
// CHECK-NEXT:       %46 = arith.andi %45, %c-79228162514264337593543950336_i256 : i256 loc(#loc13)
// CHECK-NEXT:       %47 = arith.ori %46, %43 : i256 loc(#loc13)
// CHECK-NEXT:       %48 = llvm.inttoptr %c8_i256 : i256 to !llvm.ptr<5> loc(#loc13)
// CHECK-NEXT:       llvm.store %47, %48 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc13)
// CHECK-NEXT:       %49 = "llvm.intrcall"() <{id = 4028 : i32, name = "evm.address"}> : () -> i256 loc(#loc14)
// CHECK-NEXT:       %50 = arith.andi %49, %c1461501637330902918203684832716283019655932542975_i256 : i256 loc(#loc14)
// CHECK-NEXT:       %51 = llvm.inttoptr %c8_i256 : i256 to !llvm.ptr<5> loc(#loc15)
// CHECK-NEXT:       %52 = llvm.load %51 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc15)
// CHECK-NEXT:       %53 = arith.andi %52, %c79228162514264337593543950335_i256 : i256 loc(#loc15)
// CHECK-NEXT:       %54 = arith.shli %50, %c96_i256 : i256 loc(#loc15)
// CHECK-NEXT:       %55 = arith.ori %53, %54 : i256 loc(#loc15)
// CHECK-NEXT:       %56 = llvm.inttoptr %c8_i256 : i256 to !llvm.ptr<5> loc(#loc15)
// CHECK-NEXT:       llvm.store %55, %56 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc15)
// CHECK-NEXT:       %57 = llvm.inttoptr %c9_i256 : i256 to !llvm.ptr<5> loc(#loc16)
// CHECK-NEXT:       llvm.store %c100_i256, %57 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc16)
// CHECK-NEXT:       %58 = llvm.inttoptr %c10_i256 : i256 to !llvm.ptr<5> loc(#loc17)
// CHECK-NEXT:       llvm.store %c201_i256, %58 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc17)
// CHECK-NEXT:       %59 = llvm.inttoptr %c11_i256 : i256 to !llvm.ptr<5> loc(#loc18)
// CHECK-NEXT:       %60 = llvm.load %59 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc18)
// CHECK-NEXT:       %61 = arith.andi %60, %c-340282366920938463463374607431768211456_i256 : i256 loc(#loc18)
// CHECK-NEXT:       %62 = arith.ori %61, %c202_i256 : i256 loc(#loc18)
// CHECK-NEXT:       %63 = llvm.inttoptr %c11_i256 : i256 to !llvm.ptr<5> loc(#loc18)
// CHECK-NEXT:       llvm.store %62, %63 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc18)
// CHECK-NEXT:       %64 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc19)
// CHECK-NEXT:       %65 = llvm.load %64 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc19)
// CHECK-NEXT:       %66 = arith.addi %65, %c64_i256 : i256 loc(#loc19)
// CHECK-NEXT:       %67 = arith.cmpi ugt, %66, %c18446744073709551615_i256 : i256 loc(#loc19)
// CHECK-NEXT:       %68 = arith.cmpi ult, %66, %65 : i256 loc(#loc19)
// CHECK-NEXT:       %69 = arith.ori %67, %68 : i1 loc(#loc19)
// CHECK-NEXT:       scf.if %69 {
// CHECK-NEXT:         %120 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc19)
// CHECK-NEXT:         llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %120 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc19)
// CHECK-NEXT:         %121 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc19)
// CHECK-NEXT:         llvm.store %c65_i256, %121 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc19)
// CHECK-NEXT:         %122 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc19)
// CHECK-NEXT:         "llvm.intrcall"(%122, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc19)
// CHECK-NEXT:         func.call @".unreachable"() : () -> () loc(#loc19)
// CHECK-NEXT:       } loc(#loc19)
// CHECK-NEXT:       %70 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc19)
// CHECK-NEXT:       llvm.store %66, %70 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc19)
// CHECK-NEXT:       %71 = llvm.inttoptr %65 : i256 to !llvm.ptr<1> loc(#loc19)
// CHECK-NEXT:       llvm.store %c2_i256, %71 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc19)
// CHECK-NEXT:       %72 = arith.addi %65, %c32_i256 : i256 loc(#loc19)
// CHECK-NEXT:       %73 = llvm.inttoptr %72 : i256 to !llvm.ptr<1> loc(#loc19)
// CHECK-NEXT:       llvm.store %c47687202278368593055453199545051370742183790376672955679702151372887807754240_i256, %73 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc19)
// CHECK-NEXT:       %74 = llvm.inttoptr %65 : i256 to !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:       %75 = llvm.load %74 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc20)
// CHECK-NEXT:       %76 = llvm.inttoptr %c12_i256 : i256 to !llvm.ptr<5> loc(#loc20)
// CHECK-NEXT:       %77 = llvm.load %76 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc20)
// CHECK-NEXT:       %78 = arith.shrui %77, %c1_i256 : i256 loc(#loc20)
// CHECK-NEXT:       %79 = arith.andi %77, %c1_i256 : i256 loc(#loc20)
// CHECK-NEXT:       %80 = arith.cmpi eq, %79, %c0_i256 : i256 loc(#loc20)
// CHECK-NEXT:       %81 = arith.andi %78, %c127_i256 : i256 loc(#loc20)
// CHECK-NEXT:       %82 = arith.select %80, %81, %78 : i256 loc(#loc20)
// CHECK-NEXT:       %83 = arith.cmpi ult, %82, %c32_i256 : i256 loc(#loc20)
// CHECK-NEXT:       %84 = arith.trunci %79 : i256 to i1 loc(#loc20)
// CHECK-NEXT:       %85 = arith.cmpi eq, %84, %83 : i1 loc(#loc20)
// CHECK-NEXT:       scf.if %85 {
// CHECK-NEXT:         %120 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:         llvm.store %c35408467139433450592217433187231851964531694900788300625387963629091585785856_i256, %120 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:         %121 = llvm.inttoptr %c4_i256 : i256 to !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:         llvm.store %c34_i256, %121 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:         %122 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:         "llvm.intrcall"(%122, %c36_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc20)
// CHECK-NEXT:         func.call @".unreachable"() : () -> () loc(#loc20)
// CHECK-NEXT:       } loc(#loc20)
// CHECK-NEXT:       %86 = arith.cmpi ugt, %82, %c31_i256 : i256 loc(#loc20)
// CHECK-NEXT:       scf.if %86 {
// CHECK-NEXT:         %120 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:         llvm.store %c12_i256, %120 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:         %121 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:         %122 = "llvm.intrcall"(%121, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc20)
// CHECK-NEXT:         %123 = arith.addi %75, %c31_i256 : i256 loc(#loc20)
// CHECK-NEXT:         %124 = arith.divui %123, %c32_i256 : i256 loc(#loc20)
// CHECK-NEXT:         %125 = arith.addi %122, %124 : i256 loc(#loc20)
// CHECK-NEXT:         %126 = arith.cmpi ult, %75, %c32_i256 : i256 loc(#loc20)
// CHECK-NEXT:         %127 = arith.select %126, %122, %125 : i256 loc(#loc20)
// CHECK-NEXT:         %128 = arith.addi %82, %c31_i256 : i256 loc(#loc20)
// CHECK-NEXT:         %129 = arith.divui %128, %c32_i256 : i256 loc(#loc20)
// CHECK-NEXT:         %130 = arith.addi %122, %129 : i256 loc(#loc20)
// CHECK-NEXT:         %131 = arith.index_castui %127 : i256 to index loc(#loc20)
// CHECK-NEXT:         %132 = arith.index_castui %130 : i256 to index loc(#loc20)
// CHECK-NEXT:         scf.for %arg0 = %131 to %132 step %c1 {
// CHECK-NEXT:           %133 = arith.index_castui %arg0 : index to i256 loc(#loc20)
// CHECK-NEXT:           %134 = llvm.inttoptr %133 : i256 to !llvm.ptr<5> loc(#loc20)
// CHECK-NEXT:           llvm.store %c0_i256, %134 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc20)
// CHECK-NEXT:         } loc(#loc20)
// CHECK-NEXT:       } loc(#loc20)
// CHECK-NEXT:       %87 = arith.cmpi ugt, %75, %c31_i256 : i256 loc(#loc20)
// CHECK-NEXT:       scf.if %87 {
// CHECK-NEXT:         %120 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:         llvm.store %c12_i256, %120 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:         %121 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:         %122 = "llvm.intrcall"(%121, %c32_i256) <{id = 4085 : i32, name = "evm.sha3"}> : (!llvm.ptr<1>, i256) -> i256 loc(#loc20)
// CHECK-NEXT:         %123 = arith.addi %65, %c32_i256 : i256 loc(#loc20)
// CHECK-NEXT:         %124 = arith.andi %75, %c-32_i256 : i256 loc(#loc20)
// CHECK-NEXT:         %125 = arith.index_castui %124 : i256 to index loc(#loc20)
// CHECK-NEXT:         scf.for %arg0 = %c0 to %125 step %c32 {
// CHECK-NEXT:           %130 = arith.index_castui %arg0 : index to i256 loc(#loc20)
// CHECK-NEXT:           %131 = arith.divui %130, %c32_i256 : i256 loc(#loc20)
// CHECK-NEXT:           %132 = arith.addi %123, %130 : i256 loc(#loc20)
// CHECK-NEXT:           %133 = llvm.inttoptr %132 : i256 to !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:           %134 = llvm.load %133 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc20)
// CHECK-NEXT:           %135 = arith.addi %122, %131 : i256 loc(#loc20)
// CHECK-NEXT:           %136 = llvm.inttoptr %135 : i256 to !llvm.ptr<5> loc(#loc20)
// CHECK-NEXT:           llvm.store %134, %136 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc20)
// CHECK-NEXT:         } loc(#loc20)
// CHECK-NEXT:         %126 = arith.cmpi ult, %124, %75 : i256 loc(#loc20)
// CHECK-NEXT:         scf.if %126 {
// CHECK-NEXT:           %130 = arith.andi %75, %c31_i256 : i256 loc(#loc20)
// CHECK-NEXT:           %131 = arith.divui %124, %c32_i256 : i256 loc(#loc20)
// CHECK-NEXT:           %132 = arith.addi %123, %124 : i256 loc(#loc20)
// CHECK-NEXT:           %133 = llvm.inttoptr %132 : i256 to !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:           %134 = llvm.load %133 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc20)
// CHECK-NEXT:           %135 = arith.muli %130, %c8_i256 : i256 loc(#loc20)
// CHECK-NEXT:           %136 = arith.subi %c256_i256, %135 : i256 loc(#loc20)
// CHECK-NEXT:           %137 = arith.shli %c-1_i256, %136 : i256 loc(#loc20)
// CHECK-NEXT:           %138 = arith.andi %134, %137 : i256 loc(#loc20)
// CHECK-NEXT:           %139 = arith.addi %122, %131 : i256 loc(#loc20)
// CHECK-NEXT:           %140 = llvm.inttoptr %139 : i256 to !llvm.ptr<5> loc(#loc20)
// CHECK-NEXT:           llvm.store %138, %140 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc20)
// CHECK-NEXT:         } loc(#loc20)
// CHECK-NEXT:         %127 = arith.muli %75, %c2_i256 : i256 loc(#loc20)
// CHECK-NEXT:         %128 = arith.ori %127, %c1_i256 : i256 loc(#loc20)
// CHECK-NEXT:         %129 = llvm.inttoptr %c12_i256 : i256 to !llvm.ptr<5> loc(#loc20)
// CHECK-NEXT:         llvm.store %128, %129 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc20)
// CHECK-NEXT:       } else {
// CHECK-NEXT:         %120 = arith.cmpi ne, %75, %c0_i256 : i256 loc(#loc20)
// CHECK-NEXT:         scf.if %120 {
// CHECK-NEXT:           %121 = arith.addi %65, %c32_i256 : i256 loc(#loc20)
// CHECK-NEXT:           %122 = llvm.inttoptr %121 : i256 to !llvm.ptr<1> loc(#loc20)
// CHECK-NEXT:           %123 = llvm.load %122 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc20)
// CHECK-NEXT:           %124 = arith.muli %75, %c8_i256 : i256 loc(#loc20)
// CHECK-NEXT:           %125 = arith.subi %c256_i256, %124 : i256 loc(#loc20)
// CHECK-NEXT:           %126 = arith.shli %c-1_i256, %125 : i256 loc(#loc20)
// CHECK-NEXT:           %127 = arith.andi %123, %126 : i256 loc(#loc20)
// CHECK-NEXT:           %128 = arith.muli %75, %c2_i256 : i256 loc(#loc20)
// CHECK-NEXT:           %129 = arith.ori %127, %128 : i256 loc(#loc20)
// CHECK-NEXT:           %130 = llvm.inttoptr %c12_i256 : i256 to !llvm.ptr<5> loc(#loc20)
// CHECK-NEXT:           llvm.store %129, %130 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc20)
// CHECK-NEXT:         } else {
// CHECK-NEXT:           %121 = llvm.inttoptr %c12_i256 : i256 to !llvm.ptr<5> loc(#loc20)
// CHECK-NEXT:           llvm.store %c0_i256, %121 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc20)
// CHECK-NEXT:         } loc(#loc20)
// CHECK-NEXT:       } loc(#loc20)
// CHECK-NEXT:       %88 = llvm.inttoptr %c13_i256 : i256 to !llvm.ptr<5> loc(#loc21)
// CHECK-NEXT:       llvm.store %c300_i256, %88 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc21)
// CHECK-NEXT:       %89 = llvm.inttoptr %c13_i256 : i256 to !llvm.ptr<5> loc(#loc22)
// CHECK-NEXT:       %90 = llvm.load %89 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc22)
// CHECK-NEXT:       %91 = llvm.inttoptr %c10_i256 : i256 to !llvm.ptr<5> loc(#loc23)
// CHECK-NEXT:       llvm.store %90, %91 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc23)
// CHECK-NEXT:       %92 = llvm.inttoptr %c14_i256 : i256 to !llvm.ptr<5> loc(#loc24)
// CHECK-NEXT:       %93 = llvm.load %92 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc24)
// CHECK-NEXT:       %94 = arith.andi %93, %c-256_i256 : i256 loc(#loc24)
// CHECK-NEXT:       %95 = arith.ori %94, %c1_i256 : i256 loc(#loc24)
// CHECK-NEXT:       %96 = llvm.inttoptr %c14_i256 : i256 to !llvm.ptr<5> loc(#loc24)
// CHECK-NEXT:       llvm.store %95, %96 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc24)
// CHECK-NEXT:       %97 = llvm.inttoptr %c14_i256 : i256 to !llvm.ptr<5> loc(#loc25)
// CHECK-NEXT:       %98 = llvm.load %97 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc25)
// CHECK-NEXT:       %99 = arith.andi %98, %c-65281_i256 : i256 loc(#loc25)
// CHECK-NEXT:       %100 = arith.ori %99, %c512_i256 : i256 loc(#loc25)
// CHECK-NEXT:       %101 = llvm.inttoptr %c14_i256 : i256 to !llvm.ptr<5> loc(#loc25)
// CHECK-NEXT:       llvm.store %100, %101 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc25)
// CHECK-NEXT:       %102 = llvm.inttoptr %c14_i256 : i256 to !llvm.ptr<5> loc(#loc26)
// CHECK-NEXT:       %103 = llvm.load %102 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc26)
// CHECK-NEXT:       %104 = arith.andi %103, %c-16711681_i256 : i256 loc(#loc26)
// CHECK-NEXT:       %105 = arith.ori %104, %c196608_i256 : i256 loc(#loc26)
// CHECK-NEXT:       %106 = llvm.inttoptr %c14_i256 : i256 to !llvm.ptr<5> loc(#loc26)
// CHECK-NEXT:       llvm.store %105, %106 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc26)
// CHECK-NEXT:       %107 = llvm.inttoptr %c14_i256 : i256 to !llvm.ptr<5> loc(#loc27)
// CHECK-NEXT:       %108 = llvm.load %107 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc27)
// CHECK-NEXT:       %109 = arith.andi %108, %c-4278190081_i256 : i256 loc(#loc27)
// CHECK-NEXT:       %110 = arith.ori %109, %c67108864_i256 : i256 loc(#loc27)
// CHECK-NEXT:       %111 = llvm.inttoptr %c14_i256 : i256 to !llvm.ptr<5> loc(#loc27)
// CHECK-NEXT:       llvm.store %110, %111 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc27)
// CHECK-NEXT:       %112 = llvm.inttoptr %c18_i256 : i256 to !llvm.ptr<5> loc(#loc28)
// CHECK-NEXT:       llvm.store %c43690_i256, %112 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc28)
// CHECK-NEXT:       %113 = llvm.inttoptr %c15_i256 : i256 to !llvm.ptr<5> loc(#loc29)
// CHECK-NEXT:       llvm.store %c48059_i256, %113 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc29)
// CHECK-NEXT:       %114 = llvm.inttoptr %c15_i256 : i256 to !llvm.ptr<5> loc(#loc30)
// CHECK-NEXT:       %115 = llvm.load %114 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc30)
// CHECK-NEXT:       %116 = llvm.inttoptr %c16_i256 : i256 to !llvm.ptr<5> loc(#loc31)
// CHECK-NEXT:       llvm.store %115, %116 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc31)
// CHECK-NEXT:       %117 = llvm.inttoptr %c18_i256 : i256 to !llvm.ptr<5> loc(#loc32)
// CHECK-NEXT:       %118 = llvm.load %117 {alignment = 1 : i64} : !llvm.ptr<5> -> i256 loc(#loc32)
// CHECK-NEXT:       %119 = llvm.inttoptr %c17_i256 : i256 to !llvm.ptr<5> loc(#loc33)
// CHECK-NEXT:       llvm.store %118, %119 {alignment = 1 : i64} : i256, !llvm.ptr<5> loc(#loc33)
// CHECK-NEXT:       return loc(#loc2)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:67:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:68:15)
// CHECK-NEXT: #loc4 = loc({{.*}}:68:4)
// CHECK-NEXT: #loc5 = loc({{.*}}:69:18)
// CHECK-NEXT: #loc6 = loc({{.*}}:69:4)
// CHECK-NEXT: #loc7 = loc({{.*}}:70:21)
// CHECK-NEXT: #loc8 = loc({{.*}}:70:4)
// CHECK-NEXT: #loc9 = loc({{.*}}:71:14)
// CHECK-NEXT: #loc10 = loc({{.*}}:71:4)
// CHECK-NEXT: #loc11 = loc({{.*}}:72:4)
// CHECK-NEXT: #loc12 = loc({{.*}}:73:20)
// CHECK-NEXT: #loc13 = loc({{.*}}:73:4)
// CHECK-NEXT: #loc14 = loc({{.*}}:74:30)
// CHECK-NEXT: #loc15 = loc({{.*}}:74:4)
// CHECK-NEXT: #loc16 = loc({{.*}}:75:4)
// CHECK-NEXT: #loc17 = loc({{.*}}:76:4)
// CHECK-NEXT: #loc18 = loc({{.*}}:77:4)
// CHECK-NEXT: #loc19 = loc({{.*}}:78:31)
// CHECK-NEXT: #loc20 = loc({{.*}}:78:4)
// CHECK-NEXT: #loc21 = loc({{.*}}:79:4)
// CHECK-NEXT: #loc22 = loc({{.*}}:80:28)
// CHECK-NEXT: #loc23 = loc({{.*}}:80:4)
// CHECK-NEXT: #loc24 = loc({{.*}}:82:4)
// CHECK-NEXT: #loc25 = loc({{.*}}:83:4)
// CHECK-NEXT: #loc26 = loc({{.*}}:84:4)
// CHECK-NEXT: #loc27 = loc({{.*}}:85:4)
// CHECK-NEXT: #loc28 = loc({{.*}}:86:4)
// CHECK-NEXT: #loc29 = loc({{.*}}:87:4)
// CHECK-NEXT: #loc30 = loc({{.*}}:88:25)
// CHECK-NEXT: #loc31 = loc({{.*}}:88:4)
// CHECK-NEXT: #loc32 = loc({{.*}}:89:25)
// CHECK-NEXT: #loc33 = loc({{.*}}:89:4)
// CHECK-EMPTY:
