// RUN: solc --mlir-action=print-std-mlir --mlir-target=evm --mmlir --mlir-print-debuginfo %s | FileCheck %s

abstract contract A {
  function fa() public virtual;
}

interface I {
  function fi() external;
}

contract C {}

function name_contract() pure returns (string memory) {
  return type(C).name;
}

function name_abstract() pure returns (string memory) {
  return type(A).name;
}

function name_interface() pure returns (string memory) {
  return type(I).name;
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module @C_9 attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka} {
// CHECK-NEXT:   func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:     %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %1 = "llvm.intrcall"() <{id = 4040 : i32, name = "evm.callvalue"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %2 = arith.cmpi ne, %1, %c0_i256 : i256 loc(#loc1)
// CHECK-NEXT:     scf.if %2 {
// CHECK-NEXT:       %19 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%19, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       func.call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     %3 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["C_9"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %4 = "llvm.intrcall"() <{id = 4042 : i32, name = "evm.codesize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %5 = arith.subi %4, %3 : i256 loc(#loc1)
// CHECK-NEXT:     %6 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %7 = llvm.load %6 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %8 = arith.addi %7, %5 : i256 loc(#loc1)
// CHECK-NEXT:     %9 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     llvm.store %8, %9 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %10 = llvm.inttoptr %7 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %11 = llvm.inttoptr %3 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%10, %11, %5) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @C_9() : () -> () loc(#loc1)
// CHECK-NEXT:     %12 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %13 = llvm.load %12 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc1)
// CHECK-NEXT:     %14 = "llvm.intrcall"() <{id = 4046 : i32, metadata = ["C_9_deployed"], name = "evm.dataoffset"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %15 = "llvm.intrcall"() <{id = 4047 : i32, metadata = ["C_9_deployed"], name = "evm.datasize"}> : () -> i256 loc(#loc1)
// CHECK-NEXT:     %16 = llvm.inttoptr %13 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %17 = llvm.inttoptr %14 : i256 to !llvm.ptr<4> loc(#loc1)
// CHECK-NEXT:     "llvm.intr.memcpy"(%16, %17, %15) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<4>, i256) -> () loc(#loc1)
// CHECK-NEXT:     %18 = llvm.inttoptr %13 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%18, %15) <{id = 4078 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @name_contract_20() -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c30304960855078848021012718732742538383473003799210616369701789564571014397952_i256 = arith.constant 30304960855078848021012718732742538383473003799210616369701789564571014397952 : i256 loc(#loc)
// CHECK-NEXT:     %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:     %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc3)
// CHECK-NEXT:     %2 = arith.addi %1, %c64_i256 : i256 loc(#loc3)
// CHECK-NEXT:     %3 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:     llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:     %4 = llvm.inttoptr %1 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:     llvm.store %c1_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:     %5 = arith.addi %1, %c32_i256 : i256 loc(#loc3)
// CHECK-NEXT:     %6 = llvm.inttoptr %5 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:     llvm.store %c30304960855078848021012718732742538383473003799210616369701789564571014397952_i256, %6 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:     return %1 : i256 loc(#loc4)
// CHECK-NEXT:   } loc(#loc2)
// CHECK-NEXT:   func.func @name_abstract_31() -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c29400335157912315244266070412362164103369332044010299463143527189509193072640_i256 = arith.constant 29400335157912315244266070412362164103369332044010299463143527189509193072640 : i256 loc(#loc)
// CHECK-NEXT:     %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc6)
// CHECK-NEXT:     %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc6)
// CHECK-NEXT:     %2 = arith.addi %1, %c64_i256 : i256 loc(#loc6)
// CHECK-NEXT:     %3 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc6)
// CHECK-NEXT:     llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc6)
// CHECK-NEXT:     %4 = llvm.inttoptr %1 : i256 to !llvm.ptr<1> loc(#loc6)
// CHECK-NEXT:     llvm.store %c1_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc6)
// CHECK-NEXT:     %5 = arith.addi %1, %c32_i256 : i256 loc(#loc6)
// CHECK-NEXT:     %6 = llvm.inttoptr %5 : i256 to !llvm.ptr<1> loc(#loc6)
// CHECK-NEXT:     llvm.store %c29400335157912315244266070412362164103369332044010299463143527189509193072640_i256, %6 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc6)
// CHECK-NEXT:     return %1 : i256 loc(#loc7)
// CHECK-NEXT:   } loc(#loc5)
// CHECK-NEXT:   func.func @name_interface_42() -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c33018837946578446351252663693883661223784019064811567089376576689756478373888_i256 = arith.constant 33018837946578446351252663693883661223784019064811567089376576689756478373888 : i256 loc(#loc)
// CHECK-NEXT:     %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc9)
// CHECK-NEXT:     %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc9)
// CHECK-NEXT:     %2 = arith.addi %1, %c64_i256 : i256 loc(#loc9)
// CHECK-NEXT:     %3 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc9)
// CHECK-NEXT:     llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc9)
// CHECK-NEXT:     %4 = llvm.inttoptr %1 : i256 to !llvm.ptr<1> loc(#loc9)
// CHECK-NEXT:     llvm.store %c1_i256, %4 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc9)
// CHECK-NEXT:     %5 = arith.addi %1, %c32_i256 : i256 loc(#loc9)
// CHECK-NEXT:     %6 = llvm.inttoptr %5 : i256 to !llvm.ptr<1> loc(#loc9)
// CHECK-NEXT:     llvm.store %c33018837946578446351252663693883661223784019064811567089376576689756478373888_i256, %6 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc9)
// CHECK-NEXT:     return %1 : i256 loc(#loc10)
// CHECK-NEXT:   } loc(#loc8)
// CHECK-NEXT:   func.func @C_9() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     return loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT:   module @C_9_deployed attributes {llvm.data_layout = "E-p:256:256-i256:256:256-S256-a:256:256", llvm.target_triple = "evm-unknown-unknown", sol.evm_version = #Osaka} {
// CHECK-NEXT:     func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:     func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:       %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:       %c128_i256 = arith.constant 128 : i256 loc(#loc1)
// CHECK-NEXT:       %c64_i256 = arith.constant 64 : i256 loc(#loc1)
// CHECK-NEXT:       %0 = llvm.inttoptr %c64_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       llvm.store %c128_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       %1 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:       "llvm.intrcall"(%1, %c0_i256) <{id = 4080 : i32, name = "evm.revert"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:       call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:       llvm.unreachable loc(#loc1)
// CHECK-NEXT:     } loc(#loc1)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:10:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:12:0)
// CHECK-NEXT: #loc3 = loc({{.*}}:13:9)
// CHECK-NEXT: #loc4 = loc({{.*}}:13:2)
// CHECK-NEXT: #loc5 = loc({{.*}}:16:0)
// CHECK-NEXT: #loc6 = loc({{.*}}:17:9)
// CHECK-NEXT: #loc7 = loc({{.*}}:17:2)
// CHECK-NEXT: #loc8 = loc({{.*}}:20:0)
// CHECK-NEXT: #loc9 = loc({{.*}}:21:9)
// CHECK-NEXT: #loc10 = loc({{.*}}:21:2)
// CHECK-EMPTY:
