// RUN: solc --strict-assembly --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

object "Test" {
  code {
    let a := 7
    let b := 33
    let c := and(a, b)
    let d := or(a, b)
    let e := xor(a, b)
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Prague = #sol<EvmVersion Prague>
// CHECK-NEXT: module attributes {sol.evm_version = #Prague} {
// CHECK-NEXT:   yul.object @Test {
// CHECK-NEXT:     %c7_i256 = arith.constant 7 : i256 loc(#loc1)
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc2)
// CHECK-NEXT:     %0 = llvm.alloca %c1_i256 x i256 {alignment = 32 : i64} : (i256) -> !llvm.ptr loc(#loc3)
// CHECK-NEXT:     llvm.store %c7_i256, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc2)
// CHECK-NEXT:     %c33_i256 = arith.constant 33 : i256 loc(#loc4)
// CHECK-NEXT:     %c1_i256_0 = arith.constant 1 : i256 loc(#loc5)
// CHECK-NEXT:     %1 = llvm.alloca %c1_i256_0 x i256 {alignment = 32 : i64} : (i256) -> !llvm.ptr loc(#loc6)
// CHECK-NEXT:     llvm.store %c33_i256, %1 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc5)
// CHECK-NEXT:     %2 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc7)
// CHECK-NEXT:     %3 = llvm.load %1 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc8)
// CHECK-NEXT:     %4 = arith.andi %2, %3 : i256 loc(#loc9)
// CHECK-NEXT:     %c1_i256_1 = arith.constant 1 : i256 loc(#loc10)
// CHECK-NEXT:     %5 = llvm.alloca %c1_i256_1 x i256 {alignment = 32 : i64} : (i256) -> !llvm.ptr loc(#loc11)
// CHECK-NEXT:     llvm.store %4, %5 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc10)
// CHECK-NEXT:     %6 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc12)
// CHECK-NEXT:     %7 = llvm.load %1 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc13)
// CHECK-NEXT:     %8 = arith.ori %6, %7 : i256 loc(#loc14)
// CHECK-NEXT:     %c1_i256_2 = arith.constant 1 : i256 loc(#loc15)
// CHECK-NEXT:     %9 = llvm.alloca %c1_i256_2 x i256 {alignment = 32 : i64} : (i256) -> !llvm.ptr loc(#loc16)
// CHECK-NEXT:     llvm.store %8, %9 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc15)
// CHECK-NEXT:     %10 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc17)
// CHECK-NEXT:     %11 = llvm.load %1 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc18)
// CHECK-NEXT:     %12 = arith.xori %10, %11 : i256 loc(#loc19)
// CHECK-NEXT:     %c1_i256_3 = arith.constant 1 : i256 loc(#loc20)
// CHECK-NEXT:     %13 = llvm.alloca %c1_i256_3 x i256 {alignment = 32 : i64} : (i256) -> !llvm.ptr loc(#loc21)
// CHECK-NEXT:     llvm.store %12, %13 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc20)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:4:13)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:4)
// CHECK-NEXT: #loc3 = loc({{.*}}:4:8)
// CHECK-NEXT: #loc4 = loc({{.*}}:5:13)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:4)
// CHECK-NEXT: #loc6 = loc({{.*}}:5:8)
// CHECK-NEXT: #loc7 = loc({{.*}}:6:17)
// CHECK-NEXT: #loc8 = loc({{.*}}:6:20)
// CHECK-NEXT: #loc9 = loc({{.*}}:6:13)
// CHECK-NEXT: #loc10 = loc({{.*}}:6:4)
// CHECK-NEXT: #loc11 = loc({{.*}}:6:8)
// CHECK-NEXT: #loc12 = loc({{.*}}:7:16)
// CHECK-NEXT: #loc13 = loc({{.*}}:7:19)
// CHECK-NEXT: #loc14 = loc({{.*}}:7:13)
// CHECK-NEXT: #loc15 = loc({{.*}}:7:4)
// CHECK-NEXT: #loc16 = loc({{.*}}:7:8)
// CHECK-NEXT: #loc17 = loc({{.*}}:8:17)
// CHECK-NEXT: #loc18 = loc({{.*}}:8:20)
// CHECK-NEXT: #loc19 = loc({{.*}}:8:13)
// CHECK-NEXT: #loc20 = loc({{.*}}:8:4)
// CHECK-NEXT: #loc21 = loc({{.*}}:8:8)
// CHECK-EMPTY:
