// RUN: solc --strict-assembly --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

object "Test" {
  code {
    codecopy(0, dataoffset("Test"), datasize("Test"))
  }
  object "Test_deployed" {
    code {}
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module attributes {sol.evm_version = #Osaka} {
// CHECK-NEXT:   yul.object @Test {
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc1)
// CHECK-NEXT:     %0 = yul.dataoffset {obj = @Test} loc(#loc2)
// CHECK-NEXT:     %1 = yul.datasize {obj = @Test} loc(#loc3)
// CHECK-NEXT:     yul.codecopy %c0_i256, %0, %1 loc(#loc4)
// CHECK-NEXT:     yul.object @Test_deployed {
// CHECK-NEXT:     } loc(#loc)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:4:13)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:16)
// CHECK-NEXT: #loc3 = loc({{.*}}:4:36)
// CHECK-NEXT: #loc4 = loc({{.*}}:4:4)
// CHECK-EMPTY:
