// RUN: solc --strict-assembly --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

object "Test" {
  code {
    returndatacopy(0, 0, returndatasize())
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   sol.object @Test {
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc1)
// CHECK-NEXT:     %c0_i256_0 = arith.constant 0 : i256 loc(#loc2)
// CHECK-NEXT:     %0 = sol.returndatasize loc(#loc3)
// CHECK-NEXT:     sol.returndatacopy %c0_i256, %c0_i256_0, %0 loc(#loc4)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:4:19)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:22)
// CHECK-NEXT: #loc3 = loc({{.*}}:4:25)
// CHECK-NEXT: #loc4 = loc({{.*}}:4:4)
// CHECK-EMPTY:
