// RUN: solc --strict-assembly --mlir-action=print-std-mlir --mlir-target=evm --mmlir --mlir-print-debuginfo %s | FileCheck %s

object "Test" {
  code {
    let r := create(1, 2, 3)
    r := create2(1, 2, 3, 4)
  }
}


// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Osaka = #sol<EvmVersion Osaka>
// CHECK-NEXT: module @Test attributes {sol.evm_version = #Osaka} {
// CHECK-NEXT:   func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c4_i256 = arith.constant 4 : i256 loc(#loc)
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:     %c2_i256 = arith.constant 2 : i256 loc(#loc)
// CHECK-NEXT:     %c3_i256 = arith.constant 3 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.inttoptr %c2_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     %1 = "llvm.intrcall"(%c1_i256, %0, %c3_i256) <{id = 4044 : i32, name = "evm.create"}> : (i256, !llvm.ptr<1>, i256) -> i256 loc(#loc1)
// CHECK-NEXT:     %2 = llvm.alloca %c1_i256 x i256 {alignment = 32 : i64} : (i256) -> !llvm.ptr loc(#loc2)
// CHECK-NEXT:     llvm.store %1, %2 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc3)
// CHECK-NEXT:     %3 = llvm.inttoptr %c2_i256 : i256 to !llvm.ptr<1> loc(#loc4)
// CHECK-NEXT:     %4 = "llvm.intrcall"(%c1_i256, %3, %c3_i256, %c4_i256) <{id = 4045 : i32, name = "evm.create2"}> : (i256, !llvm.ptr<1>, i256, i256) -> i256 loc(#loc4)
// CHECK-NEXT:     llvm.store %4, %2 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc5)
// CHECK-NEXT:     llvm.unreachable loc(#loc)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:4:13)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:8)
// CHECK-NEXT: #loc3 = loc({{.*}}:4:4)
// CHECK-NEXT: #loc4 = loc({{.*}}:5:9)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:4)
// CHECK-EMPTY:
